# Generated by Django 4.2.1 on 2026-04-16 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('module_type', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=255)),
                ('from_value', models.CharField(max_length=255)),
                ('to_value', models.CharField(max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ManyToManyField(blank=True, related_name='computation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='admin_scrip_status_30c824_idx'), models.Index(fields=['module_type', 'attribute'], name='admin_scrip_module__1b4de2_idx')],
            },
        ),
    ]
