# Generated by Django 4.2.1 on 2026-04-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computationjob',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
