image: python:3.11
definitions:
  steps:
    - step: &predeploy
        name: test App
        script:
          - echo 'deploying djangoexact'
    - step: &deploy
        name: Deploy App
        script:
          - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
          - SDK_VERSION=420.0.0
          - SDK_FILENAME=google-cloud-sdk-${SDK_VERSION}-linux-x86_64.tar.gz
          - curl -O -J https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/${SDK_FILENAME}
          - tar -zxvf ${SDK_FILENAME} --directory ${HOME}
          - export PATH=${PATH}:${HOME}/google-cloud-sdk/bin
          - echo ${PROJECT_KEYFILE:0:120}
          
          - echo $PROJECT_KEYFILE > /tmp/key-file.json
          - gcloud auth activate-service-account --key-file /tmp/key-file.json

          - apt-get install wget
          - wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          - chmod +x cloud_sql_proxy
          - ./cloud_sql_proxy -instances=$DB_INSTANCE_CONNECTION=tcp:$DB_PORT > cloudsql.log 2>&1 &

          - cd djangoexact

          - sed -i "s|\$SERVICE_NAME|$SERVICE_NAME|g" app.yaml
          - sed -i "s|\$PROJECT_ID|$PROJECT_ID|g" app.yaml
          - sed -i "s|\$DB_ENGINE|$DB_ENGINE|g" app.yaml
          - sed -i "s|\$DB_HOST|$DB_HOST|g" app.yaml
          - sed -i "s|\$DB_USERNAME|$DB_USERNAME|g" app.yaml
          - sed -i "s|\$DB_PASSWORD|$DB_PASSWORD|g" app.yaml
          - sed -i "s|\$DB_NAME|$DB_NAME|g" app.yaml
          - sed -i "s|\$DB_PORT|$DB_PORT|g" app.yaml
          - sed -i "s|\$FIREBASE_API_KEY|$FIREBASE_API_KEY|g" app.yaml
          - sed -i "s|\$FIREBASE_SERVICE_ACCOUNT|$FIREBASE_SERVICE_ACCOUNT|g" app.yaml

          - sed -i "s|\$DB_ENGINE|$DB_ENGINE|g" djangoexact/settings.py
          - sed -i "s|\$DB_INSTANCE_CONNECTION|$DB_INSTANCE_CONNECTION|g" djangoexact/settings.py
          - sed -i "s|\$DB_HOST|127.0.0.1|g" djangoexact/settings.py
          - sed -i "s|\$DB_USERNAME|$DB_USERNAME|g" djangoexact/settings.py
          - sed -i "s|\$DB_PASSWORD|$DB_PASSWORD|g" djangoexact/settings.py
          - sed -i "s|\$DB_NAME|$DB_NAME|g" djangoexact/settings.py
          - sed -i "s|\$DB_PORT|$DB_PORT|g" djangoexact/settings.py
          - sed -i "s|\$ALLOWED_HOST|$ALLOWED_HOST|g" djangoexact/settings.py
          - sed -i "s|\$SECRET_KEY|$SECRET_KEY|g" djangoexact/settings.py
          - sed -i "s|\$FIREBASE_API_KEY|$FIREBASE_API_KEY|g" djangoexact/settings.py
          - sed -i "s|\$FIREBASE_AUTH_DOMAIN|$FIREBASE_AUTH_DOMAIN|g" djangoexact/settings.py
          - sed -i "s|\$FIREBASE_PROJECT_ID|$FIREBASE_PROJECT_ID|g" djangoexact/settings.py
          - sed -i "s|\$FIREBASE_STORAGE_BUCKET|$FIREBASE_STORAGE_BUCKET|g" djangoexact/settings.py
          - sed -i "s|\$FIREBASE_MESSAGING_SENDER_ID|$FIREBASE_MESSAGING_SENDER_ID|g" djangoexact/settings.py
          - sed -i "s|\$FIREBASE_APP_ID|$FIREBASE_APP_ID|g" djangoexact/settings.py
          - sed -i "s|\$FIREBASE_MEASUREMENT_ID|$FIREBASE_MEASUREMENT_ID|g" djangoexact/settings.py

          - pip install -r requirements.txt
          # - yes | python manage.py makemigrations --merge
          - python manage.py migrate
          - python manage.py collectstatic --noinput

          - pip list
          - sed -i "s|127.0.0.1|$DB_HOST|g" djangoexact/settings.py

          - gcloud config set project $PROJECT_ID
          - gcloud app deploy app.yaml --project $PROJECT_ID --verbosity=debug
          - gcloud app versions list --service=$SERVICE_NAME --project=$PROJECT_ID --format="value(version.id)" --sort-by="~version.createTime" | tail -n +100 | xargs -r gcloud app versions delete -q
pipelines:
  branches:
    develop:
      - step: *predeploy
      - step:
          <<: *deploy
          deployment: develop
    review:
      - step: *predeploy
      - step:
          <<: *deploy
          deployment: review
    master:
      - step: *predeploy
      - step:
          <<: *deploy
          deployment: production
          trigger: manual