[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version = "1.17.10"
update_changelog_on_bump = true
tag = false
version_files = [
  "djangoexact/djangoexact/__init__.py"
]