# Generated by Django 4.2.1 on 2024-10-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_date_updated_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='0916', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
