"""Excel workbook builder for the scenario-builder export.

The builder produces a multi-sheet workbook:

* "Run Info"  -- timestamp, requester, scenario count, the global filters that
  were applied to every scenario.
* "Summary"   -- one row per scenario with descriptive statistics.
* "<scenario name>" * N -- per-scenario detail sheet with the statistics
  block, the resolved global + per-change filters, and the full changes
  table including the matched ChangeRecord count for each change.

The public entry point is :func:`build_scenarios_workbook`.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Iterable

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from admin_scripts.scenario_utils import _build_single_change_q, stats_for_scenario
from minitool.models import ChangeRecord


RUN_INFO_SHEET = "Run Info"
SUMMARY_SHEET = "Summary"

_HEADER_FILL = PatternFill(start_color="FFE7E6E6", end_color="FFE7E6E6", fill_type="solid")
_HEADER_FONT = Font(bold=True)
_BLOCK_FONT = Font(bold=True, color="FF1F4E78")
_KEY_FONT = Font(bold=True)

_NUMBER_FMT = "#,##0.0000"
_INT_FMT = "#,##0"
_MAX_COL_WIDTH = 50
_MIN_COL_WIDTH = 10

# Characters Excel forbids in a sheet name.
_FORBIDDEN_SHEET_CHARS = set("[]:*?/\\")

_STAT_LABELS = (
    ("Count", "count", _INT_FMT),
    ("Sum Total", "sum_total", _NUMBER_FMT),
    ("Mean", "mean", _NUMBER_FMT),
    ("Median", "median", _NUMBER_FMT),
    ("Min", "min", _NUMBER_FMT),
    ("Max", "max", _NUMBER_FMT),
    ("Std Dev", "std", _NUMBER_FMT),
    ("Q1", "q1", _NUMBER_FMT),
    ("Q3", "q3", _NUMBER_FMT),
    ("IQR", "iqr", _NUMBER_FMT),
    ("CI 95%", "ci_95", _NUMBER_FMT),
    ("CI 99%", "ci_99", _NUMBER_FMT),
)

_SUMMARY_HEADERS = (
    "Category",
    "Scenario Name",
    "Count",
    "Sum Total",
    "Mean",
    "Median",
    "Min",
    "Max",
    "Std Dev",
    "Q1",
    "Q3",
    "IQR",
    "CI 95%",
    "CI 99%",
)

_CHANGES_HEADERS = (
    "Change #",
    "Module Type",
    "Field",
    "From Value",
    "To Value",
    "Unit",
    "Matched Records",
    "Climate",
    "Moisture",
    "Soil Type",
)


def _safe_sheet_name(name: str, used: set[str]) -> str:
    """Return a workbook-unique, Excel-legal sheet name (<= 31 chars).

    Forbidden characters are replaced with ``_``. Collisions are resolved by
    appending `` (2)``, `` (3)``, ... while keeping the total length within
    Excel's 31-char limit.
    """
    cleaned = "".join("_" if c in _FORBIDDEN_SHEET_CHARS else c for c in (name or "")).strip()
    if not cleaned:
        cleaned = "Scenario"
    base = cleaned[:31]
    candidate = base
    suffix = 2
    while candidate in used:
        tail = f" ({suffix})"
        candidate = f"{base[: max(1, 31 - len(tail))]}{tail}"
        suffix += 1
    used.add(candidate)
    return candidate


def _format_filter_value(value) -> str:
    if value is None:
        return ""
    if isinstance(value, (list, tuple)):
        return ", ".join(str(v) for v in value)
    return str(value)


def _autosize(ws) -> None:
    for col_cells in ws.columns:
        if not col_cells:
            continue
        col_letter = get_column_letter(col_cells[0].column)
        longest = 0
        for cell in col_cells:
            if cell.value is None:
                continue
            length = len(str(cell.value))
            if length > longest:
                longest = length
        ws.column_dimensions[col_letter].width = min(max(longest + 2, _MIN_COL_WIDTH), _MAX_COL_WIDTH)


def _write_header_row(ws, row: int, headers: Iterable[str]) -> None:
    for col_idx, label in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=col_idx, value=label)
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
        cell.alignment = Alignment(horizontal="left")


def _write_block_title(ws, row: int, title: str) -> None:
    cell = ws.cell(row=row, column=1, value=title)
    cell.font = _BLOCK_FONT


def _write_kv(ws, row: int, key: str, value, number_format: str | None = None) -> None:
    ws.cell(row=row, column=1, value=key).font = _KEY_FONT
    cell = ws.cell(row=row, column=2, value=value)
    if number_format and isinstance(value, (int, float)) and not isinstance(value, bool):
        cell.number_format = number_format


def _write_run_info(ws, scenarios, global_filters, requested_by, now) -> None:
    ws.title = RUN_INFO_SHEET
    _write_kv(ws, 1, "Generated at", now.strftime("%Y-%m-%d %H:%M:%S"))
    _write_kv(ws, 2, "Generated by", requested_by or "")
    _write_kv(
        ws,
        3,
        "Scenario count",
        sum(1 for s in scenarios if s.get("changes")),
        number_format=_INT_FMT,
    )

    row = 5
    _write_block_title(ws, row, "GLOBAL FILTERS")
    row += 1
    if not global_filters:
        _write_kv(ws, row, "(none)", "")
    else:
        for key, value in global_filters.items():
            _write_kv(ws, row, key, _format_filter_value(value))
            row += 1
    _autosize(ws)


def _write_summary(ws, summary_rows) -> None:
    _write_header_row(ws, 1, _SUMMARY_HEADERS)
    for r, row_data in enumerate(summary_rows, start=2):
        for c, key in enumerate(_SUMMARY_HEADERS, start=1):
            value = row_data.get(key)
            cell = ws.cell(row=r, column=c, value=value)
            if key == "Count":
                cell.number_format = _INT_FMT
            elif key in ("Category", "Scenario Name"):
                continue
            elif isinstance(value, (int, float)) and not isinstance(value, bool):
                cell.number_format = _NUMBER_FMT
    ws.freeze_panes = "A2"
    _autosize(ws)


def _matched_record_count(change: dict, global_filters: dict) -> int:
    if not change.get("module_type"):
        return 0
    q = _build_single_change_q(change, global_filters)
    return ChangeRecord.objects.filter(q).count()


def _write_detail_sheet(ws, scenario: dict, stats: dict, global_filters: dict) -> None:
    row = 1
    _write_kv(ws, row, "Scenario Name", scenario.get("scenario_name") or "")
    row += 1
    _write_kv(ws, row, "Category", scenario.get("category") or "")
    row += 2

    _write_block_title(ws, row, "STATISTICS")
    row += 1
    for label, key, fmt in _STAT_LABELS:
        _write_kv(ws, row, label, stats.get(key), number_format=fmt)
        row += 1
    row += 1

    _write_block_title(ws, row, "GLOBAL FILTERS")
    row += 1
    if not global_filters:
        _write_kv(ws, row, "(none)", "")
        row += 1
    else:
        for key, value in global_filters.items():
            _write_kv(ws, row, key, _format_filter_value(value))
            row += 1
    row += 1

    _write_block_title(ws, row, "CHANGES")
    row += 1
    _write_header_row(ws, row, _CHANGES_HEADERS)
    row += 1
    for i, change in enumerate(scenario.get("changes") or [], start=1):
        filters = change.get("filters") or {}
        values = [
            i,
            change.get("module_type", ""),
            (change.get("start") or {}).get("field", ""),
            (change.get("start") or {}).get("value", ""),
            (change.get("end") or {}).get("value", ""),
            change.get("unit", "") or "",
            _matched_record_count(change, global_filters),
            _format_filter_value(filters.get("climate")),
            _format_filter_value(filters.get("moisture")),
            _format_filter_value(filters.get("soil_type")),
        ]
        for c, val in enumerate(values, start=1):
            cell = ws.cell(row=row, column=c, value=val)
            if c in (1, 7):
                cell.number_format = _INT_FMT
        row += 1
    _autosize(ws)


def build_scenarios_workbook(
    scenarios: list[dict],
    global_filters: dict,
    requested_by: str | None = None,
    now: datetime | None = None,
) -> bytes:
    """Build the multi-sheet scenarios workbook and return its bytes.

    ``scenarios`` is the output of ``_parse_scenarios_from_post`` (each entry
    has ``scenario_name``, ``category``, ``changes`` with optional per-change
    ``filters`` / ``unit``). Scenarios with no changes are skipped silently
    so the workbook never contains an empty detail sheet.
    """
    now = now or datetime.now()

    wb = Workbook()
    run_info_ws = wb.active
    _write_run_info(run_info_ws, scenarios, global_filters, requested_by, now)

    summary_ws = wb.create_sheet(SUMMARY_SHEET)

    used_names = {RUN_INFO_SHEET, SUMMARY_SHEET}
    summary_rows: list[dict] = []

    for scenario in scenarios:
        changes = scenario.get("changes") or []
        if not changes:
            continue

        stats = stats_for_scenario(changes, global_filters)

        summary_rows.append({
            "Category": scenario.get("category", "") or "",
            "Scenario Name": scenario.get("scenario_name", "") or "Unnamed Scenario",
            "Count": stats.get("count", 0),
            "Sum Total": stats.get("sum_total"),
            "Mean": stats.get("mean"),
            "Median": stats.get("median"),
            "Min": stats.get("min"),
            "Max": stats.get("max"),
            "Std Dev": stats.get("std"),
            "Q1": stats.get("q1"),
            "Q3": stats.get("q3"),
            "IQR": stats.get("iqr"),
            "CI 95%": stats.get("ci_95"),
            "CI 99%": stats.get("ci_99"),
        })

        sheet_name = _safe_sheet_name(scenario.get("scenario_name") or "Scenario", used_names)
        detail_ws = wb.create_sheet(sheet_name)
        _write_detail_sheet(detail_ws, scenario, stats, global_filters)

    _write_summary(summary_ws, summary_rows)

    out = io.BytesIO()
    wb.save(out)
    return out.getvalue()
