runtime: python311
service: $SERVICE_NAME
instance_class: F2

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

- url: .*
  script: main.app

env_variables:
  PROJECT_ID: "$PROJECT_ID"
  DB_ENGINE: "$DB_ENGINE"
  DB_HOST: "$DB_HOST"
  DB_USERNAME: "$DB_USERNAME"
  DB_PASSWORD: "$DB_PASSWORD"
  DB_NAME: "$DB_NAME"
  DB_PORT: "$DB_PORT"