# Generated by Django 4.1.3 on 2022-11-20 15:49

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroforestrySystemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalWarmingPotential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('co2', models.FloatField()),
                ('ch4', models.FloatField()),
                ('n2o', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LandUseParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwp', models.FloatField()),
                ('is_fire_used', models.BooleanField(default=False)),
                ('forested_area_start', models.IntegerField()),
                ('forested_area_with', models.IntegerField()),
                ('forested_area_without', models.IntegerField()),
                ('rfc_ag_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the aboveground biomass of the agroforestry system (t C/ha/yr)', null=True)),
                ('rfg_bg_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the belowground biomass of the agroforestry system (t C/ha/yr)', null=True)),
                ('rfc_litter_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the litter of the agroforestry system (t C/ha/yr)', null=True)),
                ('rfc_deadwood_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the deadwood of the agroforestry system (t C/ha/yr)', null=True)),
                ('rfc_soil_c_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the soil of the agroforestry system (t C/ha/yr)', null=True)),
                ('final_rfc_biomass_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the biomass of the agroforestry system (t C/ha/yr)', null=True)),
                ('final_rfc_soil_c_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the soil of the agroforestry system (t C/ha/yr)', null=True)),
                ('agroforestry_system_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agroforestrysystemtype')),
            ],
        ),
        migrations.CreateModel(
            name='LandUseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganicAmendmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganicInputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreSeasonWaterRegimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Project statuses',
            },
        ),
        migrations.CreateModel(
            name='ResidueManagementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TillageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VegetationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaterRegimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TotalBiomassAfterDefo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='SoilOrganicCarbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('funding_agency', models.CharField(max_length=100)),
                ('executing_agency', models.CharField(max_length=100)),
                ('duration_in_years', models.IntegerField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('global_warming_potential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.globalwarmingpotential')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('soil_organic_carbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soilorganiccarbon')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='api.projectstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='PerennialCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_residue_burned', models.BooleanField(default=False)),
                ('crop_yield', models.FloatField()),
                ('ha_start', models.FloatField(null=True)),
                ('ha_with', models.FloatField(null=True)),
                ('ha_without', models.FloatField(null=True)),
                ('notes', models.TextField(null=True)),
                ('agroforestry_system_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agroforestrysystemtype')),
                ('ha_with_dynamics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perennial_ha_with_dynamics', to='api.changedynamic')),
                ('ha_without_dynamics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perennial_ha_without_dynamics', to='api.changedynamic')),
                ('luc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perennials', to='api.landuseparameters')),
                ('organic_input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype')),
                ('tillage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagetype')),
            ],
        ),
        migrations.CreateModel(
            name='NitrousEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('moisture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.AddField(
            model_name='landuseparameters',
            name='final_land_use_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='landuseparameters',
            name='forested_area_with_dynamics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forested_ha_roc', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='landuseparameters',
            name='forested_area_without_dynamics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reforested_area_without_dynamics', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='landuseparameters',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luc', to='api.project'),
        ),
        migrations.AddField(
            model_name='landuseparameters',
            name='vegetation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
        migrations.CreateModel(
            name='FloodedRice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivation_period', models.IntegerField(default=113)),
                ('crop_yield', models.FloatField()),
                ('ha_start', models.FloatField(null=True)),
                ('ha_with', models.FloatField(null=True)),
                ('ha_without', models.FloatField(null=True)),
                ('remaining_flooded_rice_ha', models.FloatField(null=True)),
                ('notes', models.TextField(null=True)),
                ('ha_with_dynamics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ha_with_dynamics', to='api.changedynamic')),
                ('ha_without_dynamics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ha_without_dynamics', to='api.changedynamic')),
                ('organic_amendment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicamendmenttype')),
                ('pre_season_water_regime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_season_water_regime_type', to='api.preseasonwaterregimetype')),
                ('water_regime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.waterregimetype')),
            ],
        ),
        migrations.CreateModel(
            name='DefoBiomassChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='CroplandRelativeCarbonStockChangeFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_yield', models.FloatField()),
                ('notes', models.TextField(null=True)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
                ('luc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landuseparameters')),
                ('organic_input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype')),
                ('residue_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.residuemanagementtype')),
                ('tillage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagetype')),
            ],
        ),
    ]
