# Generated by Django 4.1.3 on 2022-11-27 21:35

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfforestationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fire_used', models.BooleanField(default=False)),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('initial_biomass_t2', models.FloatField(blank=True, null=True)),
                ('initial_soil_carbon_t2', models.FloatField(blank=True, null=True)),
                ('final_ag_biomass_le_20yrs_t2', models.FloatField(blank=True, null=True)),
                ('final_bg_biomass_le_20yrs_t2', models.FloatField(blank=True, null=True)),
                ('final_bg_biomass_gt_20yrs_t2', models.FloatField(blank=True, null=True)),
                ('final_rcs_t2', models.FloatField(blank=True, null=True)),
                ('final_litter_t2', models.FloatField(blank=True, null=True)),
                ('final_dw_t2', models.FloatField(blank=True, null=True)),
                ('final_soil_carbon_t2', models.FloatField(blank=True, null=True)),
                ('yearly_ghg_t2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='DeforestationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fire_used', models.BooleanField(default=False)),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('hwp', models.FloatField()),
                ('ha_start', models.IntegerField()),
                ('rcs_ag_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for above-ground biomass (in tC/ha)', null=True)),
                ('rcs_bg_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for below-ground biomass (in tC/ha)', null=True)),
                ('rcs_litter_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for litter (in tC/ha)', null=True)),
                ('rcs_deadwood_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for deadwood (in tC/ha)', null=True)),
                ('rcs_soil_c_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon (in tC/ha)', null=True)),
                ('final_rcs_biomass_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for biomass in final land use (in tC/ha)', null=True)),
                ('final_rcs_soil_c_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon in final land use (in tC/ha)', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandUseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganicAmendmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganicInputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtherLandUseChangeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fire_used', models.BooleanField(default=False)),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSeasonWaterRegimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Project statuses',
            },
        ),
        migrations.CreateModel(
            name='ResidueManagementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TillageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VegetationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaterRegimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('funding_agency', models.CharField(max_length=100)),
                ('executing_agency', models.CharField(max_length=100)),
                ('implementation_duration_yrs', models.FloatField()),
                ('capitalization_duration_yrs', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
    ]
