# Generated by Django 4.1.3 on 2022-11-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipcc', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gw_potential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.globalwarmingpotential'),
        ),
        migrations.AddField(
            model_name='project',
            name='moisture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture'),
        ),
        migrations.AddField(
            model_name='project',
            name='soc_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.soilorganiccarbon'),
        ),
        migrations.AddField(
            model_name='project',
            name='soil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projectstatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='final_land_use_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_final_land_use_type', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='ha_w_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='land_use_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='vegetation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
        migrations.AddField(
            model_name='landusetype',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='ha_w_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='land_use_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='vegetation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='ha_w_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='land_use_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='vegetation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
    ]
