# Generated by Django 4.2.1 on 2024-02-14 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipcc', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallfishery',
            name='fui_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcc.smallfisheryfui'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='gear_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_gear_type_start', to='api.smallfisherygeartype'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='gear_type_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_gear_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='gear_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_gear_type_w', to='api.smallfisherygeartype'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='gear_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_gear_type_wo', to='api.smallfisherygeartype'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='ice_preserved_catch_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ice_preserved_catch_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='inshore_ice_production_country_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='refrigerant_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_refrigerant_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='total_catch_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_total_catch_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='ha_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ha_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='setaside',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='setaside',
            name='ha_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ha_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='setaside',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='setaside',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='road',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='road',
            name='length_km_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_length_km_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='road',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='road',
            name='road_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_road_type_start', to='api.roadtype'),
        ),
        migrations.AddField(
            model_name='road',
            name='road_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_road_type_w', to='api.roadtype'),
        ),
        migrations.AddField(
            model_name='road',
            name='road_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_road_type_wo', to='api.roadtype'),
        ),
        migrations.AddField(
            model_name='road',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='api.settlement'),
        ),
        migrations.AddField(
            model_name='road',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='road',
            name='width_m_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_width_m_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group'),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.project'),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='climate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate'),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='project',
            name='gw_potential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.globalwarmingpotential'),
        ),
        migrations.AddField(
            model_name='project',
            name='moisture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture'),
        ),
        migrations.AddField(
            model_name='project',
            name='soil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projectstatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='crop_yield_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_yield_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='is_biomass_burned_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_is_biomass_burned_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='organic_input_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_start', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='organic_input_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='organic_input_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_w', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='organic_input_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_wo', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_start', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_management_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_w', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_wo', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='final_land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_land_use_type', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='initial_land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_land_use_type', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='area_m2_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_area_m2_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_infrastructure', to='api.settlement'),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='area_not_drained_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_area_not_drained_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='ditches_area_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ditches_area_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='drainage_area_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_drainage_area_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='fire_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fire_type_start', to='api.firetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='fire_type_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fire_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='fire_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fire_type_w', to='api.firetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='fire_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fire_type_wo', to='api.firetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='is_peat_for_energy_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_peat_is_for_energy_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_area_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_peat_area_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_ditches_area_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_peat_ditches_area_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_extraction_height_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_peat_extraction_height_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_peat_type_start', to='api.peattype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_type_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_peat_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_peat_type_w', to='api.peattype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_peat_type_wo', to='api.peattype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='soil_fire_impact_percentage_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_soil_fire_impact_percentage_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='soil_fire_periodicity_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_soil_fire_periodicity_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='crop_yield_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_yield_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='is_biomass_burned_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_is_biomass_burned_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='organic_input_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_start', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='organic_input_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='organic_input_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_w', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='organic_input_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_wo', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_seasons', to='api.perennialcropping'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='tillage_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_start', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='tillage_management_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='tillage_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_w', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='tillage_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_wo', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='organic_amendment_type_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_start', to='api.organicamendmenttype'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='organic_amendment_type_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_w', to='api.organicamendmenttype'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='organic_amendment_type_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_wo', to='api.organicamendmenttype'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_seasons', to='api.floodedrice'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='water_management_type_after_cultivation_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_start', to='api.watermanagementtypeaftercultivation'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='water_management_type_after_cultivation_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_w', to='api.watermanagementtypeaftercultivation'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='water_management_type_after_cultivation_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_wo', to='api.watermanagementtypeaftercultivation'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='water_management_type_before_cultivation_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_start', to='api.watermanagementtypebeforecultivation'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='water_management_type_before_cultivation_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_w', to='api.watermanagementtypebeforecultivation'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='water_management_type_before_cultivation_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_wo', to='api.watermanagementtypebeforecultivation'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='complementary_manure_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_manure_management_type_t2_start', to='api.manuremanagementtype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='complementary_manure_management_type_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_complementary_manure_management_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='complementary_manure_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_manure_management_type_t2_w', to='api.manuremanagementtype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='complementary_manure_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_manure_management_type_t2_wo', to='api.manuremanagementtype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='heads_number_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_heads_number_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_category_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_livestock_categories_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_livestock_category_type', to='api.livestockcategorytype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_production_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_production_type_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_livestock_production_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_production_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_livestock_productions_w', to='api.livestockproductiontype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_production_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_livestock_productions_wo', to='api.livestockproductiontype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='percentage_heads_on_pasture_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_percentage_heads_on_pasture_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='production_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_production_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='fish_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fishtype'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='fui_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcc.largefisheryfui'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='gear_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_gear_type_start', to='api.largefisherygeartype'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='gear_type_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_gear_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='gear_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_gear_type_w', to='api.largefisherygeartype'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='gear_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_gear_type_wo', to='api.largefisherygeartype'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='ice_preserved_catch_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ice_preserved_catch_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='inshore_ice_production_country_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='refrigerant_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_refrigerant_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='total_catch_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_total_catch_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='landusetype',
            name='climates',
            field=models.ManyToManyField(related_name='land_use_types', to='api.climate'),
        ),
        migrations.AddField(
            model_name='landusetype',
            name='forest_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.foresttype'),
        ),
        migrations.AddField(
            model_name='landusetype',
            name='module_types',
            field=models.ManyToManyField(related_name='land_use_types', to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='landusetype',
            name='moistures',
            field=models.ManyToManyField(related_name='land_use_types', to='api.moisture'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='module_type_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='module_type_w',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w', to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='module_type_wo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wo', to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='irrigation_system_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_systems', to='api.irrigationsystemtype'),
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_systems', to='api.irrigation'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fueltype'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='irrigation_system_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_phases', to='api.irrigationsystemtype'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_phases', to='api.irrigation'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='power_origin_country_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='inputtype',
            name='macro_input_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.macroinputtype'),
        ),
        migrations.AddField(
            model_name='inputentry',
            name='input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inputtype'),
        ),
        migrations.AddField(
            model_name='inputentry',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_entries', to='api.input'),
        ),
        migrations.AddField(
            model_name='inputentry',
            name='value_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_value_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='input',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='input',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='input',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='fire_impact_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fire_impact_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='fire_periodicity_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fire_periodicity_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='grassland_management_type_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_grassland_management_type_start', to='api.grasslandmanagementtype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='grassland_management_type_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_grassland_management_type_w', to='api.grasslandmanagementtype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='grassland_management_type_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_grassland_management_type_wo', to='api.grasslandmanagementtype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='is_fire_used_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_is_fire_used_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='yield_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_yield_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='fueltype',
            name='fuel_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fuelusetype'),
        ),
        migrations.AddField(
            model_name='fueltype',
            name='macro_fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.macrofueltype'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fueltype'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='api.energy'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='average_yearly_degradation_percentage_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_average_yearly_degradation_percentage_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='forest_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.foresttype'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_percentage_agb_logged_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logging_percentage_agb_logged_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_percentage_biomass_for_energy_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logging_percentage_biomass_for_energy_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_recurrence_yrs_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logging_recurrence_yrs_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_length_yrs_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rotation_length_yrs_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_percentage_biomass_for_energy_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rotation_percentage_biomass_for_energy_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='forestdisturbance',
            name='disturbance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disturbancetype'),
        ),
        migrations.AddField(
            model_name='forestdisturbance',
            name='disturbance_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_disturbance_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestdisturbance',
            name='forest_management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disturbances', to='api.forestmanagement'),
        ),
        migrations.AddField(
            model_name='forestdisturbance',
            name='percentage_biomass_destruction_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_disturbance_percentage_biomass_destruction_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestdisturbance',
            name='recurrence_yrs_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_disturbance_recurrence_yrs_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='organic_amendment_type_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_start', to='api.organicamendmenttype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='organic_amendment_type_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_w', to='api.organicamendmenttype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='organic_amendment_type_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_wo', to='api.organicamendmenttype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_after_cultivation_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_start', to='api.watermanagementtypeaftercultivation'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_after_cultivation_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_w', to='api.watermanagementtypeaftercultivation'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_after_cultivation_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_wo', to='api.watermanagementtypeaftercultivation'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_before_cultivation_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_start', to='api.watermanagementtypebeforecultivation'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_before_cultivation_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_w', to='api.watermanagementtypebeforecultivation'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_before_cultivation_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_wo', to='api.watermanagementtypebeforecultivation'),
        ),
        migrations.AddField(
            model_name='energy',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='energy',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='energy',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='ef_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.emissionfactorsource'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electricities', to='api.energy'),
        ),
        migrations.AddField(
            model_name='degradedland',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='degradedland',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='degradedland',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='degradedland',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='degradedland',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='degradedland',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='degradedland',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='degradedland',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='country',
            name='gleam_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='api.gleamregion'),
        ),
        migrations.AddField(
            model_name='country',
            name='ipcc_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='api.ipccregion'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='api.region'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='area_not_drained_or_rewetted_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_area_not_drained_or_rewetted_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='area_under_drainage_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_area_under_drainage_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='area_w_restored_vegetation_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_area_w_restored_vegetation_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='avg_salinity_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.salinitytype'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='drained_area_excavated_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_drained_area_excavated_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='ha_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ha_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='soil_type_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.soiltype'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='climate',
            name='moistures',
            field=models.ManyToManyField(related_name='climates', to='api.moisture'),
        ),
        migrations.AddField(
            model_name='building',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='building',
            name='area_m2_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_surface_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='building',
            name='building_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_building_type_start', to='api.buildingtype'),
        ),
        migrations.AddField(
            model_name='building',
            name='building_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_building_type_w', to='api.buildingtype'),
        ),
        migrations.AddField(
            model_name='building',
            name='building_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_building_type_wo', to='api.buildingtype'),
        ),
        migrations.AddField(
            model_name='building',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='building',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='api.settlement'),
        ),
        migrations.AddField(
            model_name='building',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='crop_yield_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_yield_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_residue_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_residue_management_type', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_residue_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_residue_management_type_w', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_residue_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_residue_management_type_wo', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='organic_input_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_start', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='organic_input_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='organic_input_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_w', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='organic_input_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_wo', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='residue_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_start', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='residue_management_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='residue_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_w', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='residue_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_wo', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='tillage_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_start', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='tillage_management_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='tillage_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_w', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='tillage_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_wo', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='change_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='activity',
            name='climate_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.climate'),
        ),
        migrations.AddField(
            model_name='activity',
            name='module_types',
            field=models.ManyToManyField(related_name='activities', to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='moisture_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moisture'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='soil_type_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.soiltype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.country'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='projectinvitation',
            unique_together={('project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='inputtype',
            unique_together={('macro_input_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='fueltype',
            unique_together={('name', 'fuel_use_type', 'macro_fuel_type')},
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('name', 'project')},
        ),
    ]
