# Generated by Django 4.1.3 on 2022-11-20 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalbiomassafterdefo',
            name='crop',
        ),
        migrations.AddField(
            model_name='totalbiomassafterdefo',
            name='agroforestry_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.agroforestrysystemtype'),
            preserve_default=False,
        ),
    ]
