# Generated by Django 4.1.3 on 2022-12-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipcc', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gw_potential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.globalwarmingpotential'),
        ),
        migrations.AddField(
            model_name='project',
            name='moisture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture'),
        ),
        migrations.AddField(
            model_name='project',
            name='soc_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.soilorganiccarbon'),
        ),
        migrations.AddField(
            model_name='project',
            name='soil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projectstatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='final_land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_final_land_use_type', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='ha_w_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='initial_land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_initial_land_use_type', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.owner'),
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AddField(
            model_name='landusetype',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deforestation'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='deforested_vegetation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='final_land_use_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('parent__isnull', True), ('parent__name', 'Agroforestry'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='ha_w_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='defoannualcropping',
            name='main_season_crop',
            field=models.ForeignKey(limit_choices_to=models.Q(('parent__name', 'Annual cropping')), on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='defoannualcropping',
            name='organic_input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='defoannualcropping',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defo_assignments', to='api.deforestationinput'),
        ),
        migrations.AddField(
            model_name='defoannualcropping',
            name='residue_management_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='defoannualcropping',
            name='tillage_management_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.afforestation'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='final_vegetation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='ha_w_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='initial_land_use_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('parent__isnull', True), ('parent__name', 'Agroforestry'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='affoannualcrop',
            name='main_season_crop',
            field=models.ForeignKey(limit_choices_to=models.Q(('parent__name', 'Annual cropping')), on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='affoannualcrop',
            name='organic_input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='affoannualcrop',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affo_assignments', to='api.afforestationinput'),
        ),
        migrations.AddField(
            model_name='affoannualcrop',
            name='residue_management_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='affoannualcrop',
            name='tillage_management_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.module'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activitytype'),
        ),
    ]
