# Generated by Django 4.1.3 on 2022-11-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_totalbiomassafterdefo_crop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IPCCSoilOrcanicCarbonCNRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('agroforestry_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agroforestrysystemtype')),
            ],
        ),
        migrations.CreateModel(
            name='IPCCLitterDeadwoodCarbonStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litter', models.FloatField()),
                ('dw', models.FloatField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forest')),
            ],
        ),
        migrations.CreateModel(
            name='IPCCLandUseStockExchangeFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('agroforestry_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agroforestrysystemtype')),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='IPCCDefaultEmissionFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.input')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='IPCCCombustionFactorValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField()),
                ('ch4', models.FloatField()),
                ('n2o', models.FloatField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forest')),
            ],
        ),
    ]
