# Generated by Django 4.1.3 on 2022-12-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afforestationinput',
            name='final_ag_biomass_gt_20yrs_t2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
