# Generated by Django 4.1.3 on 2022-12-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualCroppingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('crop_yield', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FloodedRiceInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('cultivation_period', models.IntegerField(default=113)),
                ('crop_yield', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GrasslandInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('years_w_fire_management', models.IntegerField(blank=True, null=True)),
                ('years_wo_fire_management', models.IntegerField(blank=True, null=True)),
                ('yield_start', models.FloatField(blank=True, null=True)),
                ('yield_w', models.FloatField(blank=True, null=True)),
                ('yield_wo', models.FloatField(blank=True, null=True)),
                ('soil_carbon_start_t2', models.FloatField(blank=True, null=True)),
                ('soil_carbon_w_t2', models.FloatField(blank=True, null=True)),
                ('soil_carbon_wo_t2', models.FloatField(blank=True, null=True)),
                ('agb_t2', models.FloatField(blank=True, null=True)),
                ('combustion_factor_t2', models.FloatField(blank=True, null=True)),
                ('implementation_year_start', models.IntegerField(blank=True, null=True)),
                ('ha_start', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrasslandManagementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockCategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('production_start', models.FloatField(blank=True, null=True)),
                ('production_w', models.FloatField(blank=True, null=True)),
                ('production_wo', models.FloatField(blank=True, null=True)),
                ('heads_number_start', models.IntegerField(blank=True, null=True)),
                ('heads_number_w', models.IntegerField(blank=True, null=True)),
                ('heads_number_wo', models.IntegerField(blank=True, null=True)),
                ('enteric_fermentation_start_t2', models.FloatField(blank=True, null=True)),
                ('enteric_fermentation_w_t2', models.FloatField(blank=True, null=True)),
                ('enteric_fermentation_wo_t2', models.FloatField(blank=True, null=True)),
                ('pasture_percentage_start_t2', models.FloatField(blank=True, null=True)),
                ('pasture_percentage_w_t2', models.FloatField(blank=True, null=True)),
                ('pasture_percentage_wo_t2', models.FloatField(blank=True, null=True)),
                ('emission_factor_start_t2', models.FloatField(blank=True, null=True)),
                ('emission_factor_w_t2', models.FloatField(blank=True, null=True)),
                ('emission_factor_wo_t2', models.FloatField(blank=True, null=True)),
                ('n2o_start_t2', models.FloatField(blank=True, null=True)),
                ('n2o_w_t2', models.FloatField(blank=True, null=True)),
                ('n2o_wo_t2', models.FloatField(blank=True, null=True)),
                ('emission_factor_ch4_t2', models.FloatField(blank=True, null=True)),
                ('emission_factor_n20_t2', models.FloatField(blank=True, null=True)),
                ('implementation_year_start', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockProductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManureManagementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerennialCroppingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('is_biomass_burned', models.BooleanField()),
                ('crop_yield', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='affoannualcrop',
            name='main_season_crop',
        ),
        migrations.RemoveField(
            model_name='affoannualcrop',
            name='organic_input_type',
        ),
        migrations.RemoveField(
            model_name='affoannualcrop',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='affoannualcrop',
            name='residue_management_type',
        ),
        migrations.RemoveField(
            model_name='affoannualcrop',
            name='tillage_management_type',
        ),
        migrations.DeleteModel(
            name='AssignmentType',
        ),
        migrations.RemoveField(
            model_name='defoannualcropping',
            name='main_season_crop',
        ),
        migrations.RemoveField(
            model_name='defoannualcropping',
            name='organic_input_type',
        ),
        migrations.RemoveField(
            model_name='defoannualcropping',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='defoannualcropping',
            name='residue_management_type',
        ),
        migrations.RemoveField(
            model_name='defoannualcropping',
            name='tillage_management_type',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.RenameField(
            model_name='deforestationinput',
            old_name='deforested_vegetation_type',
            new_name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.RemoveField(
            model_name='afforestationinput',
            name='final_vegetation_type',
        ),
        migrations.RemoveField(
            model_name='afforestationinput',
            name='initial_land_use_type',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='final_land_use_type',
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='final_ag_biomass_gt_20yrs_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='final_ag_biomass_le_20yrs_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='final_bg_biomass_gt_20yrs_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='final_bg_biomass_le_20yrs_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='final_dw_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='final_land_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='final_litter_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='final_rcs_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='final_soil_carbon_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='initial_biomass_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='initial_land_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='initial_soil_carbon_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.owner'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='yearly_ghg_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='final_rcs_biomass_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for biomass in final land use (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='final_rcs_soil_c_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon in final land use (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='land_use_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent__isnull', True), ('parent__name', 'Agroforestry'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.owner'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='rcs_ag_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for above-ground biomass (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='rcs_bg_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for below-ground biomass (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='rcs_deadwood_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for deadwood (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='rcs_litter_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for litter (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='rcs_soil_c_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon (in tC/ha)', null=True),
        ),
        migrations.AlterField(
            model_name='afforestationinput',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AlterField(
            model_name='afforestationinput',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changedynamic'),
        ),
        migrations.AlterField(
            model_name='afforestationinput',
            name='is_fire_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changedynamic'),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='hwp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='is_fire_used',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameModel(
            old_name='ChangeDynamic',
            new_name='ChangeRate',
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
        migrations.DeleteModel(
            name='AffoAnnualCrop',
        ),
        migrations.DeleteModel(
            name='Afforestation',
        ),
        migrations.DeleteModel(
            name='DefoAnnualCropping',
        ),
        migrations.DeleteModel(
            name='Deforestation',
        ),
        migrations.AddField(
            model_name='perennialcroppinginput',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='perennialcroppinginput',
            name='agroforestry_system',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent__name', 'Agroforestry')), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='perennialcroppinginput',
            name='organic_input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='perennialcroppinginput',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.owner'),
        ),
        migrations.AddField(
            model_name='perennialcroppinginput',
            name='tillage_management_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='livestockinput',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='livestockinput',
            name='heads_number_w_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_heads_number_w_rate', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='livestockinput',
            name='heads_number_wo_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_heads_number_wo_rate', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='livestockinput',
            name='livestock_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype'),
        ),
        migrations.AddField(
            model_name='livestockinput',
            name='livestock_production_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype'),
        ),
        migrations.AddField(
            model_name='livestockinput',
            name='manure_management_type_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manuremanagementtype'),
        ),
        migrations.AddField(
            model_name='livestockinput',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.owner'),
        ),
        migrations.AddField(
            model_name='grasslandinput',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='grasslandinput',
            name='grassland_at_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_start', to='api.grasslandmanagementtype'),
        ),
        migrations.AddField(
            model_name='grasslandinput',
            name='grassland_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_with', to='api.grasslandmanagementtype'),
        ),
        migrations.AddField(
            model_name='grasslandinput',
            name='grassland_without',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_without', to='api.grasslandmanagementtype'),
        ),
        migrations.AddField(
            model_name='grasslandinput',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.owner'),
        ),
        migrations.AddField(
            model_name='floodedriceinput',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='floodedriceinput',
            name='organic_amendment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicamendmenttype'),
        ),
        migrations.AddField(
            model_name='floodedriceinput',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.owner'),
        ),
        migrations.AddField(
            model_name='floodedriceinput',
            name='water_management_type_after_cultivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watermanagementtypeaftercultivation'),
        ),
        migrations.AddField(
            model_name='floodedriceinput',
            name='water_management_type_before_cultivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watermanagementtypebeforecultivation'),
        ),
        migrations.AddField(
            model_name='annualcroppinginput',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='annualcroppinginput',
            name='main_season_crop',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent__name', 'Annual Cropland')), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcroppinginput',
            name='organic_input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='annualcroppinginput',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.owner'),
        ),
        migrations.AddField(
            model_name='annualcroppinginput',
            name='residue_management_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcroppinginput',
            name='tillage_management_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype'),
        ),
    ]
