# Generated by Django 4.2.1 on 2024-02-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockcategorytype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
