# Generated by Django 4.1.3 on 2022-12-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_annualcroppinginput_floodedriceinput_grasslandinput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerate',
            name='value',
            field=models.FloatField(unique=True),
        ),
    ]
