# Generated by Django 4.1.3 on 2022-11-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_forest_input_ipccsoilorcaniccarboncnratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcccombustionfactorvalues',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
