# Generated by Django 4.2.1 on 2024-02-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_livestockcategorytype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_w',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_wo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_w',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_wo',
            field=models.IntegerField(default=0),
        ),
    ]
