# Generated by Django 4.1.3 on 2022-12-07 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0003_afforestationinput_final_ag_biomass_gt_20yrs_t2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TillageManagementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaterManagementTypeAfterCultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaterManagementTypeBeforeCultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='afforestationinput',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='deforestationinput',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='otherlandusechangeinput',
            old_name='project_id',
            new_name='project',
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='afforestationinput',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PerennialCroppingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_biomass_burned', models.BooleanField()),
                ('crop_yield', models.FloatField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('organic_input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype')),
                ('tillage_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloodedRiceInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cultivation_period', models.IntegerField(default=113)),
                ('crop_yield', models.FloatField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organic_amendment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicamendmenttype')),
                ('water_management_type_after_cultivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watermanagementtypeaftercultivation')),
                ('water_management_type_before_cultivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watermanagementtypebeforecultivation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnualCroppingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('crop_yield', models.FloatField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('organic_input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype')),
                ('residue_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.residuemanagementtype')),
                ('tillage_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemainingPerennialCroppingInput',
            fields=[
                ('perennialcroppinginput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.perennialcroppinginput')),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('ha_start', models.IntegerField()),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('ha_w_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic')),
                ('ha_wo_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changedynamic')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.perennialcroppinginput',),
        ),
        migrations.CreateModel(
            name='RemainingFloodedRiceInput',
            fields=[
                ('floodedriceinput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.floodedriceinput')),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('ha_start', models.IntegerField()),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('ha_total_remaining', models.IntegerField()),
                ('ha_w_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic')),
                ('ha_wo_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changedynamic')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.floodedriceinput',),
        ),
        migrations.CreateModel(
            name='RemainingAnnualCroppingInput',
            fields=[
                ('annualcroppinginput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.annualcroppinginput')),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('ha_start', models.IntegerField()),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('ha_w_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic')),
                ('ha_wo_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changedynamic')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.annualcroppinginput',),
        ),
    ]
