# Generated by Django 4.1.3 on 2022-11-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ipcccombustionfactorvalues_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCCDataOnMangroves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agb_dry_matter', models.FloatField()),
                ('c_fraction', models.FloatField()),
                ('agb_c', models.FloatField()),
                ('agb_growth', models.FloatField()),
                ('r', models.FloatField()),
                ('bgb', models.FloatField()),
                ('litter', models.FloatField()),
                ('dw', models.FloatField()),
                ('soc_ref', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
    ]
