# Generated by Django 4.1.3 on 2022-12-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tillagemanagementtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualcroppinginput',
            name='land_use_type',
        ),
        migrations.RemoveField(
            model_name='perennialcroppinginput',
            name='land_use_type',
        ),
    ]
