# Generated by Django 4.1.3 on 2022-12-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_changerate_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='soc_ref_t2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
