# Generated by Django 4.2.1 on 2024-02-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_forestmanagement_logging_start_year_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forestmanagement',
            name='land_use_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='land_use_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='land_use_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='soil_carbon_t2_start',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='soil_carbon_t2_w',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='soil_carbon_t2_wo',
        ),
    ]
