# Generated by Django 4.1.3 on 2022-12-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_soc_ref_t2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landusetype',
            old_name='needs_assignment',
            new_name='needs_assessment',
        ),
    ]
