# Generated by Django 4.1.3 on 2022-11-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ipccdataonmangroves'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCCAGBiomass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forest')),
            ],
        ),
    ]
