# Generated by Django 4.1.3 on 2022-12-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_annualcroppinginput_land_use_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afforestationinput',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='afforestationinput',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='otherlandusechangeinput',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='otherlandusechangeinput',
            name='object_id',
        ),
    ]
