# Generated by Django 4.2.1 on 2024-02-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_forestmanagement_land_use_factor_t2_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_percentage_agb_logged_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_percentage_agb_logged_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_percentage_agb_logged_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_percentage_biomass_for_energy_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_percentage_biomass_for_energy_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_percentage_biomass_for_energy_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_recurrence_yrs_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_recurrence_yrs_w',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_recurrence_yrs_wo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_length_yrs_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_length_yrs_w',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_length_yrs_wo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_percentage_biomass_for_energy_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_percentage_biomass_for_energy_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_percentage_biomass_for_energy_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
