# Generated by Django 4.1.3 on 2022-12-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_needs_assignment_landusetype_needs_assessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afforestationinput',
            old_name='initial_land_use',
            new_name='land_use_type',
        ),
        migrations.RenameField(
            model_name='annualcroppinginput',
            old_name='main_season_crop',
            new_name='land_use_type',
        ),
        migrations.RenameField(
            model_name='perennialcroppinginput',
            old_name='agroforestry_system',
            new_name='land_use_type',
        ),
    ]
