# Generated by Django 4.1.3 on 2022-12-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_afforestationinput_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualcroppinginput',
            old_name='object_id',
            new_name='input_id',
        ),
        migrations.RenameField(
            model_name='floodedriceinput',
            old_name='object_id',
            new_name='input_id',
        ),
        migrations.RenameField(
            model_name='perennialcroppinginput',
            old_name='object_id',
            new_name='input_id',
        ),
    ]
