# Generated by Django 4.2.1 on 2024-02-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_forestmanagement_logging_percentage_agb_logged_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestmanagement',
            name='average_yearly_degradation_percentage_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='average_yearly_degradation_percentage_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='average_yearly_degradation_percentage_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
