# Generated by Django 4.1.3 on 2022-11-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ipccagbiomass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipccagbiomass',
            name='country',
        ),
        migrations.AddField(
            model_name='ipccagbiomass',
            name='continent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.continent'),
            preserve_default=False,
        ),
    ]
