# Generated by Django 4.1.3 on 2022-11-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_ipccagbiomass_country_ipccagbiomass_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcccombustionfactorvalues',
            name='forest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agroforestrysystemtype'),
        ),
    ]
