# Generated by Django 4.1.3 on 2022-12-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_initial_land_use_afforestationinput_land_use_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afforestationinput',
            old_name='final_land_use',
            new_name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='otherlandusechangeinput',
            name='final_land_use_type',
        ),
        migrations.AddField(
            model_name='otherlandusechangeinput',
            name='land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type', to='api.landusetype'),
        ),
    ]
