# Generated by Django 4.2.1 on 2024-02-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_forestmanagement_average_yearly_degradation_percentage_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organicinputtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
