# Generated by Django 4.2.1 on 2024-02-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_organicinputtype_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='ag_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='ag_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='ag_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='agb_max_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='agb_max_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='agb_max_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='bg_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='bg_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='bg_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='crop_yield_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='crop_yield_thread',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='crop_yield_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='crop_yield_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='fire_periodicity_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='fire_periodicity_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='fire_periodicity_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='input_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='input_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='input_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='is_biomass_burned_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='is_biomass_burned_thread',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='is_biomass_burned_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='is_biomass_burned_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='organic_input_type_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='organic_input_type_thread',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='organic_input_type_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='organic_input_type_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='residue_burned_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='residue_burned_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='residue_burned_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='soc_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='soc_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='soc_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='tillage_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='tillage_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='tillage_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='tillage_management_type_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='tillage_management_type_thread',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='tillage_management_type_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='tillage_management_type_wo',
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='biomass_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='biomass_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='biomass_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='residue_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_start', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='residue_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_w', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='residue_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_wo', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='yield_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='yield_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='yield_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minorseasonperennialcropping',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, limit_choices_to={'land_use_type__parent__class_name': 'PerennialCropping'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AlterField(
            model_name='minorseasonperennialcropping',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, limit_choices_to={'land_use_type__parent__class_name': 'PerennialCropping'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AlterField(
            model_name='minorseasonperennialcropping',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, limit_choices_to={'land_use_type__parent__class_name': 'PerennialCropping'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.CreateModel(
            name='MinorSeasonAnnualCropping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(blank=True, null=True)),
                ('flu_t2_start', models.FloatField(blank=True, null=True)),
                ('flu_t2_w', models.FloatField(blank=True, null=True)),
                ('flu_t2_wo', models.FloatField(blank=True, null=True)),
                ('fi_t2_start', models.FloatField(blank=True, null=True)),
                ('fi_t2_w', models.FloatField(blank=True, null=True)),
                ('fi_t2_wo', models.FloatField(blank=True, null=True)),
                ('fmg_t2_start', models.FloatField(blank=True, null=True)),
                ('fmg_t2_w', models.FloatField(blank=True, null=True)),
                ('fmg_t2_wo', models.FloatField(blank=True, null=True)),
                ('yield_start', models.FloatField(blank=True, null=True)),
                ('yield_w', models.FloatField(blank=True, null=True)),
                ('yield_wo', models.FloatField(blank=True, null=True)),
                ('biomass_factor_t2_start', models.FloatField(blank=True, null=True)),
                ('biomass_factor_t2_w', models.FloatField(blank=True, null=True)),
                ('biomass_factor_t2_wo', models.FloatField(blank=True, null=True)),
                ('land_use_change', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange')),
                ('land_use_type_start', models.ForeignKey(blank=True, limit_choices_to={'land_use_type__parent__class_name': 'PerennialCropping'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype')),
                ('land_use_type_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread')),
                ('land_use_type_w', models.ForeignKey(blank=True, limit_choices_to={'land_use_type__parent__class_name': 'PerennialCropping'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype')),
                ('land_use_type_wo', models.ForeignKey(blank=True, limit_choices_to={'land_use_type__parent__class_name': 'PerennialCropping'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_seasons', to='api.annualcropping')),
                ('residue_management_type_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_start', to='api.residuemanagementtype')),
                ('residue_management_type_w', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_w', to='api.residuemanagementtype')),
                ('residue_management_type_wo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_wo', to='api.residuemanagementtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
