# Generated by Django 4.1.3 on 2022-12-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_final_land_use_afforestationinput_vegetation_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landusetype',
            old_name='parent',
            new_name='parent_land_use',
        ),
    ]
