# Generated by Django 4.1.3 on 2022-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_ipcccombustionfactorvalues_forest'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='land_use',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
