# Generated by Django 4.1.3 on 2022-11-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_land_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcclitterdeadwoodcarbonstock',
            name='forest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
    ]
