# Generated by Django 4.2.1 on 2024-02-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_minorseasonperennialcropping_ag_t2_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_view_modules', 'Can view modules'), ('can_add_modules', 'Can add modules'), ('can_change_modules', 'Can change modules'), ('can_delete_modules', 'Can delete modules'))},
        ),
    ]
