# Generated by Django 4.1.3 on 2022-12-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_activitytype_landusetype_assessment_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landusetype',
            name='parent_land_use',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_land_use': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.landusetype'),
        ),
    ]
