# Generated by Django 4.1.3 on 2022-11-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_ipcclitterdeadwoodcarbonstock_forest'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCCAboveGroundBiomass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('agroforestry_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agroforestrysystemtype')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
            ],
        ),
    ]
