# Generated by Django 4.2.1 on 2024-02-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_forestmanagement_forest_condition_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestdisturbance',
            name='disturbance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.disturbancetype'),
        ),
    ]
