# Generated by Django 4.1.3 on 2022-12-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_landusetype_parent_land_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcroppinginput',
            name='land_use_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent_land_use__name', 'Annual Cropland')), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='land_use_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent_land_use__isnull', True), ('parent_land_use__name', 'Agroforestry'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AlterField(
            model_name='perennialcroppinginput',
            name='land_use_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent_land_use__name', 'Agroforestry')), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
    ]
