# Generated by Django 4.1.3 on 2022-11-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ipccabovegroundbiomass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipccabovegroundbiomass',
            name='agroforestry_system',
        ),
        migrations.AddField(
            model_name='ipccabovegroundbiomass',
            name='vegetation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
            preserve_default=False,
        ),
    ]
