# Generated by Django 4.2.1 on 2024-02-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_forestdisturbance_disturbance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forestmanagement',
            name='forest_condition_type',
        ),
    ]
