# Generated by Django 4.1.3 on 2022-12-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_annualcroppinginput_land_use_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherlandusechangeinput',
            old_name='initial_biomas_t2',
            new_name='initial_biomass_t2',
        ),
    ]
