# Generated by Django 4.1.3 on 2022-11-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ipccbelowgroundbiomass'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipccbelowgroundbiomass',
            name='threshold',
            field=models.FloatField(null=True),
        ),
    ]
