# Generated by Django 4.2.1 on 2024-02-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_forestmanagement_forest_condition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestmanagement',
            name='forest_condition_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.forestconditiontype'),
            preserve_default=False,
        ),
    ]
