# Generated by Django 4.1.3 on 2022-12-20 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_initial_biomas_t2_otherlandusechangeinput_initial_biomass_t2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afforestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fire_used', models.BooleanField(default=False)),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('initial_biomass_t2', models.FloatField(blank=True, null=True)),
                ('initial_soil_carbon_t2', models.FloatField(blank=True, null=True)),
                ('final_ag_biomass_le_20yrs_t2', models.FloatField(blank=True, null=True)),
                ('final_ag_biomass_gt_20yrs_t2', models.FloatField(blank=True, null=True)),
                ('final_bg_biomass_le_20yrs_t2', models.FloatField(blank=True, null=True)),
                ('final_bg_biomass_gt_20yrs_t2', models.FloatField(blank=True, null=True)),
                ('final_rcs_t2', models.FloatField(blank=True, null=True)),
                ('final_litter_t2', models.FloatField(blank=True, null=True)),
                ('final_dw_t2', models.FloatField(blank=True, null=True)),
                ('final_soil_carbon_t2', models.FloatField(blank=True, null=True)),
                ('yearly_ghg_t2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnualCropping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('crop_yield', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deforestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwp', models.FloatField()),
                ('is_fire_used', models.BooleanField(default=False)),
                ('ha_start', models.IntegerField()),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('rcs_ag_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for above-ground biomass (in tC/ha)', null=True)),
                ('rcs_bg_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for below-ground biomass (in tC/ha)', null=True)),
                ('rcs_litter_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for litter (in tC/ha)', null=True)),
                ('rcs_deadwood_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for deadwood (in tC/ha)', null=True)),
                ('rcs_soil_c_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon (in tC/ha)', null=True)),
                ('final_rcs_biomass_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for biomass in final land use (in tC/ha)', null=True)),
                ('final_rcs_soil_c_t2', models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon in final land use (in tC/ha)', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloodedRice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('cultivation_period', models.IntegerField(default=113)),
                ('crop_yield', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grassland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('years_w_fire_management', models.IntegerField(blank=True, null=True)),
                ('years_wo_fire_management', models.IntegerField(blank=True, null=True)),
                ('yield_start', models.FloatField(blank=True, null=True)),
                ('yield_w', models.FloatField(blank=True, null=True)),
                ('yield_wo', models.FloatField(blank=True, null=True)),
                ('soil_carbon_start_t2', models.FloatField(blank=True, null=True)),
                ('soil_carbon_w_t2', models.FloatField(blank=True, null=True)),
                ('soil_carbon_wo_t2', models.FloatField(blank=True, null=True)),
                ('agb_t2', models.FloatField(blank=True, null=True)),
                ('combustion_factor_t2', models.FloatField(blank=True, null=True)),
                ('implementation_year_start', models.IntegerField(blank=True, null=True)),
                ('ha_start', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('production_start', models.FloatField(blank=True, null=True)),
                ('production_w', models.FloatField(blank=True, null=True)),
                ('production_wo', models.FloatField(blank=True, null=True)),
                ('heads_number_start', models.IntegerField(blank=True, null=True)),
                ('heads_number_w', models.IntegerField(blank=True, null=True)),
                ('heads_number_wo', models.IntegerField(blank=True, null=True)),
                ('enteric_fermentation_start_t2', models.FloatField(blank=True, null=True)),
                ('enteric_fermentation_w_t2', models.FloatField(blank=True, null=True)),
                ('enteric_fermentation_wo_t2', models.FloatField(blank=True, null=True)),
                ('pasture_percentage_start_t2', models.FloatField(blank=True, null=True)),
                ('pasture_percentage_w_t2', models.FloatField(blank=True, null=True)),
                ('pasture_percentage_wo_t2', models.FloatField(blank=True, null=True)),
                ('emission_factor_start_t2', models.FloatField(blank=True, null=True)),
                ('emission_factor_w_t2', models.FloatField(blank=True, null=True)),
                ('emission_factor_wo_t2', models.FloatField(blank=True, null=True)),
                ('n2o_start_t2', models.FloatField(blank=True, null=True)),
                ('n2o_w_t2', models.FloatField(blank=True, null=True)),
                ('n2o_wo_t2', models.FloatField(blank=True, null=True)),
                ('emission_factor_ch4_t2', models.FloatField(blank=True, null=True)),
                ('emission_factor_n20_t2', models.FloatField(blank=True, null=True)),
                ('implementation_year_start', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherLandUseChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_fire_used', models.BooleanField(default=False)),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('initial_biomass_t2', models.FloatField(blank=True, null=True)),
                ('initial_soil_carbon_t2', models.FloatField(blank=True, null=True)),
                ('final_biomass_t2', models.FloatField(blank=True, null=True)),
                ('final_soil_carbon_t2', models.FloatField(blank=True, null=True)),
                ('implementation_year_start', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerennialCropping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('is_biomass_burned', models.BooleanField()),
                ('crop_yield', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='annualcroppinginput',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='annualcroppinginput',
            name='land_use_type',
        ),
        migrations.RemoveField(
            model_name='annualcroppinginput',
            name='organic_input_type',
        ),
        migrations.RemoveField(
            model_name='annualcroppinginput',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='annualcroppinginput',
            name='residue_management_type',
        ),
        migrations.RemoveField(
            model_name='annualcroppinginput',
            name='tillage_management_type',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='ha_w_rate',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='ha_wo_rate',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='land_use_type',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='floodedriceinput',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='floodedriceinput',
            name='organic_amendment_type',
        ),
        migrations.RemoveField(
            model_name='floodedriceinput',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='floodedriceinput',
            name='water_management_type_after_cultivation',
        ),
        migrations.RemoveField(
            model_name='floodedriceinput',
            name='water_management_type_before_cultivation',
        ),
        migrations.RemoveField(
            model_name='grasslandinput',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='grasslandinput',
            name='grassland_at_start',
        ),
        migrations.RemoveField(
            model_name='grasslandinput',
            name='grassland_with',
        ),
        migrations.RemoveField(
            model_name='grasslandinput',
            name='grassland_without',
        ),
        migrations.RemoveField(
            model_name='grasslandinput',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='livestockinput',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='livestockinput',
            name='heads_number_w_rate',
        ),
        migrations.RemoveField(
            model_name='livestockinput',
            name='heads_number_wo_rate',
        ),
        migrations.RemoveField(
            model_name='livestockinput',
            name='livestock_category',
        ),
        migrations.RemoveField(
            model_name='livestockinput',
            name='livestock_production_type',
        ),
        migrations.RemoveField(
            model_name='livestockinput',
            name='manure_management_type_t2',
        ),
        migrations.RemoveField(
            model_name='livestockinput',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='module',
            name='project',
        ),
        migrations.RemoveField(
            model_name='otherlandusechangeinput',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='otherlandusechangeinput',
            name='ha_w_rate',
        ),
        migrations.RemoveField(
            model_name='otherlandusechangeinput',
            name='ha_wo_rate',
        ),
        migrations.RemoveField(
            model_name='otherlandusechangeinput',
            name='initial_land_use_type',
        ),
        migrations.RemoveField(
            model_name='otherlandusechangeinput',
            name='land_use_type',
        ),
        migrations.RemoveField(
            model_name='otherlandusechangeinput',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='perennialcroppinginput',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='perennialcroppinginput',
            name='land_use_type',
        ),
        migrations.RemoveField(
            model_name='perennialcroppinginput',
            name='organic_input_type',
        ),
        migrations.RemoveField(
            model_name='perennialcroppinginput',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='perennialcroppinginput',
            name='tillage_management_type',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='module',
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AfforestationInput',
        ),
        migrations.DeleteModel(
            name='AnnualCroppingInput',
        ),
        migrations.DeleteModel(
            name='DeforestationInput',
        ),
        migrations.DeleteModel(
            name='FloodedRiceInput',
        ),
        migrations.DeleteModel(
            name='GrasslandInput',
        ),
        migrations.DeleteModel(
            name='LivestockInput',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='OtherLandUseChangeInput',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='PerennialCroppingInput',
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='land_use_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent_land_use__name', 'Agroforestry')), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='organic_input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_management_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='otherlandusechange',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='otherlandusechange',
            name='final_land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='otherlandusechange',
            name='ha_w_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='otherlandusechange',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='otherlandusechange',
            name='initial_land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_initial_land_use_type', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='heads_number_w_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_heads_number_w_rate', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='heads_number_wo_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_heads_number_wo_rate', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_production_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='manure_management_type_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manuremanagementtype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='grassland_at_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_start', to='api.grasslandmanagementtype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='grassland_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_with', to='api.grasslandmanagementtype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='grassland_without',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_without', to='api.grasslandmanagementtype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='organic_amendment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicamendmenttype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_after_cultivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watermanagementtypeaftercultivation'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_before_cultivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watermanagementtypebeforecultivation'),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='ha_w_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='land_use_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent_land_use__isnull', True), ('parent_land_use__name', 'Agroforestry'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='vegetation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='land_use_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent_land_use__name', 'Annual Cropland')), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='organic_input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='residue_management_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='tillage_management_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='afforestation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AddField(
            model_name='afforestation',
            name='ha_w_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='afforestation',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='afforestation',
            name='land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='afforestation',
            name='vegetation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
    ]
