# Generated by Django 4.1.3 on 2022-11-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ipccbelowgroundbiomass_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipccbelowgroundbiomass',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
