# Generated by Django 4.2.1 on 2024-02-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_forestmanagement_forest_condition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestmanagement',
            name='forest_condition_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.forestconditiontype'),
        ),
    ]
