# Generated by Django 4.1.3 on 2022-12-22 00:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_moduletype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherLandUseChange',
            new_name='OtherLandUse',
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters are allowed.'), django.core.validators.RegexValidator('[A-Z][a-z]*(\\s[A-Z][a-z]*)*', 'Only capitalized words are allowed.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.user'),
        ),
    ]
