# Generated by Django 4.1.3 on 2022-11-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_ipccbelowgroundbiomass_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='land_use',
        ),
    ]
