# Generated by Django 4.1.3 on 2022-12-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_otherlandusechange_otherlanduse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestDegradationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fire_used_w', models.BooleanField(default=False)),
                ('is_fire_used_wo', models.BooleanField(default=False)),
                ('fire_periodicity_w', models.IntegerField(blank=True, null=True)),
                ('fire_periodicity_wo', models.IntegerField(blank=True, null=True)),
                ('fire_impact_w', models.FloatField(blank=True, null=True)),
                ('fire_impact_wo', models.FloatField(blank=True, null=True)),
                ('ha_start', models.IntegerField(blank=True, null=True)),
                ('ha_w', models.IntegerField(blank=True, null=True)),
                ('ha_wo', models.IntegerField(blank=True, null=True)),
                ('ag_carbon_t2', models.FloatField(blank=True, null=True)),
                ('bg_carbon_t2', models.FloatField(blank=True, null=True)),
                ('litter_t2', models.FloatField(blank=True, null=True)),
                ('deadwood_t2', models.FloatField(blank=True, null=True)),
                ('soil_carbon_t2', models.FloatField(blank=True, null=True)),
                ('land_input_factor_start_t2', models.FloatField(blank=True, null=True)),
                ('land_input_factor_w_t2', models.FloatField(blank=True, null=True)),
                ('land_input_factor_wo_t2', models.FloatField(blank=True, null=True)),
                ('implementation_year_start_t2', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('degradation_level_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_start', to='api.forestdegradationlevel')),
                ('degradation_level_start_t2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_start_t2', to='api.forestdegradationlevel')),
                ('degradation_level_w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_w', to='api.forestdegradationlevel')),
                ('degradation_level_w_t2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_w_t2', to='api.forestdegradationlevel')),
                ('degradation_level_wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_wo', to='api.forestdegradationlevel')),
                ('degradation_level_wo_t2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_wo_t2', to='api.forestdegradationlevel')),
                ('ha_w_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate')),
                ('ha_wo_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changerate')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
