# Generated by Django 4.2.1 on 2024-02-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_project_created_at_project_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lock_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
