# Generated by Django 4.1.3 on 2022-11-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_project_land_use'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPCCAGBiomass',
        ),
    ]
