# Generated by Django 4.1.3 on 2022-11-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_ipccagbiomass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalWarmingPotential',
            new_name='IPCCGlobalWarmingPotential',
        ),
        migrations.RenameModel(
            old_name='NitrousEmissionFactor',
            new_name='IPCCNitrousEmissionFactor',
        ),
        migrations.RenameModel(
            old_name='SoilOrganicCarbon',
            new_name='IPCCSoilOrganicCarbon',
        ),
        migrations.RenameModel(
            old_name='TotalBiomassAfterDefo',
            new_name='IPCCTotalBiomassAfterDefo',
        ),
        migrations.RemoveField(
            model_name='defobiomasschanges',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='defobiomasschanges',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='defobiomasschanges',
            name='moisture',
        ),
        migrations.DeleteModel(
            name='CroplandRelativeCarbonStockChangeFactors',
        ),
        migrations.DeleteModel(
            name='DefoBiomassChanges',
        ),
    ]
