# Generated by Django 4.2.1 on 2024-03-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_project_lock_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
