# Generated by Django 4.2.1 on 2024-03-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_activity_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
