# Generated by Django 4.1.3 on 2022-11-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_globalwarmingpotential_ipccglobalwarmingpotential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.projectstatus'),
        ),
        migrations.CreateModel(
            name='LandUseChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwp', models.FloatField()),
                ('is_fire_used', models.BooleanField(default=False)),
                ('ha_start', models.IntegerField()),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('rfc_ag_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the aboveground biomass of the agroforestry system (t C/ha/yr)', null=True)),
                ('rfg_bg_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the belowground biomass of the agroforestry system (t C/ha/yr)', null=True)),
                ('rfc_litter_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the litter of the agroforestry system (t C/ha/yr)', null=True)),
                ('rfc_deadwood_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the deadwood of the agroforestry system (t C/ha/yr)', null=True)),
                ('rfc_soil_c_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the soil of the agroforestry system (t C/ha/yr)', null=True)),
                ('final_rfc_biomass_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the biomass of the agroforestry system (t C/ha/yr)', null=True)),
                ('final_rfc_soil_c_t2', models.FloatField(help_text='The average annual rate of carbon sequestration in the soil of the agroforestry system (t C/ha/yr)', null=True)),
                ('agroforestry_system_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agroforestrysystemtype')),
                ('final_land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('ha_w_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luc_ha_w_rate', to='api.changedynamic')),
                ('ha_wo_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luc_ha_wo_rate', to='api.changedynamic')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luc', to='api.project')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
        migrations.AlterField(
            model_name='annualcrop',
            name='luc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusechange'),
        ),
        migrations.AlterField(
            model_name='perennialcrop',
            name='luc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perennials', to='api.landusechange'),
        ),
        migrations.DeleteModel(
            name='LandUseParameters',
        ),
    ]
