# Generated by Django 4.1.3 on 2022-12-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_firetype_peattype_trophictype_waterbodytype_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InlandWaterbodies',
            new_name='InlandWaterbody',
        ),
    ]
