# Generated by Django 4.1.3 on 2022-12-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_inlandwaterbodies_inlandwaterbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
