# Generated by Django 4.2.1 on 2024-03-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_activity_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='notes',
            new_name='text',
        ),
    ]
