# Generated by Django 4.1.3 on 2022-11-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_project_status_landusechange_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floodedrice',
            old_name='ha_with',
            new_name='ha_w',
        ),
        migrations.RenameField(
            model_name='floodedrice',
            old_name='ha_without',
            new_name='ha_wo',
        ),
        migrations.RenameField(
            model_name='perennialcrop',
            old_name='ha_with',
            new_name='ha_w',
        ),
        migrations.RenameField(
            model_name='perennialcrop',
            old_name='ha_without',
            new_name='ha_wo',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='ha_with_dynamics',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='ha_without_dynamics',
        ),
        migrations.RemoveField(
            model_name='perennialcrop',
            name='ha_with_dynamics',
        ),
        migrations.RemoveField(
            model_name='perennialcrop',
            name='ha_without_dynamics',
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='ha_w_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rice_ha_w_rate', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='ha_wo_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rice_ha_wo_rate', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='perennialcrop',
            name='ha_w_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perennial_ha_w_rate', to='api.changedynamic'),
        ),
        migrations.AddField(
            model_name='perennialcrop',
            name='ha_wo_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perennial_ha_wo_rate', to='api.changedynamic'),
        ),
        migrations.AlterField(
            model_name='annualcrop',
            name='luc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_crops', to='api.landusechange'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='pre_season_water_regime_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rice_pre_season_water_regime_type', to='api.preseasonwaterregimetype'),
        ),
        migrations.AlterField(
            model_name='perennialcrop',
            name='luc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perennial_crops', to='api.landusechange'),
        ),
    ]
