# Generated by Django 4.1.3 on 2022-12-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_activitytype_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytype',
            name='verbose_name',
        ),
        migrations.AddField(
            model_name='moduletype',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduletype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
