# Generated by Django 4.2.1 on 2024-03-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_notes_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcropping',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='aquaculture',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='building',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='degradedland',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='input',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='landusechange',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='otherinfrastructure',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='otherlanduse',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='road',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='setaside',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='waterbody',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
    ]
