# Generated by Django 4.1.3 on 2022-11-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_ha_with_floodedrice_ha_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='capitalization_duration',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='implementation_duration',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
