# Generated by Django 4.1.3 on 2022-12-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_activitytype_verbose_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualcropping',
            name='main_biomass_factor_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_land_use_factor_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_organic_input_factor_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_soil_carbon_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_tillage_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_biomass_factor_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_crop_type_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_crop_type', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_residue_management_type_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_residue_management_type', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_yield_t2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
