# Generated by Django 4.1.3 on 2022-11-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_project_capitalization_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='capitalization_duration',
            new_name='capitalization_duration_yrs',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='implementation_duration',
            new_name='implementation_duration_yrs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration_in_years',
        ),
    ]
