# Generated by Django 4.1.3 on 2022-11-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_capitalization_duration_project_capitalization_duration_yrs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='global_warming_potential',
            new_name='gw_potential',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='soil_organic_carbon',
            new_name='soc_ref',
        ),
    ]
