# Generated by Django 4.1.3 on 2022-12-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_annualcropping_main_biomass_factor_t2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualcropping',
            name='ha_start',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='ha_start_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_start_rate', to='api.changerate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='ha_w',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='ha_w_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='ha_wo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='ha_wo_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changerate'),
            preserve_default=False,
        ),
    ]
