# Generated by Django 4.2.1 on 2024-03-25 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_annualcropping_notes_alter_aquaculture_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setaside',
            name='biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='setaside',
            name='biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='setaside',
            name='biomass_t2_wo',
        ),
        migrations.RemoveField(
            model_name='setaside',
            name='ha_start',
        ),
        migrations.RemoveField(
            model_name='setaside',
            name='ha_thread',
        ),
        migrations.RemoveField(
            model_name='setaside',
            name='ha_w',
        ),
        migrations.RemoveField(
            model_name='setaside',
            name='ha_wo',
        ),
        migrations.AddField(
            model_name='setaside',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setaside',
            name='fi_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setaside',
            name='fi_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setaside',
            name='fi_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setaside',
            name='fmg_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setaside',
            name='fmg_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setaside',
            name='fmg_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setaside',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='setaside',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='setaside',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='setaside',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='setaside',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_percentage_agb_logged_start',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_percentage_agb_logged_w',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_percentage_agb_logged_wo',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
