# Generated by Django 4.1.3 on 2022-12-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_annualcropping_ha_start_annualcropping_ha_start_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualcropping',
            name='ha_start_rate',
        ),
    ]
