# Generated by Django 4.1.3 on 2022-11-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_global_warming_potential_project_gw_potential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcccombustionfactorvalues',
            name='forest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projectstatus'),
        ),
    ]
