# Generated by Django 4.2.1 on 2024-03-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_setaside_biomass_t2_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_recurrence_yrs_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_recurrence_yrs_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_recurrence_yrs_wo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_length_yrs_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_length_yrs_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_length_yrs_wo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
