# Generated by Django 4.1.3 on 2022-12-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_annualcropping_ha_start_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualcropping',
            old_name='main_tillage_factor',
            new_name='main_tillage_factor_t2',
        ),
    ]
