# Generated by Django 4.2.1 on 2024-04-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_forestmanagement_logging_recurrence_yrs_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='ha_start',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='ha_thread',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='ha_w',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='ha_wo',
        ),
    ]
