# Generated by Django 4.1.3 on 2022-11-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_ipcccombustionfactorvalues_forest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipcccombustionfactorvalues',
            old_name='forest',
            new_name='vegetation_type',
        ),
    ]
