# Generated by Django 4.2.1 on 2024-04-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_settlement_ha_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='building',
            name='biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='building',
            name='biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='building',
            name='biomass_t2_wo',
        ),
        migrations.RemoveField(
            model_name='building',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='building',
            name='soc_t2_start',
        ),
        migrations.RemoveField(
            model_name='building',
            name='soc_t2_w',
        ),
        migrations.RemoveField(
            model_name='building',
            name='soc_t2_wo',
        ),
        migrations.RemoveField(
            model_name='building',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='building',
            name='status',
        ),
        migrations.RemoveField(
            model_name='otherinfrastructure',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='otherinfrastructure',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='otherinfrastructure',
            name='soc_t2_start',
        ),
        migrations.RemoveField(
            model_name='otherinfrastructure',
            name='soc_t2_w',
        ),
        migrations.RemoveField(
            model_name='otherinfrastructure',
            name='soc_t2_wo',
        ),
        migrations.RemoveField(
            model_name='otherinfrastructure',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='otherinfrastructure',
            name='status',
        ),
        migrations.RemoveField(
            model_name='road',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='road',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='road',
            name='soc_t2_start',
        ),
        migrations.RemoveField(
            model_name='road',
            name='soc_t2_w',
        ),
        migrations.RemoveField(
            model_name='road',
            name='soc_t2_wo',
        ),
        migrations.RemoveField(
            model_name='road',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='road',
            name='status',
        ),
    ]
