# Generated by Django 4.1.3 on 2022-12-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_main_tillage_factor_annualcropping_main_tillage_factor_t2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rewetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_w', models.IntegerField(blank=True, null=True)),
                ('ha_wo', models.IntegerField(blank=True, null=True)),
                ('restored_biomass_percentage_w', models.FloatField(blank=True, null=True)),
                ('restored_biomass_percentage_wo', models.FloatField(blank=True, null=True)),
                ('ag_t2', models.FloatField(blank=True, null=True)),
                ('bg_t2', models.FloatField(blank=True, null=True)),
                ('litter_t2', models.FloatField(blank=True, null=True)),
                ('deadwood_t2', models.FloatField(blank=True, null=True)),
                ('ef_co2_t2', models.FloatField(blank=True, null=True)),
                ('ef_ch4_t2', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('avg_salinity_t2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salinity')),
                ('ha_w_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate')),
                ('ha_wo_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changerate')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_start', models.IntegerField(blank=True, null=True)),
                ('ha_w_excavated_percentage', models.FloatField(blank=True, null=True)),
                ('ha_wo_excavated_percentage', models.FloatField(blank=True, null=True)),
                ('extracted_ag_t2', models.FloatField(blank=True, null=True)),
                ('extracted_bg_t2', models.FloatField(blank=True, null=True)),
                ('extracted_litter_t2', models.FloatField(blank=True, null=True)),
                ('extracted_deadwood_t2', models.FloatField(blank=True, null=True)),
                ('extracted_soil_t2', models.FloatField(blank=True, null=True)),
                ('c_after_excavation_t2', models.FloatField(blank=True, null=True)),
                ('drained_percentage_start', models.FloatField(blank=True, null=True)),
                ('drained_percentage_w', models.FloatField(blank=True, null=True)),
                ('drained_percentage_wo', models.FloatField(blank=True, null=True)),
                ('drained_ag_t2', models.FloatField(blank=True, null=True)),
                ('drained_bg_t2', models.FloatField(blank=True, null=True)),
                ('drained_litter_t2', models.FloatField(blank=True, null=True)),
                ('drained_deadwood_t2', models.FloatField(blank=True, null=True)),
                ('drained_soil_t2', models.FloatField(blank=True, null=True)),
                ('ef_drainage_t2', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('drained_soil_type_t2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_drained_soil_type_t2', to='api.soiltype')),
                ('extracted_soil_type_t2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_extracted_soil_type_t2', to='api.soiltype')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoastalWaterbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_start', models.IntegerField(blank=True, null=True)),
                ('ha_w', models.IntegerField(blank=True, null=True)),
                ('ha_wo', models.IntegerField(blank=True, null=True)),
                ('ch4_start_t2', models.FloatField(blank=True, null=True)),
                ('ch4_w_t2', models.FloatField(blank=True, null=True)),
                ('ch4_wo_t2', models.FloatField(blank=True, null=True)),
                ('trophic_alpha_t2', models.FloatField(blank=True, null=True)),
                ('trophic_mean_annual_t2', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('ha_w_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate')),
                ('ha_wo_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changerate')),
                ('trophic_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trophictype')),
                ('waterbody_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.waterbodytype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
