# Generated by Django 4.2.1 on 2024-04-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_building_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='settlement',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='otherinfrastructure',
            old_name='settlement',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='settlement',
            new_name='parent',
        ),
    ]
