# Generated by Django 4.1.3 on 2022-12-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_salinity_rewetting_extraction_coastalwaterbody'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraction',
            old_name='drained_ag_t2',
            new_name='drainage_ag_t2',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='drained_bg_t2',
            new_name='drainage_bg_t2',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='drained_deadwood_t2',
            new_name='drainage_deadwood_t2',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='drained_litter_t2',
            new_name='drainage_litter_t2',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='drained_percentage_start',
            new_name='drainage_percentage_start',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='drained_percentage_w',
            new_name='drainage_percentage_w',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='drained_percentage_wo',
            new_name='drainage_percentage_wo',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='drained_soil_t2',
            new_name='drainage_soil_t2',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='drained_soil_type_t2',
            new_name='drainage_soil_type_t2',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='extracted_ag_t2',
            new_name='extraction_ag_t2',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='extracted_bg_t2',
            new_name='extraction_bg_t2',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='extracted_deadwood_t2',
            new_name='extraction_deadwood_t2',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='extracted_litter_t2',
            new_name='extraction_litter_t2',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='extracted_soil_t2',
            new_name='extraction_soil_t2',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='extracted_soil_type_t2',
            new_name='extraction_soil_type_t2',
        ),
    ]
