# Generated by Django 4.1.3 on 2022-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_perennialcrop_luc_deforestationinput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deforestationinput',
            name='final_rfc_biomass_t2',
            field=models.FloatField(blank=True, help_text='The average annual rate of carbon sequestration in the biomass of the agroforestry system (t C/ha/yr)', null=True),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='final_rfc_soil_c_t2',
            field=models.FloatField(blank=True, help_text='The average annual rate of carbon sequestration in the soil of the agroforestry system (t C/ha/yr)', null=True),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='rfc_ag_t2',
            field=models.FloatField(blank=True, help_text='The average annual rate of carbon sequestration in the aboveground biomass of the agroforestry system (t C/ha/yr)', null=True),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='rfc_deadwood_t2',
            field=models.FloatField(blank=True, help_text='The average annual rate of carbon sequestration in the deadwood of the agroforestry system (t C/ha/yr)', null=True),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='rfc_litter_t2',
            field=models.FloatField(blank=True, help_text='The average annual rate of carbon sequestration in the litter of the agroforestry system (t C/ha/yr)', null=True),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='rfc_soil_c_t2',
            field=models.FloatField(blank=True, help_text='The average annual rate of carbon sequestration in the soil of the agroforestry system (t C/ha/yr)', null=True),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='rfg_bg_t2',
            field=models.FloatField(blank=True, help_text='The average annual rate of carbon sequestration in the belowground biomass of the agroforestry system (t C/ha/yr)', null=True),
        ),
    ]
