# Generated by Django 4.1.3 on 2022-11-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_deforestationinput_final_rfc_biomass_t2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcrop',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
