# Generated by Django 4.2.1 on 2024-04-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_settlement_building_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='inputentry',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='minorseasonannualcropping',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
        migrations.AddField(
            model_name='road',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
    ]
