# Generated by Django 4.1.3 on 2023-02-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_drained_ag_t2_extraction_drainage_ag_t2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisheryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='extraction',
            name='drainage_percentage_w_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_drainage_percentage_w_rate', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='extraction',
            name='drainage_percentage_wo_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_drainage_percentage_wo_rate', to='api.changerate'),
        ),
        migrations.CreateModel(
            name='SmallFisheryFUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('fishery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fisherytype')),
                ('gear_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.geartype')),
            ],
        ),
        migrations.CreateModel(
            name='SmallFishery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrigerant_pc_start', models.FloatField(blank=True, null=True)),
                ('refrigerant_pc_w', models.FloatField(blank=True, null=True)),
                ('refrigerant_pc_wo', models.FloatField(blank=True, null=True)),
                ('refrigerant_gwp', models.FloatField(blank=True, default=1810, null=True)),
                ('fui_start', models.FloatField(blank=True, null=True)),
                ('fui_w', models.FloatField(blank=True, null=True)),
                ('fui_wo', models.FloatField(blank=True, null=True)),
                ('total_catch_yr_start', models.FloatField(blank=True, null=True)),
                ('total_catch_yr_w', models.FloatField(blank=True, null=True)),
                ('total_catch_yr_wo', models.FloatField(blank=True, null=True)),
                ('ice_preserved_catch_pc_start', models.FloatField(blank=True, null=True)),
                ('ice_preserved_catch_pc_w', models.FloatField(blank=True, null=True)),
                ('ice_preserved_catch_pc_wo', models.FloatField(blank=True, null=True)),
                ('energy_emission_factor_t2', models.FloatField(blank=True, null=True)),
                ('refrigerant_lost_per_tonne_t2', models.FloatField(blank=True, null=True)),
                ('refrigerant_gwp_t2', models.FloatField(blank=True, null=True)),
                ('inshore_ice_production_emissions_t2', models.FloatField(blank=True, null=True)),
                ('inshore_ice_production_kwh_per_tonne_t2', models.FloatField(blank=True, null=True)),
                ('implementation_year_t2', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('fishery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fisherytype')),
                ('fui_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.smallfisheryfui')),
                ('gear_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.geartype')),
                ('inshore_ice_production_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('total_catch_yr_w_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_total_catch_yr_w_rate', to='api.changerate')),
                ('total_catch_yr_wo_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_total_catch_yr_wo_rate', to='api.changerate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LargeFisheryFUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fishtype')),
                ('gear_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.geartype')),
            ],
        ),
        migrations.CreateModel(
            name='LargeFishery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrigerant_pc_start', models.FloatField(blank=True, null=True)),
                ('refrigerant_pc_w', models.FloatField(blank=True, null=True)),
                ('refrigerant_pc_wo', models.FloatField(blank=True, null=True)),
                ('refrigerant_gwp', models.FloatField(blank=True, default=1810, null=True)),
                ('fui_start', models.FloatField(blank=True, null=True)),
                ('fui_w', models.FloatField(blank=True, null=True)),
                ('fui_wo', models.FloatField(blank=True, null=True)),
                ('total_catch_yr_start', models.FloatField(blank=True, null=True)),
                ('total_catch_yr_w', models.FloatField(blank=True, null=True)),
                ('total_catch_yr_wo', models.FloatField(blank=True, null=True)),
                ('ice_preserved_catch_pc_start', models.FloatField(blank=True, null=True)),
                ('ice_preserved_catch_pc_w', models.FloatField(blank=True, null=True)),
                ('ice_preserved_catch_pc_wo', models.FloatField(blank=True, null=True)),
                ('energy_emission_factor_t2', models.FloatField(blank=True, null=True)),
                ('refrigerant_lost_per_tonne_t2', models.FloatField(blank=True, null=True)),
                ('refrigerant_gwp_t2', models.FloatField(blank=True, null=True)),
                ('inshore_ice_production_emissions_t2', models.FloatField(blank=True, null=True)),
                ('inshore_ice_production_kwh_per_tonne_t2', models.FloatField(blank=True, null=True)),
                ('implementation_year_t2', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('fishery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fisherytype')),
                ('fui_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.largefisheryfui')),
                ('gear_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.geartype')),
                ('inshore_ice_production_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('total_catch_yr_w_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_total_catch_yr_w_rate', to='api.changerate')),
                ('total_catch_yr_wo_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_total_catch_yr_wo_rate', to='api.changerate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectricityEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ef_grid', models.FloatField(blank=True, null=True)),
                ('final_ef_grid', models.FloatField(blank=True, null=True)),
                ('operating_margin', models.FloatField(blank=True, null=True)),
                ('combined_margin', models.FloatField(blank=True, null=True)),
                ('for_formulas', models.FloatField(blank=True, null=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='Aquaculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('annual_feed_quantity_start', models.FloatField(blank=True, null=True)),
                ('annual_feed_quantity_w', models.FloatField(blank=True, null=True)),
                ('annual_feed_quantity_wo', models.FloatField(blank=True, null=True)),
                ('annual_production_start', models.FloatField(blank=True, null=True)),
                ('annual_production_w', models.FloatField(blank=True, null=True)),
                ('annual_production_wo', models.FloatField(blank=True, null=True)),
                ('feed_use_emissions_t2', models.FloatField(blank=True, null=True)),
                ('production_n2o_ef_t2', models.FloatField(blank=True, null=True)),
                ('implementation_year_t2', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('annual_feed_quantity_w_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_annual_feed_quantity_w_rate', to='api.changerate')),
                ('annual_feed_quantity_wo_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_annual_feed_quantity_wo_rate', to='api.changerate')),
                ('annual_production_w_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_annual_production_w_rate', to='api.changerate')),
                ('annual_production_wo_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_annual_production_wo_rate', to='api.changerate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
