# Generated by Django 4.1.3 on 2023-02-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_fisherytype_fishtype_geartype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalinityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3)),
            ],
        ),
    ]
