# Generated by Django 4.1.3 on 2022-11-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_annualcrop_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestationinput',
            old_name='deforested_vegetation_type',
            new_name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='ipcctotalbiomassafterdefo',
            name='agroforestry_system',
        ),
        migrations.AddField(
            model_name='ipcctotalbiomassafterdefo',
            name='vegetation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
            preserve_default=False,
        ),
    ]
