# Generated by Django 4.2.1 on 2024-04-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_building_status_electricity_status_fuel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherinfrastructure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_infrastructures', to='api.settlement'),
        ),
    ]
