# Generated by Django 4.1.3 on 2023-02-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_salinitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='deforestation',
            name='module_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
    ]
