# Generated by Django 4.2.1 on 2024-04-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_otherinfrastructure_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='mwh_renewables_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_mwh_renewables_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='mwh_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_mwh_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='fuel_consumption_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_consumption_thread', to='api.commentthread'),
        ),
    ]
