# Generated by Django 4.1.3 on 2022-11-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_deforested_vegetation_type_deforestationinput_vegetation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcclandusestockexchangefactor',
            name='agroforestry_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
    ]
