# Generated by Django 4.1.3 on 2022-11-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_ipcclandusestockexchangefactor_agroforestry_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestationinput',
            old_name='final_land_use_type',
            new_name='land_use_type',
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='ha_w_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic'),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changedynamic'),
        ),
        migrations.AlterField(
            model_name='deforestationinput',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.CreateModel(
            name='OtherLandUseChangeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fire_used', models.BooleanField(default=False)),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('final_land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_final_land_use_type', to='api.landusetype')),
                ('ha_w_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic')),
                ('ha_wo_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changedynamic')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AfforestationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fire_used', models.BooleanField(default=False)),
                ('ha_w', models.IntegerField()),
                ('ha_wo', models.IntegerField()),
                ('ha_w_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changedynamic')),
                ('ha_wo_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changedynamic')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
