# Generated by Django 4.2.1 on 2024-04-09 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_electricity_mwh_renewables_thread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_type_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_building_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='gross_irrigation_water_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_gross_irrigation_water_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='ha_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='ha_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='road',
            name='road_type_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_road_type_thread', to='api.commentthread'),
        ),
    ]
