# Generated by Django 4.1.3 on 2023-02-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_deforestation_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='afforestation',
            name='module_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
    ]
