# Generated by Django 4.1.3 on 2022-11-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_final_land_use_type_deforestationinput_land_use_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUseMacroType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='landusetype',
            name='input_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusemacrotype'),
        ),
    ]
