# Generated by Django 4.1.3 on 2023-02-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_afforestation_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualcropping',
            name='module_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='module_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
    ]
