# Generated by Django 4.2.1 on 2024-04-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_building_building_type_thread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Config parameters',
            },
        ),
    ]
