# Generated by Django 4.1.3 on 2022-11-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_landusemacrotype_landusetype_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landusetype',
            name='input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusemacrotype'),
        ),
    ]
