# Generated by Django 4.2.1 on 2024-04-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_configparams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigParams',
            new_name='ConfigParam',
        ),
    ]
