# Generated by Django 4.1.3 on 2023-02-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_annualcropping_module_type_otherlanduse_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='afforestationsoilmanagement',
            name='module_type',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='module_type',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='coastalwaterbody',
            name='module_type',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='deforestationsoilmanagement',
            name='module_type',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='extraction',
            name='module_type',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='module_type',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='forest',
            name='module_type',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='forestlandmanagement',
            name='module_type',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='module_type',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='inlandwaterbody',
            name='module_type',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='module_type',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='module_type',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='otherlandmanagement',
            name='module_type',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='otherlandusesoilmanagement',
            name='module_type',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='peatextractionlandmanagement',
            name='module_type',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='module_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='rewetting',
            name='module_type',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='module_type',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
    ]
