# Generated by Django 4.1.3 on 2022-11-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_landusetype_input_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandUseMacroType',
            new_name='LandUseChildrenType',
        ),
        migrations.RenameField(
            model_name='landusetype',
            old_name='input_type',
            new_name='children_type',
        ),
    ]
