# Generated by Django 4.1.3 on 2023-02-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_afforestationsoilmanagement_module_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afforestation',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='afforestationsoilmanagement',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='aquaculture',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='coastalwaterbody',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='deforestation',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='deforestationsoilmanagement',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='forest',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='forestlandmanagement',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='inlandwaterbody',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='largefishery',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='otherlandmanagement',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='otherlanduse',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='otherlandusesoilmanagement',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='peatextractionlandmanagement',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='rewetting',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='smallfishery',
            name='module_type',
        ),
    ]
