# Generated by Django 4.2.1 on 2024-04-09 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_configparams_configparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='landusechange',
            name='dry_matter_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_use_change_dry_matter_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='is_fire_used_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_use_change_is_fire_used_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='module_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_use_change_module_type_thread', to='api.commentthread'),
        ),
    ]
