# Generated by Django 4.2.1 on 2024-04-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_landusechange_dry_matter_thread_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configparam',
            options={'verbose_name_plural': 'Configuration parameters'},
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='soc_ref_t2_start',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='soc_ref_t2_w',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='soc_ref_t2_wo',
        ),
    ]
