# Generated by Django 4.1.3 on 2023-02-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_afforestation_module_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewetting',
            name='avg_salinity_t2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salinitytype'),
        ),
        migrations.DeleteModel(
            name='Salinity',
        ),
    ]
