# Generated by Django 4.1.3 on 2022-11-23 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_landusemacrotype_landusechildrentype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landusetype',
            name='children_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusechildrentype'),
        ),
    ]
