# Generated by Django 4.1.3 on 2023-02-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_rewetting_avg_salinity_t2_delete_salinity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='c_after_excavation_t2',
            field=models.FloatField(blank=True, default=0.96, null=True),
        ),
    ]
