# Generated by Django 4.2.1 on 2024-04-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_configparam_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organicsoil',
            old_name='offsite_ch4_peat_t2',
            new_name='offsite_ch4_peat_t2_start',
        ),
        migrations.RenameField(
            model_name='organicsoil',
            old_name='offsite_doc_peat_t2',
            new_name='offsite_ch4_peat_t2_w',
        ),
        migrations.RenameField(
            model_name='organicsoil',
            old_name='onsite_ch4_peat_t2',
            new_name='offsite_ch4_peat_t2_wo',
        ),
        migrations.RenameField(
            model_name='organicsoil',
            old_name='onsite_co2_peat_t2',
            new_name='offsite_doc_peat_t2_start',
        ),
        migrations.RenameField(
            model_name='organicsoil',
            old_name='onsite_n2o_peat_t2',
            new_name='offsite_doc_peat_t2_w',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='peat_type_start',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='peat_type_w',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='peat_type_wo',
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='offsite_doc_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_peat_type', to='api.peattype'),
        ),
    ]
