# Generated by Django 4.2.1 on 2024-04-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_offsite_ch4_peat_t2_organicsoil_offsite_ch4_peat_t2_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorseasonannualcropping',
            name='residue_management_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='minorseasonannualcropping',
            name='yield_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_yield_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='residue_management_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='yield_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_yield_thread', to='api.commentthread'),
        ),
    ]
