# Generated by Django 4.1.3 on 2022-11-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_landusetype_children_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='landusetype',
            name='is_father',
            field=models.BooleanField(default=False),
        ),
    ]
