# Generated by Django 4.1.3 on 2022-11-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_landusetype_is_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landusetype',
            name='children_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
    ]
