# Generated by Django 4.2.1 on 2024-04-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_minorseasonannualcropping_residue_management_type_thread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestdisturbance',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
    ]
