# Generated by Django 4.1.3 on 2023-02-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_country_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='perennialcropping',
            name='ag_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='bg_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='fire_periodicity_t2',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='ha_start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='ha_w',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='ha_w_rate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='ha_wo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='ha_wo_rate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changerate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='input_factor_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='residue_burned_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='sc_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_factor_t2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
