# Generated by Django 4.2.1 on 2024-04-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_forestdisturbance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forestdisturbance',
            old_name='forest_management',
            new_name='parent',
        ),
    ]
