# Generated by Django 4.1.3 on 2023-02-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_perennialcropping_ag_t2_perennialcropping_bg_t2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perennialcropping',
            old_name='sc_t2',
            new_name='soc_t2',
        ),
    ]
