# Generated by Django 4.1.3 on 2022-11-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_landusetype_children_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landusetype',
            name='is_father',
        ),
    ]
