# Generated by Django 4.1.3 on 2022-11-24 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_landusetype_is_father'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landusetype',
            name='children_type',
        ),
        migrations.AddField(
            model_name='landusetype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.landusetype'),
        ),
    ]
