# Generated by Django 4.2.1 on 2024-04-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_forest_management_forestdisturbance_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organicsoil',
            old_name='peat_density_t2',
            new_name='peat_density_t2_start',
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_density_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_density_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
