# Generated by Django 4.1.3 on 2023-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_sc_t2_perennialcropping_soc_t2'),
    ]

    operations = [
        migrations.AddField(
            model_name='perennialcropping',
            name='flu_t2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
