# Generated by Django 4.2.1 on 2024-05-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_peat_density_t2_organicsoil_peat_density_t2_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaculture',
            name='electricity_ef_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='electricity_ef_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='electricity_ef_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
