# Generated by Django 4.1.3 on 2023-02-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_perennialcropping_flu_t2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perennialcropping',
            name='fire_periodicity_t2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
