# Generated by Django 4.1.3 on 2022-11-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_landusetype_children_type_landusetype_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandUseChildrenType',
        ),
    ]
