# Generated by Django 4.1.3 on 2022-11-24 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_delete_landusechildrentype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipccsoilorcaniccarboncnratio',
            name='agroforestry_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
    ]
