# Generated by Django 4.1.3 on 2023-02-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_perennialcropping_fire_periodicity_t2'),
    ]

    operations = [
        migrations.AddField(
            model_name='afforestation',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='afforestationsoilmanagement',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='coastalwaterbody',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='deforestationsoilmanagement',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='extraction',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='forest',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='forestlandmanagement',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='inlandwaterbody',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='otherlandmanagement',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='otherlandusesoilmanagement',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='peatextractionlandmanagement',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='rewetting',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='parent_module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
    ]
