# Generated by Django 4.2.1 on 2024-05-02 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_aquaculture_electricity_ef_t2_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="uid",
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator("^[0-9a-zA-Z]*$", "Only alphanumeric characters are allowed.")], null=True, verbose_name="UID"),
            preserve_default=False,
        ),
    ]
