# Generated by Django 4.1.3 on 2022-11-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_ipccsoilorcaniccarboncnratio_agroforestry_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipccsoilorcaniccarboncnratio',
            old_name='agroforestry_system',
            new_name='land_use_type',
        ),
    ]
