# Generated by Django 4.2.1 on 2024-05-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_customuser_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uid',
            new_name='firebase_uid',
        ),
    ]
