# Generated by Django 4.1.3 on 2022-11-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_rename_agroforestry_system_ipccsoilorcaniccarboncnratio_land_use_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualcrop',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='annualcrop',
            name='luc',
        ),
        migrations.RemoveField(
            model_name='annualcrop',
            name='organic_input_type',
        ),
        migrations.RemoveField(
            model_name='annualcrop',
            name='residue_management_type',
        ),
        migrations.RemoveField(
            model_name='annualcrop',
            name='tillage_type',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='ha_w_rate',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='ha_wo_rate',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='organic_amendment_type',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='pre_season_water_regime_type',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='water_regime_type',
        ),
        migrations.DeleteModel(
            name='Forest',
        ),
        migrations.RemoveField(
            model_name='perennialcrop',
            name='agroforestry_system_type',
        ),
        migrations.RemoveField(
            model_name='perennialcrop',
            name='defo_id',
        ),
        migrations.RemoveField(
            model_name='perennialcrop',
            name='ha_w_rate',
        ),
        migrations.RemoveField(
            model_name='perennialcrop',
            name='ha_wo_rate',
        ),
        migrations.RemoveField(
            model_name='perennialcrop',
            name='organic_input_type',
        ),
        migrations.RemoveField(
            model_name='perennialcrop',
            name='tillage_type',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='final_rfc_biomass_t2',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='final_rfc_soil_c_t2',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='rfc_ag_t2',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='rfc_deadwood_t2',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='rfc_litter_t2',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='rfc_soil_c_t2',
        ),
        migrations.RemoveField(
            model_name='deforestationinput',
            name='rfg_bg_t2',
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='final_rcs_biomass_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for biomass in final land use (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='final_rcs_soil_c_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon in final land use (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='rcs_ag_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for above-ground biomass (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='rcs_bg_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for below-ground biomass (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='rcs_deadwood_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for deadwood (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='rcs_litter_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for litter (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestationinput',
            name='rcs_soil_c_t2',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon (in tC/ha)', null=True),
        ),
        migrations.AlterField(
            model_name='ipccsoilorcaniccarboncnratio',
            name='land_use_type',
            field=models.ForeignKey(limit_choices_to={'parent': None}, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AlterField(
            model_name='landusetype',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.landusetype'),
        ),
        migrations.DeleteModel(
            name='AgroforestrySystemType',
        ),
        migrations.DeleteModel(
            name='AnnualCrop',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='FloodedRice',
        ),
        migrations.DeleteModel(
            name='PerennialCrop',
        ),
    ]
