# Generated by Django 4.2.1 on 2024-05-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_rename_uid_customuser_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firebase_uid',
        ),
    ]
