# Generated by Django 4.1.3 on 2023-02-24 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_afforestation_parent_module_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='parent_afforestation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assessment', to='api.afforestation'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='parent_deforestation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assessment', to='api.deforestation'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='parent_other_land_use',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assessment', to='api.otherlanduse'),
        ),
    ]
