# Generated by Django 4.1.3 on 2023-02-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_grassland_parent_afforestation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherlandmanagement',
            old_name='rewitting_n2o_t2',
            new_name='rewetting_n2o_t2',
        ),
        migrations.RenameField(
            model_name='otherlandmanagement',
            old_name='rewitting_offsite_doc_t2',
            new_name='rewetting_offsite_doc_t2',
        ),
        migrations.RenameField(
            model_name='otherlandmanagement',
            old_name='rewitting_onsite_ch4_t2',
            new_name='rewetting_onsite_ch4_t2',
        ),
        migrations.RenameField(
            model_name='otherlandmanagement',
            old_name='rewitting_onsite_co2_t2',
            new_name='rewetting_onsite_co2_t2',
        ),
        migrations.AddField(
            model_name='afforestation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationsoilmanagement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coastalwaterbody',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deforestationsoilmanagement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestlandmanagement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inlandwaterbody',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherlandmanagement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherlandusesoilmanagement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionlandmanagement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewetting',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afforestation',
            name='ha_w',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='afforestation',
            name='ha_wo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='afforestationsoilmanagement',
            name='ha_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afforestationsoilmanagement',
            name='ha_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='ha_start',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='ha_w',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='ha_wo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coastalwaterbody',
            name='ha_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwaterbody',
            name='ha_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwaterbody',
            name='ha_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deforestation',
            name='ha_start',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deforestation',
            name='ha_w',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deforestation',
            name='ha_wo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deforestationsoilmanagement',
            name='ha_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deforestationsoilmanagement',
            name='ha_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deforestationsoilmanagement',
            name='ha_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forest',
            name='ha_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forest',
            name='ha_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forest',
            name='ha_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestlandmanagement',
            name='ha_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inlandwaterbody',
            name='ha_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inlandwaterbody',
            name='ha_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inlandwaterbody',
            name='ha_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherlandmanagement',
            name='drainage_ha_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherlandmanagement',
            name='drainage_ha_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherlandmanagement',
            name='drainage_ha_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherlandmanagement',
            name='land_use_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherlanduse',
            name='ha_w',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='otherlanduse',
            name='ha_wo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='otherlandusesoilmanagement',
            name='ha_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherlandusesoilmanagement',
            name='ha_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peatextractionlandmanagement',
            name='ha_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peatextractionlandmanagement',
            name='ha_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peatextractionlandmanagement',
            name='ha_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='ha_start',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='ha_w',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='ha_wo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rewetting',
            name='ha_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewetting',
            name='ha_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
