# Generated by Django 4.2.1 on 2024-05-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_customuser_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_biomass_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_biomass_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_biomass_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_land_use_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_land_use_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_land_use_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_organic_input_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_organic_input_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_organic_input_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_soil_carbon_t2_start',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_soil_carbon_t2_w',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_soil_carbon_t2_wo',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_tillage_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_tillage_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='main_tillage_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonannualcropping',
            name='biomass_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonannualcropping',
            name='biomass_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonannualcropping',
            name='biomass_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='biomass_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='biomass_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='biomass_factor_t2_wo',
        ),
        migrations.AddField(
            model_name='minorseasonannualcropping',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonannualcropping',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonannualcropping',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropping',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
