# Generated by Django 4.2.1 on 2024-05-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_annualcropping_main_biomass_factor_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minorseasonannualcropping',
            old_name='yield_start',
            new_name='crop_yield_start',
        ),
        migrations.RenameField(
            model_name='minorseasonannualcropping',
            old_name='yield_w',
            new_name='crop_yield_w',
        ),
        migrations.RenameField(
            model_name='minorseasonannualcropping',
            old_name='yield_wo',
            new_name='crop_yield_wo',
        ),
        migrations.RenameField(
            model_name='minorseasonperennialcropping',
            old_name='yield_start',
            new_name='crop_yield_start',
        ),
        migrations.RenameField(
            model_name='minorseasonperennialcropping',
            old_name='yield_w',
            new_name='crop_yield_w',
        ),
        migrations.RenameField(
            model_name='minorseasonperennialcropping',
            old_name='yield_wo',
            new_name='crop_yield_wo',
        ),
    ]
