# Generated by Django 4.1.3 on 2023-02-27 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_rename_rewitting_n2o_t2_otherlandmanagement_rewetting_n2o_t2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='ha_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='ha_w_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grassland',
            name='ha_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='ha_wo_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changerate'),
            preserve_default=False,
        ),
    ]
