# Generated by Django 4.1.3 on 2023-02-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_grassland_ha_w_grassland_ha_w_rate_grassland_ha_wo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='is_fire_used_w',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grassland',
            name='is_fire_used_wo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grassland',
            name='ha_wo_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changerate'),
        ),
    ]
