# Generated by Django 4.2.1 on 2024-05-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_rename_yield_start_minorseasonannualcropping_crop_yield_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minorseasonannualcropping',
            old_name='yield_thread',
            new_name='crop_yield_thread',
        ),
        migrations.RenameField(
            model_name='minorseasonperennialcropping',
            old_name='yield_thread',
            new_name='crop_yield_thread',
        ),
    ]
