# Generated by Django 4.2.1 on 2024-05-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_rename_yield_thread_minorseasonannualcropping_crop_yield_thread_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodedrice',
            name='land_use_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='land_use_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='land_use_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='main_biomass_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='main_biomass_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='main_biomass_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='land_use_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='land_use_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='land_use_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='main_biomass_factor_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='main_biomass_factor_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='main_biomass_factor_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='soc_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='soc_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='soc_t2_wo',
        ),
    ]
