# Generated by Django 4.1.3 on 2023-02-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_grassland_is_fire_used_w_grassland_is_fire_used_wo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grassland',
            old_name='grassland_at_start',
            new_name='grassland_management_type_start',
        ),
        migrations.RenameField(
            model_name='grassland',
            old_name='grassland_without',
            new_name='grassland_management_type_w',
        ),
        migrations.RenameField(
            model_name='grassland',
            old_name='grassland_with',
            new_name='grassland_management_type_wo',
        ),
    ]
