# Generated by Django 4.2.1 on 2024-05-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_floodedrice_land_use_factor_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodedrice',
            name='cultivation_period_start',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='cultivation_period_w',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='cultivation_period_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='cultivation_period_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='cultivation_period_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='cultivation_period_wo',
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='cultivation_period_t2_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='cultivation_period_t2_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='cultivation_period_t2_wo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='cultivation_period_t2_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='cultivation_period_t2_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='cultivation_period_t2_wo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
