# Generated by Django 4.1.3 on 2023-02-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_rename_grassland_at_start_grassland_grassland_management_type_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='electricityemission',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='electricityemission',
            name='country',
        ),
        migrations.RemoveField(
            model_name='largefisheryfui',
            name='fish_type',
        ),
        migrations.RemoveField(
            model_name='largefisheryfui',
            name='gear_type',
        ),
        migrations.RemoveField(
            model_name='smallfisheryfui',
            name='fishery_type',
        ),
        migrations.RemoveField(
            model_name='smallfisheryfui',
            name='gear_type',
        ),
    ]
