# Generated by Django 4.2.1 on 2024-05-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_floodedrice_cultivation_period_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='building_type_start',
        ),
        migrations.RemoveField(
            model_name='building',
            name='building_type_w',
        ),
        migrations.RemoveField(
            model_name='building',
            name='building_type_wo',
        ),
        migrations.RemoveField(
            model_name='road',
            name='road_type_start',
        ),
        migrations.RemoveField(
            model_name='road',
            name='road_type_w',
        ),
        migrations.RemoveField(
            model_name='road',
            name='road_type_wo',
        ),
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_building_type', to='api.buildingtype'),
        ),
        migrations.AddField(
            model_name='road',
            name='road_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_road_type', to='api.roadtype'),
        ),
    ]
