# Generated by Django 4.1.3 on 2023-02-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0032_smallfisheryfui_largefisheryfui_and_more'),
        ('api', '0050_fueltype_remove_electricityemission_continent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largefishery',
            name='fui_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcc.largefisheryfui'),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='fui_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcc.smallfisheryfui'),
        ),
        migrations.DeleteModel(
            name='ElectricityEmission',
        ),
        migrations.DeleteModel(
            name='LargeFisheryFUI',
        ),
        migrations.DeleteModel(
            name='SmallFisheryFUI',
        ),
    ]
