# Generated by Django 4.2.1 on 2024-05-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_building_building_type_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coastalwetland',
            old_name='ha_start',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='coastalwetland',
            name='ha_w',
        ),
        migrations.RemoveField(
            model_name='coastalwetland',
            name='ha_wo',
        ),
    ]
