# Generated by Django 4.1.3 on 2023-02-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_largefishery_fui_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255)),
                ('module_id', models.IntegerField()),
                ('old_module', models.JSONField()),
                ('new_module', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
