# Generated by Django 4.2.1 on 2024-05-13 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_rename_ha_start_coastalwetland_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Firebase UID'),
        ),
    ]
