# Generated by Django 4.1.3 on 2023-02-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_modulechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulechange',
            name='field_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulechange',
            name='new_value',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulechange',
            name='old_value',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
