# Generated by Django 4.1.3 on 2023-02-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_modulechange_field_name_modulechange_new_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulechange',
            name='new_module',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulechange',
            name='new_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modulechange',
            name='old_module',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulechange',
            name='old_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
