# Generated by Django 4.2.1 on 2024-05-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_customuser_firebase_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_view_modules', 'Can view modules'), ('can_add_modules', 'Can add modules'), ('can change_modules', 'Can change modules'), ('can delete_modules', 'Can delete modules'))},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
