# Generated by Django 4.1.3 on 2023-02-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_modulechange_new_module_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuleChange',
            new_name='DataChange',
        ),
    ]
