# Generated by Django 4.2.1 on 2024-05-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_customuser_options_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectinvitation',
            unique_together={('project', 'user', 'group')},
        ),
    ]
