# Generated by Django 4.2.1 on 2024-06-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_projectinvitation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='completion_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
