# Generated by Django 4.1.3 on 2023-02-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_rename_modulechange_datachange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataChange',
        ),
    ]
