# Generated by Django 4.2.1 on 2024-06-07 09:39

import api.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_activity_completion_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.ForeignKey(blank=True, default=api.utilities.get_activity_default_status, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statustype'),
        ),
    ]
