# Generated by Django 4.1.3 on 2023-02-27 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_afforestation_created_at_afforestation_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='largefishery',
            name='fishery_type',
        ),
        migrations.AddField(
            model_name='largefishery',
            name='fish_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.fishtype'),
            preserve_default=False,
        ),
    ]
