# Generated by Django 4.2.1 on 2024-06-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_activity_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricity',
            old_name='ef_t2',
            new_name='ef_t2_start',
        ),
        migrations.RenameField(
            model_name='electricity',
            old_name='transmission_loss',
            new_name='transmission_loss_start',
        ),
        migrations.AddField(
            model_name='electricity',
            name='ef_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='ef_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='transmission_loss_w',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='electricity',
            name='transmission_loss_wo',
            field=models.FloatField(default=0.1),
        ),
    ]
