# Generated by Django 4.1.3 on 2023-02-28 16:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_remove_largefishery_fishery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_start', to='api.grasslandmanagementtype'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_without', to='api.grasslandmanagementtype'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_with', to='api.grasslandmanagementtype'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='ha_w_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='ha_wo_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changerate'),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='ice_preserved_catch_pc_start',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='ice_preserved_catch_pc_w',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='ice_preserved_catch_pc_wo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='refrigerant_pc_start',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='refrigerant_pc_w',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='refrigerant_pc_wo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='ice_preserved_catch_pc_start',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='ice_preserved_catch_pc_w',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='ice_preserved_catch_pc_wo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='refrigerant_pc_start',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='refrigerant_pc_w',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='refrigerant_pc_wo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
    ]
