# Generated by Django 4.2.1 on 2024-06-25 09:14

import api.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_rename_ef_t2_electricity_ef_t2_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_type',
            field=models.ForeignKey(blank=True, default=api.utilities.get_default_peat_type, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_peat_type', to='api.peattype'),
        ),
    ]
