# Generated by Django 4.1.3 on 2023-03-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_grassland_grassland_management_type_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestdegradationlevel',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
