# Generated by Django 4.2.1 on 2024-06-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_organicsoil_peat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualcropping',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.organicsoil'),
        ),
        migrations.AddField(
            model_name='degradedland',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.organicsoil'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.organicsoil'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.organicsoil'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.organicsoil'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organicsoil'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.organicsoil'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.organicsoil'),
        ),
        migrations.AddField(
            model_name='setaside',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.organicsoil'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.organicsoil'),
        ),
    ]
