# Generated by Django 4.1.3 on 2023-03-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_forestdegradationlevel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest',
            name='degradation_level_start_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_start_t2', to='api.forestdegradationlevel'),
        ),
        migrations.AlterField(
            model_name='forest',
            name='degradation_level_w_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_w_t2', to='api.forestdegradationlevel'),
        ),
        migrations.AlterField(
            model_name='forest',
            name='degradation_level_wo_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_wo_t2', to='api.forestdegradationlevel'),
        ),
    ]
