# Generated by Django 4.1.3 on 2023-03-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_forest_degradation_level_start_t2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landusetype',
            old_name='parent_land_use',
            new_name='parent',
        ),
    ]
