# Generated by Django 4.1.3 on 2023-03-05 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_rename_parent_land_use_landusetype_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landusetype',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.landusetype'),
        ),
    ]
