# Generated by Django 4.2.1 on 2024-06-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
