# Generated by Django 4.2.1 on 2024-06-28 07:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcropping',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organic_soil_%(class)s', to='api.organicsoil'),
        ),
        migrations.AlterField(
            model_name='degradedland',
            name='area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='degradedland',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organic_soil_%(class)s', to='api.organicsoil'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organic_soil_%(class)s', to='api.organicsoil'),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organic_soil_%(class)s', to='api.organicsoil'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organic_soil_%(class)s', to='api.organicsoil'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organic_soil_%(class)s', to='api.organicsoil'),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organic_soil_%(class)s', to='api.organicsoil'),
        ),
        migrations.AlterField(
            model_name='setaside',
            name='area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='setaside',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organic_soil_%(class)s', to='api.organicsoil'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='organic_soil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organic_soil_%(class)s', to='api.organicsoil'),
        ),
    ]
