# Generated by Django 4.1.3 on 2023-03-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_landusetype_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landusetype',
            name='assessment_activity',
        ),
        migrations.RemoveField(
            model_name='landusetype',
            name='needs_assessment',
        ),
    ]
