# Generated by Django 4.1.3 on 2023-03-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_remove_landusetype_assessment_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcropping',
            name='land_use_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent__name', 'Annual Cropland')), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AlterField(
            model_name='deforestation',
            name='land_use_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent__isnull', True), ('parent__name', 'Agroforestry'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AlterField(
            model_name='otherlandmanagement',
            name='land_use_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('parent__isnull', True), ('parent__name', 'Agroforestry'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='land_use_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent__name', 'Agroforestry')), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
    ]
