# Generated by Django 4.1.3 on 2023-03-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_annualcropping_land_use_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcropping',
            name='crop_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='ha_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='ha_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='ha_w_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate'),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='ha_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='ha_wo_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate+', to='api.changerate'),
        ),
    ]
