# Generated by Django 4.0.4 on 2023-03-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_annualcropping_crop_yield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest',
            name='ha_w_rate',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate'),
        ),
        migrations.AlterField(
            model_name='forest',
            name='ha_wo_rate',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changerate'),
        ),
    ]
