# Generated by Django 4.2.1 on 2024-07-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_historicalproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalprojectinvitation',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.invitationstatustype'),
        ),
        migrations.AlterField(
            model_name='projectinvitation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invitationstatustype'),
        ),
    ]
