# Generated by Django 4.0.4 on 2023-03-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_forest_ha_w_rate_alter_forest_ha_wo_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perennialcropping',
            name='crop_yield',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
