# Generated by Django 4.2.1 on 2024-07-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_invitationstatustype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='settlement_type_thread',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlement_type_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_settlement_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='settlement_type_start',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.settlementtype'),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='settlement_type_w',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.settlementtype'),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='settlement_type_wo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.settlementtype'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlement_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_settlement_type_start', to='api.settlementtype'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlement_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_settlement_type_w', to='api.settlementtype'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlement_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_settlement_type_wo', to='api.settlementtype'),
        ),
    ]
