# Generated by Django 4.0.4 on 2023-03-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_perennialcropping_crop_yield'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='input',
            name='name',
        ),
        migrations.AddField(
            model_name='input',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='co2_e_emissions_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='co2_emissions_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='implementation_year_t2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='n2o_emissions_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='value_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='value_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='value_w_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_value_w_rate', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='input',
            name='value_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='value_wo_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_value_wo_rate', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='input',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.inputtype'),
            preserve_default=False,
        ),
    ]
