# Generated by Django 4.2.1 on 2024-07-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_settlementtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='agb_t2_start',
        ),
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='agb_t2_w',
        ),
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='agb_t2_wo',
        ),
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='bgb_t2_start',
        ),
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='bgb_t2_w',
        ),
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='bgb_t2_wo',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='agb_t2_start',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='agb_t2_w',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='agb_t2_wo',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='bgb_t2_start',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='bgb_t2_w',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='bgb_t2_wo',
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
