# Generated by Django 4.0.4 on 2023-03-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0041_delete_inputreference'),
        ('api', '0069_inputtype_remove_input_name_input_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroInputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='input',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='input',
            name='co2_e_emissions_t2',
        ),
        migrations.RemoveField(
            model_name='input',
            name='co2_emissions_t2',
        ),
        migrations.RemoveField(
            model_name='input',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='input',
            name='implementation_year_t2',
        ),
        migrations.RemoveField(
            model_name='input',
            name='n2o_emissions_t2',
        ),
        migrations.RemoveField(
            model_name='input',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='input',
            name='type',
        ),
        migrations.RemoveField(
            model_name='input',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='input',
            name='value_start',
        ),
        migrations.RemoveField(
            model_name='input',
            name='value_w',
        ),
        migrations.RemoveField(
            model_name='input',
            name='value_w_rate',
        ),
        migrations.RemoveField(
            model_name='input',
            name='value_wo',
        ),
        migrations.RemoveField(
            model_name='input',
            name='value_wo_rate',
        ),
        migrations.AddField(
            model_name='input',
            name='name',
            field=models.CharField(default='Lime Application', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InputType',
        ),
    ]
