# Generated by Django 4.2.1 on 2024-07-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_historicalsettlement_agb_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='is_settlement_start',
        ),
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='is_settlement_w',
        ),
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='is_settlement_wo',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='is_settlement_start',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='is_settlement_w',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='is_settlement_wo',
        ),
    ]
