# Generated by Django 4.0.4 on 2023-03-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_macroinputtype_remove_input_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('macro_input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.macroinputtype')),
            ],
            options={
                'unique_together': {('macro_input_type', 'name')},
            },
        ),
    ]
