# Generated by Django 4.2.1 on 2024-07-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_remove_historicalsettlement_is_settlement_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
