# Generated by Django 4.0.4 on 2023-03-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_input_name_input_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtype',
            name='macro_input_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.macroinputtype'),
        ),
    ]
