# Generated by Django 4.2.1 on 2024-07-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_climate_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climate',
            old_name='active',
            new_name='is_active',
        ),
    ]
