# Generated by Django 4.2.1 on 2024-07-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_rename_active_climate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='moisture',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
