# Generated by Django 4.0.4 on 2023-03-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_alter_inputtype_macro_input_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('surface_w', models.FloatField(blank=True, null=True)),
                ('surface_wo', models.FloatField(blank=True, null=True)),
                ('t_co2_m2_t2', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buildingtype')),
                ('input_type', models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='api.inputtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
