# Generated by Django 4.2.1 on 2023-06-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_buildingtype_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='largefishery',
            old_name='energy_emission_factor_t2',
            new_name='energy_emission_factor_t2_start',
        ),
        migrations.RenameField(
            model_name='largefishery',
            old_name='inshore_ice_production_emissions_t2',
            new_name='energy_emission_factor_t2_w',
        ),
        migrations.RenameField(
            model_name='largefishery',
            old_name='refrigerant_gwp_t2',
            new_name='energy_emission_factor_t2_wo',
        ),
        migrations.RenameField(
            model_name='largefishery',
            old_name='refrigerant_lost_per_tonne_t2',
            new_name='refrigerant_gwp_t2_start',
        ),
        migrations.RenameField(
            model_name='smallfishery',
            old_name='energy_emission_factor_t2',
            new_name='energy_emission_factor_t2_start',
        ),
        migrations.RenameField(
            model_name='smallfishery',
            old_name='inshore_ice_production_emissions_t2',
            new_name='energy_emission_factor_t2_w',
        ),
        migrations.RenameField(
            model_name='smallfishery',
            old_name='refrigerant_gwp_t2',
            new_name='energy_emission_factor_t2_wo',
        ),
        migrations.RenameField(
            model_name='smallfishery',
            old_name='refrigerant_lost_per_tonne_t2',
            new_name='refrigerant_gwp_t2_start',
        ),
        migrations.RemoveField(
            model_name='largefishery',
            name='gear_type',
        ),
        migrations.RemoveField(
            model_name='smallfishery',
            name='gear_type',
        ),
        migrations.AddField(
            model_name='largefishery',
            name='gear_type_start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_start', to='api.geartype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='largefishery',
            name='gear_type_w',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_w', to='api.geartype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='largefishery',
            name='gear_type_wo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_wo', to='api.geartype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='largefishery',
            name='refrigerant_gwp_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='refrigerant_gwp_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='refrigerant_lost_per_tonne_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='refrigerant_lost_per_tonne_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='refrigerant_lost_per_tonne_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='tonnes_of_ice_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='tonnes_of_ice_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='tonnes_of_ice_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='gear_type_start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_start', to='api.geartype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='gear_type_w',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_w', to='api.geartype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='gear_type_wo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_wo', to='api.geartype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='refrigerant_gwp_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='refrigerant_gwp_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='refrigerant_lost_per_tonne_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='refrigerant_lost_per_tonne_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='refrigerant_lost_per_tonne_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='tonnes_of_ice_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='tonnes_of_ice_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='tonnes_of_ice_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.project'),
        ),
        migrations.AlterField(
            model_name='afforestation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='afforestationsoilmanagement',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='aquaculture',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='building',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='building',
            name='input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inputtype'),
        ),
        migrations.AlterField(
            model_name='coastalwaterbody',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='deforestation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='deforestationsoilmanagement',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='forest',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='forest',
            name='ha_w_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_w_rate', to='api.changerate'),
        ),
        migrations.AlterField(
            model_name='forest',
            name='ha_wo_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_wo_rate', to='api.changerate'),
        ),
        migrations.AlterField(
            model_name='forestlandmanagement',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='inlandwaterbody',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='input',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='otherlandmanagement',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='otherlanduse',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='otherlandusesoilmanagement',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='peatextractionlandmanagement',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='rewetting',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='rewetting',
            name='avg_salinity_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salinitytype'),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity'),
        ),
    ]
