# Generated by Django 4.2.1 on 2023-06-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_rename_energy_emission_factor_t2_largefishery_energy_emission_factor_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='largefishery',
            old_name='inshore_ice_production_kwh_per_tonne_t2',
            new_name='inshore_ice_production_kwh_per_tonne_t2_start',
        ),
        migrations.RenameField(
            model_name='smallfishery',
            old_name='inshore_ice_production_kwh_per_tonne_t2',
            new_name='inshore_ice_production_kwh_per_tonne_t2_start',
        ),
        migrations.AddField(
            model_name='largefishery',
            name='inshore_ice_production_kwh_per_tonne_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='inshore_ice_production_kwh_per_tonne_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='inshore_ice_production_kwh_per_tonne_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='inshore_ice_production_kwh_per_tonne_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
