# Generated by Django 4.2.1 on 2024-07-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduletype',
            name='is_fixed_assessment',
        ),
    ]
