# Generated by Django 4.2.1 on 2023-06-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_rename_inshore_ice_production_kwh_per_tonne_t2_largefishery_inshore_ice_production_kwh_per_tonne_t2_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='largefishery',
            old_name='inshore_ice_production_country',
            new_name='inshore_ice_production_country_t2',
        ),
        migrations.RenameField(
            model_name='smallfishery',
            old_name='inshore_ice_production_country',
            new_name='inshore_ice_production_country_t2',
        ),
    ]
