# Generated by Django 4.2.1 on 2024-07-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_alter_landusechange_organic_soil'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodedrice',
            name='residue_availability_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='residue_availability_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='residue_availability_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfloodedrice',
            name='residue_availability_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfloodedrice',
            name='residue_availability_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfloodedrice',
            name='residue_availability_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalminorseasonfloodedrice',
            name='residue_availability_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalminorseasonfloodedrice',
            name='residue_availability_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalminorseasonfloodedrice',
            name='residue_availability_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='residue_availability_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='residue_availability_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='residue_availability_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
