# Generated by Django 4.2.1 on 2023-06-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_rename_inshore_ice_production_country_largefishery_inshore_ice_production_country_t2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCCRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
