# Generated by Django 4.2.1 on 2024-07-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_floodedrice_residue_availability_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproject',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'owner')},
        ),
    ]
