# Generated by Django 4.2.1 on 2023-06-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_ipccregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='ipcc_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ipccregion'),
        ),
    ]
