# Generated by Django 4.2.1 on 2024-07-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_activity_created_at_activity_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualcropping',
            name='residue_availability_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='residue_availability_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='residue_availability_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalannualcropping',
            name='residue_availability_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalannualcropping',
            name='residue_availability_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalannualcropping',
            name='residue_availability_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
