# Generated by Django 4.2.1 on 2023-06-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_remove_continent_ipcc_region_country_ipcc_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLEAMRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
