# Generated by Django 4.2.1 on 2024-07-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0081_annualcropping_residue_availability_t2_start_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="definition",
            name="model_name",
        ),
        migrations.AddField(
            model_name="definition",
            name="module_type",
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name="definitions", to="api.moduletype"),
            preserve_default=False,
        ),
    ]
