# Generated by Django 4.2.1 on 2023-06-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_gleamregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='gleam_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gleamregion'),
        ),
    ]
