# Generated by Django 4.2.1 on 2023-06-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_country_gleam_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='api.continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='gleam_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='api.gleamregion'),
        ),
        migrations.AlterField(
            model_name='country',
            name='ipcc_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='api.ipccregion'),
        ),
    ]
