# Generated by Django 4.2.1 on 2024-07-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_remove_definition_model_name_definition_module_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProjectGroup',
            new_name='ProjectMembership',
        ),
    ]
