# Generated by Django 4.2.1 on 2023-06-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_alter_country_continent_alter_country_gleam_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestock',
            old_name='livestock_category',
            new_name='livestock_category_type',
        ),
    ]
