# Generated by Django 4.2.1 on 2024-07-31 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_rename_userprojectgroup_projectmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='aquaculture',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='degradedland',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalannualcropping',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalaquaculture',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicaldegradedland',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalenergy',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalfloodedrice',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalgrassland',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalinput',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalirrigation',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicallandusechange',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicallargefishery',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicallivestock',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalotherlanduse',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalperennialcropping',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalsetaside',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalsettlement',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalsmallfishery',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='historicalwaterbody',
            name='notes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.note'),
        ),
        migrations.AlterField(
            model_name='input',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='landusechange',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='otherlanduse',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='setaside',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
        migrations.AlterField(
            model_name='waterbody',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.note'),
        ),
    ]
