# Generated by Django 4.2.1 on 2023-07-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_croptype_remove_annualcropping_land_use_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcropping',
            name='minor_crop_type_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_crop_type', to='api.croptype'),
        ),
    ]
