# Generated by Django 4.2.1 on 2023-07-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ipcc", "0070_alter_smallfisheryfui_unique_together"),
        ("api", "0086_alter_annualcropping_minor_crop_type_t2"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmallFisheryGearType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name="GearType",
            new_name="LargeFisheryGearType",
        ),
        migrations.AlterField(
            model_name="largefishery",
            name="gear_type_start",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_gear_type_start",
                to="api.largefisherygeartype",
            ),
        ),
        migrations.AlterField(
            model_name="largefishery",
            name="gear_type_w",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_gear_type_w",
                to="api.largefisherygeartype",
            ),
        ),
        migrations.AlterField(
            model_name="largefishery",
            name="gear_type_wo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_gear_type_wo",
                to="api.largefisherygeartype",
            ),
        ),
        migrations.AlterField(
            model_name="smallfishery",
            name="gear_type_start",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_gear_type_start",
                to="api.smallfisherygeartype",
            ),
        ),
        migrations.AlterField(
            model_name="smallfishery",
            name="gear_type_w",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_gear_type_w",
                to="api.smallfisherygeartype",
            ),
        ),
        migrations.AlterField(
            model_name="smallfishery",
            name="gear_type_wo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_gear_type_wo",
                to="api.smallfisherygeartype",
            ),
        ),
    ]
