# Generated by Django 4.2.1 on 2023-07-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0087_smallfisherygeartype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="largefishery",
            name="gear_type_start",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_gear_type_start",
                to="api.largefisherygeartype",
            ),
        ),
        migrations.AlterField(
            model_name="largefishery",
            name="gear_type_w",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_gear_type_w",
                to="api.largefisherygeartype",
            ),
        ),
        migrations.AlterField(
            model_name="largefishery",
            name="gear_type_wo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_gear_type_wo",
                to="api.largefisherygeartype",
            ),
        ),
    ]
