# Generated by Django 4.2.1 on 2024-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_historicalcustomuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalminorseasonannualcropping',
            name='biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='historicalminorseasonannualcropping',
            name='biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='historicalminorseasonannualcropping',
            name='biomass_t2_wo',
        ),
        migrations.RemoveField(
            model_name='historicalminorseasonperennialcropping',
            name='biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='historicalminorseasonperennialcropping',
            name='biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='historicalminorseasonperennialcropping',
            name='biomass_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonannualcropping',
            name='biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonannualcropping',
            name='biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonannualcropping',
            name='biomass_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonperennialcropping',
            name='biomass_t2_wo',
        ),
        migrations.AddField(
            model_name='historicalperennialcropping',
            name='residue_availability_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperennialcropping',
            name='residue_availability_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperennialcropping',
            name='residue_availability_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='residue_availability_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='residue_availability_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='residue_availability_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
