# Generated by Django 4.2.1 on 2023-07-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_extractionsoiltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallfishery',
            name='fishery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fisherytype'),
        ),
    ]
