# Generated by Django 4.2.1 on 2023-07-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_alter_smallfishery_fishery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largefisherygeartype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='smallfisherygeartype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
