# Generated by Django 4.2.1 on 2024-08-14 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0090_remove_historicalsettlement_biomass_t2_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprojectinvitation",
            name="token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="historicalprojectinvitation",
            name="token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectinvitation",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="projectinvitation",
            name="token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
