# Generated by Django 4.2.1 on 2023-07-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_alter_largefisherygeartype_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perennialcropping',
            name='land_use_type',
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='crop_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent__name', 'Agroforestry')), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.croptype'),
        ),
    ]
