# Generated by Django 4.2.1 on 2024-08-14 08:02

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("api", "ProjectInvitation")
    for row in MyModel.objects.all():
        row.token = uuid.uuid4()
        row.save(update_fields=["token"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0091_historicalprojectinvitation_token_and_more"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
