# Generated by Django 4.2.1 on 2023-07-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_remove_perennialcropping_land_use_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perennialcropping',
            name='crop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.croptype'),
        ),
    ]
