# Generated by Django 4.2.1 on 2024-08-14 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0092_auto_20240814_0802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
