# Generated by Django 4.2.1 on 2023-07-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_alter_perennialcropping_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organicinputtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
