# Generated by Django 4.2.1 on 2024-08-14 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20240814_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperennialcropping',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperennialcropping',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperennialcropping',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinvitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
