# Generated by Django 4.2.1 on 2023-07-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_alter_organicinputtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptype',
            name='is_main_crop',
            field=models.BooleanField(default=False),
        ),
    ]
