# Generated by Django 4.2.1 on 2024-08-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_historicalperennialcropping_biomass_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='soil_carbon_t2_start',
        ),
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='soil_carbon_t2_w',
        ),
        migrations.RemoveField(
            model_name='historicalsettlement',
            name='soil_carbon_t2_wo',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='soil_carbon_t2_start',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='soil_carbon_t2_w',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='soil_carbon_t2_wo',
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
