# Generated by Django 4.2.1 on 2024-08-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_remove_historicalsettlement_soil_carbon_t2_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsetaside',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsetaside',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsetaside',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setaside',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setaside',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setaside',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
