# Generated by Django 4.2.1 on 2024-08-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_historicalsetaside_biomass_t2_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_not_drained_or_rewetted_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_not_drained_or_rewetted_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_not_drained_or_rewetted_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_under_drainage_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_under_drainage_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_under_drainage_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_w_restored_vegetation_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_w_restored_vegetation_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_w_restored_vegetation_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='drained_area_excavated_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='drained_area_excavated_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='drained_area_excavated_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_not_drained_or_rewetted_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_not_drained_or_rewetted_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_not_drained_or_rewetted_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_under_drainage_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_under_drainage_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_under_drainage_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_w_restored_vegetation_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_w_restored_vegetation_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_w_restored_vegetation_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='drained_area_excavated_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='drained_area_excavated_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='drained_area_excavated_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
