# Generated by Django 4.2.1 on 2023-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_alter_continent_name_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tillagemanagementtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
