# Generated by Django 4.2.1 on 2024-08-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_alter_coastalwetland_area_not_drained_or_rewetted_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallandusechange',
            name='dry_matter_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicallandusechange',
            name='dry_matter_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicallandusechange',
            name='dry_matter_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='landusechange',
            name='dry_matter_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='landusechange',
            name='dry_matter_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='landusechange',
            name='dry_matter_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
