# Generated by Django 4.2.1 on 2023-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_alter_tillagemanagementtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroforestrySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
