# Generated by Django 4.2.1 on 2023-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_agroforestrysystem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgroforestrySystem',
        ),
        migrations.AddField(
            model_name='croptype',
            name='is_agrofoforestry',
            field=models.BooleanField(default=False),
        ),
    ]
