# Generated by Django 4.2.1 on 2024-08-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_alter_historicallandusechange_dry_matter_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationsystemtype',
            name='module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
    ]
