# Generated by Django 4.2.1 on 2024-08-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_irrigationsystemtype_module_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='irrigationsystemtype',
            unique_together={('module_type', 'name')},
        ),
    ]
