# Generated by Django 4.2.1 on 2023-07-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_delete_agroforestrysystem_croptype_is_agrofoforestry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualcropping',
            old_name='crop_yield',
            new_name='crop_yield_start',
        ),
        migrations.RenameField(
            model_name='annualcropping',
            old_name='main_biomass_factor_t2',
            new_name='main_biomass_factor_t2_start',
        ),
        migrations.RenameField(
            model_name='annualcropping',
            old_name='main_land_use_factor_t2',
            new_name='main_land_use_factor_t2_start',
        ),
        migrations.RenameField(
            model_name='annualcropping',
            old_name='main_organic_input_factor_t2',
            new_name='main_organic_input_factor_t2_start',
        ),
        migrations.RenameField(
            model_name='annualcropping',
            old_name='main_soil_carbon_t2',
            new_name='main_soil_carbon_t2_start',
        ),
        migrations.RenameField(
            model_name='annualcropping',
            old_name='main_tillage_factor_t2',
            new_name='main_tillage_factor_t2_start',
        ),
        migrations.RenameField(
            model_name='annualcropping',
            old_name='minor_biomass_factor_t2',
            new_name='minor_biomass_factor_t2_start',
        ),
        migrations.RenameField(
            model_name='annualcropping',
            old_name='minor_crop_type_t2',
            new_name='minor_crop_type_start',
        ),
        migrations.RenameField(
            model_name='annualcropping',
            old_name='minor_residue_management_type_t2',
            new_name='minor_residue_management_type_start',
        ),
        migrations.RenameField(
            model_name='annualcropping',
            old_name='minor_yield_t2',
            new_name='minor_yield_start',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='organic_input_type',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='residue_management_type',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='tillage_management_type',
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='crop_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_type_start', to='api.croptype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='crop_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_type_w', to='api.croptype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='crop_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_type_wo', to='api.croptype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='crop_yield_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='crop_yield_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_biomass_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_biomass_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_land_use_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_land_use_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_organic_input_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_organic_input_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_soil_carbon_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_soil_carbon_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_tillage_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='main_tillage_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_biomass_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_biomass_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_crop_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_crop_type_w', to='api.croptype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_crop_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_crop_type_wo', to='api.croptype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_residue_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_residue_management_type_w', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_residue_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_residue_management_type_wo', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_yield_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_yield_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='organic_input_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_start', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='organic_input_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_w', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='organic_input_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_wo', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='residue_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_start', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='residue_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_w', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='residue_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_wo', to='api.residuemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='soc_ref_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='soc_ref_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='soc_ref_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='tillage_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_start', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='tillage_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_w', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='tillage_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_wo', to='api.tillagemanagementtype'),
        ),
    ]
