# Generated by Django 4.2.1 on 2023-07-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_rename_crop_yield_annualcropping_crop_yield_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='capitalization_duration_yrs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='implementation_duration_yrs',
            field=models.IntegerField(),
        ),
    ]
