# Generated by Django 4.2.1 on 2024-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_alter_irrigationsystemtype_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='irrigationsystemtype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='irrigationsystemtype',
            name='module_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='irrigation_system_types', to='api.moduletype'),
        ),
        migrations.RemoveField(
            model_name='irrigationsystemtype',
            name='module_type',
        ),
    ]
