# Generated by Django 4.2.1 on 2024-08-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_alter_irrigationsystemtype_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltype',
            name='land_use_types',
            field=models.ManyToManyField(related_name='fuel_types', to='api.landusetype'),
        ),
    ]
