# Generated by Django 4.2.1 on 2023-07-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_alter_project_capitalization_duration_yrs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestock',
            old_name='livestock_category_type',
            new_name='livestock_category_type_start',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='livestock_production_type',
            new_name='livestock_production_type_start',
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_category_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_livestock_categories_w', to='api.livestockcategorytype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_category_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_livestock_categories_wo', to='api.livestockcategorytype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_production_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_livestock_productions_w', to='api.livestockproductiontype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_production_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_livestock_productions_wo', to='api.livestockproductiontype'),
        ),
    ]
