# Generated by Django 4.2.1 on 2024-08-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_fueltype_land_use_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueltype',
            name='land_use_types',
        ),
        migrations.AddField(
            model_name='fueltype',
            name='module_types',
            field=models.ManyToManyField(related_name='fuel_types', to='api.moduletype'),
        ),
    ]
