# Generated by Django 4.2.1 on 2023-07-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_rename_livestock_category_type_livestock_livestock_category_type_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='change_rate_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_rate_start', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='activity',
            name='change_rate_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_rate_w', to='api.changerate'),
        ),
        migrations.AddField(
            model_name='activity',
            name='change_rate_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_rate_wo', to='api.changerate'),
        ),
    ]
