# Generated by Django 4.2.1 on 2024-08-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_remove_fueltype_land_use_types_fueltype_module_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='last_year_of_accounting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_year_of_accounting',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
