# Generated by Django 4.2.1 on 2023-07-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_activity_change_rate_start_activity_change_rate_w_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestock',
            old_name='emission_factor_ch4_t2',
            new_name='emission_factor_ch4_prp_t2',
        ),
    ]
