# Generated by Django 4.2.1 on 2023-07-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_rename_emission_factor_ch4_t2_livestock_emission_factor_ch4_prp_t2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestock',
            old_name='emission_factor_ch4_prp_t2',
            new_name='emission_factor_ch4_t2',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='emission_factor_start_t2',
            new_name='prp_ch4_start_t2',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='emission_factor_w_t2',
            new_name='prp_ch4_w_t2',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='emission_factor_wo_t2',
            new_name='prp_ch4_wo_t2',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='n2o_start_t2',
            new_name='prp_n2o_start_t2',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='n2o_w_t2',
            new_name='prp_n2o_w_t2',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='n2o_wo_t2',
            new_name='prp_n2o_wo_t2',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='pasture_percentage_start_t2',
            new_name='prp_percentage_start_t2',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='pasture_percentage_w_t2',
            new_name='prp_percentage_w_t2',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='pasture_percentage_wo_t2',
            new_name='prp_percentage_wo_t2',
        ),
    ]
