# Generated by Django 4.2.1 on 2024-08-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_historicalproject_last_year_of_accounting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproject',
            old_name='start_year',
            new_name='start_year_of_activities',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_year',
            new_name='start_year_of_activities',
        ),
    ]
