# Generated by Django 4.2.1 on 2023-07-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_rename_emission_factor_ch4_prp_t2_livestock_emission_factor_ch4_t2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestock',
            old_name='emission_factor_ch4_t2',
            new_name='emission_factor_ch4_t2_start',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='emission_factor_n20_t2',
            new_name='emission_factor_ch4_t2_w',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='manure_management_type_t2',
        ),
        migrations.AddField(
            model_name='livestock',
            name='emission_factor_n20_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='emission_factor_n20_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='manure_management_type_t2_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_manure_management_type_t2_start', to='api.manuremanagementtype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='manure_management_type_t2_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_manure_management_type_t2_w', to='api.manuremanagementtype'),
        ),
    ]
