# Generated by Django 4.2.1 on 2024-08-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_rename_start_year_historicalproject_start_year_of_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='capitalization_years',
        ),
        migrations.RemoveField(
            model_name='project',
            name='capitalization_years',
        ),
    ]
