# Generated by Django 4.2.1 on 2024-08-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_remove_historicalproject_capitalization_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degradedland',
            name='ha_start',
        ),
        migrations.RemoveField(
            model_name='degradedland',
            name='ha_w',
        ),
        migrations.RemoveField(
            model_name='degradedland',
            name='ha_wo',
        ),
        migrations.RemoveField(
            model_name='historicaldegradedland',
            name='ha_start',
        ),
        migrations.RemoveField(
            model_name='historicaldegradedland',
            name='ha_w',
        ),
        migrations.RemoveField(
            model_name='historicaldegradedland',
            name='ha_wo',
        ),
    ]
