# Generated by Django 4.2.1 on 2023-07-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_rename_emission_factor_ch4_t2_livestock_emission_factor_ch4_t2_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='emission_factor_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='emission_factor_n20_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='manure_management_type_t2_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_manure_management_type_t2_wo', to='api.manuremanagementtype'),
        ),
    ]
