# Generated by Django 4.2.1 on 2024-08-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_remove_degradedland_ha_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='ef_t2',
            new_name='ef_ch4_t2_start',
        ),
        migrations.RenameField(
            model_name='historicalfuel',
            old_name='ef_t2',
            new_name='ef_ch4_t2_start',
        ),
        migrations.AddField(
            model_name='fuel',
            name='ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
