# Generated by Django 4.2.1 on 2023-07-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_rename_emission_factor_n20_t2_start_livestock_emission_factor_n2o_t2_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestock',
            old_name='emission_factor_n20_t2_w',
            new_name='emission_factor_n2o_t2_w',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='emission_factor_n20_t2_wo',
            new_name='emission_factor_n2o_t2_wo',
        ),
    ]
