# Generated by Django 4.2.1 on 2024-08-26 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0036_globalwarmingpotential_ch4_fossil'),
        ('api', '0108_rename_ef_t2_fuel_ef_ch4_t2_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gw_potential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ipcc.globalwarmingpotential'),
        ),
    ]
