# Generated by Django 4.2.1 on 2023-08-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0109_rename_emission_factor_n20_t2_w_livestock_emission_factor_n2o_t2_w_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelUseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MacroFuelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Electricity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("electricity_start", models.FloatField(blank=True, null=True)),
                ("electricity_w", models.FloatField(blank=True, null=True)),
                ("electrivity_wo", models.FloatField(blank=True, null=True)),
                ("fuel_start", models.FloatField(blank=True, null=True)),
                ("fuel_w", models.FloatField(blank=True, null=True)),
                ("fuel_wo", models.FloatField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="api.activity",
                    ),
                ),
                (
                    "fuel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.fueltype",
                    ),
                ),
                (
                    "origin_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.country",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="fueltype",
            name="fuel_use_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.fuelusetype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fueltype",
            name="macro_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.macrofueltype",
            ),
            preserve_default=False,
        ),
    ]
