# Generated by Django 4.2.1 on 2024-08-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0037_remove_inputreference_gw_potential'),
        ('api', '0109_alter_project_gw_potential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gw_potential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.globalwarmingpotential'),
        ),
    ]
