# Generated by Django 4.2.1 on 2024-09-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_alter_project_gw_potential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='last_year_of_accounting',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='start_year_of_activities',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='last_year_of_accounting',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='start_year_of_activities',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
