# Generated by Django 4.2.1 on 2023-08-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_alter_fueltype_fuel_use_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltype',
            name='macro_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.macrofueltype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fueltype',
            unique_together={('name', 'fuel_use_type', 'macro_type')},
        ),
    ]
