# Generated by Django 4.2.1 on 2024-09-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_alter_historicalproject_last_year_of_accounting_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalDegradedLand',
            new_name='HistoricalOtherLand',
        ),
        migrations.RenameModel(
            old_name='DegradedLand',
            new_name='OtherLand',
        ),
        migrations.AlterModelOptions(
            name='historicalotherland',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical other land', 'verbose_name_plural': 'historical other lands'},
        ),
    ]
