# Generated by Django 4.2.1 on 2024-09-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_rename_historicaldegradedland_historicalotherland_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnnualCropping',
            new_name='AnnualCropland',
        ),
        migrations.RenameModel(
            old_name='HistoricalAnnualCropping',
            new_name='HistoricalAnnualCropland',
        ),
        migrations.RenameModel(
            old_name='HistoricalMinorSeasonPerennialCropping',
            new_name='HistoricalMinorSeasonAnnualCropland',
        ),
        migrations.RenameModel(
            old_name='HistoricalMinorSeasonAnnualCropping',
            new_name='HistoricalMinorSeasonPerennialCropland',
        ),
        migrations.RenameModel(
            old_name='HistoricalPerennialCropping',
            new_name='HistoricalPerennialCropland',
        ),
        migrations.RenameModel(
            old_name='MinorSeasonPerennialCropping',
            new_name='MinorSeasonAnnualCropland',
        ),
        migrations.RenameModel(
            old_name='MinorSeasonAnnualCropping',
            new_name='MinorSeasonPerennialCropland',
        ),
        migrations.RenameModel(
            old_name='PerennialCropping',
            new_name='PerennialCropland',
        ),
        migrations.AlterModelOptions(
            name='historicalannualcropland',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical annual cropland', 'verbose_name_plural': 'historical annual croplands'},
        ),
        migrations.AlterModelOptions(
            name='historicalminorseasonannualcropland',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical minor season annual cropland', 'verbose_name_plural': 'historical minor season annual croplands'},
        ),
        migrations.AlterModelOptions(
            name='historicalminorseasonperennialcropland',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical minor season perennial cropland', 'verbose_name_plural': 'historical minor season perennial croplands'},
        ),
        migrations.AlterModelOptions(
            name='historicalperennialcropland',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical perennial cropland', 'verbose_name_plural': 'historical perennial croplands'},
        ),
    ]
