# Generated by Django 4.2.1 on 2023-08-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_alter_fueltype_macro_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
