# Generated by Django 4.2.1 on 2023-08-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_livestockparameters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LivestockParameters',
            new_name='LivestockParameter',
        ),
    ]
