# Generated by Django 4.2.1 on 2024-09-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_rename_annualcropping_annualcropland_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='gwp_ch4_fossil_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='gwp_ch4_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='gwp_co2_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='gwp_n2o_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gwp_ch4_fossil_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gwp_ch4_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gwp_co2_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gwp_n2o_t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalminorseasonannualcropland',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.annualcropland'),
        ),
        migrations.AlterField(
            model_name='historicalminorseasonperennialcropland',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.perennialcropland'),
        ),
        migrations.AlterField(
            model_name='minorseasonannualcropland',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_seasons', to='api.annualcropland'),
        ),
        migrations.AlterField(
            model_name='minorseasonperennialcropland',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_seasons', to='api.perennialcropland'),
        ),
    ]
