# Generated by Django 4.2.1 on 2024-09-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_historicalproject_gwp_ch4_fossil_t2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletype',
            name='is_container',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
