# Generated by Django 4.2.1 on 2023-08-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_rename_livestockparameters_livestockparameter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Electricity',
            new_name='Energy',
        ),
    ]
