# Generated by Django 4.2.1 on 2024-09-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_moduletype_is_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduletype',
            name='is_container',
            field=models.BooleanField(default=False),
        ),
    ]
