# Generated by Django 4.2.1 on 2023-08-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_rename_electricity_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mwh_start', models.FloatField(blank=True, null=True)),
                ('mwh_w', models.FloatField(blank=True, null=True)),
                ('mwh_wo', models.FloatField(blank=True, null=True)),
                ('ef_t2', models.FloatField(blank=True, null=True)),
                ('transmission_loss', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmissionFactorSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fuel_start', models.FloatField(blank=True, null=True)),
                ('fuel_w', models.FloatField(blank=True, null=True)),
                ('fuel_wo', models.FloatField(blank=True, null=True)),
                ('ef_t2', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fueltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Energy',
        ),
        migrations.AddField(
            model_name='electricity',
            name='ef_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.emissionfactorsource'),
        ),
    ]
