# Generated by Django 4.2.1 on 2024-09-09 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_alter_moduletype_is_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='other_executing_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='other_funding_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='other_executing_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='other_funding_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='executing_agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.executingagency'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='funding_agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fundingagency'),
        ),
        migrations.AlterField(
            model_name='project',
            name='executing_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.executingagency'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fundingagency'),
        ),
    ]
