# Generated by Django 4.2.1 on 2023-08-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_electricity_emissionfactorsource_fuel_delete_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='transmission_loss',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
    ]
