# Generated by Django 4.2.1 on 2024-09-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_historicalproject_other_executing_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='other_executing_agency',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='other_funding_agency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='other_executing_agency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='other_funding_agency',
        ),
    ]
