# Generated by Django 4.2.1 on 2023-08-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_alter_electricity_transmission_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='transmission_loss',
            field=models.FloatField(default=0.1),
        ),
    ]
