# Generated by Django 4.2.1 on 2023-08-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_alter_electricity_transmission_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='account_for_co2',
            field=models.BooleanField(default=False),
        ),
    ]
