# Generated by Django 4.2.1 on 2024-09-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_remove_historicalproject_other_executing_agency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='executing_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='executing_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
