# Generated by Django 4.2.1 on 2024-09-09 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_alter_historicalproject_executing_agency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallivestock',
            old_name='percentage_heads_on_pasture_thread',
            new_name='prp_percentage_t2_thread',
        ),
        migrations.RemoveField(
            model_name='historicallivestock',
            name='percentage_heads_on_pasture_start',
        ),
        migrations.RemoveField(
            model_name='historicallivestock',
            name='percentage_heads_on_pasture_w',
        ),
        migrations.RemoveField(
            model_name='historicallivestock',
            name='percentage_heads_on_pasture_wo',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='percentage_heads_on_pasture_start',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='percentage_heads_on_pasture_thread',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='percentage_heads_on_pasture_w',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='percentage_heads_on_pasture_wo',
        ),
        migrations.AddField(
            model_name='livestock',
            name='prp_percentage_t2_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_prp_percentage_t2_thread', to='api.commentthread'),
        ),
    ]
