# Generated by Django 4.2.1 on 2023-08-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_fuel_account_for_co2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='fuel',
            new_name='fuel_type',
        ),
    ]
