# Generated by Django 4.2.1 on 2024-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_rename_percentage_heads_on_pasture_thread_historicallivestock_prp_percentage_t2_thread_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='status',
        ),
    ]
