# Generated by Django 4.2.1 on 2023-08-07 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0120_rename_fuel_fuel_fuel_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fueltype",
            old_name="macro_type",
            new_name="macro_fuel_type",
        ),
        migrations.AlterUniqueTogether(
            name="fueltype",
            unique_together={("name", "fuel_use_type", "macro_fuel_type")},
        ),
    ]
