# Generated by Django 4.2.1 on 2023-08-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_rename_macro_type_fueltype_macro_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fueltype',
            unique_together={('name', 'fuel_use_type', 'macro_fuel_type')},
        ),
    ]
