# Generated by Django 4.2.1 on 2024-09-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_remove_activity_completion_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcropland',
            name='crop_yield_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcropland',
            name='crop_yield_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcropland',
            name='crop_yield_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalannualcropland',
            name='crop_yield_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalannualcropland',
            name='crop_yield_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalannualcropland',
            name='crop_yield_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
