# Generated by Django 4.2.1 on 2023-08-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_alter_fueltype_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='electricity',
            name='mwh_renewables_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='mwh_renewables_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='mwh_renewables_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IrrigationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ha_start', models.FloatField(blank=True, null=True)),
                ('ha_w', models.FloatField(blank=True, null=True)),
                ('ha_wo', models.FloatField(blank=True, null=True)),
                ('ef_t2_start', models.FloatField(blank=True, null=True)),
                ('ef_t2_w', models.FloatField(blank=True, null=True)),
                ('ef_t2_wo', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('irrigation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.irrigationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IrrigationPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('well_depth', models.FloatField(blank=True, null=True)),
                ('ha_start', models.FloatField(blank=True, null=True)),
                ('ha_w', models.FloatField(blank=True, null=True)),
                ('ha_wo', models.FloatField(blank=True, null=True)),
                ('gross_irrigation_water_start', models.FloatField(blank=True, null=True)),
                ('gross_irrigation_water_w', models.FloatField(blank=True, null=True)),
                ('gross_irrigation_water_wo', models.FloatField(blank=True, null=True)),
                ('ef_t2_start', models.FloatField(blank=True, null=True)),
                ('ef_t2_w', models.FloatField(blank=True, null=True)),
                ('ef_t2_wo', models.FloatField(blank=True, null=True)),
                ('transmission_loss_t2_start', models.FloatField(blank=True, null=True)),
                ('transmission_loss_t2_w', models.FloatField(blank=True, null=True)),
                ('transmission_loss_t2_wo', models.FloatField(blank=True, null=True)),
                ('average_pressure_t2', models.FloatField(blank=True, null=True)),
                ('total_dynamic_head_t2', models.FloatField(blank=True, null=True)),
                ('pumping_efficiency_t2_start', models.FloatField(blank=True, null=True)),
                ('pumping_efficiency_t2_w', models.FloatField(blank=True, null=True)),
                ('pumping_efficiency_t2_wo', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('energy_source_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.energysourcetype')),
                ('irrigation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.irrigationtype')),
                ('power_origin_country_t2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
