# Generated by Django 4.2.1 on 2024-09-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_alter_annualcropland_crop_yield_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualcropland',
            old_name='crop_yield_start',
            new_name='crop_yield_t2_start',
        ),
        migrations.RenameField(
            model_name='annualcropland',
            old_name='crop_yield_w',
            new_name='crop_yield_t2_w',
        ),
        migrations.RenameField(
            model_name='annualcropland',
            old_name='crop_yield_wo',
            new_name='crop_yield_t2_wo',
        ),
        migrations.RenameField(
            model_name='historicalannualcropland',
            old_name='crop_yield_start',
            new_name='crop_yield_t2_start',
        ),
        migrations.RenameField(
            model_name='historicalannualcropland',
            old_name='crop_yield_w',
            new_name='crop_yield_t2_w',
        ),
        migrations.RenameField(
            model_name='historicalannualcropland',
            old_name='crop_yield_wo',
            new_name='crop_yield_t2_wo',
        ),
    ]
