# Generated by Django 4.2.1 on 2023-08-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_energysourcetype_irrigationtype_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IrrigationType',
            new_name='IrrigationSystemType',
        ),
        migrations.RenameField(
            model_name='irrigationphase',
            old_name='irrigation_type',
            new_name='irrigation_system_type',
        ),
        migrations.RenameField(
            model_name='irrigationsystem',
            old_name='irrigation_type',
            new_name='irrigation_system_type',
        ),
    ]
