# Generated by Django 4.2.1 on 2023-08-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_rename_irrigationtype_irrigationsystemtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltype',
            name='macro_fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.macrofueltype'),
        ),
    ]
