# Generated by Django 4.2.1 on 2024-09-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_remove_historicalperennialcropland_ag_t2_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration_t2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='duration_t2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
