# Generated by Django 4.2.1 on 2023-08-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_alter_fueltype_macro_fuel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationphase',
            name='energy_source_type',
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fueltype'),
        ),
    ]
