# Generated by Django 4.2.1 on 2023-08-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_remove_irrigationphase_energy_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundwaterIrrigationSystemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='irrigationphase',
            name='irrigation_system_type',
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='groundwater_irrigation_system_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groundwaterirrigationsystemtype'),
        ),
    ]
