# Generated by Django 4.2.1 on 2024-09-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_alter_activity_duration_t2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_w',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_wo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_w',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_wo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='logging_start_year_t2_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='logging_start_year_t2_w',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='logging_start_year_t2_wo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='rotation_start_year_t2_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='rotation_start_year_t2_w',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='rotation_start_year_t2_wo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
