# Generated by Django 4.2.1 on 2023-08-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_groundwaterirrigationsystemtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationphase',
            name='groundwater_irrigation_system_type',
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='irrigation_system_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.irrigationsystemtype'),
        ),
    ]
