# Generated by Django 4.2.1 on 2024-09-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_alter_forestmanagement_logging_start_year_t2_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
