# Generated by Django 4.2.1 on 2023-08-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0094_remove_irrigationpressurerequirement_groundwater_irrigation_system_type_and_more'),
        ('api', '0128_remove_irrigationphase_groundwater_irrigation_system_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroundwaterIrrigationSystemType',
        ),
    ]
