# Generated by Django 4.2.1 on 2024-09-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_organizationtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallargefishery',
            old_name='energy_emission_factor_t2_start',
            new_name='energy_emission_factor_co2_t2_start',
        ),
        migrations.RenameField(
            model_name='historicallargefishery',
            old_name='energy_emission_factor_t2_w',
            new_name='energy_emission_factor_co2_t2_w',
        ),
        migrations.RenameField(
            model_name='historicallargefishery',
            old_name='energy_emission_factor_t2_wo',
            new_name='energy_emission_factor_co2_t2_wo',
        ),
        migrations.RenameField(
            model_name='historicalsmallfishery',
            old_name='energy_emission_factor_t2_start',
            new_name='energy_emission_factor_co2_t2_start',
        ),
        migrations.RenameField(
            model_name='historicalsmallfishery',
            old_name='energy_emission_factor_t2_w',
            new_name='energy_emission_factor_co2_t2_w',
        ),
        migrations.RenameField(
            model_name='historicalsmallfishery',
            old_name='energy_emission_factor_t2_wo',
            new_name='energy_emission_factor_co2_t2_wo',
        ),
        migrations.RenameField(
            model_name='largefishery',
            old_name='energy_emission_factor_t2_start',
            new_name='energy_emission_factor_co2_t2_start',
        ),
        migrations.RenameField(
            model_name='largefishery',
            old_name='energy_emission_factor_t2_w',
            new_name='energy_emission_factor_co2_t2_w',
        ),
        migrations.RenameField(
            model_name='largefishery',
            old_name='energy_emission_factor_t2_wo',
            new_name='energy_emission_factor_co2_t2_wo',
        ),
        migrations.RenameField(
            model_name='smallfishery',
            old_name='energy_emission_factor_t2_start',
            new_name='energy_emission_factor_co2_t2_start',
        ),
        migrations.RenameField(
            model_name='smallfishery',
            old_name='energy_emission_factor_t2_w',
            new_name='energy_emission_factor_co2_t2_w',
        ),
        migrations.RenameField(
            model_name='smallfishery',
            old_name='energy_emission_factor_t2_wo',
            new_name='energy_emission_factor_co2_t2_wo',
        ),
        migrations.AddField(
            model_name='historicallargefishery',
            name='energy_emission_factor_ch4_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallargefishery',
            name='energy_emission_factor_ch4_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallargefishery',
            name='energy_emission_factor_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallargefishery',
            name='energy_emission_factor_n2o_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallargefishery',
            name='energy_emission_factor_n2o_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallargefishery',
            name='energy_emission_factor_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsmallfishery',
            name='energy_emission_factor_ch4_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsmallfishery',
            name='energy_emission_factor_ch4_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsmallfishery',
            name='energy_emission_factor_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsmallfishery',
            name='energy_emission_factor_n2o_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsmallfishery',
            name='energy_emission_factor_n2o_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsmallfishery',
            name='energy_emission_factor_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='energy_emission_factor_ch4_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='energy_emission_factor_ch4_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='energy_emission_factor_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='energy_emission_factor_n2o_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='energy_emission_factor_n2o_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='energy_emission_factor_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='energy_emission_factor_ch4_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='energy_emission_factor_ch4_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='energy_emission_factor_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='energy_emission_factor_n2o_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='energy_emission_factor_n2o_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='energy_emission_factor_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
