# Generated by Django 4.2.1 on 2023-08-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_delete_groundwaterirrigationsystemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
