# Generated by Django 4.2.1 on 2023-08-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_irrigationparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.FloatField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Activity states',
                'unique_together': {('name', 'value')},
            },
        ),
    ]
