# Generated by Django 4.2.1 on 2024-09-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_rename_energy_emission_factor_t2_start_historicallargefishery_energy_emission_factor_co2_t2_start_an'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalirrigationphase',
            old_name='ef_t2_start',
            new_name='ef_ch4_t2_start',
        ),
        migrations.RenameField(
            model_name='historicalirrigationphase',
            old_name='ef_t2_w',
            new_name='ef_ch4_t2_w',
        ),
        migrations.RenameField(
            model_name='historicalirrigationphase',
            old_name='ef_t2_wo',
            new_name='ef_ch4_t2_wo',
        ),
        migrations.RenameField(
            model_name='irrigationphase',
            old_name='ef_t2_start',
            new_name='ef_ch4_t2_start',
        ),
        migrations.RenameField(
            model_name='irrigationphase',
            old_name='ef_t2_w',
            new_name='ef_ch4_t2_w',
        ),
        migrations.RenameField(
            model_name='irrigationphase',
            old_name='ef_t2_wo',
            new_name='ef_ch4_t2_wo',
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
