# Generated by Django 4.2.1 on 2023-08-10 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_activitystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
    ]
