# Generated by Django 4.2.1 on 2023-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_activity_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationparameter',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
