# Generated by Django 4.2.1 on 2023-08-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
            preserve_default=False,
        ),
    ]
