# Generated by Django 4.2.1 on 2024-09-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_activitytype_name_en_activitytype_name_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallargefishery',
            name='fui_start',
        ),
        migrations.RemoveField(
            model_name='historicallargefishery',
            name='fui_w',
        ),
        migrations.RemoveField(
            model_name='historicallargefishery',
            name='fui_wo',
        ),
        migrations.RemoveField(
            model_name='historicalsmallfishery',
            name='fui_start',
        ),
        migrations.RemoveField(
            model_name='historicalsmallfishery',
            name='fui_w',
        ),
        migrations.RemoveField(
            model_name='historicalsmallfishery',
            name='fui_wo',
        ),
        migrations.RemoveField(
            model_name='largefishery',
            name='fui_start',
        ),
        migrations.RemoveField(
            model_name='largefishery',
            name='fui_w',
        ),
        migrations.RemoveField(
            model_name='largefishery',
            name='fui_wo',
        ),
        migrations.RemoveField(
            model_name='smallfishery',
            name='fui_start',
        ),
        migrations.RemoveField(
            model_name='smallfishery',
            name='fui_w',
        ),
        migrations.RemoveField(
            model_name='smallfishery',
            name='fui_wo',
        ),
        migrations.AddField(
            model_name='historicallargefishery',
            name='fui_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_start'),
        ),
        migrations.AddField(
            model_name='historicallargefishery',
            name='fui_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_w'),
        ),
        migrations.AddField(
            model_name='historicallargefishery',
            name='fui_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalsmallfishery',
            name='fui_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalsmallfishery',
            name='fui_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalsmallfishery',
            name='fui_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_wo'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='fui_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_start'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='fui_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_w'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='fui_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_wo'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='fui_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_start'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='fui_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_w'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='fui_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='fui_t2_wo'),
        ),
    ]
