# Generated by Django 4.2.1 on 2024-09-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_remove_historicallargefishery_fui_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='soc_t2',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2'),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='soc_t2',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2'),
        ),
    ]
