# Generated by Django 4.2.1 on 2023-08-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_comment_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='largefishery',
            name='total_catch_yr_w_rate',
        ),
        migrations.RemoveField(
            model_name='largefishery',
            name='total_catch_yr_wo_rate',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='heads_number_w_rate',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='heads_number_wo_rate',
        ),
        migrations.RemoveField(
            model_name='smallfishery',
            name='total_catch_yr_w_rate',
        ),
        migrations.RemoveField(
            model_name='smallfishery',
            name='total_catch_yr_wo_rate',
        ),
        migrations.AddField(
            model_name='largefishery',
            name='gear_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_gear_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='ice_preserved_catch_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ice_preserved_catch_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='refrigerant_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_refrigerant_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='total_catch_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_total_catch_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='heads_number_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_heads_number_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_category_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_livestock_categories_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_production_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_livestock_production_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='production_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_production_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='gear_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_gear_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='ice_preserved_catch_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ice_preserved_catch_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='refrigerant_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_refrigerant_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='total_catch_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_total_catch_thread', to='api.commentthread'),
        ),
    ]
