# Generated by Django 4.2.1 on 2023-08-28 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_commentthread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largefishery',
            name='gear_type_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_gear_type_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='ice_preserved_catch_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ice_preserved_catch_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='refrigerant_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_refrigerant_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='total_catch_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_total_catch_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='heads_number_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_heads_number_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='livestock_category_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_livestock_categories_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='livestock_production_type_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_livestock_production_type_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='production_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_production_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='gear_type_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_gear_type_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='ice_preserved_catch_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ice_preserved_catch_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='refrigerant_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_refrigerant_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='total_catch_thread',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_total_catch_thread', to='api.commentthread'),
        ),
    ]
