# Generated by Django 4.2.1 on 2024-10-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_activity_soc_t2_historicalactivity_soc_t2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallargefishery',
            name='fui_default',
        ),
        migrations.RemoveField(
            model_name='historicalsmallfishery',
            name='fui_default',
        ),
        migrations.RemoveField(
            model_name='largefishery',
            name='fui_default',
        ),
        migrations.RemoveField(
            model_name='smallfishery',
            name='fui_default',
        ),
    ]
