# Generated by Django 4.2.1 on 2024-10-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_climate_name_en_climate_name_es_climate_name_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grassland',
            name='fire_impact_start',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='fire_impact_start'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='fire_impact_w',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='fire_impact_w'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='fire_impact_wo',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='fire_impact_wo'),
        ),
        migrations.AlterField(
            model_name='historicalgrassland',
            name='fire_impact_start',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='fire_impact_start'),
        ),
        migrations.AlterField(
            model_name='historicalgrassland',
            name='fire_impact_w',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='fire_impact_w'),
        ),
        migrations.AlterField(
            model_name='historicalgrassland',
            name='fire_impact_wo',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='fire_impact_wo'),
        ),
    ]
