# Generated by Django 4.2.1 on 2024-10-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_alter_grassland_fire_impact_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='agb_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_t2_start'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='agb_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_t2_w'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='agb_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_t2_wo'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='bgb_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_t2_start'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='bgb_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_t2_w'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='bgb_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='agb_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='agb_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='agb_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='bgb_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='bgb_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='bgb_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_t2_wo'),
        ),
    ]
