# Generated by Django 4.2.1 on 2024-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_grassland_agb_t2_start_grassland_agb_t2_w_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='ef_ch4_t2_start',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='ef_ch4_t2_w',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='ef_ch4_t2_wo',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='ef_co2_t2_start',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='ef_co2_t2_w',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='ef_co2_t2_wo',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='ef_n2o_t2_start',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='ef_n2o_t2_w',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='ef_n2o_t2_wo',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='ef_ch4_t2_start',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='ef_ch4_t2_w',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='ef_ch4_t2_wo',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='ef_co2_t2_start',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='ef_co2_t2_w',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='ef_co2_t2_wo',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='ef_n2o_t2_start',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='ef_n2o_t2_w',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='ef_n2o_t2_wo',
        ),
        migrations.AddField(
            model_name='fuel',
            name='ef_ch4_t2',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='ef_co2_t2',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='ef_n2o_t2',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='ef_ch4_t2',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='ef_co2_t2',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='ef_n2o_t2',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2'),
        ),
    ]
