# Generated by Django 4.2.1 on 2023-08-28 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_alter_largefishery_gear_type_thread_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='activity',
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.commentthread'),
        ),
    ]
