# Generated by Django 4.2.1 on 2024-10-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_remove_historicalotherland_agb_t2_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, verbose_name='Model Name')),
                ('field_name', models.CharField(max_length=255, verbose_name='Field Name')),
                ('description', models.TextField(verbose_name='Field Description')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=10, verbose_name='Language Code')),
            ],
            options={
                'verbose_name': 'Field Definition',
                'verbose_name_plural': 'Field Definitions',
                'unique_together': {('model_name', 'field_name', 'language_code')},
            },
        ),
    ]
