# Generated by Django 4.2.1 on 2024-10-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_fielddefinition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fielddefinition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='api.moduletype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fielddefinition',
            unique_together={('model', 'field_name', 'language_code')},
        ),
        migrations.RemoveField(
            model_name='fielddefinition',
            name='model_name',
        ),
    ]
