# Generated by Django 4.2.1 on 2023-08-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_smallfisheryparameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestation',
            old_name='is_fire_used',
            new_name='is_fire_used_start',
        ),
        migrations.RemoveField(
            model_name='deforestation',
            name='ha_w_rate',
        ),
        migrations.RemoveField(
            model_name='deforestation',
            name='ha_wo_rate',
        ),
        migrations.RemoveField(
            model_name='deforestation',
            name='land_use_type',
        ),
        migrations.AddField(
            model_name='deforestation',
            name='is_fire_used_w',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='is_fire_used_wo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent__isnull', True), ('parent__name', 'Agroforestry'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent__isnull', True), ('parent__name', 'Agroforestry'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent__isnull', True), ('parent__name', 'Agroforestry'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
    ]
