# Generated by Django 4.2.1 on 2024-10-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_alter_fielddefinition_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fielddefinition',
            old_name='model',
            new_name='module_type',
        ),
        migrations.AlterUniqueTogether(
            name='fielddefinition',
            unique_together={('module_type', 'field_name', 'language_code')},
        ),
    ]
