# Generated by Django 4.2.1 on 2023-08-30 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_rename_is_fire_used_deforestation_is_fire_used_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestation',
            old_name='final_rcs_biomass_t2',
            new_name='final_rcs_biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='deforestation',
            name='vegetation_type',
        ),
        migrations.AddField(
            model_name='deforestation',
            name='final_rcs_biomass_t2_w',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for biomass in final land use (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='final_rcs_biomass_t2_wo',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for biomass in final land use (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='vegetation_type_start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_vegetation_type_start', to='api.vegetationtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deforestation',
            name='vegetation_type_w',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_vegetation_type_w', to='api.vegetationtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deforestation',
            name='vegetation_type_wo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_vegetation_type_wo', to='api.vegetationtype'),
            preserve_default=False,
        ),
    ]
