# Generated by Django 4.2.1 on 2023-08-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_rename_final_rcs_biomass_t2_deforestation_final_rcs_biomass_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestation',
            old_name='rcs_litter_t2',
            new_name='rcs_litter_t2_start',
        ),
        migrations.AddField(
            model_name='deforestation',
            name='rcs_litter_t2_w',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for litter (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='rcs_litter_t2_wo',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for litter (in tC/ha)', null=True),
        ),
    ]
