# Generated by Django 4.2.1 on 2024-10-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_fielddefinition_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fielddefinition',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='fielddefinition',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='fielddefinition',
            name='description_fr',
        ),
    ]
