# Generated by Django 4.2.1 on 2024-10-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_remove_fielddefinition_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddefinition',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Field Description'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Field Description'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Field Description'),
        ),
    ]
