# Generated by Django 4.2.1 on 2023-08-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_rename_rcs_litter_t2_deforestation_rcs_litter_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestation',
            old_name='rcs_deadwood_t2',
            new_name='rcs_deadwood_t2_start',
        ),
        migrations.RenameField(
            model_name='deforestation',
            old_name='rcs_soil_c_t2',
            new_name='rcs_soil_c_t2_start',
        ),
        migrations.AddField(
            model_name='deforestation',
            name='rcs_deadwood_t2_w',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for deadwood (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='rcs_deadwood_t2_wo',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for deadwood (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='rcs_soil_c_t2_w',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='rcs_soil_c_t2_wo',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon (in tC/ha)', null=True),
        ),
    ]
