# Generated by Django 4.2.1 on 2023-08-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_rename_rcs_deadwood_t2_deforestation_rcs_deadwood_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestation',
            old_name='hwp',
            new_name='hwp_start',
        ),
        migrations.AddField(
            model_name='deforestation',
            name='hwp_w',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deforestation',
            name='hwp_wo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
