# Generated by Django 4.2.1 on 2023-08-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_rename_hwp_deforestation_hwp_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestation',
            old_name='rcs_ag_t2',
            new_name='rcs_ag_t2_start',
        ),
        migrations.RenameField(
            model_name='deforestation',
            old_name='rcs_bg_t2',
            new_name='rcs_bg_t2_start',
        ),
        migrations.AddField(
            model_name='deforestation',
            name='rcs_ag_t2_w',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for above-ground biomass (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='rcs_ag_t2_wo',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for above-ground biomass (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='rcs_bg_t2_w',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for below-ground biomass (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='rcs_bg_t2_wo',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for below-ground biomass (in tC/ha)', null=True),
        ),
    ]
