# Generated by Django 4.2.1 on 2024-10-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_rename_energy_emission_factor_ch4_t2_start_historicallargefishery_energy_ef_ch4_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricity',
            old_name='ef_t2_start',
            new_name='energy_ef_t2_start',
        ),
        migrations.RenameField(
            model_name='electricity',
            old_name='ef_t2_w',
            new_name='energy_ef_t2_w',
        ),
        migrations.RenameField(
            model_name='electricity',
            old_name='ef_t2_wo',
            new_name='energy_ef_t2_wo',
        ),
        migrations.RenameField(
            model_name='historicalelectricity',
            old_name='ef_t2_start',
            new_name='energy_ef_t2_start',
        ),
        migrations.RenameField(
            model_name='historicalelectricity',
            old_name='ef_t2_w',
            new_name='energy_ef_t2_w',
        ),
        migrations.RenameField(
            model_name='historicalelectricity',
            old_name='ef_t2_wo',
            new_name='energy_ef_t2_wo',
        ),
    ]
