# Generated by Django 4.2.1 on 2023-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_rename_rcs_ag_t2_deforestation_rcs_ag_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestation',
            old_name='final_rcs_soil_c_t2',
            new_name='final_rcs_soil_c_t2_start',
        ),
        migrations.AddField(
            model_name='deforestation',
            name='final_rcs_soil_c_t2_w',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon in final land use (in tC/ha)', null=True),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='final_rcs_soil_c_t2_wo',
            field=models.FloatField(blank=True, help_text='Custom reference carbon stock for soil carbon in final land use (in tC/ha)', null=True),
        ),
    ]
