# Generated by Django 4.2.1 on 2024-10-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_rename_ef_t2_start_electricity_energy_ef_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricity',
            old_name='energy_ef_t2_start',
            new_name='electricity_ef_t2_start',
        ),
        migrations.RenameField(
            model_name='electricity',
            old_name='energy_ef_t2_w',
            new_name='electricity_ef_t2_w',
        ),
        migrations.RenameField(
            model_name='electricity',
            old_name='energy_ef_t2_wo',
            new_name='electricity_ef_t2_wo',
        ),
        migrations.RenameField(
            model_name='historicalelectricity',
            old_name='energy_ef_t2_start',
            new_name='electricity_ef_t2_start',
        ),
        migrations.RenameField(
            model_name='historicalelectricity',
            old_name='energy_ef_t2_w',
            new_name='electricity_ef_t2_w',
        ),
        migrations.RenameField(
            model_name='historicalelectricity',
            old_name='energy_ef_t2_wo',
            new_name='electricity_ef_t2_wo',
        ),
    ]
