# Generated by Django 4.2.1 on 2024-10-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_rename_energy_ef_t2_start_electricity_electricity_ef_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='ef_ch4_t2',
            new_name='energy_ef_ch4_t2',
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='ef_co2_t2',
            new_name='energy_ef_co2_t2',
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='ef_n2o_t2',
            new_name='energy_ef_n2o_t2',
        ),
        migrations.RenameField(
            model_name='historicalfuel',
            old_name='ef_ch4_t2',
            new_name='energy_ef_ch4_t2',
        ),
        migrations.RenameField(
            model_name='historicalfuel',
            old_name='ef_co2_t2',
            new_name='energy_ef_co2_t2',
        ),
        migrations.RenameField(
            model_name='historicalfuel',
            old_name='ef_n2o_t2',
            new_name='energy_ef_n2o_t2',
        ),
    ]
