# Generated by Django 4.2.1 on 2023-08-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_rename_final_rcs_soil_c_t2_deforestation_final_rcs_soil_c_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestation',
            old_name='final_rcs_soil_c_t2_start',
            new_name='soc_after_defo_t2_start',
        ),
        migrations.RenameField(
            model_name='deforestation',
            old_name='final_rcs_soil_c_t2_w',
            new_name='soc_after_defo_t2_w',
        ),
        migrations.RenameField(
            model_name='deforestation',
            old_name='final_rcs_soil_c_t2_wo',
            new_name='soc_after_defo_t2_wo',
        ),
    ]
