# Generated by Django 4.2.1 on 2023-08-30 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_rename_final_rcs_soil_c_t2_start_deforestation_soc_after_defo_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualcropping',
            name='ha_w_rate',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='ha_wo_rate',
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='crop_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='crop_yield_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_yield_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='ha_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='organic_input_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='residue_management_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='tillage_management_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_thread', to='api.commentthread'),
        ),
    ]
