# Generated by Django 4.2.1 on 2024-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_rename_ef_ch4_t2_fuel_energy_ef_ch4_t2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='area',
            field=models.FloatField(default=0, verbose_name='area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='area',
            field=models.FloatField(default=0, verbose_name='area'),
            preserve_default=False,
        ),
    ]
