# Generated by Django 4.2.1 on 2024-10-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_activity_area_historicalactivity_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='area',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='area',
        ),
    ]
