# Generated by Django 4.2.1 on 2023-08-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_remove_annualcropping_ha_w_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perennialcropping',
            old_name='crop_yield',
            new_name='crop_yield_start',
        ),
        migrations.RenameField(
            model_name='perennialcropping',
            old_name='is_biomass_burned',
            new_name='is_biomass_burned_start',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='ha_w_rate',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='ha_wo_rate',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='organic_input_type',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='tillage_management_type',
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='crop_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_type_start', to='api.croptype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='crop_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='crop_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_type_w', to='api.croptype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='crop_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_type_wo', to='api.croptype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='crop_yield_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crop_yield_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='crop_yield_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='crop_yield_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='ha_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='is_biomass_burned_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_is_biomass_burned_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='is_biomass_burned_w',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='is_biomass_burned_wo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='organic_input_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_start', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='organic_input_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='organic_input_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_w', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='organic_input_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_wo', to='api.organicinputtype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_start', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_management_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_w', to='api.tillagemanagementtype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_wo', to='api.tillagemanagementtype'),
        ),
    ]
