# Generated by Django 4.2.1 on 2023-08-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_rename_crop_yield_perennialcropping_crop_yield_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perennialcropping',
            old_name='ag_t2',
            new_name='ag_t2_start',
        ),
        migrations.RenameField(
            model_name='perennialcropping',
            old_name='bg_t2',
            new_name='ag_t2_w',
        ),
        migrations.RenameField(
            model_name='perennialcropping',
            old_name='fire_periodicity_t2',
            new_name='ag_t2_wo',
        ),
        migrations.RenameField(
            model_name='perennialcropping',
            old_name='flu_t2',
            new_name='bg_t2_start',
        ),
        migrations.RenameField(
            model_name='perennialcropping',
            old_name='input_factor_t2',
            new_name='bg_t2_w',
        ),
        migrations.RenameField(
            model_name='perennialcropping',
            old_name='residue_burned_t2',
            new_name='bg_t2_wo',
        ),
        migrations.RenameField(
            model_name='perennialcropping',
            old_name='soc_t2',
            new_name='fire_periodicity_t2_start',
        ),
        migrations.RenameField(
            model_name='perennialcropping',
            old_name='tillage_factor_t2',
            new_name='fire_periodicity_t2_w',
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='fire_periodicity_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='flu_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='flu_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='flu_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='input_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='input_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='input_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='residue_burned_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='residue_burned_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='residue_burned_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='tillage_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
