# Generated by Django 4.2.1 on 2024-10-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_alter_activity_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.project', verbose_name='project'),
        ),
    ]
