# Generated by Django 4.2.1 on 2023-09-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_rename_ag_t2_perennialcropping_ag_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='change_rate_start',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='change_rate_w',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='change_rate_wo',
        ),
        migrations.AddField(
            model_name='activity',
            name='change_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_rate', to='api.changerate'),
        ),
    ]
