# Generated by Django 4.2.1 on 2024-10-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_alter_activity_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='building',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='building',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='forestdisturbance',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='forestdisturbance',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='forestdisturbance',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalbuilding',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalbuilding',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalbuilding',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalelectricity',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalelectricity',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalelectricity',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalforestdisturbance',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalforestdisturbance',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalforestdisturbance',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalinputentry',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalinputentry',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalinputentry',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalirrigationsystem',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalirrigationsystem',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalirrigationsystem',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonannualcropland',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonannualcropland',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonannualcropland',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonfloodedrice',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonfloodedrice',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonfloodedrice',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonperennialcropland',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonperennialcropland',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonperennialcropland',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalotherinfrastructure',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalotherinfrastructure',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalotherinfrastructure',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalroad',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalroad',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalroad',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='inputentry',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='inputentry',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='inputentry',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='minorseasonannualcropland',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='minorseasonannualcropland',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='minorseasonannualcropland',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropland',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropland',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropland',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
        migrations.AddField(
            model_name='road',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_start'),
        ),
        migrations.AddField(
            model_name='road',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_w'),
        ),
        migrations.AddField(
            model_name='road',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='soc_t2_wo'),
        ),
    ]
