# Generated by Django 4.2.1 on 2023-09-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_remove_activity_change_rate_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquacultureParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='aquaculture',
            old_name='annual_feed_quantity_start',
            new_name='electricity_used_t2_start',
        ),
        migrations.RenameField(
            model_name='aquaculture',
            old_name='annual_feed_quantity_w',
            new_name='electricity_used_t2_w',
        ),
        migrations.RenameField(
            model_name='aquaculture',
            old_name='annual_feed_quantity_wo',
            new_name='electricity_used_t2_wo',
        ),
        migrations.RenameField(
            model_name='aquaculture',
            old_name='feed_use_emissions_t2',
            new_name='n2o_from_production_t2_start',
        ),
        migrations.RenameField(
            model_name='aquaculture',
            old_name='production_n2o_ef_t2',
            new_name='n2o_from_production_t2_w',
        ),
        migrations.RemoveField(
            model_name='aquaculture',
            name='annual_feed_quantity_w_rate',
        ),
        migrations.RemoveField(
            model_name='aquaculture',
            name='annual_feed_quantity_wo_rate',
        ),
        migrations.RemoveField(
            model_name='aquaculture',
            name='annual_production_w_rate',
        ),
        migrations.RemoveField(
            model_name='aquaculture',
            name='annual_production_wo_rate',
        ),
        migrations.RemoveField(
            model_name='aquaculture',
            name='implementation_year_t2',
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='n2o_from_production_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='change_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_rate', to='api.changerate'),
        ),
    ]
