# Generated by Django 4.2.1 on 2023-09-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_aquacultureparameter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grassland',
            old_name='agb_t2',
            new_name='agb_t2_start',
        ),
        migrations.RenameField(
            model_name='grassland',
            old_name='combustion_factor_t2',
            new_name='agb_t2_w',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='ha_w_rate',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='ha_wo_rate',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='implementation_year_start',
        ),
        migrations.AddField(
            model_name='grassland',
            name='agb_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='combustion_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='combustion_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='combustion_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_management_type_start', to='api.grasslandmanagementtype'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_management_type_w', to='api.grasslandmanagementtype'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_management_type_wo', to='api.grasslandmanagementtype'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='ha_start',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
