# Generated by Django 4.2.1 on 2024-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_building_soc_t2_start_building_soc_t2_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalminorseasonfloodedrice',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='biomass_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonfloodedrice',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='biomass_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonfloodedrice',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='biomass_t2_wo'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='biomass_t2_start'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='biomass_t2_w'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='biomass_t2_wo'),
        ),
    ]
