# Generated by Django 4.2.1 on 2023-09-01 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_rename_agb_t2_grassland_agb_t2_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrasslandParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='soil_carbon_start_t2',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='soil_carbon_w_t2',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='soil_carbon_wo_t2',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='years_w_fire_management',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='years_wo_fire_management',
        ),
        migrations.AddField(
            model_name='grassland',
            name='fire_impact_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='fire_impact_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fire_impact_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='fire_impact_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='fire_impact_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='fire_periodicity_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='fire_periodicity_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fire_periodicity_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='fire_periodicity_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='fire_periodicity_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='ha_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ha_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='is_fire_used_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grassland',
            name='is_fire_used_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_is_fire_used_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='soil_carbon_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='soil_carbon_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='soil_carbon_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='yield_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_yield_thread', to='api.commentthread'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='is_fire_used_w',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='is_fire_used_wo',
            field=models.BooleanField(default=False),
        ),
    ]
