# Generated by Django 4.2.1 on 2024-10-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_historicalminorseasonfloodedrice_biomass_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalminorseasonfloodedrice',
            name='biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='historicalminorseasonfloodedrice',
            name='biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='historicalminorseasonfloodedrice',
            name='biomass_t2_wo',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='minorseasonfloodedrice',
            name='biomass_t2_wo',
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='area_not_drained_start',
            field=models.FloatField(default=0, verbose_name='area_not_drained_start'),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='area_not_drained_w',
            field=models.FloatField(default=0, verbose_name='area_not_drained_w'),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='area_not_drained_wo',
            field=models.FloatField(default=0, verbose_name='area_not_drained_wo'),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='ditches_area_start',
            field=models.FloatField(default=0, verbose_name='ditches_area_start'),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='ditches_area_w',
            field=models.FloatField(default=0, verbose_name='ditches_area_w'),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='ditches_area_wo',
            field=models.FloatField(default=0, verbose_name='ditches_area_wo'),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='drainage_area_start',
            field=models.FloatField(default=0, verbose_name='drainage_area_start'),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='drainage_area_w',
            field=models.FloatField(default=0, verbose_name='drainage_area_w'),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='drainage_area_wo',
            field=models.FloatField(default=0, verbose_name='drainage_area_wo'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='area_not_drained_start',
            field=models.FloatField(default=0, verbose_name='area_not_drained_start'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='area_not_drained_w',
            field=models.FloatField(default=0, verbose_name='area_not_drained_w'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='area_not_drained_wo',
            field=models.FloatField(default=0, verbose_name='area_not_drained_wo'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='ditches_area_start',
            field=models.FloatField(default=0, verbose_name='ditches_area_start'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='ditches_area_w',
            field=models.FloatField(default=0, verbose_name='ditches_area_w'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='ditches_area_wo',
            field=models.FloatField(default=0, verbose_name='ditches_area_wo'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='drainage_area_start',
            field=models.FloatField(default=0, verbose_name='drainage_area_start'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='drainage_area_w',
            field=models.FloatField(default=0, verbose_name='drainage_area_w'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='drainage_area_wo',
            field=models.FloatField(default=0, verbose_name='drainage_area_wo'),
        ),
    ]
