# Generated by Django 4.2.1 on 2023-09-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_annualcroplandparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganicSoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('drainage_area_start', models.FloatField(blank=True, null=True)),
                ('drainage_area_w', models.FloatField(blank=True, null=True)),
                ('drainage_area_wo', models.FloatField(blank=True, null=True)),
                ('area_not_drained_start', models.FloatField(blank=True, null=True)),
                ('area_not_drained_w', models.FloatField(blank=True, null=True)),
                ('area_not_drained_wo', models.FloatField(blank=True, null=True)),
                ('ditches_area_start', models.FloatField(blank=True, null=True)),
                ('ditches_area_w', models.FloatField(blank=True, null=True)),
                ('ditches_area_wo', models.FloatField(blank=True, null=True)),
                ('is_fire_on_soil_start', models.BooleanField(default=False)),
                ('is_fire_on_soil_w', models.BooleanField(default=False)),
                ('is_fire_on_soil_wo', models.BooleanField(default=False)),
                ('soil_fire_periodicity_start', models.FloatField(blank=True, null=True)),
                ('soil_fire_periodicity_w', models.FloatField(blank=True, null=True)),
                ('soil_fire_periodicity_wo', models.FloatField(blank=True, null=True)),
                ('soil_fire_impact_percentage_start', models.FloatField(blank=True, null=True)),
                ('soil_fire_impact_percentage_w', models.FloatField(blank=True, null=True)),
                ('soil_fire_impact_percentage_wo', models.FloatField(blank=True, null=True)),
                ('has_peat_extraction', models.BooleanField(default=False)),
                ('peat_area_start', models.FloatField(blank=True, null=True)),
                ('peat_area_w', models.FloatField(blank=True, null=True)),
                ('peat_area_wo', models.FloatField(blank=True, null=True)),
                ('peat_ditches_area_start', models.FloatField(blank=True, null=True)),
                ('peat_ditches_area_w', models.FloatField(blank=True, null=True)),
                ('peat_ditches_area_wo', models.FloatField(blank=True, null=True)),
                ('peat_extraction_height_start', models.FloatField(blank=True, null=True)),
                ('peat_extraction_height_w', models.FloatField(blank=True, null=True)),
                ('peat_extraction_height_wo', models.FloatField(blank=True, null=True)),
                ('peat_is_for_energy_start', models.BooleanField(default=False)),
                ('peat_is_for_energy_w', models.BooleanField(default=False)),
                ('peat_is_for_energy_wo', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('area_not_drained_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_area_not_drained_thread', to='api.commentthread')),
                ('ditches_area_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ditches_area_thread', to='api.commentthread')),
                ('drainage_area_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_drainage_area_thread', to='api.commentthread')),
                ('is_fire_on_soil_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_is_fire_on_soil_thread', to='api.commentthread')),
                ('peat_area_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_peat_area_thread', to='api.commentthread')),
                ('peat_ditches_area_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_peat_ditches_area_thread', to='api.commentthread')),
                ('peat_extraction_height_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_peat_extraction_height_thread', to='api.commentthread')),
                ('peat_is_for_energy_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_peat_is_for_energy_thread', to='api.commentthread')),
                ('peat_type_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_peat_type_start', to='api.peattype')),
                ('peat_type_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_peat_type_thread', to='api.commentthread')),
                ('peat_type_w', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_peat_type_w', to='api.peattype')),
                ('peat_type_wo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_peat_type_wo', to='api.peattype')),
                ('soil_fire_impact_percentage_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_soil_fire_impact_percentage_thread', to='api.commentthread')),
                ('soil_fire_periodicity_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_soil_fire_periodicity_thread', to='api.commentthread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
