# Generated by Django 4.2.1 on 2023-09-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_organicsoil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organicsoil',
            old_name='peat_is_for_energy_start',
            new_name='is_peat_for_energy_start',
        ),
        migrations.RenameField(
            model_name='organicsoil',
            old_name='peat_is_for_energy_thread',
            new_name='is_peat_is_for_energy_thread',
        ),
        migrations.RenameField(
            model_name='organicsoil',
            old_name='peat_is_for_energy_w',
            new_name='is_peat_is_for_energy_w',
        ),
        migrations.RenameField(
            model_name='organicsoil',
            old_name='peat_is_for_energy_wo',
            new_name='is_peat_is_for_energy_wo',
        ),
    ]
