# Generated by Django 4.2.1 on 2023-09-04 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_rename_peat_is_for_energy_start_organicsoil_is_peat_for_energy_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='t_co2_m2_t2',
            new_name='ef_t2_start',
        ),
        migrations.RemoveField(
            model_name='building',
            name='building_type',
        ),
        migrations.RemoveField(
            model_name='building',
            name='input_type',
        ),
        migrations.AddField(
            model_name='building',
            name='building_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_building_type_start', to='api.buildingtype'),
        ),
        migrations.AddField(
            model_name='building',
            name='building_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_building_type_w', to='api.buildingtype'),
        ),
        migrations.AddField(
            model_name='building',
            name='building_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_building_type_wo', to='api.buildingtype'),
        ),
        migrations.AddField(
            model_name='building',
            name='ef_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='ef_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='input_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_input_type_start', to='api.inputtype'),
        ),
        migrations.AddField(
            model_name='building',
            name='input_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_input_type_w', to='api.inputtype'),
        ),
        migrations.AddField(
            model_name='building',
            name='input_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_input_type_wo', to='api.inputtype'),
        ),
        migrations.AddField(
            model_name='building',
            name='surface_start',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
