# Generated by Django 4.2.1 on 2023-09-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_rename_t_co2_m2_t2_building_ef_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='input_type_start',
        ),
        migrations.RemoveField(
            model_name='building',
            name='input_type_w',
        ),
        migrations.RemoveField(
            model_name='building',
            name='input_type_wo',
        ),
    ]
