# Generated by Django 4.2.1 on 2024-10-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_annualcropland_cached_results_by_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualcropland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='energy',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalannualcropland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalaquaculture',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalcoastalwetland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalenergy',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalfloodedrice',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalinput',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalirrigation',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicallandusechange',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicallargefishery',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicallivestock',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalorganicsoil',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalotherland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalotherlanduse',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalsetaside',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalsmallfishery',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalwaterbody',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='input',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='otherland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='setaside',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
    ]
