# Generated by Django 4.2.1 on 2024-10-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_annualcropland_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='forestdisturbance',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalbuilding',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalelectricity',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalforestdisturbance',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalinputentry',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalirrigationsystem',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonannualcropland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonfloodedrice',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonperennialcropland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalotherinfrastructure',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='historicalroad',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='inputentry',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='minorseasonannualcropland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropland',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='road',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_modified'),
        ),
    ]
