# Generated by Django 4.2.1 on 2024-10-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_building_last_modified_electricity_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermanagementtypeaftercultivation',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watermanagementtypeaftercultivation',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watermanagementtypeaftercultivation',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watermanagementtypebeforecultivation',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watermanagementtypebeforecultivation',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watermanagementtypebeforecultivation',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
