# Generated by Django 4.2.1 on 2023-09-05 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_alter_largefishery_refrigerant_pc_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largefishery',
            name='refrigerant_pc_start',
            field=models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='refrigerant_pc_w',
            field=models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='refrigerant_pc_wo',
            field=models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='refrigerant_pc_start',
            field=models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='refrigerant_pc_w',
            field=models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='refrigerant_pc_wo',
            field=models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-1]*\\.?[0-9]*$', 'Only correctly formatted percentages are allowed.')]),
        ),
    ]
