# Generated by Django 4.2.1 on 2024-10-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_watermanagementtypeaftercultivation_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Projects'},
        ),
    ]
