# Generated by Django 4.2.1 on 2023-09-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_alter_largefishery_ice_preserved_catch_pc_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floodedrice',
            old_name='crop_yield',
            new_name='crop_yield_start',
        ),
        migrations.RenameField(
            model_name='floodedrice',
            old_name='cultivation_period',
            new_name='cultivation_period_start',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='organic_amendment_type',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='water_management_type_after_cultivation',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='water_management_type_before_cultivation',
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='crop_yield_w',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='crop_yield_wo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='cultivation_period_w',
            field=models.IntegerField(default=113),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='cultivation_period_wo',
            field=models.IntegerField(default=113),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='organic_amendment_type_start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_start', to='api.organicamendmenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='organic_amendment_type_w',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_w', to='api.organicamendmenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='organic_amendment_type_wo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_wo', to='api.organicamendmenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_after_cultivation_start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_start', to='api.watermanagementtypeaftercultivation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_after_cultivation_w',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_w', to='api.watermanagementtypeaftercultivation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_after_cultivation_wo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_wo', to='api.watermanagementtypeaftercultivation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_before_cultivation_start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_start', to='api.watermanagementtypebeforecultivation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_before_cultivation_w',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_w', to='api.watermanagementtypebeforecultivation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='water_management_type_before_cultivation_wo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_wo', to='api.watermanagementtypebeforecultivation'),
            preserve_default=False,
        ),
    ]
