# Generated by Django 4.2.1 on 2023-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_rename_crop_yield_floodedrice_crop_yield_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodedrice',
            name='ha_start',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='ha_w',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='ha_wo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
