# Generated by Django 4.2.1 on 2024-10-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0168_tag_project_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
        migrations.AddField(
            model_name="tag",
            name="project",
            field=models.ForeignKey(default=955, on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="api.project"),
            preserve_default=False,
        ),
    ]
