# Generated by Django 4.2.1 on 2023-09-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_floodedrice_ha_start_floodedrice_ha_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodedrice',
            name='efc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='efc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='efc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='efi_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='efi_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='efi_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='rice_straw_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='rice_straw_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='rice_straw_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='sfo_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='sfo_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='sfo_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='sfp_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='sfp_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='sfp_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='sfw_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='sfw_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='sfw_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
