# Generated by Django 4.2.1 on 2024-10-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_remove_project_tags_tag_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ProjectTag',
        ),
        migrations.AlterModelOptions(
            name='projecttag',
            options={'verbose_name_plural': 'Project Tags'},
        ),
        migrations.AlterUniqueTogether(
            name='projecttag',
            unique_together={('name', 'project')},
        ),
    ]
