# Generated by Django 4.2.1 on 2024-10-29 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_rename_tag_projecttag_alter_projecttag_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projecttag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projecttag',
            unique_together={('name', 'user', 'project')},
        ),
    ]
