# Generated by Django 4.2.1 on 2023-09-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_floodedrice_efc_t2_start_floodedrice_efc_t2_w_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoastalWetlandParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoastalWetland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ha_start', models.FloatField(blank=True, null=True)),
                ('ha_w', models.FloatField(blank=True, null=True)),
                ('ha_wo', models.FloatField(blank=True, null=True)),
                ('area_under_drainage_start', models.FloatField(blank=True, null=True)),
                ('area_under_drainage_w', models.FloatField(blank=True, null=True)),
                ('area_under_drainage_wo', models.FloatField(blank=True, null=True)),
                ('drained_area_excavated_start', models.FloatField(blank=True, null=True)),
                ('drained_area_excavated_w', models.FloatField(blank=True, null=True)),
                ('drained_area_excavated_wo', models.FloatField(blank=True, null=True)),
                ('area_not_drained_or_rewetted_start', models.FloatField(blank=True, null=True)),
                ('area_not_drained_or_rewetted_w', models.FloatField(blank=True, null=True)),
                ('area_not_drained_or_rewetted_wo', models.FloatField(blank=True, null=True)),
                ('area_w_restored_vegetation_start', models.FloatField(blank=True, null=True)),
                ('area_w_restored_vegetation_w', models.FloatField(blank=True, null=True)),
                ('area_w_restored_vegetation_wo', models.FloatField(blank=True, null=True)),
                ('soc_t2_start', models.FloatField(blank=True, null=True)),
                ('soc_t2_w', models.FloatField(blank=True, null=True)),
                ('soc_t2_wo', models.FloatField(blank=True, null=True)),
                ('pc_c_lost_after_excavation_t2_start', models.FloatField(blank=True, null=True)),
                ('pc_c_lost_after_excavation_t2_w', models.FloatField(blank=True, null=True)),
                ('pc_c_lost_after_excavation_t2_wo', models.FloatField(blank=True, null=True)),
                ('agb_t2_start', models.FloatField(blank=True, null=True)),
                ('agb_t2_w', models.FloatField(blank=True, null=True)),
                ('agb_t2_wo', models.FloatField(blank=True, null=True)),
                ('bgb_t2_start', models.FloatField(blank=True, null=True)),
                ('bgb_t2_w', models.FloatField(blank=True, null=True)),
                ('bgb_t2_wo', models.FloatField(blank=True, null=True)),
                ('litter_t2_start', models.FloatField(blank=True, null=True)),
                ('litter_t2_w', models.FloatField(blank=True, null=True)),
                ('litter_t2_wo', models.FloatField(blank=True, null=True)),
                ('deadwood_t2_start', models.FloatField(blank=True, null=True)),
                ('deadwood_t2_w', models.FloatField(blank=True, null=True)),
                ('deadwood_t2_wo', models.FloatField(blank=True, null=True)),
                ('drainage_ef_t2_start', models.FloatField(blank=True, null=True)),
                ('drainage_ef_t2_w', models.FloatField(blank=True, null=True)),
                ('drainage_ef_t2_wo', models.FloatField(blank=True, null=True)),
                ('co2_rewetting_start', models.FloatField(blank=True, null=True)),
                ('co2_rewetting_w', models.FloatField(blank=True, null=True)),
                ('co2_rewetting_wo', models.FloatField(blank=True, null=True)),
                ('ch4_rewetting_start', models.FloatField(blank=True, null=True)),
                ('ch4_rewetting_w', models.FloatField(blank=True, null=True)),
                ('ch4_rewetting_wo', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('area_not_drained_or_rewetted_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_area_not_drained_or_rewetted_thread', to='api.commentthread')),
                ('area_under_drainage_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_area_under_drainage_thread', to='api.commentthread')),
                ('area_w_restored_vegetation_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_area_w_restored_vegetation_thread', to='api.commentthread')),
                ('avg_salinity_t2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.salinitytype')),
                ('drained_area_excavated_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_drained_area_excavated_thread', to='api.commentthread')),
                ('ha_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ha_thread', to='api.commentthread')),
                ('soil_type_t2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.soiltype')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
