# Generated by Django 4.2.1 on 2024-10-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_alter_projecttag_unique_together_projecttag_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttag',
            unique_together={('name', 'slug', 'user', 'project')},
        ),
    ]
