# Generated by Django 4.2.1 on 2023-09-07 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_coastalwetlandparameter_coastalwetland'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waterbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('ch4_ef_t2_start', models.FloatField(blank=True, null=True)),
                ('ch4_ef_t2_w', models.FloatField(blank=True, null=True)),
                ('ch4_ef_t2_wo', models.FloatField(blank=True, null=True)),
                ('alpha_t2_start', models.FloatField(blank=True, null=True)),
                ('alpha_t2_w', models.FloatField(blank=True, null=True)),
                ('alpha_t2_wo', models.FloatField(blank=True, null=True)),
                ('mean_annual_t2_start', models.FloatField(blank=True, null=True)),
                ('mean_annual_t2_w', models.FloatField(blank=True, null=True)),
                ('mean_annual_t2_wo', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('trophic_class_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_trophic_class_start', to='api.trophictype')),
                ('trophic_class_w', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_trophic_class_w', to='api.trophictype')),
                ('trophic_class_wo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_trophic_class_wo', to='api.trophictype')),
                ('waterbody_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.waterbodytype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
