# Generated by Django 4.2.1 on 2023-09-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_waterbody'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterbody',
            old_name='trophic_class_start',
            new_name='trophic_type_start',
        ),
        migrations.RenameField(
            model_name='waterbody',
            old_name='trophic_class_w',
            new_name='trophic_type_w',
        ),
        migrations.RenameField(
            model_name='waterbody',
            old_name='trophic_class_wo',
            new_name='trophic_type_wo',
        ),
    ]
