# Generated by Django 4.2.1 on 2024-10-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_alter_projecttag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
