# Generated by Django 4.2.1 on 2023-09-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_rename_trophic_class_start_waterbody_trophic_type_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ha_start', models.FloatField(blank=True, null=True)),
                ('ha_w', models.FloatField(blank=True, null=True)),
                ('ha_wo', models.FloatField(blank=True, null=True)),
                ('is_settlement_start', models.BooleanField(default=False)),
                ('is_settlement_w', models.BooleanField(default=False)),
                ('is_settlement_wo', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('ha_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ha_thread', to='api.commentthread')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SetAside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ha_start', models.FloatField(blank=True, null=True)),
                ('ha_w', models.FloatField(blank=True, null=True)),
                ('ha_wo', models.FloatField(blank=True, null=True)),
                ('is_set_aside_start', models.BooleanField(default=False)),
                ('is_set_aside_w', models.BooleanField(default=False)),
                ('is_set_aside_wo', models.BooleanField(default=False)),
                ('soc_t2_start', models.FloatField(blank=True, null=True)),
                ('soc_t2_w', models.FloatField(blank=True, null=True)),
                ('soc_t2_wo', models.FloatField(blank=True, null=True)),
                ('flu_t2_start', models.FloatField(blank=True, null=True)),
                ('flu_t2_w', models.FloatField(blank=True, null=True)),
                ('flu_t2_wo', models.FloatField(blank=True, null=True)),
                ('agb_t2_start', models.FloatField(blank=True, null=True)),
                ('agb_t2_w', models.FloatField(blank=True, null=True)),
                ('agb_t2_wo', models.FloatField(blank=True, null=True)),
                ('bgb_t2_start', models.FloatField(blank=True, null=True)),
                ('bgb_t2_w', models.FloatField(blank=True, null=True)),
                ('bgb_t2_wo', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('ha_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ha_thread', to='api.commentthread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
