# Generated by Django 4.2.1 on 2023-09-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_settlement_setaside'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegradedLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ha_start', models.FloatField(blank=True, null=True)),
                ('ha_w', models.FloatField(blank=True, null=True)),
                ('ha_wo', models.FloatField(blank=True, null=True)),
                ('is_degraded_land_start', models.BooleanField(default=False)),
                ('is_degraded_land_w', models.BooleanField(default=False)),
                ('is_degraded_land_wo', models.BooleanField(default=False)),
                ('soc_t2_start', models.FloatField(blank=True, null=True)),
                ('soc_t2_w', models.FloatField(blank=True, null=True)),
                ('soc_t2_wo', models.FloatField(blank=True, null=True)),
                ('flu_t2_start', models.FloatField(blank=True, null=True)),
                ('flu_t2_w', models.FloatField(blank=True, null=True)),
                ('flu_t2_wo', models.FloatField(blank=True, null=True)),
                ('agb_t2_start', models.FloatField(blank=True, null=True)),
                ('agb_t2_w', models.FloatField(blank=True, null=True)),
                ('agb_t2_wo', models.FloatField(blank=True, null=True)),
                ('bgb_t2_start', models.FloatField(blank=True, null=True)),
                ('bgb_t2_w', models.FloatField(blank=True, null=True)),
                ('bgb_t2_wo', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
