# Generated by Django 4.2.1 on 2024-11-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_packagingmaterialtype_refrigeranttype_valuechain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprocessing',
            old_name='energy_type_thread',
            new_name='fuel_type_thread',
        ),
        migrations.RemoveField(
            model_name='historicalprocessing',
            name='energy_type_start',
        ),
        migrations.RemoveField(
            model_name='historicalprocessing',
            name='energy_type_w',
        ),
        migrations.RemoveField(
            model_name='historicalprocessing',
            name='energy_type_wo',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='energy_type_start',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='energy_type_thread',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='energy_type_w',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='energy_type_wo',
        ),
        migrations.AddField(
            model_name='historicalprocessing',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'fuel_use_type__name': 'Stationary'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype'),
        ),
        migrations.AddField(
            model_name='historicalprocessing',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'fuel_use_type__name': 'Stationary'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype'),
        ),
        migrations.AddField(
            model_name='historicalprocessing',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'fuel_use_type__name': 'Stationary'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype'),
        ),
        migrations.AddField(
            model_name='processing',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, limit_choices_to={'fuel_use_type__name': 'Stationary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fuel_type_start', to='api.fueltype'),
        ),
        migrations.AddField(
            model_name='processing',
            name='fuel_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fuel_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='processing',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, limit_choices_to={'fuel_use_type__name': 'Stationary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fuel_type_w', to='api.fueltype'),
        ),
        migrations.AddField(
            model_name='processing',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, limit_choices_to={'fuel_use_type__name': 'Stationary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fuel_type_wo', to='api.fueltype'),
        ),
    ]
