# Generated by Django 4.2.1 on 2023-09-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_degradedland'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coastalwetland',
            old_name='ch4_rewetting_start',
            new_name='ch4_rewetting_t2_start',
        ),
        migrations.RenameField(
            model_name='coastalwetland',
            old_name='ch4_rewetting_w',
            new_name='ch4_rewetting_t2_w',
        ),
        migrations.RenameField(
            model_name='coastalwetland',
            old_name='ch4_rewetting_wo',
            new_name='ch4_rewetting_t2_wo',
        ),
        migrations.RenameField(
            model_name='coastalwetland',
            old_name='co2_rewetting_start',
            new_name='co2_rewetting_t2_start',
        ),
        migrations.RenameField(
            model_name='coastalwetland',
            old_name='co2_rewetting_w',
            new_name='co2_rewetting_t2_w',
        ),
        migrations.RenameField(
            model_name='coastalwetland',
            old_name='co2_rewetting_wo',
            new_name='co2_rewetting_t2_wo',
        ),
    ]
