# Generated by Django 4.2.1 on 2024-11-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_rename_energy_type_thread_historicalprocessing_fuel_type_thread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
