# Generated by Django 4.2.1 on 2023-09-11 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_rename_ch4_rewetting_start_coastalwetland_ch4_rewetting_t2_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='building',
            old_name='surface_start',
            new_name='area_m2_start',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='surface_w',
            new_name='area_m2_w',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='surface_wo',
            new_name='area_m2_wo',
        ),
        migrations.AddField(
            model_name='building',
            name='area_m2_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_surface_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='building',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_settlement', to='api.settlement'),
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ef_t2_start', models.FloatField(blank=True, null=True)),
                ('ef_t2_w', models.FloatField(blank=True, null=True)),
                ('ef_t2_wo', models.FloatField(blank=True, null=True)),
                ('length_km_start', models.FloatField(blank=True, null=True)),
                ('length_km_w', models.FloatField(blank=True, null=True)),
                ('length_km_wo', models.FloatField(blank=True, null=True)),
                ('width_m_start', models.FloatField(blank=True, null=True)),
                ('width_m_w', models.FloatField(blank=True, null=True)),
                ('width_m_wo', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('length_km_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_length_km_thread', to='api.commentthread')),
                ('road_type_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_road_type_start', to='api.roadtype')),
                ('road_type_w', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_road_type_w', to='api.roadtype')),
                ('road_type_wo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_road_type_wo', to='api.roadtype')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_settlement', to='api.settlement')),
                ('width_m_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_width_m_thread', to='api.commentthread')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ef_t2_start', models.FloatField(blank=True, null=True)),
                ('ef_t2_w', models.FloatField(blank=True, null=True)),
                ('ef_t2_wo', models.FloatField(blank=True, null=True)),
                ('area_m2_start', models.FloatField(blank=True, null=True)),
                ('area_m2_w', models.FloatField(blank=True, null=True)),
                ('area_m2_wo', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('area_m2_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_area_m2_thread', to='api.commentthread')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_settlement', to='api.settlement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
