# Generated by Django 4.2.1 on 2024-11-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_packagingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocessing',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.country'),
        ),
        migrations.AddField(
            model_name='processing',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_country_of_origin', to='api.country'),
        ),
    ]
