# Generated by Django 4.2.1 on 2023-09-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_sitelocationtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUseChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ha', models.FloatField(blank=True, null=True)),
                ('fire_use_start', models.FloatField(blank=True, null=True)),
                ('fire_use_w', models.FloatField(blank=True, null=True)),
                ('fire_use_wo', models.FloatField(blank=True, null=True)),
                ('dry_matter_start', models.FloatField(blank=True, null=True)),
                ('dry_matter_w', models.FloatField(blank=True, null=True)),
                ('dry_matter_wo', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('module_type_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_end', to='api.moduletype')),
                ('module_type_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_start', to='api.moduletype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
