# Generated by Django 4.2.1 on 2023-09-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_landusechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landusechange',
            name='module_type_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='api.moduletype'),
        ),
        migrations.AlterField(
            model_name='landusechange',
            name='module_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='api.moduletype'),
        ),
    ]
