# Generated by Django 4.2.1 on 2023-09-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_alter_landusechange_module_type_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landusechange',
            name='dry_matter_start',
        ),
        migrations.RemoveField(
            model_name='landusechange',
            name='fire_use_start',
        ),
    ]
