# Generated by Django 4.2.1 on 2024-11-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_packagingtype_valuechain_transport_storage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackagingType',
        ),
    ]
