# Generated by Django 4.2.1 on 2023-09-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_remove_landusechange_dry_matter_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landusechange',
            name='fire_use_w',
        ),
        migrations.RemoveField(
            model_name='landusechange',
            name='fire_use_wo',
        ),
    ]
