# Generated by Django 4.2.1 on 2024-11-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_delete_packagingtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpackaging',
            old_name='kf_of_packaging_material_start',
            new_name='kg_of_packaging_material_start',
        ),
        migrations.RenameField(
            model_name='historicalpackaging',
            old_name='kf_of_packaging_material_thread',
            new_name='kg_of_packaging_material_thread',
        ),
        migrations.RenameField(
            model_name='historicalpackaging',
            old_name='kf_of_packaging_material_w',
            new_name='kg_of_packaging_material_w',
        ),
        migrations.RenameField(
            model_name='historicalpackaging',
            old_name='kf_of_packaging_material_wo',
            new_name='kg_of_packaging_material_wo',
        ),
        migrations.RenameField(
            model_name='packaging',
            old_name='kf_of_packaging_material_start',
            new_name='kg_of_packaging_material_start',
        ),
        migrations.RenameField(
            model_name='packaging',
            old_name='kf_of_packaging_material_thread',
            new_name='kg_of_packaging_material_thread',
        ),
        migrations.RenameField(
            model_name='packaging',
            old_name='kf_of_packaging_material_w',
            new_name='kg_of_packaging_material_w',
        ),
        migrations.RenameField(
            model_name='packaging',
            old_name='kf_of_packaging_material_wo',
            new_name='kg_of_packaging_material_wo',
        ),
    ]
