# Generated by Django 4.2.1 on 2023-09-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_remove_landusechange_fire_use_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landusechange',
            name='fire_use_w',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='fire_use_wo',
            field=models.BooleanField(default=False),
        ),
    ]
