# Generated by Django 4.2.1 on 2023-09-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_landusechange_fire_use_w_landusechange_fire_use_wo'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualcropping',
            name='land_use_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='land_use_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='land_use_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='land_use_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusechange'),
        ),
    ]
