# Generated by Django 4.2.1 on 2024-11-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_rename_kf_of_packaging_material_start_historicalpackaging_kg_of_packaging_material_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackaging',
            name='emission_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpackaging',
            name='emission_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpackaging',
            name='emission_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packaging',
            name='emission_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packaging',
            name='emission_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packaging',
            name='emission_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
