# Generated by Django 4.2.1 on 2024-11-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_historicalpackaging_emission_factor_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprocessing',
            old_name='country_of_origin',
            new_name='country_of_origin_t2',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='country_of_origin',
        ),
        migrations.AddField(
            model_name='historicalpackaging',
            name='country_of_origin_t2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.country'),
        ),
        migrations.AddField(
            model_name='historicalpackaging',
            name='ef_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.emissionfactorsource', verbose_name='ef_source'),
        ),
        migrations.AddField(
            model_name='historicalpackaging',
            name='energy_ef_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpackaging',
            name='energy_ef_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpackaging',
            name='energy_ef_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprocessing',
            name='ef_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.emissionfactorsource', verbose_name='ef_source'),
        ),
        migrations.AddField(
            model_name='historicalprocessing',
            name='emission_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprocessing',
            name='emission_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprocessing',
            name='emission_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprocessing',
            name='energy_ef_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprocessing',
            name='energy_ef_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprocessing',
            name='energy_ef_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstorage',
            name='country_of_origin_t2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.country'),
        ),
        migrations.AddField(
            model_name='historicalstorage',
            name='ef_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.emissionfactorsource', verbose_name='ef_source'),
        ),
        migrations.AddField(
            model_name='historicalstorage',
            name='emission_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstorage',
            name='emission_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstorage',
            name='emission_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstorage',
            name='energy_ef_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstorage',
            name='energy_ef_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstorage',
            name='energy_ef_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='country_of_origin_t2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.country'),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='ef_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.emissionfactorsource', verbose_name='ef_source'),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='emission_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='emission_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='emission_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='energy_ef_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='energy_ef_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='energy_ef_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packaging',
            name='country_of_origin_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_country_of_origin_t2', to='api.country'),
        ),
        migrations.AddField(
            model_name='packaging',
            name='ef_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.emissionfactorsource', verbose_name='ef_source'),
        ),
        migrations.AddField(
            model_name='packaging',
            name='energy_ef_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packaging',
            name='energy_ef_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packaging',
            name='energy_ef_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processing',
            name='country_of_origin_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_country_of_origin_t2', to='api.country'),
        ),
        migrations.AddField(
            model_name='processing',
            name='ef_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.emissionfactorsource', verbose_name='ef_source'),
        ),
        migrations.AddField(
            model_name='processing',
            name='emission_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processing',
            name='emission_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processing',
            name='emission_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processing',
            name='energy_ef_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processing',
            name='energy_ef_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processing',
            name='energy_ef_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='country_of_origin_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_country_of_origin_t2', to='api.country'),
        ),
        migrations.AddField(
            model_name='storage',
            name='ef_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.emissionfactorsource', verbose_name='ef_source'),
        ),
        migrations.AddField(
            model_name='storage',
            name='emission_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='emission_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='emission_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='energy_ef_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='energy_ef_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='energy_ef_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='country_of_origin_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_country_of_origin_t2', to='api.country'),
        ),
        migrations.AddField(
            model_name='transport',
            name='ef_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.emissionfactorsource', verbose_name='ef_source'),
        ),
        migrations.AddField(
            model_name='transport',
            name='emission_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='emission_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='emission_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='energy_ef_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='energy_ef_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='energy_ef_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
