# Generated by Django 4.2.1 on 2023-09-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_annualcropping_land_use_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcropping',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
    ]
