# Generated by Django 4.2.1 on 2023-09-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_alter_annualcropping_land_use_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landusechange',
            name='land_use_type_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luc_end', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luc_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='landusetype',
            name='module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moduletype'),
        ),
    ]
