# Generated by Django 4.2.1 on 2024-11-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_rename_country_of_origin_historicalprocessing_country_of_origin_t2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricity',
            old_name='country',
            new_name='country_t2',
        ),
        migrations.RenameField(
            model_name='historicalelectricity',
            old_name='country',
            new_name='country_t2',
        ),
        migrations.RenameField(
            model_name='historicalpackaging',
            old_name='country_of_origin_t2',
            new_name='country_t2',
        ),
        migrations.RenameField(
            model_name='historicalprocessing',
            old_name='country_of_origin_t2',
            new_name='country_t2',
        ),
        migrations.RenameField(
            model_name='historicalstorage',
            old_name='country_of_origin_t2',
            new_name='country_t2',
        ),
        migrations.RenameField(
            model_name='historicaltransport',
            old_name='country_of_origin_t2',
            new_name='country_t2',
        ),
        migrations.RenameField(
            model_name='packaging',
            old_name='country_of_origin_t2',
            new_name='country_t2',
        ),
        migrations.RenameField(
            model_name='processing',
            old_name='country_of_origin_t2',
            new_name='country_t2',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='country_of_origin_t2',
            new_name='country_t2',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='country_of_origin_t2',
            new_name='country_t2',
        ),
    ]
