# Generated by Django 4.2.1 on 2024-11-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_rename_country_electricity_country_t2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricity',
            old_name='country_t2',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='historicalelectricity',
            old_name='country_t2',
            new_name='country',
        ),
    ]
