# Generated by Django 4.2.1 on 2023-09-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_landusechange_land_use_type_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('rotation_occurrence_start', models.FloatField(blank=True, null=True)),
                ('rotation_occurrence_w', models.FloatField(blank=True, null=True)),
                ('rotation_occurrence_wo', models.FloatField(blank=True, null=True)),
                ('is_rotation_used_for_energy_start', models.BooleanField(default=False)),
                ('is_rotation_used_for_energy_w', models.BooleanField(default=False)),
                ('is_rotation_used_for_energy_wo', models.BooleanField(default=False)),
                ('logging_start', models.FloatField(blank=True, null=True)),
                ('logging_w', models.FloatField(blank=True, null=True)),
                ('logging_wo', models.FloatField(blank=True, null=True)),
                ('is_logging_used_for_energy_start', models.BooleanField(default=False)),
                ('is_logging_used_for_energy_w', models.BooleanField(default=False)),
                ('is_logging_used_for_energy_wo', models.BooleanField(default=False)),
                ('soil_carbon_t2_start', models.FloatField(blank=True, null=True)),
                ('soil_carbon_t2_w', models.FloatField(blank=True, null=True)),
                ('soil_carbon_t2_wo', models.FloatField(blank=True, null=True)),
                ('land_use_factor_t2_start', models.FloatField(blank=True, null=True)),
                ('land_use_factor_t2_w', models.FloatField(blank=True, null=True)),
                ('land_use_factor_t2_wo', models.FloatField(blank=True, null=True)),
                ('agb_t2_start', models.FloatField(blank=True, null=True)),
                ('agb_t2_w', models.FloatField(blank=True, null=True)),
                ('agb_t2_wo', models.FloatField(blank=True, null=True)),
                ('bgb_t2_start', models.FloatField(blank=True, null=True)),
                ('bgb_t2_w', models.FloatField(blank=True, null=True)),
                ('bgb_t2_wo', models.FloatField(blank=True, null=True)),
                ('agb_growth_rate_gt_20_yrs_t2_start', models.FloatField(blank=True, null=True)),
                ('agb_growth_rate_gt_20_yrs_t2_w', models.FloatField(blank=True, null=True)),
                ('agb_growth_rate_gt_20_yrs_t2_wo', models.FloatField(blank=True, null=True)),
                ('agb_growth_rate_le_20_yrs_t2_start', models.FloatField(blank=True, null=True)),
                ('agb_growth_rate_le_20_yrs_t2_w', models.FloatField(blank=True, null=True)),
                ('agb_growth_rate_le_20_yrs_t2_wo', models.FloatField(blank=True, null=True)),
                ('bgb_growth_rate_gt_20_yrs_t2_start', models.FloatField(blank=True, null=True)),
                ('bgb_growth_rate_gt_20_yrs_t2_w', models.FloatField(blank=True, null=True)),
                ('bgb_growth_rate_gt_20_yrs_t2_wo', models.FloatField(blank=True, null=True)),
                ('bgb_growth_rate_le_20_yrs_t2_start', models.FloatField(blank=True, null=True)),
                ('bgb_growth_rate_le_20_yrs_t2_w', models.FloatField(blank=True, null=True)),
                ('bgb_growth_rate_le_20_yrs_t2_wo', models.FloatField(blank=True, null=True)),
                ('litter_t2_start', models.FloatField(blank=True, null=True)),
                ('litter_t2_w', models.FloatField(blank=True, null=True)),
                ('litter_t2_wo', models.FloatField(blank=True, null=True)),
                ('deadwood_t2_start', models.FloatField(blank=True, null=True)),
                ('deadwood_t2_w', models.FloatField(blank=True, null=True)),
                ('deadwood_t2_wo', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('degradation_level_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_start', to='api.forestdegradationlevel')),
                ('degradation_level_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_degradation_level_thread', to='api.commentthread')),
                ('degradation_level_w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_w', to='api.forestdegradationlevel')),
                ('degradation_level_wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_wo', to='api.forestdegradationlevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Forest',
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='forest_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foresttype'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='is_logging_used_for_energy_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_is_logging_used_for_energy_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='is_rotation_used_for_energy_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_is_used_for_energy_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logging_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_occurrence_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rotation_occurrence_thread', to='api.commentthread'),
        ),
    ]
