# Generated by Django 4.2.1 on 2024-11-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_rename_energy_ef_t2_start_historicalpackaging_energy_ef_ch4_t2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprocessing',
            old_name='energy_use_per_year_start',
            new_name='kwh_energy_per_year_start',
        ),
        migrations.RenameField(
            model_name='historicalprocessing',
            old_name='energy_use_per_year_thread',
            new_name='kwh_energy_per_year_thread',
        ),
        migrations.RenameField(
            model_name='historicalprocessing',
            old_name='energy_use_per_year_w',
            new_name='kwh_energy_per_year_w',
        ),
        migrations.RenameField(
            model_name='historicalprocessing',
            old_name='energy_use_per_year_wo',
            new_name='kwh_energy_per_year_wo',
        ),
        migrations.RenameField(
            model_name='processing',
            old_name='energy_use_per_year_start',
            new_name='kwh_energy_per_year_start',
        ),
        migrations.RenameField(
            model_name='processing',
            old_name='energy_use_per_year_thread',
            new_name='kwh_energy_per_year_thread',
        ),
        migrations.RenameField(
            model_name='processing',
            old_name='energy_use_per_year_w',
            new_name='kwh_energy_per_year_w',
        ),
        migrations.RenameField(
            model_name='processing',
            old_name='energy_use_per_year_wo',
            new_name='kwh_energy_per_year_wo',
        ),
    ]
