# Generated by Django 4.2.1 on 2023-09-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_remove_deforestationsoilmanagement_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landusechange',
            old_name='ha',
            new_name='area',
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
