# Generated by Django 4.2.1 on 2024-11-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_rename_energy_use_per_year_start_historicalprocessing_kwh_energy_per_year_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstorage',
            old_name='electricity_use_per_year_start',
            new_name='kwh_energy_per_year_start',
        ),
        migrations.RenameField(
            model_name='historicalstorage',
            old_name='electricity_use_per_year_thread',
            new_name='kwh_energy_per_year_thread',
        ),
        migrations.RenameField(
            model_name='historicalstorage',
            old_name='electricity_use_per_year_w',
            new_name='kwh_energy_per_year_w',
        ),
        migrations.RenameField(
            model_name='historicalstorage',
            old_name='electricity_use_per_year_wo',
            new_name='kwh_energy_per_year_wo',
        ),
        migrations.RenameField(
            model_name='historicaltransport',
            old_name='fueò_used_per_year_thread',
            new_name='fuel_used_per_year_thread',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='electricity_use_per_year_start',
            new_name='kwh_energy_per_year_start',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='electricity_use_per_year_thread',
            new_name='kwh_energy_per_year_thread',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='electricity_use_per_year_w',
            new_name='kwh_energy_per_year_w',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='electricity_use_per_year_wo',
            new_name='kwh_energy_per_year_wo',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='fueò_used_per_year_thread',
            new_name='fuel_used_per_year_thread',
        ),
    ]
