# Generated by Django 4.2.1 on 2023-09-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_rename_ha_landusechange_area_perennialcropping_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualcropping',
            name='ha_start',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='ha_thread',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='ha_w',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='ha_wo',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='ha_start',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='ha_w',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='ha_wo',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='ha_start',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='ha_thread',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='ha_w',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='ha_wo',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='ha_start',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='ha_thread',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='ha_w',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='ha_wo',
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
