# Generated by Django 4.2.1 on 2023-09-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_remove_annualcropping_ha_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='land_use_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.landusechange'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='parent_afforestation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assessment', to='api.afforestation'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='parent_deforestation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assessment', to='api.deforestation'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='parent_other_land_use',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assessment', to='api.otherlanduse'),
        ),
    ]
