# Generated by Django 4.2.1 on 2024-11-26 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0191_historicalpackaging_name_historicalprocessing_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="valuechain",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="valuechain",
            name="status",
        ),
        migrations.RemoveField(
            model_name="historicalpackaging",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="historicalprocessing",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="historicalstorage",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="historicaltransport",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="packaging",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="processing",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="storage",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="transport",
            name="parent",
        ),
        migrations.AddField(
            model_name="historicalpackaging",
            name="activity",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.activity", verbose_name="activity"),
        ),
        migrations.AddField(
            model_name="historicalpackaging",
            name="start_year",
            field=models.IntegerField(default=1, verbose_name="start_year"),
        ),
        migrations.AddField(
            model_name="historicalprocessing",
            name="activity",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.activity", verbose_name="activity"),
        ),
        migrations.AddField(
            model_name="historicalprocessing",
            name="start_year",
            field=models.IntegerField(default=1, verbose_name="start_year"),
        ),
        migrations.AddField(
            model_name="historicalstorage",
            name="activity",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.activity", verbose_name="activity"),
        ),
        migrations.AddField(
            model_name="historicalstorage",
            name="start_year",
            field=models.IntegerField(default=1, verbose_name="start_year"),
        ),
        migrations.AddField(
            model_name="historicaltransport",
            name="activity",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.activity", verbose_name="activity"),
        ),
        migrations.AddField(
            model_name="historicaltransport",
            name="start_year",
            field=models.IntegerField(default=1, verbose_name="start_year"),
        ),
        migrations.AddField(
            model_name="packaging",
            name="activity",
            field=models.ForeignKey(default=1138, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="api.activity", verbose_name="activity"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="packaging",
            name="start_year",
            field=models.IntegerField(default=1, verbose_name="start_year"),
        ),
        migrations.AddField(
            model_name="processing",
            name="activity",
            field=models.ForeignKey(default=1138, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="api.activity", verbose_name="activity"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processing",
            name="start_year",
            field=models.IntegerField(default=1, verbose_name="start_year"),
        ),
        migrations.AddField(
            model_name="storage",
            name="activity",
            field=models.ForeignKey(default=1138, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="api.activity", verbose_name="activity"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storage",
            name="start_year",
            field=models.IntegerField(default=1, verbose_name="start_year"),
        ),
        migrations.AddField(
            model_name="transport",
            name="activity",
            field=models.ForeignKey(default=1138, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="api.activity", verbose_name="activity"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transport",
            name="start_year",
            field=models.IntegerField(default=1, verbose_name="start_year"),
        ),
        migrations.AlterField(
            model_name="historicalpackaging",
            name="status",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.statustype", verbose_name="status"),
        ),
        migrations.AlterField(
            model_name="historicalprocessing",
            name="status",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.statustype", verbose_name="status"),
        ),
        migrations.AlterField(
            model_name="historicalstorage",
            name="status",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.statustype", verbose_name="status"),
        ),
        migrations.AlterField(
            model_name="historicaltransport",
            name="status",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.statustype", verbose_name="status"),
        ),
        migrations.AlterField(
            model_name="packaging",
            name="status",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.statustype", verbose_name="status"),
        ),
        migrations.AlterField(
            model_name="processing",
            name="status",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.statustype", verbose_name="status"),
        ),
        migrations.AlterField(
            model_name="storage",
            name="status",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.statustype", verbose_name="status"),
        ),
        migrations.AlterField(
            model_name="transport",
            name="status",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.statustype", verbose_name="status"),
        ),
        migrations.DeleteModel(
            name="HistoricalValueChain",
        ),
        migrations.DeleteModel(
            name="ValueChain",
        ),
    ]
