# Generated by Django 4.2.1 on 2023-09-27 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_settlement_land_use_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organicsoil',
            name='is_fire_on_soil_start',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='is_fire_on_soil_thread',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='is_fire_on_soil_w',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='is_fire_on_soil_wo',
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='fire_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fire_type_start', to='api.firetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='fire_type_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fire_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='fire_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fire_type_w', to='api.firetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='fire_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fire_type_wo', to='api.firetype'),
        ),
    ]
