# Generated by Django 4.2.1 on 2023-09-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_remove_organicsoil_is_fire_on_soil_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organicsoil',
            name='offsite_ch4_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='offsite_ch4_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='offsite_ch4_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='offsite_doc_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='offsite_doc_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='offsite_doc_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_ch4_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_ch4_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_ch4_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_density_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_density_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='peat_density_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
