# Generated by Django 4.2.1 on 2024-11-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_remove_valuechain_activity_remove_valuechain_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fueltype',
            unique_together={('name', 'macro_fuel_type')},
        ),
        migrations.AddField(
            model_name='fueltype',
            name='fuel_use_types',
            field=models.ManyToManyField(related_name='fuel_types', to='api.fuelusetype'),
        ),
        migrations.RemoveField(
            model_name='fueltype',
            name='fuel_use_type',
        ),
    ]
