# Generated by Django 4.2.1 on 2024-11-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_alter_fueltype_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fueltype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fueltype',
            name='fuel_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_types', to='api.fuelusetype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fueltype',
            unique_together={('name', 'fuel_use_type', 'macro_fuel_type')},
        ),
        migrations.RemoveField(
            model_name='fueltype',
            name='fuel_use_types',
        ),
    ]
