# Generated by Django 4.2.1 on 2023-09-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_organicsoil_offsite_ch4_peat_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organicsoil',
            name='offsite_ch4_peat_t2_start',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='offsite_ch4_peat_t2_w',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='offsite_ch4_peat_t2_wo',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='offsite_doc_peat_t2_start',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='offsite_doc_peat_t2_w',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='offsite_doc_peat_t2_wo',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='onsite_ch4_peat_t2_start',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='onsite_ch4_peat_t2_w',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='onsite_ch4_peat_t2_wo',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_start',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_w',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_wo',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_start',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_w',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_wo',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='peat_density_t2_start',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='peat_density_t2_w',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='peat_density_t2_wo',
        ),
    ]
