# Generated by Django 4.2.1 on 2024-12-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_remove_historicalpackaging_country_t2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.packaging'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.processing'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.storage'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.transport'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.packaging'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.processing'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.storage'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.transport'),
        ),
    ]
