# Generated by Django 4.2.1 on 2023-09-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_organicsoil_offsite_ch4_peat_t2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='degradation_level_start',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='degradation_level_thread',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='degradation_level_w',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='degradation_level_wo',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='forest_type',
        ),
    ]
