# Generated by Django 4.2.1 on 2024-12-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_historicalpackagingentry_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalelectricity',
            old_name='mwh_thread',
            new_name='quantity_consumed_per_year_thread',
        ),
        migrations.RenameField(
            model_name='historicalfuel',
            old_name='fuel_consumption_thread',
            new_name='quantity_consumed_per_year_thread',
        ),
        migrations.RenameField(
            model_name='historicalpackagingentry',
            old_name='kwh_energy_per_year_thread',
            new_name='mwh_renewables_thread',
        ),
        migrations.RenameField(
            model_name='historicalprocessingentry',
            old_name='fuel_type_thread',
            new_name='mwh_renewables_thread',
        ),
        migrations.RenameField(
            model_name='historicalprocessingentry',
            old_name='kwh_energy_per_year_thread',
            new_name='quantity_consumed_per_year_thread',
        ),
        migrations.RenameField(
            model_name='historicalstorageentry',
            old_name='kwh_energy_per_year_thread',
            new_name='mwh_renewables_thread',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='mwh_start',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='mwh_thread',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='mwh_w',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='mwh_wo',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='fuel_consumption_start',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='fuel_consumption_thread',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='fuel_consumption_w',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='fuel_consumption_wo',
        ),
        migrations.RemoveField(
            model_name='historicalelectricity',
            name='mwh_start',
        ),
        migrations.RemoveField(
            model_name='historicalelectricity',
            name='mwh_w',
        ),
        migrations.RemoveField(
            model_name='historicalelectricity',
            name='mwh_wo',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='fuel_consumption_start',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='fuel_consumption_w',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='fuel_consumption_wo',
        ),
        migrations.RemoveField(
            model_name='historicalpackagingentry',
            name='kwh_energy_per_year_start',
        ),
        migrations.RemoveField(
            model_name='historicalpackagingentry',
            name='kwh_energy_per_year_w',
        ),
        migrations.RemoveField(
            model_name='historicalpackagingentry',
            name='kwh_energy_per_year_wo',
        ),
        migrations.RemoveField(
            model_name='historicalprocessingentry',
            name='fuel_type_start',
        ),
        migrations.RemoveField(
            model_name='historicalprocessingentry',
            name='fuel_type_w',
        ),
        migrations.RemoveField(
            model_name='historicalprocessingentry',
            name='fuel_type_wo',
        ),
        migrations.RemoveField(
            model_name='historicalprocessingentry',
            name='kwh_energy_per_year_start',
        ),
        migrations.RemoveField(
            model_name='historicalprocessingentry',
            name='kwh_energy_per_year_w',
        ),
        migrations.RemoveField(
            model_name='historicalprocessingentry',
            name='kwh_energy_per_year_wo',
        ),
        migrations.RemoveField(
            model_name='historicalstorageentry',
            name='kwh_energy_per_year_start',
        ),
        migrations.RemoveField(
            model_name='historicalstorageentry',
            name='kwh_energy_per_year_w',
        ),
        migrations.RemoveField(
            model_name='historicalstorageentry',
            name='kwh_energy_per_year_wo',
        ),
        migrations.RemoveField(
            model_name='packagingentry',
            name='kwh_energy_per_year_start',
        ),
        migrations.RemoveField(
            model_name='packagingentry',
            name='kwh_energy_per_year_thread',
        ),
        migrations.RemoveField(
            model_name='packagingentry',
            name='kwh_energy_per_year_w',
        ),
        migrations.RemoveField(
            model_name='packagingentry',
            name='kwh_energy_per_year_wo',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='fuel_type_start',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='fuel_type_thread',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='fuel_type_w',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='fuel_type_wo',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='kwh_energy_per_year_start',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='kwh_energy_per_year_thread',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='kwh_energy_per_year_w',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='kwh_energy_per_year_wo',
        ),
        migrations.RemoveField(
            model_name='storageentry',
            name='kwh_energy_per_year_start',
        ),
        migrations.RemoveField(
            model_name='storageentry',
            name='kwh_energy_per_year_thread',
        ),
        migrations.RemoveField(
            model_name='storageentry',
            name='kwh_energy_per_year_w',
        ),
        migrations.RemoveField(
            model_name='storageentry',
            name='kwh_energy_per_year_wo',
        ),
        migrations.AddField(
            model_name='electricity',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='quantity_consumed_per_year_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_quantity_consumed_per_year_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='quantity_consumed_per_year_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_quantity_consumed_per_year_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='historicalelectricity',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='historicalelectricity',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='historicalelectricity',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='electricity_ef_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='electricity_ef_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='electricity_ef_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='fuel_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='mwh_renewables_start',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_start'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='mwh_renewables_w',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_w'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='mwh_renewables_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_wo'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='quantity_consumed_per_year_thread',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='transmission_loss_t2_start',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='transmission_loss_t2_w',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='transmission_loss_t2_wo',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='electricity_ef_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='electricity_ef_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='electricity_ef_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='fuel_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='mwh_renewables_start',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_start'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='mwh_renewables_w',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_w'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='mwh_renewables_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_wo'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='transmission_loss_t2_start',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='transmission_loss_t2_w',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='transmission_loss_t2_wo',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='electricity_ef_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='electricity_ef_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='electricity_ef_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='fuel_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='mwh_renewables_start',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_start'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='mwh_renewables_w',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_w'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='mwh_renewables_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_wo'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='quantity_consumed_per_year_thread',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='transmission_loss_t2_start',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='transmission_loss_t2_w',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='transmission_loss_t2_wo',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='electricity_ef_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_start'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='electricity_ef_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_w'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='electricity_ef_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='fuel_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='mwh_renewables_start',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_start'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='mwh_renewables_thread',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='mwh_renewables_w',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_w'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='mwh_renewables_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_wo'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='quantity_consumed_per_year_thread',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='transmission_loss_t2_start',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_start'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='transmission_loss_t2_w',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_w'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='transmission_loss_t2_wo',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_wo'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='electricity_ef_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_start'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='electricity_ef_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_w'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='electricity_ef_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_wo'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fueltype', verbose_name='fuel_type'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='mwh_renewables_start',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_start'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='mwh_renewables_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_mwh_renewables_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='mwh_renewables_w',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_w'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='mwh_renewables_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_wo'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='quantity_consumed_per_year_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_quantity_consumed_per_year_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='transmission_loss_t2_start',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_start'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='transmission_loss_t2_w',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_w'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='transmission_loss_t2_wo',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_wo'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='electricity_ef_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_start'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='electricity_ef_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_w'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='electricity_ef_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_wo'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fueltype', verbose_name='fuel_type'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='mwh_renewables_start',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_start'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='mwh_renewables_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_mwh_renewables_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='mwh_renewables_w',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_w'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='mwh_renewables_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_wo'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='quantity_consumed_per_year_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_quantity_consumed_per_year_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='transmission_loss_t2_start',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_start'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='transmission_loss_t2_w',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_w'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='transmission_loss_t2_wo',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_wo'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='electricity_ef_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_start'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='electricity_ef_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_w'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='electricity_ef_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_wo'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fueltype', verbose_name='fuel_type'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='mwh_renewables_start',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_start'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='mwh_renewables_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_mwh_renewables_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='mwh_renewables_w',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_w'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='mwh_renewables_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_wo'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='quantity_consumed_per_year_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_quantity_consumed_per_year_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='transmission_loss_t2_start',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_start'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='transmission_loss_t2_w',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_w'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='transmission_loss_t2_wo',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_wo'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='electricity_ef_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_start'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='electricity_ef_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_w'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='electricity_ef_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_t2_wo'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fueltype', verbose_name='fuel_type'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='mwh_renewables_start',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_start'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='mwh_renewables_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_mwh_renewables_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='mwh_renewables_w',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_w'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='mwh_renewables_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='mwh_renewables_wo'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='quantity_consumed_per_year_start',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_start'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='quantity_consumed_per_year_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_quantity_consumed_per_year_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='quantity_consumed_per_year_w',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_w'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='quantity_consumed_per_year_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='quantity_consumed_per_year_wo'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='transmission_loss_t2_start',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_start'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='transmission_loss_t2_w',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_w'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='transmission_loss_t2_wo',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_wo'),
        ),
    ]
