# Generated by Django 4.2.1 on 2023-09-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_forestconditiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestmanagement',
            name='forest_condition_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_forest_condition_type', to='api.forestconditiontype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='forest_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.foresttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foresttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
