# Generated by Django 4.2.1 on 2024-12-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_rename_mwh_thread_historicalelectricity_quantity_consumed_per_year_thread_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpackagingentry',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='historicalprocessingentry',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='historicalstorageentry',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='historicaltransportentry',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='historicaltransportentry',
            name='fuel_type_thread',
        ),
        migrations.RemoveField(
            model_name='historicaltransportentry',
            name='fuel_used_per_year_start',
        ),
        migrations.RemoveField(
            model_name='historicaltransportentry',
            name='fuel_used_per_year_thread',
        ),
        migrations.RemoveField(
            model_name='historicaltransportentry',
            name='fuel_used_per_year_w',
        ),
        migrations.RemoveField(
            model_name='historicaltransportentry',
            name='fuel_used_per_year_wo',
        ),
        migrations.RemoveField(
            model_name='packagingentry',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='storageentry',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='transportentry',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='transportentry',
            name='fuel_type_thread',
        ),
        migrations.RemoveField(
            model_name='transportentry',
            name='fuel_used_per_year_start',
        ),
        migrations.RemoveField(
            model_name='transportentry',
            name='fuel_used_per_year_thread',
        ),
        migrations.RemoveField(
            model_name='transportentry',
            name='fuel_used_per_year_w',
        ),
        migrations.RemoveField(
            model_name='transportentry',
            name='fuel_used_per_year_wo',
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_start', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_w', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_wo', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_start', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_w', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_wo', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_start', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_w', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_wo', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
        migrations.AlterField(
            model_name='historicaltransportentry',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AlterField(
            model_name='historicaltransportentry',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AlterField(
            model_name='historicaltransportentry',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
        migrations.AlterField(
            model_name='transportentry',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_start', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AlterField(
            model_name='transportentry',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_w', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AlterField(
            model_name='transportentry',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_wo', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
    ]
