# Generated by Django 4.2.1 on 2023-10-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_forestmanagement_forest_condition_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afforestation',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='building',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coastalwaterbody',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deforestation',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='degradedland',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='electricity',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='extraction',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='main_biomass_factor_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='main_biomass_factor_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='main_biomass_factor_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fuel',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='grassland',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inlandwaterbody',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='input',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='livestock',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rewetting',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='road',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='setaside',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='settlement',
            name='agb_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='agb_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='agb_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='bgb_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='bgb_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='bgb_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='flu_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='flu_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='flu_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='soil_carbon_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='soil_carbon_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='soil_carbon_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='start_year',
            field=models.IntegerField(default=1),
        ),
    ]
