# Generated by Django 4.2.1 on 2023-10-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_afforestation_start_year_annualcropping_start_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='climate_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.climate'),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_t2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='soil_type_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.soiltype'),
        ),
    ]
