# Generated by Django 4.2.1 on 2024-12-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_remove_historicalpackagingentry_fuel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicalelectricity',
            name='country',
        ),
        migrations.AddField(
            model_name='electricity',
            name='country_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country', verbose_name='country_t2'),
        ),
        migrations.AddField(
            model_name='historicalelectricity',
            name='country_t2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.country', verbose_name='country_t2'),
        ),
    ]
