# Generated by Django 4.2.1 on 2024-12-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_remove_electricity_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricity',
            old_name='transmission_loss_start',
            new_name='transmission_loss_t2_start',
        ),
        migrations.RenameField(
            model_name='electricity',
            old_name='transmission_loss_w',
            new_name='transmission_loss_t2_w',
        ),
        migrations.RenameField(
            model_name='historicalelectricity',
            old_name='transmission_loss_start',
            new_name='transmission_loss_t2_start',
        ),
        migrations.RenameField(
            model_name='historicalelectricity',
            old_name='transmission_loss_w',
            new_name='transmission_loss_t2_w',
        ),
    ]
