# Generated by Django 4.2.1 on 2023-10-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_activity_climate_t2_activity_duration_t2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
    ]
