# Generated by Django 4.2.1 on 2024-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_rename_transmission_loss_start_electricity_transmission_loss_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity',
            name='transmission_loss_wo',
        ),
        migrations.RemoveField(
            model_name='historicalelectricity',
            name='transmission_loss_wo',
        ),
        migrations.AddField(
            model_name='electricity',
            name='transmission_loss_t2_wo',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalelectricity',
            name='transmission_loss_t2_wo',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_wo'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='transmission_loss_t2_start',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_start'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='transmission_loss_t2_w',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_w'),
        ),
        migrations.AlterField(
            model_name='historicalelectricity',
            name='transmission_loss_t2_start',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_start'),
        ),
        migrations.AlterField(
            model_name='historicalelectricity',
            name='transmission_loss_t2_w',
            field=models.FloatField(default=0.1, verbose_name='transmission_loss_t2_w'),
        ),
    ]
