# Generated by Django 4.2.1 on 2023-10-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_remove_activity_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduletype',
            old_name='verbose_name',
            new_name='class_name',
        ),
    ]
