# Generated by Django 4.2.1 on 2024-12-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_remove_electricity_transmission_loss_wo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinputentry',
            name='value_start',
            field=models.FloatField(blank=True, null=True, verbose_name='value_start'),
        ),
        migrations.AlterField(
            model_name='historicalinputentry',
            name='value_w',
            field=models.FloatField(blank=True, null=True, verbose_name='value_w'),
        ),
        migrations.AlterField(
            model_name='historicalinputentry',
            name='value_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='value_wo'),
        ),
        migrations.AlterField(
            model_name='inputentry',
            name='input_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inputtype', verbose_name='input_type'),
        ),
        migrations.AlterField(
            model_name='inputentry',
            name='value_start',
            field=models.FloatField(blank=True, null=True, verbose_name='value_start'),
        ),
        migrations.AlterField(
            model_name='inputentry',
            name='value_w',
            field=models.FloatField(blank=True, null=True, verbose_name='value_w'),
        ),
        migrations.AlterField(
            model_name='inputentry',
            name='value_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='value_wo'),
        ),
    ]
