# Generated by Django 4.2.1 on 2023-10-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_rename_verbose_name_moduletype_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisturbanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_year', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='forestmanagement',
            old_name='logging_start',
            new_name='average_yearly_degradation_percentage_start',
        ),
        migrations.RenameField(
            model_name='forestmanagement',
            old_name='logging_w',
            new_name='average_yearly_degradation_percentage_w',
        ),
        migrations.RenameField(
            model_name='forestmanagement',
            old_name='logging_wo',
            new_name='average_yearly_degradation_percentage_wo',
        ),
        migrations.RenameField(
            model_name='forestmanagement',
            old_name='rotation_occurrence_start',
            new_name='degradation_dry_matter_impacted_t2_start',
        ),
        migrations.RenameField(
            model_name='forestmanagement',
            old_name='rotation_occurrence_w',
            new_name='degradation_dry_matter_impacted_t2_w',
        ),
        migrations.RenameField(
            model_name='forestmanagement',
            old_name='rotation_occurrence_wo',
            new_name='degradation_dry_matter_impacted_t2_wo',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='is_logging_used_for_energy_start',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='is_logging_used_for_energy_thread',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='is_logging_used_for_energy_w',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='is_logging_used_for_energy_wo',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='is_rotation_used_for_energy_start',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='is_rotation_used_for_energy_thread',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='is_rotation_used_for_energy_w',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='is_rotation_used_for_energy_wo',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='logging_thread',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='rotation_occurrence_thread',
        ),
        migrations.RemoveField(
            model_name='landusechange',
            name='land_use_type_end',
        ),
        migrations.RemoveField(
            model_name='landusechange',
            name='land_use_type_start',
        ),
        migrations.RemoveField(
            model_name='landusechange',
            name='module_type_end',
        ),
        migrations.RemoveField(
            model_name='landusetype',
            name='parent',
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='average_yearly_degradation_percentage_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_average_yearly_degradation_percentage_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_dry_matter_logged_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_dry_matter_logged_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_dry_matter_logged_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_percentage_agb_logged_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_percentage_agb_logged_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logging_percentage_agb_logged_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_percentage_agb_logged_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_percentage_agb_logged_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_percentage_biomass_for_energy_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_percentage_biomass_for_energy_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logging_percentage_biomass_for_energy_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_percentage_biomass_for_energy_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_percentage_biomass_for_energy_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_recurrence_yrs_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_recurrence_yrs_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logging_recurrence_yrs_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_recurrence_yrs_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_recurrence_yrs_wo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_start_year_t2_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_start_year_t2_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='logging_start_year_t2_wo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_length_yrs_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_length_yrs_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rotation_length_yrs_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_length_yrs_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_length_yrs_wo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_percentage_biomass_for_energy_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_percentage_biomass_for_energy_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rotation_percentage_biomass_for_energy_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_percentage_biomass_for_energy_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_percentage_biomass_for_energy_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_wo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='module_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w', to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='module_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wo', to='api.moduletype'),
        ),
        migrations.AddField(
            model_name='landusetype',
            name='is_land_use_change',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ForestDisturbance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_yrs_start', models.IntegerField(blank=True, null=True)),
                ('recurrence_yrs_w', models.IntegerField(blank=True, null=True)),
                ('recurrence_yrs_wo', models.IntegerField(blank=True, null=True)),
                ('percentage_biomass_destruction_start', models.FloatField(blank=True, null=True)),
                ('percentage_biomass_destruction_w', models.FloatField(blank=True, null=True)),
                ('percentage_biomass_destruction_wo', models.FloatField(blank=True, null=True)),
                ('start_year_t2_start', models.IntegerField(blank=True, null=True)),
                ('start_year_t2_w', models.IntegerField(blank=True, null=True)),
                ('start_year_t2_wo', models.IntegerField(blank=True, null=True)),
                ('dry_matter_impacted_t2_start', models.FloatField(blank=True, null=True)),
                ('dry_matter_impacted_t2_w', models.FloatField(blank=True, null=True)),
                ('dry_matter_impacted_t2_wo', models.FloatField(blank=True, null=True)),
                ('disturbance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disturbancetype')),
                ('disturbance_type_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_disturbance_type_thread', to='api.commentthread')),
                ('forest_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forestmanagement')),
                ('percentage_biomass_destruction_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_disturbance_percentage_biomass_destruction_thread', to='api.commentthread')),
                ('recurrence_yrs_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_disturbance_recurrence_yrs_thread', to='api.commentthread')),
            ],
        ),
    ]
