# Generated by Django 4.2.1 on 2023-10-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_disturbancetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestdisturbance',
            name='start_year_t2_start',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='forestdisturbance',
            name='start_year_t2_w',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='forestdisturbance',
            name='start_year_t2_wo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_start',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_w',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_wo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_start',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_w',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_wo',
            field=models.IntegerField(default=1),
        ),
    ]
