# Generated by Django 4.2.1 on 2023-10-31 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_alter_forestdisturbance_start_year_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualcropping',
            name='crop_type_start',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='crop_type_thread',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='crop_type_w',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='crop_type_wo',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='parent_afforestation',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='parent_deforestation',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='parent_other_land_use',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='parent_afforestation',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='parent_deforestation',
        ),
        migrations.RemoveField(
            model_name='floodedrice',
            name='parent_other_land_use',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='parent_afforestation',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='parent_deforestation',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='parent_other_land_use',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='parent_afforestation',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='parent_deforestation',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='parent_other_land_use',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='parent_afforestation',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='parent_deforestation',
        ),
        migrations.RemoveField(
            model_name='organicsoil',
            name='parent_other_land_use',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='crop_type_start',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='crop_type_thread',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='crop_type_w',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='crop_type_wo',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='parent_afforestation',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='parent_deforestation',
        ),
        migrations.RemoveField(
            model_name='perennialcropping',
            name='parent_other_land_use',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='parent_afforestation',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='parent_deforestation',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='parent_other_land_use',
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='land_use_type_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
    ]
