# Generated by Django 4.2.1 on 2024-12-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_applicationparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bucket_public_url', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.project')),
            ],
        ),
    ]
