# Generated by Django 4.2.1 on 2023-10-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_remove_annualcropping_crop_type_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forestmanagement',
            old_name='land_use_type_start',
            new_name='land_use_type',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='land_use_type_w',
        ),
        migrations.RemoveField(
            model_name='forestmanagement',
            name='land_use_type_wo',
        ),
    ]
