# Generated by Django 4.2.1 on 2023-10-31 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_rename_land_use_type_start_forestmanagement_land_use_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landusetype',
            name='forest_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.foresttype'),
        ),
    ]
