# Generated by Django 4.2.1 on 2025-01-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_unit_fueltype_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='is_archived'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='is_archived'),
        ),
    ]
