# Generated by Django 4.2.1 on 2025-01-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0206_historicalproject_is_archived_project_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='historicalfuel',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='historicalirrigationphase',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='irrigationphase',
            name='fuel_type',
        ),
        migrations.AddField(
            model_name='fuel',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_start', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_w', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_wo', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='fuel_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_start', to='api.fueltype', verbose_name='fuel_type_start'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='fuel_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_w', to='api.fueltype', verbose_name='fuel_type_w'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='fuel_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fuel_type_wo', to='api.fueltype', verbose_name='fuel_type_wo'),
        ),
    ]
