# Generated by Django 4.2.1 on 2023-10-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0206_landusetype_forest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forestmanagement',
            name='forest_condition_type',
        ),
        migrations.RemoveField(
            model_name='landusetype',
            name='is_land_use_change',
        ),
        migrations.AddField(
            model_name='moduletype',
            name='is_luc',
            field=models.BooleanField(default=False),
        ),
    ]
