# Generated by Django 4.2.1 on 2023-10-31 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_remove_forestmanagement_forest_condition_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualcropping',
            name='minor_crop_type_start',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='minor_crop_type_w',
        ),
        migrations.RemoveField(
            model_name='annualcropping',
            name='minor_crop_type_wo',
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_land_use_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_land_use_type_start', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='minor_land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_minor_land_use_type_wo', to='api.landusetype'),
        ),
    ]
