# Generated by Django 4.2.1 on 2025-01-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_remove_fuel_fuel_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='energy_ef_ch4_t2',
            new_name='energy_ef_ch4_t2_start',
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='energy_ef_co2_t2',
            new_name='energy_ef_co2_t2_start',
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='energy_ef_n2o_t2',
            new_name='energy_ef_n2o_t2_start',
        ),
        migrations.RenameField(
            model_name='historicalfuel',
            old_name='energy_ef_ch4_t2',
            new_name='energy_ef_ch4_t2_start',
        ),
        migrations.RenameField(
            model_name='historicalfuel',
            old_name='energy_ef_co2_t2',
            new_name='energy_ef_co2_t2_start',
        ),
        migrations.RenameField(
            model_name='historicalfuel',
            old_name='energy_ef_n2o_t2',
            new_name='energy_ef_n2o_t2_start',
        ),
        migrations.AddField(
            model_name='fuel',
            name='energy_ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_w'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='energy_ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_wo'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='energy_ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_w'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='energy_ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_wo'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='energy_ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_w'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='energy_ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='energy_ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='energy_ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='energy_ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='energy_ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='energy_ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='energy_ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_wo'),
        ),
    ]
