# Generated by Django 4.2.1 on 2025-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_rename_energy_ef_ch4_t2_fuel_energy_ef_ch4_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpackagingentry',
            name='energy_ef_ch4_t2',
        ),
        migrations.RemoveField(
            model_name='historicalpackagingentry',
            name='energy_ef_co2_t2',
        ),
        migrations.RemoveField(
            model_name='historicalpackagingentry',
            name='energy_ef_n2o_t2',
        ),
        migrations.RemoveField(
            model_name='historicalprocessingentry',
            name='energy_ef_ch4_t2',
        ),
        migrations.RemoveField(
            model_name='historicalprocessingentry',
            name='energy_ef_co2_t2',
        ),
        migrations.RemoveField(
            model_name='historicalprocessingentry',
            name='energy_ef_n2o_t2',
        ),
        migrations.RemoveField(
            model_name='historicalstorageentry',
            name='energy_ef_ch4_t2',
        ),
        migrations.RemoveField(
            model_name='historicalstorageentry',
            name='energy_ef_co2_t2',
        ),
        migrations.RemoveField(
            model_name='historicalstorageentry',
            name='energy_ef_n2o_t2',
        ),
        migrations.RemoveField(
            model_name='historicaltransportentry',
            name='energy_ef_ch4_t2',
        ),
        migrations.RemoveField(
            model_name='historicaltransportentry',
            name='energy_ef_co2_t2',
        ),
        migrations.RemoveField(
            model_name='historicaltransportentry',
            name='energy_ef_n2o_t2',
        ),
        migrations.RemoveField(
            model_name='packagingentry',
            name='energy_ef_ch4_t2',
        ),
        migrations.RemoveField(
            model_name='packagingentry',
            name='energy_ef_co2_t2',
        ),
        migrations.RemoveField(
            model_name='packagingentry',
            name='energy_ef_n2o_t2',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='energy_ef_ch4_t2',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='energy_ef_co2_t2',
        ),
        migrations.RemoveField(
            model_name='processingentry',
            name='energy_ef_n2o_t2',
        ),
        migrations.RemoveField(
            model_name='storageentry',
            name='energy_ef_ch4_t2',
        ),
        migrations.RemoveField(
            model_name='storageentry',
            name='energy_ef_co2_t2',
        ),
        migrations.RemoveField(
            model_name='storageentry',
            name='energy_ef_n2o_t2',
        ),
        migrations.RemoveField(
            model_name='transportentry',
            name='energy_ef_ch4_t2',
        ),
        migrations.RemoveField(
            model_name='transportentry',
            name='energy_ef_co2_t2',
        ),
        migrations.RemoveField(
            model_name='transportentry',
            name='energy_ef_n2o_t2',
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='energy_ef_ch4_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='energy_ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='energy_ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='energy_ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='energy_ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='energy_ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='energy_ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='energy_ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='energy_ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='energy_ef_ch4_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='energy_ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='energy_ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='energy_ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='energy_ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='energy_ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='energy_ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='energy_ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='energy_ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='energy_ef_ch4_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='energy_ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='energy_ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='energy_ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='energy_ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='energy_ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='energy_ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='energy_ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='energy_ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='energy_ef_ch4_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='energy_ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_w'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='energy_ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='energy_ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='energy_ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_w'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='energy_ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='energy_ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='energy_ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_w'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='energy_ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_wo'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='energy_ef_ch4_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='energy_ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_w'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='energy_ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_wo'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='energy_ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='energy_ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_w'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='energy_ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_wo'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='energy_ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='energy_ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_w'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='energy_ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_wo'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='energy_ef_ch4_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='energy_ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_w'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='energy_ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_wo'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='energy_ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='energy_ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_w'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='energy_ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_wo'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='energy_ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='energy_ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_w'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='energy_ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_wo'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='energy_ef_ch4_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='energy_ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_w'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='energy_ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_wo'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='energy_ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='energy_ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_w'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='energy_ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_wo'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='energy_ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='energy_ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_w'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='energy_ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_wo'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='energy_ef_ch4_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='energy_ef_ch4_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_w'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='energy_ef_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_ch4_t2_wo'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='energy_ef_co2_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='energy_ef_co2_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_w'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='energy_ef_co2_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_co2_t2_wo'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='energy_ef_n2o_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='energy_ef_n2o_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_w'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='energy_ef_n2o_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='ef_n2o_t2_wo'),
        ),
    ]
