# Generated by Django 4.2.1 on 2023-11-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_remove_annualcropping_minor_crop_type_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationphase',
            name='irrigation_system_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_phases', to='api.irrigationsystemtype'),
        ),
    ]
