# Generated by Django 4.2.1 on 2023-11-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0209_alter_irrigationphase_irrigation_system_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landusetype',
            name='module_type',
        ),
        migrations.AddField(
            model_name='landusetype',
            name='module_types',
            field=models.ManyToManyField(related_name='land_use_types', to='api.moduletype'),
        ),
    ]
