# Generated by Django 4.2.1 on 2025-01-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0209_remove_historicalpackagingentry_energy_ef_ch4_t2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='account_for_co2',
            field=models.BooleanField(default=False, verbose_name='account_for_co2'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='account_for_co2',
            field=models.BooleanField(default=False, verbose_name='account_for_co2'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='account_for_co2',
            field=models.BooleanField(default=False, verbose_name='account_for_co2'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='account_for_co2',
            field=models.BooleanField(default=False, verbose_name='account_for_co2'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='account_for_co2',
            field=models.BooleanField(default=False, verbose_name='account_for_co2'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='account_for_co2',
            field=models.BooleanField(default=False, verbose_name='account_for_co2'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='account_for_co2',
            field=models.BooleanField(default=False, verbose_name='account_for_co2'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='account_for_co2',
            field=models.BooleanField(default=False, verbose_name='account_for_co2'),
        ),
        migrations.AlterField(
            model_name='historicalpackagingentry',
            name='country_t2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.country', verbose_name='country_t2'),
        ),
        migrations.AlterField(
            model_name='historicalprocessingentry',
            name='country_t2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.country', verbose_name='country_t2'),
        ),
        migrations.AlterField(
            model_name='historicalstorageentry',
            name='country_t2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.country', verbose_name='country_t2'),
        ),
        migrations.AlterField(
            model_name='historicaltransportentry',
            name='country_t2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.country', verbose_name='country_t2'),
        ),
        migrations.AlterField(
            model_name='packagingentry',
            name='country_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country', verbose_name='country_t2'),
        ),
        migrations.AlterField(
            model_name='processingentry',
            name='country_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country', verbose_name='country_t2'),
        ),
        migrations.AlterField(
            model_name='storageentry',
            name='country_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country', verbose_name='country_t2'),
        ),
        migrations.AlterField(
            model_name='transportentry',
            name='country_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country', verbose_name='country_t2'),
        ),
    ]
