# Generated by Django 4.2.1 on 2025-01-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0210_historicalpackagingentry_account_for_co2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('maintenance_end_time', models.DateTimeField(blank=True, null=True)),
                ('maintenance_message', models.TextField(default='The API is under maintenance. Please check back later.')),
            ],
        ),
    ]
