# Generated by Django 4.2.1 on 2023-11-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0210_remove_landusetype_module_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coastalwaterbody',
            name='waterbody_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.waterbodytype'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='vegetation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='crop_yield_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='crop_yield_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='crop_yield_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='fish_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fishtype'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='livestock_category_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='livestock_production_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype'),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='is_biomass_burned_start',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='is_biomass_burned_w',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='is_biomass_burned_wo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
