# Generated by Django 4.2.1 on 2025-01-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0211_apistatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('maintenance_end_time', models.DateTimeField(blank=True, null=True)),
                ('maintenance_message', models.TextField(default='The tool is under maintenance. Please check back later.')),
            ],
        ),
        migrations.DeleteModel(
            name='APIStatus',
        ),
    ]
