# Generated by Django 4.2.1 on 2023-11-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0211_alter_coastalwaterbody_waterbody_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationphase',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='irrigationphase',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='irrigationphase',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='irrigationsystem',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='irrigationsystem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='irrigationsystem',
            name='start_year',
        ),
        migrations.AlterField(
            model_name='irrigationsystem',
            name='irrigation_system_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_systems', to='api.irrigationsystemtype'),
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_year', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_year', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='electricity',
            name='energy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.energy'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='energy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.energy'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='irrigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_phases', to='api.irrigation'),
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='irrigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_systems', to='api.irrigation'),
        ),
    ]
