# Generated by Django 4.2.1 on 2023-11-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0212_remove_irrigationphase_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='energy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electricities', to='api.energy'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='organic_amendment_type_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_start', to='api.organicamendmenttype'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='organic_amendment_type_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_w', to='api.organicamendmenttype'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='organic_amendment_type_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_amendment_type_wo', to='api.organicamendmenttype'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='water_management_type_after_cultivation_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_start', to='api.watermanagementtypeaftercultivation'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='water_management_type_after_cultivation_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_w', to='api.watermanagementtypeaftercultivation'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='water_management_type_after_cultivation_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_after_cultivation_wo', to='api.watermanagementtypeaftercultivation'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='water_management_type_before_cultivation_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_start', to='api.watermanagementtypebeforecultivation'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='water_management_type_before_cultivation_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_w', to='api.watermanagementtypebeforecultivation'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='water_management_type_before_cultivation_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_water_management_type_before_cultivation_wo', to='api.watermanagementtypebeforecultivation'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='energy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='api.energy'),
        ),
    ]
