# Generated by Django 4.2.1 on 2025-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0212_apihealth_delete_apistatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='soiltype',
            name='module_types',
            field=models.ManyToManyField(related_name='soil_types', to='api.moduletype'),
        ),
    ]
