# Generated by Django 4.2.1 on 2025-01-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0213_soiltype_module_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soiltype',
            name='module_types',
        ),
    ]
