# Generated by Django 4.2.1 on 2023-11-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0213_alter_electricity_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestmanagement',
            name='forest_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.foresttype'),
        ),
    ]
