# Generated by Django 4.2.1 on 2025-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0214_remove_soiltype_module_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='soiltype',
            name='is_coastal',
            field=models.BooleanField(default=False),
        ),
    ]
