# Generated by Django 4.2.1 on 2023-11-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0214_alter_forestmanagement_forest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletype',
            name='is_submodule',
            field=models.BooleanField(default=False),
        ),
    ]
