# Generated by Django 4.2.1 on 2025-02-03 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0215_soiltype_is_coastal'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfileattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectfileattachment',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
