# Generated by Django 4.2.1 on 2023-11-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0216_remove_coastalwaterbody_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landusechange',
            old_name='dry_matter_end',
            new_name='dry_matter_w',
        ),
        migrations.RenameField(
            model_name='landusechange',
            old_name='is_fire_used_end',
            new_name='is_fire_used_w',
        ),
        migrations.AddField(
            model_name='landusechange',
            name='dry_matter_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='is_fire_used_wo',
            field=models.BooleanField(default=False),
        ),
    ]
