# Generated by Django 4.2.1 on 2025-02-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0217_remove_activity_start_year_t2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='start_year_of_activities_t2',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='start_year_of_activities_t2',
        ),
        migrations.AddField(
            model_name='activity',
            name='start_year_t2',
            field=models.IntegerField(blank=True, null=True, verbose_name='start_year_t2'),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='start_year_t2',
            field=models.IntegerField(blank=True, null=True, verbose_name='start_year_t2'),
        ),
    ]
