# Generated by Django 4.2.1 on 2025-02-28 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0218_remove_activity_start_year_of_activities_t2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aquaculture",
            name="annual_production_thread",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_annual_production_thread", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="fuel",
            name="fuel_type_thread",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_fuel_type_thread", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="grassland",
            name="grassland_management_type_thread",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_grassland_management_type_thread", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="historicalaquaculture",
            name="annual_production_thread",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="historicalfuel",
            name="fuel_type_thread",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="historicalgrassland",
            name="grassland_management_type_thread",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="fuel_type_thread",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="historicalpackagingentry",
            name="fuel_type_thread",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.commentthread"),
        ),
        # migrations.AddField(
        #     model_name='historicalprocessingentry',
        #     name='fuel_type_thread',
        #     field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        # ),
        migrations.AddField(
            model_name="historicalstorageentry",
            name="fuel_type_thread",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="historicaltransportentry",
            name="fuel_type_thread",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="historicalwaterbody",
            name="trophic_type_thread",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="fuel_type_thread",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_fuel_type_thread", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="packagingentry",
            name="fuel_type_thread",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_fuel_type_thread", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="processingentry",
            name="fuel_type_thread",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_fuel_type_thread", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="storageentry",
            name="fuel_type_thread",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_fuel_type_thread", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="transportentry",
            name="fuel_type_thread",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_fuel_type_thread", to="api.commentthread"),
        ),
        migrations.AddField(
            model_name="waterbody",
            name="trophic_type_thread",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_trophic_class_thread", to="api.commentthread"),
        ),
    ]
