# Generated by Django 4.2.1 on 2023-11-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0218_annualcropping_soc_t2_start_annualcropping_soc_t2_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landusetype',
            name='climate',
            field=models.ManyToManyField(related_name='land_use_types', to='api.climate'),
        ),
        migrations.AddField(
            model_name='landusetype',
            name='moisture',
            field=models.ManyToManyField(related_name='land_use_types', to='api.moisture'),
        ),
    ]
