# Generated by Django 4.2.1 on 2023-11-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0219_landusetype_climate_landusetype_moisture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landusetype',
            old_name='climate',
            new_name='climates',
        ),
        migrations.RenameField(
            model_name='landusetype',
            old_name='moisture',
            new_name='moistures',
        ),
    ]
