# Generated by Django 4.2.1 on 2023-11-20 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0220_rename_climate_landusetype_climates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coastalwetland',
            name='vegetation_type',
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degradedland',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disturbancetype',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricity',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energy',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuel',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grassland',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irrigation',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landusechange',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='largefishery',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestock',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialcropping',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='road',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setaside',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlement',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterbody',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
            preserve_default=False,
        ),
    ]
