# Generated by Django 4.2.1 on 2023-11-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0221_remove_coastalwetland_vegetation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grassland',
            name='agb_t2_start',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='agb_t2_w',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='agb_t2_wo',
        ),
    ]
