# Generated by Django 4.2.1 on 2025-03-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0221_historicalprocessingentry_fuel_type_thread"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='historicalperennialcropland',
        #     name='is_complete_renewal',
        #     field=models.BooleanField(default=False, verbose_name='is_complete_renewal'),
        # ),
        # migrations.AddField(
        #     model_name='historicalperennialcropland',
        #     name='is_system_in_maturity',
        #     field=models.BooleanField(default=True, verbose_name='is_system_in_maturity'),
        # ),
        # migrations.AddField(
        #     model_name='historicalprocessingentry',
        #     name='fuel_type_thread',
        #     field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        # ),
        migrations.AddField(
            model_name="perennialcropland",
            name="is_complete_renewal",
            field=models.BooleanField(default=False, verbose_name="is_complete_renewal"),
        ),
        migrations.AddField(
            model_name="perennialcropland",
            name="is_system_in_maturity",
            field=models.BooleanField(default=True, verbose_name="is_system_in_maturity"),
        ),
    ]
