# Generated by Django 4.2.1 on 2023-11-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0222_remove_grassland_agb_t2_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='grassland',
            name='fire_periodicity_start',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='fire_periodicity_w',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='fire_periodicity_wo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
