# Generated by Django 4.2.1 on 2023-11-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0223_gastype_alter_grassland_fire_periodicity_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcropping',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='aquaculture',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='building',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='degradedland',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='disturbancetype',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='floodedrice',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='input',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='landusechange',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='largefishery',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='otherinfrastructure',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='otherlanduse',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='perennialcropping',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='road',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='setaside',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='smallfishery',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
        migrations.AlterField(
            model_name='waterbody',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate'),
        ),
    ]
