# Generated by Django 4.2.1 on 2025-03-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0223_historicalperennialcropland_is_complete_renewal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='map_data',
            field=models.JSONField(blank=True, null=True, verbose_name='map_data'),
        ),
        migrations.AddField(
            model_name='project',
            name='map_data',
            field=models.JSONField(blank=True, null=True, verbose_name='map_data'),
        ),
    ]
