# Generated by Django 4.2.1 on 2023-11-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0224_alter_annualcropping_status_alter_aquaculture_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_management_type_start', to='api.grasslandmanagementtype'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_management_type_w', to='api.grasslandmanagementtype'),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_management_type_wo', to='api.grasslandmanagementtype'),
        ),
    ]
