# Generated by Django 4.2.1 on 2025-03-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0224_historicalproject_map_data_project_map_data"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='historicalprocessingentry',
        #     name='fuel_type_thread',
        #     field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        # ),
        migrations.AddField(
            model_name="historicalproject",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="is_public"),
        ),
        migrations.AddField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="is_public"),
        ),
    ]
