# Generated by Django 4.2.1 on 2023-11-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0225_alter_grassland_grassland_management_type_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualcropping',
            name='biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualcropping',
            name='biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
