# Generated by Django 4.2.1 on 2025-04-01 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0226_historicalprocessingentry_fuel_type_thread_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='historicalprocessingentry',
        #     name='fuel_type_thread',
        #     field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        # ),
        migrations.AddField(
            model_name="historicalproject",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="archived_at"),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="is_finalized",
            field=models.BooleanField(default=False, verbose_name="is_finalized"),
        ),
        migrations.AddField(
            model_name="project",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="archived_at"),
        ),
        migrations.AddField(
            model_name="project",
            name="is_finalized",
            field=models.BooleanField(default=False, verbose_name="is_finalized"),
        ),
    ]
