# Generated by Django 4.2.1 on 2025-04-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0227_historicalprocessingentry_fuel_type_thread_and_more"),
    ]

    operations = []
