# Generated by Django 4.2.1 on 2023-11-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0227_remove_aquaculture_soc_t2_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaculture',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disturbancetype',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disturbancetype',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disturbancetype',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='soc_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='soc_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='soc_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
