# Generated by Django 4.2.1 on 2025-04-01 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0228_energyentry_parentfueltype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentfueltype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
