# Generated by Django 4.2.1 on 2023-11-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0229_degradedland_land_use_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forestmanagement',
            old_name='land_use_type',
            new_name='land_use_type_start',
        ),
        migrations.AddField(
            model_name='degradedland',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='land_use_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_w', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='land_use_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_land_use_type_wo', to='api.landusetype'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
