# Generated by Django 4.2.1 on 2025-04-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0229_historicalprocessingentry_fuel_type_thread_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"permissions": (("can_view_modules", "Can view modules"), ("can_create_modules", "Can create modules"), ("can_change_modules", "Can change modules"), ("can_delete_modules", "Can delete modules"))},
        ),
    ]
