# Generated by Django 4.2.1 on 2023-11-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_rename_land_use_type_forestmanagement_land_use_type_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='soc_ref',
        ),
    ]
