# Generated by Django 4.2.1 on 2025-04-01 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0230_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"permissions": (("view_modules", "Can view modules"), ("add_modules", "Can create modules"), ("change_modules", "Can change modules"), ("delete_modules", "Can delete modules"))},
        ),
    ]
