# Generated by Django 4.2.1 on 2023-11-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_remove_project_soc_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='continent',
            new_name='region',
        ),
    ]
