# Generated by Django 4.2.1 on 2023-11-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0120_rename_moisture_type_nitrousemissionfactor_moisture'),
        ('api', '0232_rename_continent_project_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Continent',
            new_name='Region',
        ),
    ]
