# Generated by Django 4.2.1 on 2025-04-01 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0228_historicalprocessingentry_fuel_type_thread"),
        ("api", "0233_alter_customuser_options_and_more"),
    ]

    operations = []
