# Generated by Django 4.2.1 on 2023-11-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0234_alter_project_code_alter_project_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='continent',
            new_name='region',
        ),
    ]
