# Generated by Django 4.2.1 on 2023-11-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0235_rename_continent_country_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='region',
        ),
    ]
