# Generated by Django 4.2.1 on 2025-04-11 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0236_alter_customuser_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalirrigationphase",
            name="power_origin_country_t2",
        ),
        migrations.RemoveField(
            model_name="irrigationphase",
            name="power_origin_country_t2",
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="country_t2",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.country", verbose_name="country_t2"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="ef_source",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="api.emissionfactorsource", verbose_name="ef_source"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="electricity_ef_t2_start",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_t2_start"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="electricity_ef_t2_w",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_t2_w"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="electricity_ef_t2_wo",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_t2_wo"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="energy_ef_ch4_t2_start",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_ch4_t2"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="energy_ef_ch4_t2_w",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_ch4_t2_w"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="energy_ef_ch4_t2_wo",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_ch4_t2_wo"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="energy_ef_co2_t2_start",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_co2_t2"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="energy_ef_co2_t2_w",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_co2_t2_w"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="energy_ef_co2_t2_wo",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_co2_t2_wo"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="energy_ef_n2o_t2_start",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_n2o_t2"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="energy_ef_n2o_t2_w",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_n2o_t2_w"),
        ),
        migrations.AddField(
            model_name="historicalirrigationphase",
            name="energy_ef_n2o_t2_wo",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_n2o_t2_wo"),
        ),
        # migrations.AddField(
        #     model_name='historicalprocessingentry',
        #     name='fuel_type_thread',
        #     field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        # ),
        migrations.AddField(
            model_name="irrigationphase",
            name="country_t2",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.country", verbose_name="country_t2"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="ef_source",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.emissionfactorsource", verbose_name="ef_source"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="electricity_ef_t2_start",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_t2_start"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="electricity_ef_t2_w",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_t2_w"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="electricity_ef_t2_wo",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_t2_wo"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="energy_ef_ch4_t2_start",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_ch4_t2"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="energy_ef_ch4_t2_w",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_ch4_t2_w"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="energy_ef_ch4_t2_wo",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_ch4_t2_wo"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="energy_ef_co2_t2_start",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_co2_t2"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="energy_ef_co2_t2_w",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_co2_t2_w"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="energy_ef_co2_t2_wo",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_co2_t2_wo"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="energy_ef_n2o_t2_start",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_n2o_t2"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="energy_ef_n2o_t2_w",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_n2o_t2_w"),
        ),
        migrations.AddField(
            model_name="irrigationphase",
            name="energy_ef_n2o_t2_wo",
            field=models.FloatField(blank=True, null=True, verbose_name="ef_n2o_t2_wo"),
        ),
    ]
