# Generated by Django 4.2.1 on 2023-11-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0236_remove_project_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'user')},
        ),
    ]
