# Generated by Django 4.2.1 on 2025-04-22 21:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0237_remove_historicalirrigationphase_power_origin_country_t2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tillagetype",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="tillagetype",
            name="name_es",
        ),
        migrations.RemoveField(
            model_name="tillagetype",
            name="name_fr",
        ),
    ]
