# Generated by Django 4.2.1 on 2023-11-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0237_alter_project_options_alter_project_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherlanduse',
            name='ha_w_rate',
        ),
        migrations.RemoveField(
            model_name='otherlanduse',
            name='ha_wo_rate',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherlanduse',
            name='final_land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_land_use_type', to='api.landusetype'),
        ),
        migrations.AlterField(
            model_name='otherlanduse',
            name='initial_land_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_land_use_type', to='api.landusetype'),
        ),
    ]
