# Generated by Django 4.2.1 on 2023-11-29 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0238_remove_otherlanduse_ha_w_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='capitalization_duration_yrs',
            new_name='capitalization_years',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='implementation_duration_yrs',
            new_name='implementation_years',
        ),
        migrations.AlterField(
            model_name='activity',
            name='change_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.changerate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='organic_input_type_start',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_start', to='api.organicinputtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='organic_input_type_w',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_w', to='api.organicinputtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='organic_input_type_wo',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_wo', to='api.organicinputtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='residue_management_type_start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_start', to='api.residuemanagementtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='residue_management_type_w',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_w', to='api.residuemanagementtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='residue_management_type_wo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_wo', to='api.residuemanagementtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='tillage_management_type_start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_start', to='api.tillagemanagementtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='tillage_management_type_w',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_w', to='api.tillagemanagementtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='tillage_management_type_wo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_wo', to='api.tillagemanagementtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_grassland_management_type_start', to='api.grasslandmanagementtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_w',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_grassland_management_type_w', to='api.grasslandmanagementtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grassland',
            name='grassland_management_type_wo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_grassland_management_type_wo', to='api.grasslandmanagementtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
