# Generated by Django 4.2.1 on 2023-11-30 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_rename_state_activity_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='change_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.changerate'),
        ),
    ]
