# Generated by Django 4.2.1 on 2025-04-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_activitytype_name_ru_buildingtype_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('module_types', models.ManyToManyField(blank=True, related_name='data_sources', to='api.moduletype')),
            ],
        ),
    ]
