# Generated by Django 4.2.1 on 2023-11-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0240_alter_activity_change_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, related_name='activities', to='api.moduletype'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('name', 'project')},
        ),
    ]
