# Generated by Django 4.2.1 on 2025-04-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0240_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualcropland',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='aquaculture',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='building',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='coastalwetland',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='energy',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='energyentry',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='floodedrice',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='forestdisturbance',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalannualcropland',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalaquaculture',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalbuilding',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalcoastalwetland',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalelectricity',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalenergy',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalenergyentry',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalfloodedrice',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalforestdisturbance',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalfuel',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalinput',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalinputentry',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalirrigation',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalirrigationphase',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalirrigationsystem',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicallandusechange',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicallargefishery',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicallivestock',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonannualcropland',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonfloodedrice',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalminorseasonperennialcropland',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalorganicsoil',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalotherinfrastructure',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalotherland',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalotherlanduse',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalpackaging',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalpackagingentry',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalprocessing',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalroad',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalsetaside',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalsmallfishery',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalstorage',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalstorageentry',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicaltransportentry',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='historicalwaterbody',
            name='data_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='input',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='inputentry',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='landusechange',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='minorseasonannualcropland',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='minorseasonfloodedrice',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='minorseasonperennialcropland',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='otherinfrastructure',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='otherland',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='otherlanduse',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='packaging',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='packagingentry',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='processing',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='processingentry',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='road',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='setaside',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='storage',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='storageentry',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='transport',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datasource', verbose_name='data_source'),
        ),
    ]
