# Generated by Django 4.2.1 on 2023-11-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0241_activity_modules_alter_activity_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletype',
            name='is_fixed_assessment',
            field=models.BooleanField(default=False),
        ),
    ]
