# Generated by Django 4.2.1 on 2025-04-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0241_annualcropland_data_source_aquaculture_data_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='short_name',
            field=models.CharField(default='change me', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
