# Generated by Django 4.2.1 on 2023-11-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0242_moduletype_is_fixed_assessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='modules',
            new_name='module_types',
        ),
    ]
