# Generated by Django 4.2.1 on 2025-04-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0242_datasource_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'verbose_name_plural': 'Data sources'},
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('name', 'short_name', 'year')},
        ),
    ]
