# Generated by Django 4.2.1 on 2023-11-30 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0244_alter_grassland_grassland_management_type_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcropping',
            name='organic_input_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_start', to='api.organicinputtype'),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='organic_input_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_w', to='api.organicinputtype'),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='organic_input_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_organic_input_type_wo', to='api.organicinputtype'),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='residue_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_start', to='api.residuemanagementtype'),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='residue_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_w', to='api.residuemanagementtype'),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='residue_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_residue_management_type_wo', to='api.residuemanagementtype'),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='tillage_management_type_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_start', to='api.tillagemanagementtype'),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='tillage_management_type_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_w', to='api.tillagemanagementtype'),
        ),
        migrations.AlterField(
            model_name='annualcropping',
            name='tillage_management_type_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tillage_management_type_wo', to='api.tillagemanagementtype'),
        ),
    ]
