# Generated by Django 4.2.1 on 2023-12-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0245_alter_annualcropping_organic_input_type_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landusechange',
            name='area',
            field=models.FloatField(default=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landusechange',
            name='module_type_start',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='api.moduletype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landusechange',
            name='module_type_w',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='w', to='api.moduletype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landusechange',
            name='module_type_wo',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='wo', to='api.moduletype'),
            preserve_default=False,
        ),
    ]
