# Generated by Django 4.2.1 on 2025-05-08 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0246_auto_20250507_1229'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='HistoricalComment',
        #     fields=[
        #         ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
        #         ('date_created', models.DateTimeField(blank=True, editable=False)),
        #         ('content', models.TextField()),
        #         ('history_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('history_date', models.DateTimeField(db_index=True)),
        #         ('history_change_reason', models.CharField(max_length=100, null=True)),
        #         ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
        #         ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
        #         ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_history', to='api.comment')),
        #         ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
        #         ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.comment')),
        #         ('thread', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread')),
        #     ],
        #     options={
        #         'verbose_name': 'historical comment',
        #         'verbose_name_plural': 'historical comments',
        #         'ordering': ('-history_date', '-history_id'),
        #         'get_latest_by': ('history_date', 'history_id'),
        #     },
        #     bases=(simple_history.models.HistoricalChanges, models.Model),
        # ),
    ]
