# Generated by Django 4.2.1 on 2023-12-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0246_alter_landusechange_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration_t2',
            field=models.IntegerField(default=0),
        ),
    ]
