# Generated by Django 4.2.1 on 2023-12-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0247_alter_activity_duration_t2'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='moisture_t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moisture'),
        ),
    ]
