# Generated by Django 4.2.1 on 2025-05-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0247_historicalcomment'),
        ('api', '0247_remove_historicalperennialcropland_is_complete_renewal_and_more'),
    ]

    operations = [
    ]
