# Generated by Django 4.2.1 on 2025-07-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0248_merge_20250513_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='fire_on_soil_ch4_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='fire_on_soil_ch4_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='fire_on_soil_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='fire_on_soil_co2_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='fire_on_soil_co2_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='fire_on_soil_co2_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='fire_on_soil_co_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='fire_on_soil_co_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='fire_on_soil_co_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='mean_dry_matter_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='mean_dry_matter_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='mean_dry_matter_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_ch4_drainage_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_ch4_drainage_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_ch4_drainage_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_doc_drainage_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_doc_drainage_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_doc_drainage_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_doc_rewetting_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_doc_rewetting_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_doc_rewetting_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_ch4_drainage_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_ch4_drainage_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_ch4_drainage_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_ch4_rewetting_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_ch4_rewetting_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_ch4_rewetting_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_co2_drainage_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_co2_drainage_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_co2_drainage_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_co2_rewetting_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_co2_rewetting_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_co2_rewetting_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_n2o_drainage_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_n2o_drainage_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_n2o_drainage_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_n2o_rewetting_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_n2o_rewetting_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_n2o_rewetting_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='fire_on_soil_ch4_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='fire_on_soil_ch4_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='fire_on_soil_ch4_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='fire_on_soil_co2_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='fire_on_soil_co2_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='fire_on_soil_co2_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='fire_on_soil_co_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='fire_on_soil_co_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='fire_on_soil_co_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='mean_dry_matter_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='mean_dry_matter_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='mean_dry_matter_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_ch4_drainage_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_ch4_drainage_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_ch4_drainage_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_doc_drainage_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_doc_drainage_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_doc_drainage_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_doc_rewetting_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_doc_rewetting_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_doc_rewetting_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_ch4_drainage_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_ch4_drainage_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_ch4_drainage_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_ch4_rewetting_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_ch4_rewetting_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_ch4_rewetting_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_co2_drainage_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_co2_drainage_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_co2_drainage_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_co2_rewetting_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_co2_rewetting_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_co2_rewetting_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_n2o_drainage_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_n2o_drainage_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_n2o_drainage_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_n2o_rewetting_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_n2o_rewetting_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_n2o_rewetting_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HandInHandAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link', models.URLField(blank=True, max_length=2000, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'verbose_name': 'Hand in Hand Assessment',
                'verbose_name_plural': 'Hand in Hand Assessments',
                'ordering': ['country', 'year'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
