# Generated by Django 4.2.1 on 2025-07-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0249_alter_historicalorganicsoil_fire_on_soil_ch4_t2_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandInHandCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
