# Generated by Django 4.2.1 on 2023-12-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0249_projectinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
