# Generated by Django 4.2.1 on 2025-07-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0250_handinhandcountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handinhandassessment',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.handinhandcountry'),
        ),
    ]
