# Generated by Django 4.2.1 on 2023-12-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0250_projectinvitation_is_accepted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectinvitation',
            unique_together={('project', 'user')},
        ),
        migrations.AlterField(
            model_name='projectinvitation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='projectinvitation',
            name='email',
        ),
    ]
