# Generated by Django 4.2.1 on 2025-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0251_alter_handinhandassessment_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandInHandRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
