# Generated by Django 4.2.1 on 2023-12-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0251_alter_projectinvitation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvitation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectinvitation',
            name='updated_at',
        ),
    ]
