# Generated by Django 4.2.1 on 2025-07-15 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0252_handinhandregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='handinhandcountry',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='api.handinhandregion'),
            preserve_default=False,
        ),
    ]
