# Generated by Django 4.2.1 on 2023-12-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0252_remove_projectinvitation_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestock',
            old_name='manure_management_type_t2_start',
            new_name='complementary_manure_management_type_start',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='manure_management_type_t2_w',
            new_name='complementary_manure_management_type_w',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='manure_management_type_t2_wo',
            new_name='complementary_manure_management_type_wo',
        ),
        migrations.AddField(
            model_name='livestock',
            name='complementary_manure_management_type_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_complementary_manure_management_type_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='percentage_heads_on_pasture_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='percentage_heads_on_pasture_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_percentage_heads_on_pasture_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='percentage_heads_on_pasture_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='percentage_heads_on_pasture_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
