# Generated by Django 4.2.1 on 2025-07-15 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0253_handinhandcountry_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="project",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
