# Generated by Django 4.2.1 on 2023-12-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0254_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Agency',
            new_name='ExecutingAgency',
        ),
    ]
