# Generated by Django 4.2.1 on 2023-12-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0255_fundingagency_rename_agency_executingagency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='value_w_rate',
        ),
        migrations.RemoveField(
            model_name='input',
            name='value_wo_rate',
        ),
        migrations.AddField(
            model_name='input',
            name='value_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_value_thread', to='api.commentthread'),
        ),
    ]
