# Generated by Django 4.2.1 on 2023-12-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0256_remove_input_value_w_rate_remove_input_value_wo_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.inputtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='input',
            name='value_start',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='input',
            name='value_w',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='input',
            name='value_wo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
