# Generated by Django 4.2.1 on 2025-07-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0256_auto_20250715_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='public_id',
        ),
    ]
