# Generated by Django 4.2.1 on 2025-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0257_remove_historicalproject_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='public_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
