# Generated by Django 4.2.1 on 2023-12-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0257_alter_input_input_type_alter_input_value_start_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='InputEntry',
        ),
    ]
