# Generated by Django 4.2.1 on 2025-07-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0258_historicalproject_public_id_project_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='public_id',
        ),
    ]
