# Generated by Django 4.2.1 on 2025-07-15 15:01

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("api", "Project")
    for row in MyModel.objects.all():
        row.public_id = uuid.uuid4()
        row.save(update_fields=["public_id"])


def historical_gen_uuid(apps, schema_editor):
    HistoricalModel = apps.get_model("api", "HistoricalProject")
    for row in HistoricalModel.objects.all():
        row.public_id = uuid.uuid4()
        row.save(update_fields=["public_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0260_historicalproject_public_id_project_public_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(historical_gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
