# Generated by Django 4.2.1 on 2023-12-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0261_input_co2_e_emissions_t2_input_co2_emissions_t2_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='input',
        #     name='co2_e_emissions_t2',
        # ),
        # migrations.RemoveField(
        #     model_name='input',
        #     name='co2_emissions_t2',
        # ),
        # migrations.RemoveField(
        #     model_name='input',
        #     name='implementation_year_t2',
        # ),
        # migrations.RemoveField(
        #     model_name='input',
        #     name='input_type',
        # ),
        # migrations.RemoveField(
        #     model_name='input',
        #     name='n2o_emissions_t2',
        # ),
        # migrations.RemoveField(
        #     model_name='input',
        #     name='value_start',
        # ),
        # migrations.RemoveField(
        #     model_name='input',
        #     name='value_thread',
        # ),
        # migrations.RemoveField(
        #     model_name='input',
        #     name='value_w',
        # ),
        # migrations.RemoveField(
        #     model_name='input',
        #     name='value_wo',
        # ),
        migrations.CreateModel(
            name='InputEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_year', models.IntegerField(default=1)),
                ('soc_t2_start', models.FloatField(blank=True, null=True)),
                ('soc_t2_w', models.FloatField(blank=True, null=True)),
                ('soc_t2_wo', models.FloatField(blank=True, null=True)),
                ('value_start', models.FloatField()),
                ('value_w', models.FloatField()),
                ('value_wo', models.FloatField()),
                ('co2_emissions_t2', models.FloatField(blank=True, null=True)),
                ('n2o_emissions_t2', models.FloatField(blank=True, null=True)),
                ('co2_e_emissions_t2', models.FloatField(blank=True, null=True)),
                ('implementation_year_t2', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_entries', to='api.input')),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inputtype')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate')),
                ('value_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_value_thread', to='api.commentthread')),
            ],
            options={
                'abstract': False,
            },
        ),    
    ]
