# Generated by Django 4.2.1 on 2025-07-15 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0261_auto_20250715_1501"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="historicalproject",
        #     name="public_id",
        #     field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        # ),
        # migrations.AlterField(
        #     model_name="project",
        #     name="public_id",
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        # ),
    ]
