# Generated by Django 4.2.1 on 2025-07-16 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0262_auto_20250715_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallfisherygeartype',
            name='fishery_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='gear_types', to='api.fisherytype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
