# Generated by Django 4.2.1 on 2023-12-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0262_remove_input_co2_e_emissions_t2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputentry',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='soc_t2_start',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='soc_t2_w',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='soc_t2_wo',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='updated_at',
        ),
    ]
