# Generated by Django 4.2.1 on 2025-07-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0263_smallfisherygeartype_fishery_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='public_id',
        ),
    ]
