# Generated by Django 4.2.1 on 2023-12-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0264_inputentry_activity_inputentry_created_at_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='inputentry',
        #     name='input',
        # ),
        # migrations.DeleteModel(
        #     name='Input',
        # ),
    ]
