# Generated by Django 4.2.1 on 2025-07-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0264_remove_historicalproject_public_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smallfisherygeartype',
            old_name='fishery_type',
            new_name='fishery_types',
        ),
    ]
