# Generated by Django 4.2.1 on 2025-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0265_rename_fishery_type_smallfisherygeartype_fishery_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestmanagement',
            name='max_agb_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='max_agb_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='max_agb_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='max_agb_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='max_agb_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='max_agb_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='agb_growth_rate_gt_20_yrs_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='agb_growth_rate_gt_20_yrs_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='agb_growth_rate_gt_20_yrs_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='agb_growth_rate_le_20_yrs_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='agb_growth_rate_le_20_yrs_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='agb_growth_rate_le_20_yrs_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='bgb_growth_rate_gt_20_yrs_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='bgb_growth_rate_gt_20_yrs_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='bgb_growth_rate_gt_20_yrs_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='bgb_growth_rate_le_20_yrs_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='bgb_growth_rate_le_20_yrs_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='bgb_growth_rate_le_20_yrs_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='degradation_dry_matter_impacted_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='degradation_dry_matter_impacted_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='degradation_dry_matter_impacted_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_dry_matter_logged_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_dry_matter_logged_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_dry_matter_logged_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_w',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='logging_start_year_t2_wo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_w',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagement',
            name='rotation_start_year_t2_wo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='agb_growth_rate_gt_20_yrs_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='agb_growth_rate_gt_20_yrs_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='agb_growth_rate_gt_20_yrs_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='agb_growth_rate_le_20_yrs_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='agb_growth_rate_le_20_yrs_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='agb_growth_rate_le_20_yrs_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='bgb_growth_rate_gt_20_yrs_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='bgb_growth_rate_gt_20_yrs_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='bgb_growth_rate_gt_20_yrs_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='bgb_growth_rate_le_20_yrs_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='bgb_growth_rate_le_20_yrs_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='bgb_growth_rate_le_20_yrs_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='degradation_dry_matter_impacted_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='degradation_dry_matter_impacted_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='degradation_dry_matter_impacted_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='logging_dry_matter_logged_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='logging_dry_matter_logged_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='logging_dry_matter_logged_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='logging_start_year_t2_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='logging_start_year_t2_w',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='logging_start_year_t2_wo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='rotation_start_year_t2_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='rotation_start_year_t2_w',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalforestmanagement',
            name='rotation_start_year_t2_wo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
