# Generated by Django 4.2.1 on 2023-12-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0266_input_inputentry_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputentry',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='input',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='input_type',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='value_thread',
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.DeleteModel(
            name='InputEntry',
        ),
    ]
