# Generated by Django 4.2.1 on 2025-07-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0266_forestmanagement_max_agb_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forestmanagement',
            old_name='max_agb_t2_start',
            new_name='agb_max_t2_start',
        ),
        migrations.RenameField(
            model_name='forestmanagement',
            old_name='max_agb_t2_w',
            new_name='agb_max_t2_w',
        ),
        migrations.RenameField(
            model_name='forestmanagement',
            old_name='max_agb_t2_wo',
            new_name='agb_max_t2_wo',
        ),
        migrations.RenameField(
            model_name='historicalforestmanagement',
            old_name='max_agb_t2_start',
            new_name='agb_max_t2_start',
        ),
        migrations.RenameField(
            model_name='historicalforestmanagement',
            old_name='max_agb_t2_w',
            new_name='agb_max_t2_w',
        ),
        migrations.RenameField(
            model_name='historicalforestmanagement',
            old_name='max_agb_t2_wo',
            new_name='agb_max_t2_wo',
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='bgb_max_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='bgb_max_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='bgb_max_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='bgb_max_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='bgb_max_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='bgb_max_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
