# Generated by Django 4.2.1 on 2025-07-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0267_rename_max_agb_t2_start_forestmanagement_agb_max_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grassland',
            name='biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='biomass_t2_wo',
        ),
        migrations.RemoveField(
            model_name='historicalgrassland',
            name='biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='historicalgrassland',
            name='biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='historicalgrassland',
            name='biomass_t2_wo',
        ),
    ]
