# Generated by Django 4.2.1 on 2023-12-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0267_remove_inputentry_activity_remove_inputentry_input_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_year', models.IntegerField(default=1)),
                ('soc_t2_start', models.FloatField(blank=True, null=True)),
                ('soc_t2_w', models.FloatField(blank=True, null=True)),
                ('soc_t2_wo', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.activity')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activitystate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
