# Generated by Django 4.2.1 on 2025-07-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0268_remove_grassland_biomass_t2_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_opted_out_of_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='is_opted_out_of_emails',
            field=models.BooleanField(default=False),
        ),
    ]
