# Generated by Django 4.2.1 on 2025-07-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0269_customuser_is_opted_out_of_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganicsoil',
            name='onsite_ch4_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganicsoil',
            name='onsite_ch4_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganicsoil',
            name='onsite_ch4_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_ch4_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_ch4_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoil',
            name='onsite_ch4_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='is_peat_for_energy_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='is_peat_for_energy_w',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='is_peat_for_energy_wo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_ch4_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_ch4_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_ch4_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_doc_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_doc_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='offsite_doc_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_co2_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_co2_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_co2_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_n2o_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_n2o_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='onsite_n2o_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_area_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_area_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_area_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_density_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_density_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_density_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_ditches_area_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_ditches_area_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_ditches_area_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_extraction_height_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_extraction_height_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganicsoil',
            name='peat_extraction_height_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='is_peat_for_energy_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='is_peat_for_energy_w',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='is_peat_for_energy_wo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_ch4_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_ch4_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_ch4_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_doc_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_doc_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='offsite_doc_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_co2_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='onsite_n2o_peat_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_area_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_area_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_area_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_density_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_density_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_density_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_ditches_area_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_ditches_area_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_ditches_area_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_extraction_height_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_extraction_height_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organicsoil',
            name='peat_extraction_height_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
