# Generated by Django 4.2.1 on 2023-12-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0269_inputentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputentry',
            old_name='input',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='soc_t2_start',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='soc_t2_w',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='soc_t2_wo',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='status',
        ),
    ]
