# Generated by Django 4.2.1 on 2023-12-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0270_rename_input_inputentry_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricity',
            old_name='energy',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='energy',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='irrigationphase',
            old_name='irrigation',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='irrigationsystem',
            old_name='irrigation',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='soc_t2_start',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='soc_t2_w',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='soc_t2_wo',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='soc_t2_start',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='soc_t2_w',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='soc_t2_wo',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='status',
        ),
    ]
