# Generated by Django 4.2.1 on 2025-07-30 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0270_historicalorganicsoil_onsite_ch4_peat_t2_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opted_out', models.BooleanField(default=False, verbose_name='is_opted_out_of_project_notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Notification Preference',
                'verbose_name_plural': 'Project Notification Preferences',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
