# Generated by Django 4.2.1 on 2023-12-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0271_rename_energy_electricity_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputentry',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='input_entries', to='api.input'),
            preserve_default=False,
        ),
    ]
