# Generated by Django 4.2.1 on 2025-08-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0238_historicalprocessingentry_fuel_type_thread'),
        ('api', '0271_projectnotificationpreference'),
    ]

    operations = [
    ]
