# Generated by Django 4.2.1 on 2025-09-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0272_merge_20250804_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='initial_biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='initial_biomass_t2_thread',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='initial_biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='initial_biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='initial_biomass_t2_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='initial_biomass_t2_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_initial_biomass_t2_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='initial_biomass_t2_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='initial_biomass_t2_wo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
