# Generated by Django 4.2.1 on 2023-12-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0272_alter_inputentry_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='module_type',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.moduletype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuel',
            name='module_type',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.moduletype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputentry',
            name='module_type',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.moduletype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irrigationphase',
            name='module_type',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.moduletype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='module_type',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.moduletype'),
            preserve_default=False,
        ),
    ]
