# Generated by Django 4.2.1 on 2025-09-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0273_historicalperennialcropland_initial_biomass_t2_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperennialcropland',
            name='initial_biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='historicalperennialcropland',
            name='initial_biomass_t2_thread',
        ),
        migrations.RemoveField(
            model_name='historicalperennialcropland',
            name='initial_biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='historicalperennialcropland',
            name='initial_biomass_t2_wo',
        ),
        migrations.RemoveField(
            model_name='perennialcropland',
            name='initial_biomass_t2_start',
        ),
        migrations.RemoveField(
            model_name='perennialcropland',
            name='initial_biomass_t2_thread',
        ),
        migrations.RemoveField(
            model_name='perennialcropland',
            name='initial_biomass_t2_w',
        ),
        migrations.RemoveField(
            model_name='perennialcropland',
            name='initial_biomass_t2_wo',
        ),
    ]
