# Generated by Django 4.2.1 on 2023-12-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0273_electricity_module_type_fuel_module_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityState',
            new_name='StatusType',
        ),
        migrations.AlterModelOptions(
            name='statustype',
            options={'verbose_name_plural': 'Status types'},
        ),
    ]
