# Generated by Django 4.2.1 on 2023-12-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0274_rename_activitystate_statustype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='start_year_t2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_t2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
