# Generated by Django 4.2.1 on 2025-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0274_remove_historicalperennialcropland_initial_biomass_t2_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestmanagement',
            name='agb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='agb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='agb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_wo'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='bgb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='bgb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='forestmanagement',
            name='bgb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_wo'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='agb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='agb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='agb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_wo'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='bgb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='bgb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='grassland',
            name='bgb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='agb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='agb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='agb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='bgb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='bgb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalforestmanagement',
            name='bgb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='agb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='agb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='agb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='bgb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='bgb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalgrassland',
            name='bgb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='agb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='agb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='agb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_wo'),
        ),
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='bgb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='bgb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='historicalperennialcropland',
            name='bgb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_wo'),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='agb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='agb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='agb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='agb_rate_t2_wo'),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='bgb_rate_t2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_start'),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='bgb_rate_t2_w',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_w'),
        ),
        migrations.AddField(
            model_name='perennialcropland',
            name='bgb_rate_t2_wo',
            field=models.FloatField(blank=True, null=True, verbose_name='bgb_rate_t2_wo'),
        ),
    ]
