# Generated by Django 4.2.1 on 2023-12-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0275_activity_start_year_t2_alter_activity_duration_t2'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputentry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.inputentry'),
        ),
        
    ]
