# Generated by Django 4.2.1 on 2025-09-18 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0275_forestmanagement_agb_rate_t2_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallargefishery',
            old_name='ice_preserved_catch_thread',
            new_name='ice_preserved_catch_pc_thread',
        ),
        migrations.RenameField(
            model_name='historicallargefishery',
            old_name='refrigerant_thread',
            new_name='refrigerant_pc_thread',
        ),
        migrations.RenameField(
            model_name='historicallargefishery',
            old_name='total_catch_thread',
            new_name='total_catch_yr_thread',
        ),
        migrations.RenameField(
            model_name='historicalsmallfishery',
            old_name='ice_preserved_catch_thread',
            new_name='ice_preserved_catch_pc_thread',
        ),
        migrations.RenameField(
            model_name='historicalsmallfishery',
            old_name='refrigerant_thread',
            new_name='refrigerant_pc_thread',
        ),
        migrations.RenameField(
            model_name='historicalsmallfishery',
            old_name='total_catch_thread',
            new_name='total_catch_yr_thread',
        ),
        migrations.RenameField(
            model_name='largefishery',
            old_name='refrigerant_thread',
            new_name='refrigerant_pc_thread',
        ),
        migrations.RenameField(
            model_name='smallfishery',
            old_name='refrigerant_thread',
            new_name='refrigerant_pc_thread',
        ),
        migrations.RemoveField(
            model_name='largefishery',
            name='ice_preserved_catch_thread',
        ),
        migrations.RemoveField(
            model_name='largefishery',
            name='total_catch_thread',
        ),
        migrations.RemoveField(
            model_name='smallfishery',
            name='ice_preserved_catch_thread',
        ),
        migrations.RemoveField(
            model_name='smallfishery',
            name='total_catch_thread',
        ),
        migrations.AddField(
            model_name='largefishery',
            name='ice_preserved_catch_pc_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ice_preserved_catch_pc_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='largefishery',
            name='total_catch_yr_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_total_catch_yr_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='ice_preserved_catch_pc_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ice_preserved_catch_pc_thread', to='api.commentthread'),
        ),
        migrations.AddField(
            model_name='smallfishery',
            name='total_catch_yr_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_total_catch_yr_thread', to='api.commentthread'),
        ),
    ]
