# Generated by Django 4.2.1 on 2025-09-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0276_rename_ice_preserved_catch_thread_historicallargefishery_ice_preserved_catch_pc_thread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_b_intact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='is_b_intact',
            field=models.BooleanField(default=False),
        ),
    ]
