# Generated by Django 4.2.1 on 2023-12-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0277_alter_inputentry_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executingagency',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fundingagency',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
