# Generated by Django 4.2.1 on 2025-09-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0277_activity_is_b_intact_historicalactivity_is_b_intact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='module_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='activities', to='api.moduletype'),
        ),
    ]
