# Generated by Django 4.2.1 on 2025-10-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0278_alter_activity_module_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtype',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
