# Generated by Django 4.2.1 on 2023-12-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0278_alter_executingagency_name_alter_fundingagency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(default=845, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.commentthread'),
            preserve_default=False,
        ),
    ]
