# Generated by Django 4.2.1 on 2025-10-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0279_inputtype_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='handinhandassessment',
            name='files_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
