# Generated by Django 4.2.1 on 2025-10-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0280_handinhandassessment_files_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_not_drained_or_rewetted_start',
            field=models.FloatField(default=0, verbose_name='area_not_drained_or_rewetted_start'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_not_drained_or_rewetted_w',
            field=models.FloatField(default=0, verbose_name='area_not_drained_or_rewetted_w'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_not_drained_or_rewetted_wo',
            field=models.FloatField(default=0, verbose_name='area_not_drained_or_rewetted_wo'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_under_drainage_start',
            field=models.FloatField(default=0, verbose_name='area_under_drainage_start'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_under_drainage_w',
            field=models.FloatField(default=0, verbose_name='area_under_drainage_w'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_under_drainage_wo',
            field=models.FloatField(default=0, verbose_name='area_under_drainage_wo'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_w_restored_vegetation_start',
            field=models.FloatField(default=0, verbose_name='area_w_restored_vegetation_start'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_w_restored_vegetation_w',
            field=models.FloatField(default=0, verbose_name='area_w_restored_vegetation_w'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='area_w_restored_vegetation_wo',
            field=models.FloatField(default=0, verbose_name='area_w_restored_vegetation_wo'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='drained_area_excavated_start',
            field=models.FloatField(default=0, verbose_name='drained_area_excavated_start'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='drained_area_excavated_w',
            field=models.FloatField(default=0, verbose_name='drained_area_excavated_w'),
        ),
        migrations.AlterField(
            model_name='coastalwetland',
            name='drained_area_excavated_wo',
            field=models.FloatField(default=0, verbose_name='drained_area_excavated_wo'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_not_drained_or_rewetted_start',
            field=models.FloatField(default=0, verbose_name='area_not_drained_or_rewetted_start'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_not_drained_or_rewetted_w',
            field=models.FloatField(default=0, verbose_name='area_not_drained_or_rewetted_w'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_not_drained_or_rewetted_wo',
            field=models.FloatField(default=0, verbose_name='area_not_drained_or_rewetted_wo'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_under_drainage_start',
            field=models.FloatField(default=0, verbose_name='area_under_drainage_start'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_under_drainage_w',
            field=models.FloatField(default=0, verbose_name='area_under_drainage_w'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_under_drainage_wo',
            field=models.FloatField(default=0, verbose_name='area_under_drainage_wo'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_w_restored_vegetation_start',
            field=models.FloatField(default=0, verbose_name='area_w_restored_vegetation_start'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_w_restored_vegetation_w',
            field=models.FloatField(default=0, verbose_name='area_w_restored_vegetation_w'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='area_w_restored_vegetation_wo',
            field=models.FloatField(default=0, verbose_name='area_w_restored_vegetation_wo'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='drained_area_excavated_start',
            field=models.FloatField(default=0, verbose_name='drained_area_excavated_start'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='drained_area_excavated_w',
            field=models.FloatField(default=0, verbose_name='drained_area_excavated_w'),
        ),
        migrations.AlterField(
            model_name='historicalcoastalwetland',
            name='drained_area_excavated_wo',
            field=models.FloatField(default=0, verbose_name='drained_area_excavated_wo'),
        ),
    ]
