# Generated by Django 4.2.1 on 2025-11-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0281_alter_coastalwetland_area_not_drained_or_rewetted_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='climate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.climate'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.country'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='moisture',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.moisture'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='soil_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.soiltype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='climate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.climate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='moisture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moisture'),
        ),
        migrations.AlterField(
            model_name='project',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.soiltype'),
        ),
    ]
