# Generated by Django 4.2.1 on 2023-12-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0281_annualcropping_fi_t2_start_annualcropping_fi_t2_w_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration_t2',
            field=models.IntegerField(default=0),
        ),
    ]
