# Generated by Django 4.2.1 on 2026-02-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0282_alter_historicalproject_climate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='export_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID for identifying this project across exports/imports', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='export_id',
            field=models.UUIDField(blank=True, help_text='UUID for identifying this project across exports/imports', null=True, unique=True),
        ),
    ]
