# Generated by Django 4.2.1 on 2023-12-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0282_alter_activity_duration_t2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='inputentry',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='irrigationphase',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='irrigationsystem',
            name='module_type',
        ),
    ]
