# Generated by Django 4.2.1 on 2023-12-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0283_remove_electricity_module_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtype',
            name='has_co2_e_emissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputtype',
            name='has_co2_emissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputtype',
            name='has_n2o_emissions',
            field=models.BooleanField(default=False),
        ),
    ]
