# Generated by Django 4.2.1 on 2023-12-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0284_inputtype_has_co2_e_emissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
