# Generated by Django 4.2.1 on 2026-04-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0284_cachedresultmixin_units_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualcropland',
            name='faostat_year_t2',
            field=models.IntegerField(blank=True, null=True, verbose_name='faostat_year_t2'),
        ),
        migrations.AddField(
            model_name='historicalannualcropland',
            name='faostat_year_t2',
            field=models.IntegerField(blank=True, null=True, verbose_name='faostat_year_t2'),
        ),
    ]
