# Generated by Django 4.2.1 on 2023-12-21 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0281_alter_executingagency_abbreviation_and_more"),
        ("api", "0284_inputtype_has_co2_e_emissions_and_more"),
    ]

    operations = []
