# Generated by Django 4.2.1 on 2023-12-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0285_project_start_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="landusetype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
