# Generated by Django 5.2.13 on 2026-04-22 12:44
#
# Idempotent re-registration of historicalprocessingentry.fuel_type_thread.
# The column + index were created in production/dev by a prior version of
# migration 0246 whose AddField was later removed in commit 737447a. This
# migration resyncs the migration state with the live schema:
#   - state_operations: tell Django the field exists (so autodetector stops
#     generating new AddField migrations for it)
#   - database_operations: only create the column/index if they don't already
#     exist, so fresh databases still get a valid schema while existing
#     databases are left untouched.

import django.db.models.deletion
from django.db import migrations, models

_TABLE = "api_historicalprocessingentry"
_COLUMN = "fuel_type_thread_id"
_INDEX = "api_historicalprocessingentry_fuel_type_thread_id_f2b5f99a"

# Original Postgres path — unchanged. Existing Postgres databases already
# applied 0286 so this never re-runs there; kept verbatim for any fresh
# Postgres build.
_PG_FORWARD = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'api_historicalprocessingentry'
          AND column_name = 'fuel_type_thread_id'
    ) THEN
        ALTER TABLE api_historicalprocessingentry
            ADD COLUMN fuel_type_thread_id bigint NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = current_schema()
          AND tablename = 'api_historicalprocessingentry'
          AND indexname = 'api_historicalprocessingentry_fuel_type_thread_id_f2b5f99a'
    ) THEN
        CREATE INDEX api_historicalprocessingentry_fuel_type_thread_id_f2b5f99a
            ON api_historicalprocessingentry (fuel_type_thread_id);
    END IF;
END
$$;
"""

_PG_REVERSE = """
DROP INDEX IF EXISTS api_historicalprocessingentry_fuel_type_thread_id_f2b5f99a;
ALTER TABLE api_historicalprocessingentry DROP COLUMN IF EXISTS fuel_type_thread_id;
"""


def _forward(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "postgresql":
        schema_editor.execute(_PG_FORWARD)
        return
    # SQLite / other: emulate the idempotent column + index creation.
    with conn.cursor() as cursor:
        existing = {c.name for c in conn.introspection.get_table_description(cursor, _TABLE)}
    if _COLUMN not in existing:
        schema_editor.execute(f"ALTER TABLE {_TABLE} ADD COLUMN {_COLUMN} bigint NULL")
    schema_editor.execute(f"CREATE INDEX IF NOT EXISTS {_INDEX} ON {_TABLE} ({_COLUMN})")


def _reverse(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "postgresql":
        schema_editor.execute(_PG_REVERSE)
        return
    schema_editor.execute(f"DROP INDEX IF EXISTS {_INDEX}")
    try:
        schema_editor.execute(f"ALTER TABLE {_TABLE} DROP COLUMN {_COLUMN}")
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0285_annualcropland_faostat_year_t2'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='historicalprocessingentry',
                    name='fuel_type_thread',
                    field=models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='api.commentthread',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(_forward, _reverse),
            ],
        ),
    ]
