# Generated by Django 5.2.13 on 2026-04-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0285_annualcropland_faostat_year_t2'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocessingentry',
            name='fuel_type_thread',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.commentthread'),
        ),
    ]
