# Generated by Django 4.2.1 on 2023-12-24 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0286_landusetype_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organicsoil",
            name="has_peat_extraction",
        ),
    ]
