# Generated by Django 4.2.1 on 2026-04-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0286_fisheries_country_t2_ef_source_t2'),
        ('api', '0286_historicalprocessingentry_fuel_type_thread'),
    ]

    operations = [
    ]
