# Generated by Django 4.2.1 on 2023-12-27 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0287_remove_organicsoil_has_peat_extraction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grassland",
            name="soil_carbon_t2_start",
        ),
        migrations.RemoveField(
            model_name="grassland",
            name="soil_carbon_t2_w",
        ),
        migrations.RemoveField(
            model_name="grassland",
            name="soil_carbon_t2_wo",
        ),
    ]
