# Generated by Django 5.2.13 on 2026-05-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0287_merge_20260424_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallargefishery',
            old_name='ef_source_t2',
            new_name='ef_source',
        ),
        migrations.RenameField(
            model_name='historicalsmallfishery',
            old_name='ef_source_t2',
            new_name='ef_source',
        ),
        migrations.RenameField(
            model_name='largefishery',
            old_name='ef_source_t2',
            new_name='ef_source',
        ),
        migrations.RenameField(
            model_name='smallfishery',
            old_name='ef_source_t2',
            new_name='ef_source',
        ),
    ]
