# Generated by Django 4.2.1 on 2024-01-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0291_group_alter_userprojectgroup_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="floodedrice",
            name="user_notes",
        ),
        migrations.CreateModel(
            name="MinorSeasonFloodedRice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("start_year", models.IntegerField(default=1)),
                ("cultivation_period_start", models.IntegerField(default=113)),
                ("cultivation_period_w", models.IntegerField(default=113)),
                ("cultivation_period_wo", models.IntegerField(default=113)),
                ("crop_yield_start", models.FloatField(blank=True, null=True)),
                ("crop_yield_w", models.FloatField(blank=True, null=True)),
                ("crop_yield_wo", models.FloatField(blank=True, null=True)),
                (
                    "main_biomass_factor_t2_start",
                    models.FloatField(blank=True, null=True),
                ),
                ("main_biomass_factor_t2_w", models.FloatField(blank=True, null=True)),
                ("main_biomass_factor_t2_wo", models.FloatField(blank=True, null=True)),
                ("soc_t2_start", models.FloatField(blank=True, null=True)),
                ("soc_t2_w", models.FloatField(blank=True, null=True)),
                ("soc_t2_wo", models.FloatField(blank=True, null=True)),
                ("land_use_factor_t2_start", models.FloatField(blank=True, null=True)),
                ("land_use_factor_t2_w", models.FloatField(blank=True, null=True)),
                ("land_use_factor_t2_wo", models.FloatField(blank=True, null=True)),
                ("efc_t2_start", models.FloatField(blank=True, null=True)),
                ("efc_t2_w", models.FloatField(blank=True, null=True)),
                ("efc_t2_wo", models.FloatField(blank=True, null=True)),
                ("sfw_t2_start", models.FloatField(blank=True, null=True)),
                ("sfw_t2_w", models.FloatField(blank=True, null=True)),
                ("sfw_t2_wo", models.FloatField(blank=True, null=True)),
                ("sfp_t2_start", models.FloatField(blank=True, null=True)),
                ("sfp_t2_w", models.FloatField(blank=True, null=True)),
                ("sfp_t2_wo", models.FloatField(blank=True, null=True)),
                ("sfo_t2_start", models.FloatField(blank=True, null=True)),
                ("sfo_t2_w", models.FloatField(blank=True, null=True)),
                ("sfo_t2_wo", models.FloatField(blank=True, null=True)),
                ("efi_t2_start", models.FloatField(blank=True, null=True)),
                ("efi_t2_w", models.FloatField(blank=True, null=True)),
                ("efi_t2_wo", models.FloatField(blank=True, null=True)),
                ("rice_straw_t2_start", models.FloatField(blank=True, null=True)),
                ("rice_straw_t2_w", models.FloatField(blank=True, null=True)),
                ("rice_straw_t2_wo", models.FloatField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="api.activity",
                    ),
                ),
                (
                    "organic_amendment_type_start",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_organic_amendment_type_start",
                        to="api.organicamendmenttype",
                    ),
                ),
                (
                    "organic_amendment_type_w",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_organic_amendment_type_w",
                        to="api.organicamendmenttype",
                    ),
                ),
                (
                    "organic_amendment_type_wo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_organic_amendment_type_wo",
                        to="api.organicamendmenttype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minor_seasons",
                        to="api.floodedrice",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.statustype",
                    ),
                ),
                (
                    "water_management_type_after_cultivation_start",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_water_management_type_after_cultivation_start",
                        to="api.watermanagementtypeaftercultivation",
                    ),
                ),
                (
                    "water_management_type_after_cultivation_w",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_water_management_type_after_cultivation_w",
                        to="api.watermanagementtypeaftercultivation",
                    ),
                ),
                (
                    "water_management_type_after_cultivation_wo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_water_management_type_after_cultivation_wo",
                        to="api.watermanagementtypeaftercultivation",
                    ),
                ),
                (
                    "water_management_type_before_cultivation_start",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_water_management_type_before_cultivation_start",
                        to="api.watermanagementtypebeforecultivation",
                    ),
                ),
                (
                    "water_management_type_before_cultivation_w",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_water_management_type_before_cultivation_w",
                        to="api.watermanagementtypebeforecultivation",
                    ),
                ),
                (
                    "water_management_type_before_cultivation_wo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_water_management_type_before_cultivation_wo",
                        to="api.watermanagementtypebeforecultivation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
