# Generated by Django 4.2.1 on 2024-01-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0292_remove_floodedrice_user_notes_minorseasonfloodedrice"),
    ]

    operations = [
        migrations.AddField(
            model_name="perennialcropping",
            name="agb_max_t2_start",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="perennialcropping",
            name="agb_max_t2_w",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="perennialcropping",
            name="agb_max_t2_wo",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
