# Generated by Django 5.2.17 on 2026-08-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0292_country_iso3'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='last_recap_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_recap_sent_at'),
        ),
        migrations.AddField(
            model_name='project',
            name='last_recap_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_recap_sent_at'),
        ),
    ]
