# Generated by Django 5.2.17 on 2026-09-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0293_project_last_recap_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectnotificationpreference',
            name='is_opted_out',
        ),
        migrations.AddField(
            model_name='projectnotificationpreference',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='is_subscribed_to_project_notifications'),
        ),
    ]
