# Generated by Django 4.2.1 on 2024-01-21 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0293_perennialcropping_agb_max_t2_start_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livestock",
            old_name="enteric_fermentation_start_t2",
            new_name="enteric_fermentation_t2_start",
        ),
        migrations.RenameField(
            model_name="livestock",
            old_name="enteric_fermentation_w_t2",
            new_name="enteric_fermentation_t2_w",
        ),
        migrations.RenameField(
            model_name="livestock",
            old_name="enteric_fermentation_wo_t2",
            new_name="enteric_fermentation_t2_wo",
        ),
        migrations.RenameField(
            model_name="livestock",
            old_name="prp_ch4_start_t2",
            new_name="prp_ch4_t2_start",
        ),
        migrations.RenameField(
            model_name="livestock",
            old_name="prp_ch4_w_t2",
            new_name="prp_ch4_t2_w",
        ),
        migrations.RenameField(
            model_name="livestock",
            old_name="prp_ch4_wo_t2",
            new_name="prp_ch4_t2_wo",
        ),
        migrations.RenameField(
            model_name="livestock",
            old_name="prp_n2o_start_t2",
            new_name="prp_n2o_t2_start",
        ),
        migrations.RenameField(
            model_name="livestock",
            old_name="prp_n2o_w_t2",
            new_name="prp_n2o_t2_w",
        ),
        migrations.RenameField(
            model_name="livestock",
            old_name="prp_n2o_wo_t2",
            new_name="prp_n2o_t2_wo",
        ),
        migrations.RenameField(
            model_name="livestock",
            old_name="prp_percentage_start_t2",
            new_name="prp_percentage_t2_start",
        ),
        migrations.RenameField(
            model_name="livestock",
            old_name="prp_percentage_w_t2",
            new_name="prp_percentage_t2_w",
        ),
        migrations.RenameField(
            model_name="livestock",
            old_name="prp_percentage_wo_t2",
            new_name="prp_percentage_t2_wo",
        ),
    ]
