# Generated by Django 4.2.1 on 2024-01-23 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0294_rename_enteric_fermentation_start_t2_livestock_enteric_fermentation_t2_start_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="organicsoil",
            old_name="is_peat_is_for_energy_thread",
            new_name="is_peat_for_energy_thread",
        ),
        migrations.RenameField(
            model_name="organicsoil",
            old_name="is_peat_is_for_energy_w",
            new_name="is_peat_for_energy_w",
        ),
        migrations.RenameField(
            model_name="organicsoil",
            old_name="is_peat_is_for_energy_wo",
            new_name="is_peat_for_energy_wo",
        ),
    ]
