# Generated by Django 5.2.17 on 2026-10-09 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0294_projectnotificationpreference_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='guided_step',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z_]+(\\.[A-Za-z_]+)*$', 'Only dot-separated identifiers of letters and underscores are allowed.')], verbose_name='guided_step'),
        ),
        migrations.AddField(
            model_name='project',
            name='guided_step',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z_]+(\\.[A-Za-z_]+)*$', 'Only dot-separated identifiers of letters and underscores are allowed.')], verbose_name='guided_step'),
        ),
    ]
