# Generated by Django 4.2.1 on 2024-01-23 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0295_rename_is_peat_is_for_energy_thread_organicsoil_is_peat_for_energy_thread_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("can_view_modules", "Can view modules"),
                    ("can_create_modules", "Can create modules"),
                    ("can_change_modules", "Can edit modules"),
                    ("can_delete_modules", "Can delete modules"),
                )
            },
        ),
    ]
