# Generated by Django 4.2.1 on 2024-01-23 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0296_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("can_view_modules", "Can view modules"),
                    ("can_add_modules", "Can create modules"),
                    ("can_change_modules", "Can edit modules"),
                    ("can_delete_modules", "Can delete modules"),
                )
            },
        ),
    ]
