# Generated by Django 4.2.1 on 2024-01-24 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0285_merge_20231221_1519"),
        ("api", "0298_note_remove_annualcropping_user_notes_and_more"),
    ]

    operations = []
