# Generated by Django 4.2.1 on 2024-01-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0299_merge_20240124_1136"),
    ]

    operations = [
        migrations.AddField(
            model_name="climate",
            name="moistures",
            field=models.ManyToManyField(related_name="climates", to="api.moisture"),
        ),
    ]
