# Generated by Django 4.2.1 on 2024-01-29 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0300_climate_moistures"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fuel",
            old_name="fuel_start",
            new_name="fuel_consumption_start",
        ),
        migrations.RenameField(
            model_name="fuel",
            old_name="fuel_w",
            new_name="fuel_consumption_w",
        ),
        migrations.RenameField(
            model_name="fuel",
            old_name="fuel_wo",
            new_name="fuel_consumption_wo",
        ),
    ]
