# Generated by Django 4.2.1 on 2024-01-29 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0301_rename_fuel_start_fuel_fuel_consumption_start_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inputentry",
            name="parent",
        ),
        migrations.DeleteModel(
            name="Input",
        ),
    ]
