# Generated by Django 4.2.1 on 2024-01-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0303_input_inputentry_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputentry",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="input_entries",
                to="api.input",
            ),
        ),
    ]
