# Generated by Django 4.2.1 on 2024-01-29 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0304_alter_inputentry_parent"),
        ("api", "0305_hotfix"),
    ]

    operations = []
