# Generated by Django 4.2.1 on 2024-01-30 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0306_merge_0304_alter_inputentry_parent_0305_hotfix"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="inputentry",
        #     name="parent",
        # ),
    ]
