# Generated by Django 4.2.1 on 2024-01-30 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0307_remove_inputentry_parent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InputEntry",
        ),
    ]
