# Generated by Django 4.2.1 on 2024-01-30 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0308_delete_inputentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_start", models.FloatField()),
                ("value_w", models.FloatField()),
                ("value_wo", models.FloatField()),
                ("co2_emissions_t2", models.FloatField(blank=True, null=True)),
                ("n2o_emissions_t2", models.FloatField(blank=True, null=True)),
                ("co2_e_emissions_t2", models.FloatField(blank=True, null=True)),
                ("implementation_year_t2", models.IntegerField(blank=True, null=True)),
                (
                    "input_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.inputtype"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_entries",
                        to="api.input",
                    ),
                ),
                (
                    "value_thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_value_thread",
                        to="api.commentthread",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
