# Generated by Django 4.2.1 on 2024-01-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0309_inputentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livestock",
            name="livestock_category_type_start",
        ),
        migrations.RemoveField(
            model_name="livestock",
            name="livestock_category_type_w",
        ),
        migrations.RemoveField(
            model_name="livestock",
            name="livestock_category_type_wo",
        ),
        migrations.AddField(
            model_name="livestock",
            name="livestock_category_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_livestock_category_type",
                to="api.livestockcategorytype",
            ),
        ),
    ]
