# Generated by Django 4.2.1 on 2024-01-31 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0310_remove_livestock_livestock_category_type_start_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinorSeasonPerennialCropping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_year", models.IntegerField(default=1)),
                ("is_biomass_burned_start", models.BooleanField(blank=True, null=True)),
                ("is_biomass_burned_w", models.BooleanField(blank=True, null=True)),
                ("is_biomass_burned_wo", models.BooleanField(blank=True, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("crop_yield_start", models.FloatField(blank=True, null=True)),
                ("crop_yield_w", models.FloatField(blank=True, null=True)),
                ("crop_yield_wo", models.FloatField(blank=True, null=True)),
                ("ag_t2_start", models.FloatField(blank=True, null=True)),
                ("ag_t2_w", models.FloatField(blank=True, null=True)),
                ("ag_t2_wo", models.FloatField(blank=True, null=True)),
                ("agb_max_t2_start", models.FloatField(blank=True, null=True)),
                ("agb_max_t2_w", models.FloatField(blank=True, null=True)),
                ("agb_max_t2_wo", models.FloatField(blank=True, null=True)),
                ("bg_t2_start", models.FloatField(blank=True, null=True)),
                ("bg_t2_w", models.FloatField(blank=True, null=True)),
                ("bg_t2_wo", models.FloatField(blank=True, null=True)),
                ("soc_t2_start", models.FloatField(blank=True, null=True)),
                ("soc_t2_w", models.FloatField(blank=True, null=True)),
                ("soc_t2_wo", models.FloatField(blank=True, null=True)),
                ("tillage_factor_t2_start", models.FloatField(blank=True, null=True)),
                ("tillage_factor_t2_w", models.FloatField(blank=True, null=True)),
                ("tillage_factor_t2_wo", models.FloatField(blank=True, null=True)),
                ("input_factor_t2_start", models.FloatField(blank=True, null=True)),
                ("input_factor_t2_w", models.FloatField(blank=True, null=True)),
                ("input_factor_t2_wo", models.FloatField(blank=True, null=True)),
                ("residue_burned_t2_start", models.FloatField(blank=True, null=True)),
                ("residue_burned_t2_w", models.FloatField(blank=True, null=True)),
                ("residue_burned_t2_wo", models.FloatField(blank=True, null=True)),
                ("fire_periodicity_t2_start", models.FloatField(blank=True, null=True)),
                ("fire_periodicity_t2_w", models.FloatField(blank=True, null=True)),
                ("fire_periodicity_t2_wo", models.FloatField(blank=True, null=True)),
                ("flu_t2_start", models.FloatField(blank=True, null=True)),
                ("flu_t2_w", models.FloatField(blank=True, null=True)),
                ("flu_t2_wo", models.FloatField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="api.activity",
                    ),
                ),
                (
                    "crop_yield_thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_crop_yield_thread",
                        to="api.commentthread",
                    ),
                ),
                (
                    "is_biomass_burned_thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_is_biomass_burned_thread",
                        to="api.commentthread",
                    ),
                ),
                (
                    "notes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="api.note",
                    ),
                ),
                (
                    "organic_input_type_start",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_organic_input_type_start",
                        to="api.organicinputtype",
                    ),
                ),
                (
                    "organic_input_type_thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_organic_input_type_thread",
                        to="api.commentthread",
                    ),
                ),
                (
                    "organic_input_type_w",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_organic_input_type_w",
                        to="api.organicinputtype",
                    ),
                ),
                (
                    "organic_input_type_wo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_organic_input_type_wo",
                        to="api.organicinputtype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minor_seasons",
                        to="api.perennialcropping",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.statustype",
                    ),
                ),
                (
                    "tillage_management_type_start",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_tillage_management_type_start",
                        to="api.tillagemanagementtype",
                    ),
                ),
                (
                    "tillage_management_type_thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_tillage_management_type_thread",
                        to="api.commentthread",
                    ),
                ),
                (
                    "tillage_management_type_w",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_tillage_management_type_w",
                        to="api.tillagemanagementtype",
                    ),
                ),
                (
                    "tillage_management_type_wo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_tillage_management_type_wo",
                        to="api.tillagemanagementtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
