# Generated by Django 4.2.1 on 2024-01-31 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0311_minorseasonperennialcropping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="minorseasonperennialcropping",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="minorseasonperennialcropping",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="minorseasonperennialcropping",
            name="start_year",
        ),
        migrations.RemoveField(
            model_name="minorseasonperennialcropping",
            name="status",
        ),
    ]
