# Generated by Django 4.2.1 on 2024-01-31 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0312_remove_minorseasonperennialcropping_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="minorseasonperennialcropping",
            name="fi_t2_start",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minorseasonperennialcropping",
            name="fi_t2_w",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minorseasonperennialcropping",
            name="fi_t2_wo",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minorseasonperennialcropping",
            name="fmg_t2_start",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minorseasonperennialcropping",
            name="fmg_t2_w",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minorseasonperennialcropping",
            name="fmg_t2_wo",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minorseasonperennialcropping",
            name="land_use_change",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="api.landusechange",
            ),
        ),
        migrations.AddField(
            model_name="minorseasonperennialcropping",
            name="land_use_type_start",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_land_use_type_start",
                to="api.landusetype",
            ),
        ),
        migrations.AddField(
            model_name="minorseasonperennialcropping",
            name="land_use_type_thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_land_use_type_thread",
                to="api.commentthread",
            ),
        ),
        migrations.AddField(
            model_name="minorseasonperennialcropping",
            name="land_use_type_w",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_land_use_type_w",
                to="api.landusetype",
            ),
        ),
        migrations.AddField(
            model_name="minorseasonperennialcropping",
            name="land_use_type_wo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_land_use_type_wo",
                to="api.landusetype",
            ),
        ),
    ]
