# Generated by Django 4.2.1 on 2024-02-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0314_remove_minorseasonfloodedrice_activity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disturbancetype",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="disturbancetype",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="disturbancetype",
            name="soc_t2_start",
        ),
        migrations.RemoveField(
            model_name="disturbancetype",
            name="soc_t2_w",
        ),
        migrations.RemoveField(
            model_name="disturbancetype",
            name="soc_t2_wo",
        ),
        migrations.RemoveField(
            model_name="disturbancetype",
            name="start_year",
        ),
        migrations.RemoveField(
            model_name="disturbancetype",
            name="status",
        ),
        migrations.AlterField(
            model_name="forestdisturbance",
            name="forest_management",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disturbances",
                to="api.forestmanagement",
            ),
        ),
    ]
