# Generated by Django 4.2.1 on 2024-02-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0315_remove_disturbancetype_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soiltype",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
