# Generated by Django 4.2.1 on 2024-02-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0316_soiltype_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualcropping",
            name="crop_yield_start",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="annualcropping",
            name="crop_yield_w",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="annualcropping",
            name="crop_yield_wo",
            field=models.FloatField(default=0),
        ),
    ]
