# Generated by Django 4.2.1 on 2024-02-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0317_alter_annualcropping_crop_yield_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landusetype",
            name="regions",
            field=models.ManyToManyField(
                related_name="land_use_types", to="api.region"
            ),
        ),
    ]
