# Generated by Django 4.2.1 on 2024-02-12 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0318_landusetype_regions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landusetype",
            name="regions",
        ),
    ]
