# Generated by Django 4.2.1 on 2024-02-13 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0319_remove_landusetype_regions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("can_view_modules", "Can view modules"),
                    ("can_create_modules", "Can create modules"),
                    ("can_change_modules", "Can edit modules"),
                    ("can_delete_modules", "Can delete modules"),
                )
            },
        ),
    ]
