# Annual Cropland
DEFAULT_FIRE_PERIODICITY = 1

# Grassland
DEFAULT_COMBUSTION_FACTOR = .77

# Large Fishery
LOST_REFRIGERANT_DEFAULT = .48734
TONNES_ICE_DEFAULT = 2.8
KW_TONNES = 60

# Small Fishery
LOST_REFRIGERANT_DEFAULT = .083
TONNES_ICE_DEFAULT = 2.8
KW_TONNES = 60