# Annual Cropland
DEFAULT_FIRE_PERIODICITY = 1

# Grassland
DEFAULT_COMBUSTION_FACTOR = .77

# Large Fishery
LOST_REFRIGERANT_DEFAULT = .48734
TONNES_ICE_DEFAULT = 2.8
KW_TONNES = 60

# Small Fishery
LOST_REFRIGERANT_DEFAULT = .083
TONNES_ICE_DEFAULT = 2.8
KW_TONNES = 60

# Aquaculture
NITROUS_EF_DEFAULT = .00169

# Feed Input
FEED_EF_DEFAULT = 0

# Coastal Wetland
PERCENTAGE_C_LOST_EXCAVATION = .96