# Generated by Django 4.2.1 on 2025-04-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=255)),
                ('moisture', models.CharField(max_length=255)),
                ('soil_type', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('changes', models.JSONField()),
            ],
        ),
    ]
