# Generated by Django 4.2.1 on 2025-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsModuleTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('from_value', models.FloatField()),
                ('to_value', models.FloatField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('q1', models.FloatField()),
                ('q3', models.FloatField()),
            ],
        ),
    ]
