# Generated by Django 4.2.1 on 2025-04-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0002_statisticsmoduletotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsmoduletotal',
            name='from_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='statisticsmoduletotal',
            name='to_value',
            field=models.CharField(max_length=255),
        ),
    ]
