# Generated by Django 4.2.1 on 2025-08-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0003_alter_statisticsmoduletotal_from_value_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statisticsmoduletotal',
            unique_together={('module_type', 'field', 'from_value', 'to_value')},
        ),
    ]
