# Generated by Django 4.2.1 on 2025-08-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0004_alter_statisticsmoduletotal_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statisticsmoduletotal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='statisticsmoduletotal',
            name='climate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statisticsmoduletotal',
            name='moisture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statisticsmoduletotal',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statisticsmoduletotal',
            name='soil_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='statisticsmoduletotal',
            unique_together={('module_type', 'field', 'from_value', 'to_value', 'region', 'climate', 'moisture', 'soil_type')},
        ),
    ]
