# Generated by Django 4.2.1 on 2025-08-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0005_alter_statisticsmoduletotal_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionStatisticsByModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(max_length=255)),
                ('total', models.FloatField()),
            ],
        ),
    ]
