# Generated by Django 4.2.1 on 2025-08-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0006_emissionstatisticsbymodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionstatisticsbymodule',
            name='climate',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionstatisticsbymodule',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionstatisticsbymodule',
            name='max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionstatisticsbymodule',
            name='mean',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionstatisticsbymodule',
            name='median',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionstatisticsbymodule',
            name='min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionstatisticsbymodule',
            name='moisture',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionstatisticsbymodule',
            name='q1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionstatisticsbymodule',
            name='q3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionstatisticsbymodule',
            name='region',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionstatisticsbymodule',
            name='soil_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='emissionstatisticsbymodule',
            unique_together={('module_type', 'region', 'climate', 'moisture', 'soil_type')},
        ),
    ]
