# Generated by Django 4.2.1 on 2025-08-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0007_emissionstatisticsbymodule_climate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockChangeAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('from_value', models.CharField(max_length=255)),
                ('to_value', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('climate', models.CharField(blank=True, max_length=255, null=True)),
                ('moisture', models.CharField(blank=True, max_length=255, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=255, null=True)),
                ('livestock_category_type', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField()),
                ('sum_total', models.FloatField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('q1', models.FloatField()),
                ('q3', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['field'], name='minitool_li_field_d71849_idx'), models.Index(fields=['region'], name='minitool_li_region_51bf6f_idx'), models.Index(fields=['climate'], name='minitool_li_climate_19e38c_idx'), models.Index(fields=['moisture'], name='minitool_li_moistur_a7a7b6_idx'), models.Index(fields=['soil_type'], name='minitool_li_soil_ty_28e83d_idx'), models.Index(fields=['livestock_category_type'], name='minitool_li_livesto_dea157_idx')],
                'unique_together': {('field', 'from_value', 'to_value', 'region', 'climate', 'moisture', 'soil_type', 'livestock_category_type')},
            },
        ),
        migrations.CreateModel(
            name='LivestockChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(default='Livestock', max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=255)),
                ('moisture', models.CharField(max_length=255)),
                ('soil_type', models.CharField(max_length=255)),
                ('livestock_category_type', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('field', models.CharField(max_length=255)),
                ('from_value', models.CharField(max_length=255)),
                ('to_value', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['module_type'], name='minitool_li_module__292f1c_idx'), models.Index(fields=['region'], name='minitool_li_region_66a63a_idx'), models.Index(fields=['climate'], name='minitool_li_climate_155695_idx'), models.Index(fields=['moisture'], name='minitool_li_moistur_b8d8b7_idx'), models.Index(fields=['soil_type'], name='minitool_li_soil_ty_9a317f_idx'), models.Index(fields=['livestock_category_type'], name='minitool_li_livesto_2fdcbf_idx'), models.Index(fields=['field'], name='minitool_li_field_61531f_idx')],
                'unique_together': {('module_type', 'region', 'climate', 'moisture', 'soil_type', 'livestock_category_type', 'field', 'from_value', 'to_value')},
            },
        ),
    ]
