# Generated by Django 4.2.1 on 2025-08-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0008_livestockchangeaggregate_livestockchange'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='livestockchange',
            unique_together={('module_type', 'region', 'climate', 'moisture', 'soil_type', 'field', 'from_value', 'to_value')},
        ),
        migrations.AddField(
            model_name='livestockchange',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='livestockchangeaggregate',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='livestockchange',
            name='livestock_category_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
