# Generated by Django 4.2.1 on 2025-08-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0009_alter_livestockchange_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='livestockchange',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='livestockchangeaggregate',
            name='additional_data',
        ),
        migrations.AlterField(
            model_name='livestockchange',
            name='livestock_category_type',
            field=models.CharField(default='ao', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestockchangeaggregate',
            name='livestock_category_type',
            field=models.CharField(default='ao', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='livestockchange',
            unique_together={('module_type', 'region', 'climate', 'moisture', 'soil_type', 'livestock_category_type', 'field', 'from_value', 'to_value')},
        ),
        migrations.CreateModel(
            name='GrasslandChangeAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('from_value', models.CharField(max_length=255)),
                ('to_value', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('climate', models.CharField(blank=True, max_length=255, null=True)),
                ('moisture', models.CharField(blank=True, max_length=255, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField()),
                ('sum_total', models.FloatField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('q1', models.FloatField()),
                ('q3', models.FloatField()),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['field'], name='minitool_gr_field_955b4c_idx'), models.Index(fields=['region'], name='minitool_gr_region_45a767_idx'), models.Index(fields=['climate'], name='minitool_gr_climate_9cb949_idx'), models.Index(fields=['moisture'], name='minitool_gr_moistur_1fe7c5_idx'), models.Index(fields=['soil_type'], name='minitool_gr_soil_ty_3020fc_idx')],
                'unique_together': {('field', 'from_value', 'to_value', 'region', 'climate', 'moisture', 'soil_type')},
            },
        ),
        migrations.CreateModel(
            name='GrasslandChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=255)),
                ('moisture', models.CharField(max_length=255)),
                ('soil_type', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('field', models.CharField(max_length=255)),
                ('from_value', models.CharField(max_length=255)),
                ('to_value', models.CharField(max_length=255)),
                ('module_type', models.CharField(default='Grassland', max_length=255)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['module_type'], name='minitool_gr_module__4d4175_idx'), models.Index(fields=['region'], name='minitool_gr_region_f56f37_idx'), models.Index(fields=['climate'], name='minitool_gr_climate_83a2e5_idx'), models.Index(fields=['moisture'], name='minitool_gr_moistur_683b10_idx'), models.Index(fields=['soil_type'], name='minitool_gr_soil_ty_527ed1_idx'), models.Index(fields=['field'], name='minitool_gr_field_97a22b_idx')],
                'unique_together': {('module_type', 'region', 'climate', 'moisture', 'soil_type', 'field', 'from_value', 'to_value')},
            },
        ),
        migrations.CreateModel(
            name='FloodedRiceChangeAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('from_value', models.CharField(max_length=255)),
                ('to_value', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('climate', models.CharField(blank=True, max_length=255, null=True)),
                ('moisture', models.CharField(blank=True, max_length=255, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField()),
                ('sum_total', models.FloatField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('q1', models.FloatField()),
                ('q3', models.FloatField()),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['field'], name='minitool_fl_field_5035a1_idx'), models.Index(fields=['region'], name='minitool_fl_region_2bf6d7_idx'), models.Index(fields=['climate'], name='minitool_fl_climate_9d42df_idx'), models.Index(fields=['moisture'], name='minitool_fl_moistur_203736_idx'), models.Index(fields=['soil_type'], name='minitool_fl_soil_ty_29b628_idx')],
                'unique_together': {('field', 'from_value', 'to_value', 'region', 'climate', 'moisture', 'soil_type')},
            },
        ),
        migrations.CreateModel(
            name='FloodedRiceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=255)),
                ('moisture', models.CharField(max_length=255)),
                ('soil_type', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('field', models.CharField(max_length=255)),
                ('from_value', models.CharField(max_length=255)),
                ('to_value', models.CharField(max_length=255)),
                ('module_type', models.CharField(default='Flooded Rice', max_length=255)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['module_type'], name='minitool_fl_module__a31e4d_idx'), models.Index(fields=['region'], name='minitool_fl_region_849890_idx'), models.Index(fields=['climate'], name='minitool_fl_climate_c06aab_idx'), models.Index(fields=['moisture'], name='minitool_fl_moistur_c3b6ac_idx'), models.Index(fields=['soil_type'], name='minitool_fl_soil_ty_b81b2d_idx'), models.Index(fields=['field'], name='minitool_fl_field_d6acff_idx')],
                'unique_together': {('module_type', 'region', 'climate', 'moisture', 'soil_type', 'field', 'from_value', 'to_value')},
            },
        ),
        migrations.CreateModel(
            name='AnnualCroplandChangeAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('from_value', models.CharField(max_length=255)),
                ('to_value', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('climate', models.CharField(blank=True, max_length=255, null=True)),
                ('moisture', models.CharField(blank=True, max_length=255, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField()),
                ('sum_total', models.FloatField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('q1', models.FloatField()),
                ('q3', models.FloatField()),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['field'], name='minitool_an_field_b8e001_idx'), models.Index(fields=['region'], name='minitool_an_region_0fe211_idx'), models.Index(fields=['climate'], name='minitool_an_climate_c32158_idx'), models.Index(fields=['moisture'], name='minitool_an_moistur_1fb761_idx'), models.Index(fields=['soil_type'], name='minitool_an_soil_ty_eadb41_idx')],
                'unique_together': {('field', 'from_value', 'to_value', 'region', 'climate', 'moisture', 'soil_type')},
            },
        ),
        migrations.CreateModel(
            name='AnnualCroplandChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=255)),
                ('moisture', models.CharField(max_length=255)),
                ('soil_type', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('field', models.CharField(max_length=255)),
                ('from_value', models.CharField(max_length=255)),
                ('to_value', models.CharField(max_length=255)),
                ('module_type', models.CharField(default='Annual Cropland', max_length=255)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['module_type'], name='minitool_an_module__e0468b_idx'), models.Index(fields=['region'], name='minitool_an_region_723d4a_idx'), models.Index(fields=['climate'], name='minitool_an_climate_fb10e1_idx'), models.Index(fields=['moisture'], name='minitool_an_moistur_a40370_idx'), models.Index(fields=['soil_type'], name='minitool_an_soil_ty_2a3735_idx'), models.Index(fields=['field'], name='minitool_an_field_30d3ac_idx')],
                'unique_together': {('module_type', 'region', 'climate', 'moisture', 'soil_type', 'field', 'from_value', 'to_value')},
            },
        ),
        migrations.RemoveField(
            model_name='livestockchange',
            name='additional_data',
        ),
    ]
