# Generated by Django 4.2.1 on 2025-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0010_alter_livestockchange_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annualcroplandchange',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='annualcroplandchangeaggregate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='floodedricechange',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='floodedricechangeaggregate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='grasslandchange',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='grasslandchangeaggregate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='livestockchange',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='livestockchangeaggregate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='annualcroplandchange',
            name='custom_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='annualcroplandchangeaggregate',
            name='custom_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='floodedricechange',
            name='custom_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='floodedricechangeaggregate',
            name='custom_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='grasslandchange',
            name='custom_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='grasslandchangeaggregate',
            name='custom_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='livestockchange',
            name='custom_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='livestockchangeaggregate',
            name='custom_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='annualcroplandchange',
            unique_together={('module_type', 'region', 'climate', 'moisture', 'soil_type', 'field', 'from_value', 'to_value', 'custom_filters')},
        ),
        migrations.AlterUniqueTogether(
            name='annualcroplandchangeaggregate',
            unique_together={('field', 'from_value', 'to_value', 'region', 'climate', 'moisture', 'soil_type', 'custom_filters')},
        ),
        migrations.AlterUniqueTogether(
            name='floodedricechange',
            unique_together={('module_type', 'region', 'climate', 'moisture', 'soil_type', 'field', 'from_value', 'to_value', 'custom_filters')},
        ),
        migrations.AlterUniqueTogether(
            name='floodedricechangeaggregate',
            unique_together={('field', 'from_value', 'to_value', 'region', 'climate', 'moisture', 'soil_type', 'custom_filters')},
        ),
        migrations.AlterUniqueTogether(
            name='grasslandchange',
            unique_together={('module_type', 'region', 'climate', 'moisture', 'soil_type', 'field', 'from_value', 'to_value', 'custom_filters')},
        ),
        migrations.AlterUniqueTogether(
            name='grasslandchangeaggregate',
            unique_together={('field', 'from_value', 'to_value', 'region', 'climate', 'moisture', 'soil_type', 'custom_filters')},
        ),
        migrations.AlterUniqueTogether(
            name='livestockchange',
            unique_together={('module_type', 'region', 'climate', 'moisture', 'soil_type', 'livestock_category_type', 'field', 'from_value', 'to_value', 'custom_filters')},
        ),
        migrations.AlterUniqueTogether(
            name='livestockchangeaggregate',
            unique_together={('field', 'from_value', 'to_value', 'region', 'climate', 'moisture', 'soil_type', 'livestock_category_type', 'custom_filters')},
        ),
    ]
