# Generated by Django 4.2.1 on 2025-08-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minitool", "0011_alter_annualcroplandchange_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("module_type", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("climate", models.CharField(max_length=255)),
                ("moisture", models.CharField(max_length=255)),
                ("soil_type", models.CharField(max_length=255)),
                ("total", models.FloatField()),
                ("field", models.CharField(max_length=255)),
                ("from_value", models.CharField(max_length=255)),
                ("to_value", models.CharField(max_length=255)),
                ("custom_filters", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RenameModel(
            old_name="FloodedRiceChangeAggregate",
            new_name="ChangeAggregate",
        ),
        migrations.DeleteModel(
            name="AnnualCroplandChange",
        ),
        migrations.DeleteModel(
            name="AnnualCroplandChangeAggregate",
        ),
        migrations.DeleteModel(
            name="FloodedRiceChange",
        ),
        migrations.DeleteModel(
            name="GrasslandChange",
        ),
        migrations.DeleteModel(
            name="GrasslandChangeAggregate",
        ),
        migrations.DeleteModel(
            name="LivestockChange",
        ),
        migrations.DeleteModel(
            name="LivestockChangeAggregate",
        ),
        migrations.CreateModel(
            name="BaseChangeAggregate",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("minitool.changeaggregate",),
        ),
        migrations.CreateModel(
            name="FloodedRiceChangeAggregate",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("minitool.changeaggregate",),
        ),
        migrations.RenameIndex(
            model_name="changeaggregate",
            new_name="minitool_ch_field_d27d1f_idx",
            old_name="minitool_fl_field_5035a1_idx",
        ),
        migrations.RenameIndex(
            model_name="changeaggregate",
            new_name="minitool_ch_region_55bed3_idx",
            old_name="minitool_fl_region_2bf6d7_idx",
        ),
        migrations.RenameIndex(
            model_name="changeaggregate",
            new_name="minitool_ch_climate_ed1926_idx",
            old_name="minitool_fl_climate_9d42df_idx",
        ),
        migrations.RenameIndex(
            model_name="changeaggregate",
            new_name="minitool_ch_moistur_b1206a_idx",
            old_name="minitool_fl_moistur_203736_idx",
        ),
        migrations.RenameIndex(
            model_name="changeaggregate",
            new_name="minitool_ch_soil_ty_68087b_idx",
            old_name="minitool_fl_soil_ty_29b628_idx",
        ),
        migrations.AddIndex(
            model_name="changeaggregate",
            index=models.Index(fields=["custom_filters"], name="changeaggregate_custom_idx"),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["module_type"], name="minitool_ch_module__67bf85_idx"),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["region"], name="minitool_ch_region_a81cfc_idx"),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["climate"], name="minitool_ch_climate_b83624_idx"),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["moisture"], name="minitool_ch_moistur_55f13b_idx"),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["soil_type"], name="minitool_ch_soil_ty_5961ce_idx"),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["field"], name="minitool_ch_field_3c327d_idx"),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["custom_filters"], name="changerecord_custom_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="changerecord",
            unique_together={("module_type", "region", "climate", "moisture", "soil_type", "field", "from_value", "to_value", "custom_filters")},
        ),
        migrations.CreateModel(
            name="AnnualCroplandChange",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("minitool.changerecord",),
        ),
        migrations.CreateModel(
            name="AnnualCroplandChangeAggregate",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("minitool.changeaggregate",),
        ),
        migrations.CreateModel(
            name="BaseChange",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("minitool.changerecord",),
        ),
        migrations.CreateModel(
            name="FloodedRiceChange",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("minitool.changerecord",),
        ),
        migrations.CreateModel(
            name="GrasslandChange",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("minitool.changerecord",),
        ),
        migrations.CreateModel(
            name="GrasslandChangeAggregate",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("minitool.changeaggregate",),
        ),
        migrations.CreateModel(
            name="LivestockChange",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("minitool.changerecord",),
        ),
        migrations.CreateModel(
            name="LivestockChangeAggregate",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("minitool.changeaggregate",),
        ),
    ]
