# Generated by Django 4.2.1 on 2025-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0013_changerecord_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changeaggregate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='changeaggregate',
            name='module_type',
            field=models.CharField(default='Livestock', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='changeaggregate',
            unique_together={('module_type', 'field', 'from_value', 'to_value', 'region', 'climate', 'moisture', 'soil_type', 'custom_filters')},
        ),
        migrations.AddIndex(
            model_name='changeaggregate',
            index=models.Index(fields=['module_type'], name='minitool_ch_module__4ab003_idx'),
        ),
    ]
