# Generated by Django 4.2.1 on 2025-08-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0014_alter_changeaggregate_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_type', models.CharField(max_length=255)),
                ('changes', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='AnnualCroplandChange',
        ),
        migrations.DeleteModel(
            name='AnnualCroplandChangeAggregate',
        ),
        migrations.DeleteModel(
            name='BaseChange',
        ),
        migrations.DeleteModel(
            name='BaseChangeAggregate',
        ),
        migrations.DeleteModel(
            name='FloodedRiceChange',
        ),
        migrations.DeleteModel(
            name='FloodedRiceChangeAggregate',
        ),
        migrations.DeleteModel(
            name='GrasslandChange',
        ),
        migrations.DeleteModel(
            name='GrasslandChangeAggregate',
        ),
        migrations.DeleteModel(
            name='LivestockChange',
        ),
        migrations.DeleteModel(
            name='LivestockChangeAggregate',
        ),
    ]
