# Generated by Django 4.2.1 on 2025-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0015_emissionscenario_delete_annualcroplandchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionscenario',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
