# Generated by Django 4.2.1 on 2025-10-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0017_scenariocategory_emissionscenario_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScenarioCategory',
            new_name='EmissionScenarioCategory',
        ),
    ]
