# Generated by Django 4.2.1 on 2025-10-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0018_rename_scenariocategory_emissionscenariocategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionscenario',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmissionScenarioCategory',
        ),
    ]
