# Generated by Django 4.2.1 on 2025-10-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0021_alter_emissionscenario_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionscenario',
            name='category',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmissionScenarioCategory',
        ),
    ]
