# Generated by Django 4.2.1 on 2025-10-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0023_emissionscenariocategory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='changerecord',
            name='csv_row_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='changerecord',
            unique_together={('module_type', 'region', 'climate', 'moisture', 'soil_type', 'field', 'from_value', 'to_value', 'custom_filters', 'csv_row_data')},
        ),
        migrations.AddIndex(
            model_name='changerecord',
            index=models.Index(fields=['csv_row_data'], name='changerecord_csvdata_idx'),
        ),
    ]
