# Generated by Django 4.2.1 on 2025-10-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0023_emissionscenariocategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionscenario',
            name='module_type',
        ),
    ]
