# Generated by Django 4.2.1 on 2025-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minitool', '0024_alter_changerecord_unique_together_and_more'),
        ('minitool', '0024_remove_emissionscenario_module_type'),
    ]

    operations = [
    ]
