import os

from datetime import timedelta
from pathlib import Path
import json
import base64

import firebase_admin
from dotenv import load_dotenv

"""
Django settings for djangoexact project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

load_dotenv()

app_mode = os.getenv("APP_MODE", None)
if app_mode:
    print(f"Running in {app_mode} mode")
    dotenv_file = os.path.join(os.path.dirname(os.path.dirname(__file__)), "djangoexact", f".env.{app_mode}")
    load_dotenv(dotenv_file)
    FRONTEND_URL = "https://exact.review.fao.org" if app_mode == "review" else "https://exact.apps.fao.org"
else:
    FRONTEND_URL = "https://exact.review.fao.org" if os.getenv("BRANCH_NAME") == "review" else "https://exact.apps.fao.org"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes")

# SECURITY WARNING: keep the secret key used in production secret!
# Fail fast in non-DEBUG environments when SECRET_KEY is not provided.
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-do-not-use-in-production"
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured("SECRET_KEY environment variable is required when DEBUG is False.")

_default_hosts = "localhost,127.0.0.1,0.0.0.0"
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", _default_hosts).split(",") if h.strip()]

# CORS: allow-all only in development; production deployments must set CORS_ALLOWED_ORIGINS explicitly.
CORS_ORIGIN_ALLOW_ALL = DEBUG
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()]


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "modeltranslation",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "drf_yasg",
    "django_extensions",
    "django_archive",
    "auditlog",
    "rest_framework",
    "django_filters",
    "accounts",
    "simple_history",
    "ipcc",
    "api",
    "public",
    "blog",
    "ckeditor",
    "minitool",
    "admin_scripts",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # "accounts.middleware.FirebaseAuthenticationMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "minitool.middleware.DatabaseConnectionMiddleware",  # Add connection cleanup middleware
]

ROOT_URLCONF = "djangoexact.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoexact.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

if os.getenv("GAE_APPLICATION", None):
    # Running on production App Engine, so connect to Google Cloud SQL using
    # the unix socket at /cloudsql/<your-cloudsql-connection string>
    DATABASES = {
        "default": {
            "ENGINE": "$DB_ENGINE",
            "HOST": "/cloudsql/$DB_INSTANCE_CONNECTION",
            "USER": "$DB_USERNAME",
            "PASSWORD": "$DB_PASSWORD",
            "NAME": "$DB_NAME",
            "TEST": {
                "NAME": "$DB_NAME",
            },
            "OPTIONS": {
                "connect_timeout": 30,  # Optional: set timeout
                "application_name": "djangoexact",  # Help identify connections
            },
            "CONN_MAX_AGE": 0,  # Close connections immediately after use
            "ATOMIC_REQUESTS": False,  # Disable automatic transactions
        },
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": os.getenv("DB_ENGINE", default="$DB_ENGINE"),
            "HOST": os.getenv("DB_HOST", default="$DB_HOST"),
            "USER": os.getenv("DB_USER", default="$DB_USERNAME"),
            "PASSWORD": os.getenv("DB_PASSWORD", default="$DB_PASSWORD"),
            "NAME": os.getenv("DB_NAME", default="$DB_NAME"),
            "PORT": os.getenv("DB_PORT", default="$DB_PORT"),
            "OPTIONS": {
                "connect_timeout": 30,  # Optional: set timeout
                "application_name": "djangoexact",  # Help identify connections
            },
            "CONN_MAX_AGE": 0,  # Close connections immediately after use
            "ATOMIC_REQUESTS": False,  # Disable automatic transactions
        },
    }
    if os.getenv("CI", "").lower() == "true":
        # CI only: reuse the pre-seeded database via `manage.py test --keepdb`.
        # GitHub Actions always sets CI=true. Outside CI, Django's default
        # test_<name> database is used, so a local `manage.py test` can never
        # drop or flush the developer's real database.
        DATABASES["default"]["TEST"] = {"NAME": os.getenv("DB_NAME", default="$DB_NAME")}

DATABASE_ROUTERS = ["ipcc.db_router.AppSpecificDatabaseRouter", "api.db_router.AppSpecificDatabaseRouter"]

# Database connection management
DATABASE_CONNECTION_POOLING = True

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/


TIME_ZONE = "UTC"

USE_I18N = True
LANGUAGE_CODE = "en"
LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]
LANGUAGES = [
    ("en", "English"),
    ("fr", "French"),
    ("es", "Spanish"),
    ("ru", "Russian"),
]

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATIC_URL = "/static/"

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # "rest_framework.authentication.BasicAuthentication",
        # "rest_framework.authentication.SessionAuthentication",
        # "rest_framework_simplejwt.authentication.JWTAuthentication",
        "accounts.firebase.FirebaseAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/min",
        "user": "1000/min",
    },
}

# Auditlog Settings
AUDITLOG_INCLUDE_ALL_MODELS = True
AUDITLOG_EXCLUDE_TRACKING_FIELDS = ("created", "modified")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "TOKEN_OBTAIN_SERIALIZER": "accounts.serializers.MyTokenObtainPairSerializer",
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname} {asctime}] {module} \t {message}",
            "style": "{",
        },
    },
}

APPEND_SLASH = False

AUTH_USER_MODEL = "api.CustomUser"

ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "$EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT", "$EMAIL_PORT")
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("SMTP_USER_EMAIL", "$SMTP_USER_EMAIL")
EMAIL_HOST_PASSWORD = os.getenv("SMTP_USER_PASSWORD", "$SMTP_USER_PASSWORD")

# Firebase settings
try:
    FIREBASE_CONFIG = {
        "apiKey": os.getenv("FIREBASE_API_KEY", "$FIREBASE_API_KEY"),
        "authDomain": os.getenv("FIREBASE_AUTH_DOMAIN", "$FIREBASE_AUTH_DOMAIN"),
        "projectId": os.getenv("FIREBASE_PROJECT_ID", "$FIREBASE_PROJECT_ID"),
        "storageBucket": os.getenv("FIREBASE_STORAGE_BUCKET", "$FIREBASE_STORAGE_BUCKET"),
        "messagingSenderId": os.getenv("FIREBASE_MESSAGING_SENDER_ID", "$FIREBASE_MESSAGING_SENDER_ID"),
        "appId": os.getenv("FIREBASE_APP_ID", "$FIREBASE_APP_ID"),
        "measurementId": os.getenv("FIREBASE_MEASUREMENT_ID", "$FIREBASE_MEASUREMENT_ID"),
        "databaseURL": "",
        "serviceAccount": json.loads(base64.b64decode(os.getenv("FIREBASE_SERVICE_ACCOUNT", "$FIREBASE_SERVICE_ACCOUNT")).decode()),
    }

    from accounts.firebase_auth import FirebaseAuth
    auth = FirebaseAuth(FIREBASE_CONFIG["apiKey"])
    firebase_admin.initialize_app(firebase_admin.credentials.Certificate(FIREBASE_CONFIG["serviceAccount"]))
except Exception as e:
    raise Exception(f"Firebase config not found: {e}") from e

UNFOLD = {
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": True,  # Dropdown with all applications and models
    },
}

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"

STORAGE_BUCKET = os.getenv("STORAGE_BUCKET", "$STORAGE_BUCKET")
DEFAULT_FROM_EMAIL = os.getenv("SMTP_USER_EMAIL", "$SMTP_USER_EMAIL")

# Computation Jobs — Cloud Run
# Set to a Cloud Run Job resource name to enable GCP dispatch.
# Empty string = subprocess fallback (local dev).
CLOUD_RUN_COMPUTATION_JOB_NAME = os.environ.get("CLOUD_RUN_COMPUTATION_JOB_NAME", "")
CLOUD_RUN_REGION = os.environ.get("CLOUD_RUN_REGION", "europe-west1")

# Job Notifications
# Set to True to enable email notifications for completed jobs.
JOB_NOTIFICATIONS_ENABLED = os.environ.get("JOB_NOTIFICATIONS_ENABLED", "").lower() in ("true", "1", "yes")
