name: Django Exact

on:
  push:
    branches: [ review-testing-pipeline, review ]
  pull_request:
    branches: [ review ]

jobs:
  setup:
    runs-on: ubuntu-latest
    environment:
      name: review
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.11'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
  
  workspace_ops:
    needs: setup
    runs-on: ubuntu-latest
    environment:
      name: review   
    steps:
    - id: 'Auth_And_Deploy'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.PROJECT_KEYFILE }}
    - name: 'Set Up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'    

    - name: 'Get Clud SQL'
      run: |
        gcloud config set project ${{ vars.PROJECT_ID }} 
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        SDK_VERSION=420.0.0
        SDK_FILENAME=google-cloud-sdk-${SDK_VERSION}-linux-x86_64.tar.gz
        curl -O -J https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/${SDK_FILENAME}
        tar -zxvf ${SDK_FILENAME} --directory ${HOME}
        export PATH=${PATH}:${HOME}/google-cloud-sdk/bin

        sudo apt-get install wget
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        ./cloud_sql_proxy -instances=${{ vars.DB_INSTANCE_CONNECTION }}=tcp:${{ vars.DB_PORT }} > cloudsql.log 2>&1 &
         
        sleep 5

        # Ensure correct working directory
        cd $GITHUB_WORKSPACE
        echo 'Print work directory'
        pwd
        ls $GITHUB_WORKSPACE/djangoexact/
        
        sed -i 's|\$SERVICE_NAME|${{ vars.SERVICE_NAME }}|g' $GITHUB_WORKSPACE/djangoexact/app.yaml
        sed -i 's|\$PROJECT_ID|${{ vars.PROJECT_ID }}|g' $GITHUB_WORKSPACE/djangoexact/app.yaml
        sed -i 's|\$DB_ENGINE|${{ vars.DB_ENGINE }}|g' $GITHUB_WORKSPACE/djangoexact/app.yaml
        sed -i 's|\$DB_HOST|${{ vars.DB_HOST }}|g' $GITHUB_WORKSPACE/djangoexact/app.yaml
        sed -i 's|\$DB_USERNAME|${{ vars.DB_USERNAME }}|g' $GITHUB_WORKSPACE/djangoexact/app.yaml
        sed -i 's|\$DB_PASSWORD|${{ secrets.DB_PASSWORD }}|g' $GITHUB_WORKSPACE/djangoexact/app.yaml
        sed -i 's|\$DB_NAME|${{ vars.DB_NAME }}|g' $GITHUB_WORKSPACE/djangoexact/app.yaml
        sed -i 's|\$DB_PORT|${{ vars.DB_PORT }}|g' $GITHUB_WORKSPACE/djangoexact/app.yaml

        echo "$(cat djangoexact/app.yaml)"

        sed -i 's|\$DB_ENGINE|${{ vars.DB_ENGINE }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_INSTANCE_CONNECTION|${{ vars.DB_INSTANCE_CONNECTION }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_HOST|${{ vars.DB_HOST }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_USERNAME|${{ vars.DB_USERNAME  }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_PASSWORD|${{ secrets.DB_PASSWORD }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_NAME|${{ vars.DB_NAME }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_PORT|${{ vars.DB_PORT }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$ALLOWED_HOST|${{ vars.ALLOWED_HOST }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$SECRET_KEY|${{ secrets.SECRET_KEY }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\\\$EMAIL_HOST|${{ vars.EMAIL_HOST }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\\\$EMAIL_PORT|${{ vars.EMAIL_PORT }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\\\$SMTP_USER_EMAIL|${{ vars.SMTP_USER_EMAIL }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\\\$SMTP_USER_PASSWORD|${{ secrets.SMTP_USER_PASSWORD }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_API_KEY|${{ vars.FIREBASE_API_KEY }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_AUTH_DOMAIN|${{ vars.FIREBASE_AUTH_DOMAIN }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_PROJECT_ID|${{ vars.FIREBASE_PROJECT_ID }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_STORAGE_BUCKET|${{ vars.FIREBASE_STORAGE_BUCKET }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_MESSAGING_SENDER_ID|${{ vars.FIREBASE_MESSAGING_SENDER_ID }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_APP_ID|${{ vars.FIREBASE_APP_ID }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_MEASUREMENT_ID|${{ vars.FIREBASE_MEASUREMENT_ID }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_SERVICE_ACCOUNT|${{ vars.FIREBASE_SERVICE_ACCOUNT }}|g' djangoexact/djangoexact/settings.py

        echo "$(cat djangoexact/djangoexact/settings.py)"

        pip install -r djangoexact/requirements.txt

        python djangoexact/manage.py migrate
        python djangoexact/manage.py collectstatic --noinput

        pip list
        sed -i "s|127.0.0.1|${{ vars.SECONDARY_DB_PORT }}|g" djangoexact/djangoexact/settings.py

        gcloud config set project ${{ vars.PROJECT_ID }}
        gcloud app deploy djangoexact/app.yaml --project ${{ vars.PROJECT_ID }} --verbosity=debug
        gcloud app versions list --service=${{ vars.SERVICE_NAME }} --project=${{ vars.PROJECT_ID }} --format="value(version.id)" --sort-by="~version.createTime" | tail -n +100 | xargs -r gcloud app versions delete -q
  
#   deploy:
#     needs: setup
#     runs-on: ubuntu-latest
#     environment:
#       name: review
#     steps:
#     - id: 'Auth_And_Deploy'
#       uses: 'google-github-actions/auth@v2'
#       with:
#         credentials_json: ${{ secrets.PROJECT_KEYFILE }}
        
#     - name: 'Set Up Cloud SDK'
#       uses: 'google-github-actions/setup-gcloud@v2'
  
#     - name: 'Use gcloud CLI'
#       run: 'gcloud auth list --filter=status:ACTIVE --format="value(account)"' 
#     - name: 'gcloud deployment'
#       uses: actions/checkout@v4
#     - run: |
#         sed -i 's|\$SERVICE_NAME|${{ vars.SERVICE_NAME }}|g' djangoexact/app.yaml
#         sed -i 's|\$PROJECT_ID|${{ vars.PROJECT_ID }}|g' djangoexact/app.yaml
#         sed -i 's|\$DB_ENGINE|${{ vars.DB_ENGINE }}|g' djangoexact/app.yaml
#         sed -i 's|\$DB_HOST|${{ vars.DB_HOST }}|g' djangoexact/app.yaml
#         sed -i 's|\$DB_USERNAME|${{ vars.DB_USERNAME }}|g' djangoexact/app.yaml
#         sed -i 's|\$DB_PASSWORD|${{ secrets.DB_PASSWORD }}|g' djangoexact/app.yaml
#         sed -i 's|\$DB_NAME|${{ vars.DB_NAME }}|g' djangoexact/app.yaml
#         sed -i 's|\$DB_PORT|${{ vars.DB_PORT }}|g' djangoexact/app.yaml

#         echo "$(cat djangoexact/app.yaml)"

#         sed -i 's|\$DB_ENGINE|${{ vars.DB_ENGINE }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$DB_INSTANCE_CONNECTION|${{ vars.DB_INSTANCE_CONNECTION }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$DB_HOST|${{ vars.DB_HOST }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$DB_USERNAME|${{ vars.DB_USERNAME  }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$DB_PASSWORD|${{ secrets.DB_PASSWORD }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$DB_NAME|${{ vars.DB_NAME }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$DB_PORT|${{ vars.DB_PORT }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$ALLOWED_HOST|${{ vars.ALLOWED_HOST }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$SECRET_KEY|${{ secrets.SECRET_KEY }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\\\$EMAIL_HOST|${{ vars.EMAIL_HOST }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\\\$EMAIL_PORT|${{ vars.EMAIL_PORT }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\\\$SMTP_USER_EMAIL|${{ vars.SMTP_USER_EMAIL }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\\\$SMTP_USER_PASSWORD|${{ secrets.SMTP_USER_PASSWORD }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$FIREBASE_API_KEY|${{ vars.FIREBASE_API_KEY }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$FIREBASE_AUTH_DOMAIN|${{ vars.FIREBASE_AUTH_DOMAIN }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$FIREBASE_PROJECT_ID|${{ vars.FIREBASE_PROJECT_ID }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$FIREBASE_STORAGE_BUCKET|${{ vars.FIREBASE_STORAGE_BUCKET }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$FIREBASE_MESSAGING_SENDER_ID|${{ vars.FIREBASE_MESSAGING_SENDER_ID }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$FIREBASE_APP_ID|${{ vars.FIREBASE_APP_ID }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$FIREBASE_MEASUREMENT_ID|${{ vars.FIREBASE_MEASUREMENT_ID }}|g' djangoexact/djangoexact/settings.py
#         sed -i 's|\$FIREBASE_SERVICE_ACCOUNT|${{ vars.FIREBASE_SERVICE_ACCOUNT }}|g' djangoexact/djangoexact/settings.py

#         echo "$(cat djangoexact/djangoexact/settings.py)"

#         pip install -r djangoexact/requirements.txt

#         python djangoexact/manage.py migrate
#         python djangoexact/manage.py collectstatic --noinput

#         pip list
#         sed -i "s|127.0.0.1|${{ vars.SECONDARY_DB_PORT }}|g" djangoexact/djangoexact/settings.py

#         gcloud config set project ${{ vars.PROJECT_ID }}
#         gcloud app deploy djangoexact/app.yaml --project ${{ vars.PROJECT_ID }} --verbosity=debug
#         gcloud app versions list --service=${{ vars.SERVICE_NAME }} --project=${{ vars.PROJECT_ID }} --format="value(version.id)" --sort-by="~version.createTime" | tail -n +100 | xargs -r gcloud app versions delete -q