name: Django Exact

on:
  push:
    branches: [ review-testing-pipeline, review ]
  pull_request:
    branches: [ review ]

jobs:
  setup:
    runs-on: ubuntu-latest
    environment:
      name: review
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.11'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
  
  workspace_ops:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: review   
    steps:
      - uses: actions/checkout@v4
      # - id: 'Auth_And_Deploy'
      #   uses: 'google-github-actions/auth@v2'
      #   with:
      #     workload_identity_provider: 'projects/741920004150/locations/global/workloadIdentityPools/fao-exact-review-wip/providers/github'
      #     service_account: 'github-action-exact-django-web@fao-exact-review.iam.gserviceaccount.com'
          
      - name: Download Cloud SQL Proxy
        run: |
          sudo apt-get install wget
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy

      - name: Start Cloud SQL Proxy
        run: |
          ./cloud_sql_proxy -instances=${{ vars.DB_INSTANCE_CONNECTION }}=tcp:3306 > cloudsql.log 2>&1 &
          sleep 10  # Ensure the proxy is up
          echo 'cat cloudsql.log'
          cat cloudsql.log

      # - name: Save Cloud SQL Proxy as an artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: cloud_sql_proxy_log
      #     path: ./cloudsql.log
  
  deploy:
    needs: workspace_ops
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: review
    steps:
    # - id: 'Auth'
    #   uses: 'google-github-actions/auth@v2'
    #   with:
    #     credentials_json: ${{ secrets.PROJECT_KEYFILE }}
        
    - name: 'Set Up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
  
    # - name: 'Use gcloud CLI'
    #   run:  'gcloud auth list --filter=status:ACTIVE --format="value(account)"' 
    - name: 'gcloud deployment'
      uses: actions/checkout@v4
    # - name: Download Cloud SQL Proxy log artifact
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: cloud_sql_proxy_log 
         
    - run: |
        
        echo ${{ secrets.PROJECT_KEYFILE }} > /tmp/key-file.json
        gcloud auth activate-service-account --key-file /tmp/key-file.json
        sed -i 's|\$SERVICE_NAME|${{ vars.SERVICE_NAME }}|g' djangoexact/app.yaml
        sed -i 's|\$PROJECT_ID|${{ vars.PROJECT_ID }}|g' djangoexact/app.yaml
        sed -i 's|\$DB_ENGINE|${{ vars.DB_ENGINE }}|g' djangoexact/app.yaml
        sed -i 's|\$DB_HOST|${{ vars.DB_HOST }}|g' djangoexact/app.yaml
        sed -i 's|\$DB_USERNAME|${{ vars.DB_USERNAME }}|g' djangoexact/app.yaml
        sed -i 's|\$DB_PASSWORD|${{ secrets.DB_PASSWORD }}|g' djangoexact/app.yaml
        sed -i 's|\$DB_NAME|${{ vars.DB_NAME }}|g' djangoexact/app.yaml
        sed -i 's|\$DB_PORT|${{ vars.DB_PORT }}|g' djangoexact/app.yaml

        echo "$(cat djangoexact/app.yaml)"

        sed -i 's|\$DB_ENGINE|${{ vars.DB_ENGINE }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_INSTANCE_CONNECTION|${{ vars.DB_INSTANCE_CONNECTION }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_HOST|${{ vars.DB_HOST }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_USERNAME|${{ vars.DB_USERNAME  }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_PASSWORD|${{ secrets.DB_PASSWORD }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_NAME|${{ vars.DB_NAME }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$DB_PORT|${{ vars.DB_PORT }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$ALLOWED_HOST|${{ vars.ALLOWED_HOST }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$SECRET_KEY|${{ secrets.SECRET_KEY }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\\\$EMAIL_HOST|${{ vars.EMAIL_HOST }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\\\$EMAIL_PORT|${{ vars.EMAIL_PORT }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\\\$SMTP_USER_EMAIL|${{ vars.SMTP_USER_EMAIL }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\\\$SMTP_USER_PASSWORD|${{ secrets.SMTP_USER_PASSWORD }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_API_KEY|${{ vars.FIREBASE_API_KEY }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_AUTH_DOMAIN|${{ vars.FIREBASE_AUTH_DOMAIN }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_PROJECT_ID|${{ vars.FIREBASE_PROJECT_ID }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_STORAGE_BUCKET|${{ vars.FIREBASE_STORAGE_BUCKET }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_MESSAGING_SENDER_ID|${{ vars.FIREBASE_MESSAGING_SENDER_ID }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_APP_ID|${{ vars.FIREBASE_APP_ID }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_MEASUREMENT_ID|${{ vars.FIREBASE_MEASUREMENT_ID }}|g' djangoexact/djangoexact/settings.py
        sed -i 's|\$FIREBASE_SERVICE_ACCOUNT|${{ vars.FIREBASE_SERVICE_ACCOUNT }}|g' djangoexact/djangoexact/settings.py

        echo "$(cat djangoexact/djangoexact/settings.py)"

        pip install -r djangoexact/requirements.txt

        
        python djangoexact/manage.py collectstatic --noinput

        pip list
        sed -i "s|127.0.0.1|${{ vars.DB_HOST }}|g" djangoexact/djangoexact/settings.py

        gcloud app deploy djangoexact/app.yaml --project ${{ vars.PROJECT_ID }} --verbosity=debug
        gcloud app versions list --service=${{ vars.SERVICE_NAME }} --project=${{ vars.PROJECT_ID }} --format="value(version.id)" --sort-by="~version.createTime" | tail -n +100 | xargs -r gcloud app versions delete -q

     #line 138    python djangoexact/manage.py migrate