# Generated by Django 4.1.3 on 2022-11-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalWarmingPotential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('co2', models.FloatField()),
                ('ch4', models.FloatField()),
                ('n2o', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalBiomassAfterDefo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
        migrations.CreateModel(
            name='SoilOrganicCarbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
            ],
        ),
        migrations.CreateModel(
            name='SoilOrcanicCarbonCNRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('land_use_type', models.ForeignKey(limit_choices_to={'parent': None}, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
        migrations.CreateModel(
            name='NitrousEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('moisture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='LitterDeadwoodCarbonStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litter', models.FloatField()),
                ('dw', models.FloatField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
        migrations.CreateModel(
            name='LandUseStockExchangeFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('agroforestry_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultEmissionFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.input')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='DataOnMangroves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agb_dry_matter', models.FloatField()),
                ('c_fraction', models.FloatField()),
                ('agb_c', models.FloatField()),
                ('agb_growth', models.FloatField()),
                ('r', models.FloatField()),
                ('bgb', models.FloatField()),
                ('litter', models.FloatField()),
                ('dw', models.FloatField()),
                ('soc_ref', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='CombustionFactorValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField()),
                ('ch4', models.FloatField()),
                ('n2o', models.FloatField()),
                ('value', models.FloatField()),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
        migrations.CreateModel(
            name='BelowGroundBiomass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
        migrations.CreateModel(
            name='AboveGroundBiomass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
    ]
