# Generated by Django 4.2.1 on 2024-02-14 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalWarmingPotential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('co2', models.FloatField()),
                ('ch4', models.FloatField()),
                ('n2o', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrophicStateFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('chloa', models.FloatField()),
                ('trophic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trophictype')),
            ],
        ),
        migrations.CreateModel(
            name='TotalBiomassAfterDefo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('value', models.FloatField(null=True)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='TillageCarbonStockExchangeFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('tillage_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype')),
            ],
        ),
        migrations.CreateModel(
            name='SoilOrganicCarbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
            ],
        ),
        migrations.CreateModel(
            name='SoilOrcanicCarbonCNRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
        migrations.CreateModel(
            name='RoadEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('road_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roadtype')),
            ],
        ),
        migrations.CreateModel(
            name='RiceYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='RiceSFW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('water_management_type_after_cultivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watermanagementtypeaftercultivation')),
            ],
        ),
        migrations.CreateModel(
            name='RiceSFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('water_management_type_before_cultivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watermanagementtypebeforecultivation')),
            ],
        ),
        migrations.CreateModel(
            name='RiceSFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('organic_amendment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicamendmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='RiceDefaultEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivation_period', models.IntegerField()),
                ('value', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='RewettingMethaneFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('salinity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salinitytype')),
            ],
        ),
        migrations.CreateModel(
            name='RewettingCarbonFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='PerennialMaxAGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
        migrations.CreateModel(
            name='PerennialBGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='PerennialAGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='PeatExtractionEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(default=0)),
                ('co2_unit', models.CharField(default='tC/ha/yr', max_length=100)),
                ('doc', models.FloatField(default=0)),
                ('doc_unit', models.CharField(default='tC/ha/yr', max_length=100)),
                ('ch4', models.FloatField(default=0)),
                ('ch4_unit', models.CharField(default='kg CH4/ha/yr', max_length=100)),
                ('n2o', models.FloatField(default=0)),
                ('n2o_unit', models.CharField(default='kg N2O/ha/yr', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('peat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peattype')),
                ('site_location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitelocationtype')),
            ],
        ),
        migrations.CreateModel(
            name='PeatExtractionConversionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('weight_unit', models.CharField(default='tC/t air dry peat', max_length=100)),
                ('volume', models.FloatField(default=0)),
                ('volume_unit', models.CharField(default='tC/m3 air dry peat', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('peat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peattype')),
            ],
        ),
        migrations.CreateModel(
            name='OtherConstructedWaterbodiesEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('waterbody_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.waterbodytype')),
            ],
        ),
        migrations.CreateModel(
            name='OrganicSoilRewettingEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(default=0)),
                ('co2_unit', models.CharField(default='tCO2-C/ha/yr', max_length=100)),
                ('doc', models.FloatField(default=0)),
                ('doc_unit', models.CharField(default='tCO2-C/ha/yr', max_length=100)),
                ('ch4', models.FloatField(default=0)),
                ('ch4_unit', models.CharField(default='kg CH4-C/ha/yr', max_length=100)),
                ('n2o', models.FloatField(default=0)),
                ('n2o_unit', models.CharField(default='tN2O-N/ha/yr', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moduletype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('peat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peattype')),
            ],
        ),
        migrations.CreateModel(
            name='OrganicSoilGefEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(default=0)),
                ('co2_unit', models.CharField(default='g CO2-C/kg dry matter burned', max_length=100)),
                ('co', models.FloatField(default=0)),
                ('co_unit', models.CharField(default='g CO/kg dry matter burned', max_length=100)),
                ('ch4', models.FloatField(default=0)),
                ('ch4_unit', models.CharField(default='g CH4/kg dry matter burned', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='OrganicSoilFuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('unit', models.CharField(default='t dm/ha', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('fire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.firetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='OrganicSoilDrainageEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(default=0)),
                ('co2_unit', models.CharField(default='tC/ha/yr', max_length=100)),
                ('doc', models.FloatField(default=0)),
                ('doc_unit', models.CharField(default='tC/ha/yr', max_length=100)),
                ('ch4', models.FloatField(default=0)),
                ('ch4_unit', models.CharField(default='kg CH4/ha/yr', max_length=100)),
                ('n2o', models.FloatField(default=0)),
                ('n2o_unit', models.CharField(default='kg N2O/ha/yr', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moduletype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('peat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peattype')),
                ('site_location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitelocationtype')),
            ],
        ),
        migrations.CreateModel(
            name='OrganicInputCarbonStockExchangeFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('organic_input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype')),
            ],
        ),
        migrations.CreateModel(
            name='NitrousEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='MethaneEntericFermentationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('ipcc_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ipccregion')),
                ('livestock_category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('livestock_production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ManureManagementVolatilizationMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockTAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('ipcc_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ipccregion')),
                ('livestock_category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('livestock_production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockNER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('ipcc_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ipccregion')),
                ('livestock_category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('livestock_production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockEntericEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('livestock_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockAnimalWasteManagementSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('ipcc_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ipccregion')),
                ('livestock_category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('livestock_production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
                ('manure_management_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manuremanagementtype')),
            ],
        ),
        migrations.CreateModel(
            name='LitterDeadwoodCarbonStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litter', models.FloatField()),
                ('dw', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('forest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foresttype')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
        migrations.CreateModel(
            name='LandUseCarbonStockExchangeFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationSystemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('irrigation_system_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.irrigationsystemtype')),
            ],
            options={
                'verbose_name_plural': 'Irrigation system data',
            },
        ),
        migrations.CreateModel(
            name='IrrigationPressureRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_denomination', models.CharField(max_length=255)),
                ('bar_start', models.FloatField()),
                ('bar_end', models.FloatField()),
                ('avg_pressure', models.FloatField()),
                ('head', models.FloatField()),
                ('irrigation_system_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.irrigationsystemtype')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationPhaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_factor', models.FloatField()),
                ('calorific_value', models.FloatField(blank=True, null=True)),
                ('co2_emissions', models.FloatField(blank=True, null=True)),
                ('ch4_emissions', models.FloatField(blank=True, null=True)),
                ('n2o_emissions', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fueltype')),
            ],
        ),
        migrations.CreateModel(
            name='InputReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_multiplier', models.FloatField(blank=True, null=True)),
                ('co2_emissions_multiplier', models.FloatField(blank=True, null=True)),
                ('n2o_quantity_multiplier', models.FloatField(blank=True, null=True)),
                ('n2o_emissions_multiplier', models.FloatField(blank=True, null=True)),
                ('production_quantity_multiplier', models.FloatField(blank=True, null=True)),
                ('production_emissions_multiplier', models.FloatField(blank=True, null=True)),
                ('gw_potential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.globalwarmingpotential')),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inputtype')),
            ],
        ),
        migrations.CreateModel(
            name='InputEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_value', models.FloatField(blank=True, null=True)),
                ('n2o_value', models.FloatField(blank=True, null=True)),
                ('co2_eq_value', models.FloatField(blank=True, null=True)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inputtype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('water_regime_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.waterregimetype')),
            ],
        ),
        migrations.CreateModel(
            name='GrasslandStockExchangeFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmg', models.FloatField(default=1)),
                ('flu', models.FloatField(default=1)),
                ('fi', models.FloatField(default=1)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('grassland_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grasslandmanagementtype')),
            ],
        ),
        migrations.CreateModel(
            name='GrasslandSOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('grassland_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grasslandmanagementtype')),
            ],
        ),
        migrations.CreateModel(
            name='ForestTotalBiomass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='ForestManagementBGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('forest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foresttype')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='ForestManagementAGBGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_after_20_years', models.FloatField()),
                ('value_upto_20_years', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('forest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foresttype')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='ForestManagementAGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agb_min', models.FloatField(default=0)),
                ('agb_max', models.FloatField(default=0)),
                ('agb_growth_min', models.FloatField(default=0)),
                ('agb_growth_max', models.FloatField(default=0)),
                ('agb_unit', models.CharField(default='tonnes d.m./ha', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('forest_condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forestconditiontype')),
                ('forest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foresttype')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='ForestCombustionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(null=True)),
                ('ch4', models.FloatField(null=True)),
                ('n2o', models.FloatField(null=True)),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('forest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foresttype')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
        migrations.CreateModel(
            name='FMGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('tillage_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype')),
            ],
        ),
        migrations.CreateModel(
            name='FiresCombustionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
        migrations.CreateModel(
            name='FIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('organic_input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyDefaultEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_co2_eq', models.FloatField(blank=True, null=True)),
                ('net_calorific_value', models.FloatField(blank=True, null=True)),
                ('co2', models.FloatField(blank=True, null=True)),
                ('ch4', models.FloatField(blank=True, null=True)),
                ('n2o', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fueltype')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ef_grid', models.FloatField(blank=True, null=True)),
                ('final_ef_grid', models.FloatField(blank=True, null=True)),
                ('operating_margin', models.FloatField(blank=True, null=True)),
                ('combined_margin', models.FloatField(blank=True, null=True)),
                ('for_formulas', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='DrainageEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultSoilCarbonStock1Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultSoilCarbonStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('organic_input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype')),
            ],
        ),
        migrations.CreateModel(
            name='DataOnMangrove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agb_dry_matter', models.FloatField()),
                ('c_fraction', models.FloatField()),
                ('agb_c', models.FloatField()),
                ('agb_growth', models.FloatField()),
                ('r', models.FloatField()),
                ('bgb', models.FloatField()),
                ('litter', models.FloatField()),
                ('dw', models.FloatField()),
                ('soc_ref', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='CropYieldStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_2016', models.FloatField(blank=True, null=True)),
                ('year_2017', models.FloatField(blank=True, null=True)),
                ('year_2018', models.FloatField(blank=True, null=True)),
                ('year_2019', models.FloatField(blank=True, null=True)),
                ('year_2020', models.FloatField(blank=True, null=True)),
                ('average', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
        migrations.CreateModel(
            name='CropNitrousEstimationDefaultFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope', models.FloatField(blank=True, null=True)),
                ('intercept', models.FloatField(blank=True, null=True)),
                ('n_ag_residues', models.FloatField()),
                ('rs_t', models.FloatField()),
                ('n_bg_t', models.FloatField()),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
        migrations.CreateModel(
            name='CroplandFMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('tillage_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype')),
            ],
        ),
        migrations.CreateModel(
            name='CroplandFLU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='CroplandFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('organic_input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype')),
            ],
        ),
        migrations.CreateModel(
            name='CoastalLitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='CoastalDeadwood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='CoastalBGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='CoastalAGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='BurningEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField()),
                ('co', models.FloatField()),
                ('ch4', models.FloatField()),
                ('n2o', models.FloatField()),
                ('nox', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.emissionfactorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buildingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Atwood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField(default=0)),
                ('area_2014_km2', models.FloatField(default=0)),
                ('mg_c_ha', models.FloatField(default=0)),
                ('sd', models.FloatField(blank=True, default=None, null=True)),
                ('score', models.FloatField(blank=True, default=None, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='AfforestationLandUseStockExchangeFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='AfforestationCombustionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(null=True)),
                ('ch4', models.FloatField(null=True)),
                ('n2o', models.FloatField(null=True)),
                ('value', models.FloatField()),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
        migrations.CreateModel(
            name='SmallFisheryFUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('fishery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fisherytype')),
                ('gear_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.smallfisherygeartype')),
            ],
            options={
                'unique_together': {('fishery_type', 'gear_type')},
            },
        ),
        migrations.CreateModel(
            name='LivestockVSER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('emission_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcc.emissiontype')),
                ('ipcc_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ipccregion')),
                ('livestock_category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('livestock_production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
            ],
            options={
                'unique_together': {('livestock_production_type', 'livestock_category_type', 'ipcc_region')},
            },
        ),
        migrations.CreateModel(
            name='LivestockManureEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('emission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.emissiontype')),
                ('livestock_category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('livestock_production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
                ('manure_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manuremanagementtype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
            options={
                'unique_together': {('emission_type', 'livestock_production_type', 'livestock_category_type', 'climate', 'moisture', 'manure_management_type')},
            },
        ),
        migrations.CreateModel(
            name='LargeFisheryFUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fishtype')),
                ('gear_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.largefisherygeartype')),
            ],
            options={
                'unique_together': {('fish_type', 'gear_type')},
            },
        ),
        migrations.CreateModel(
            name='GrasslandAGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
            options={
                'unique_together': {('climate', 'moisture')},
            },
        ),
        migrations.CreateModel(
            name='FLUData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
            options={
                'unique_together': {('climate', 'moisture', 'land_use_type')},
            },
        ),
        migrations.CreateModel(
            name='AfforestationFLU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
            options={
                'unique_together': {('climate', 'moisture', 'land_use_type')},
            },
        ),
    ]
