# Generated by Django 4.1.3 on 2022-12-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_annualcroppinginput_floodedriceinput_grasslandinput_and_more'),
        ('ipcc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultemissionfactors',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype'),
        ),
    ]
