# Generated by Django 4.1.3 on 2022-11-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbiomassafterdefo',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='totalbiomassafterdefo',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
