# Generated by Django 4.2.1 on 2024-02-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockvser',
            name='emission_type',
        ),
    ]
