# Generated by Django 4.1.3 on 2022-11-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        ('ipcc', '0002_totalbiomassafterdefo_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalbiomassafterdefo',
            name='vegetation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
    ]
