# Generated by Django 4.2.1 on 2024-02-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_forestmanagement_land_use_factor_t2_start_and_more'),
        ('ipcc', '0002_remove_livestockvser_emission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firescombustionfactor',
            name='land_use_type',
            field=models.ForeignKey(limit_choices_to={'module_types__class_name': 'PerennialCropping'}, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype', unique=True),
        ),
    ]
