# Generated by Django 4.1.3 on 2022-12-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0002_alter_defaultemissionfactors_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BurningEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField()),
                ('co', models.FloatField()),
                ('ch4', models.FloatField()),
                ('n2o', models.FloatField()),
                ('nox', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.emissionfactorcategory')),
            ],
        ),
    ]
