# Generated by Django 4.2.1 on 2024-02-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_forestmanagement_land_use_factor_t2_start_and_more'),
        ('ipcc', '0003_alter_firescombustionfactor_land_use_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perennialmaxagb',
            unique_together={('climate', 'land_use_type')},
        ),
    ]
