# Generated by Django 4.1.3 on 2022-12-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_activitytype_verbose_name_and_more'),
        ('ipcc', '0003_emissionfactorcategory_burningemissionfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiresCombustionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
    ]
