# Generated by Django 4.1.3 on 2022-11-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0003_alter_totalbiomassafterdefo_vegetation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalbiomassafterdefo',
            old_name='vegetation_type',
            new_name='land_use_type',
        ),
    ]
