# Generated by Django 4.1.3 on 2022-11-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0004_rename_vegetation_type_totalbiomassafterdefo_land_use_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustionfactorvalues',
            name='ch4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='combustionfactorvalues',
            name='co2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='combustionfactorvalues',
            name='n2o',
            field=models.FloatField(null=True),
        ),
    ]
