# Generated by Django 4.1.3 on 2022-12-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0004_firescombustionfactor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firescombustionfactor',
            old_name='category',
            new_name='land_use_type',
        ),
    ]
