# Generated by Django 4.2.1 on 2024-02-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_forestmanagement_average_yearly_degradation_percentage_start_and_more'),
        ('ipcc', '0005_alter_firescombustionfactor_land_use_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='landusecarbonstockexchangefactor',
            unique_together={('climate', 'moisture', 'land_use_type')},
        ),
    ]
