# Generated by Django 4.1.3 on 2022-11-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0005_alter_combustionfactorvalues_ch4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litterdeadwoodcarbonstock',
            old_name='forest',
            new_name='vegetation_type',
        ),
    ]
