# Generated by Django 4.2.1 on 2024-02-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0006_alter_landusecarbonstockexchangefactor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestmanagementagb',
            name='from_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forestmanagementagb',
            name='to_year',
            field=models.IntegerField(default=0),
        ),
    ]
