# Generated by Django 4.1.3 on 2022-11-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0006_rename_forest_litterdeadwoodcarbonstock_vegetation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landusestockexchangefactor',
            old_name='agroforestry_system',
            new_name='land_use_type',
        ),
    ]
