# Generated by Django 4.1.3 on 2022-12-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0006_cropnitrousestimationdefaultfactor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropnitrousestimationdefaultfactor',
            old_name='value',
            new_name='intercept',
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='n_ag_residues',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='n_bg_t',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='rs_t',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='slope',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
