# Generated by Django 4.1.3 on 2022-12-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0007_rename_value_cropnitrousestimationdefaultfactor_intercept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropnitrousestimationdefaultfactor',
            name='intercept',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
