# Generated by Django 4.1.3 on 2022-11-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0007_rename_agroforestry_system_landusestockexchangefactor_land_use_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilorganiccarbon',
            old_name='soil',
            new_name='soil_type',
        ),
    ]
