# Generated by Django 4.2.1 on 2024-02-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0007_forestmanagementagb_from_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forestmanagementagb',
            name='to_year',
        ),
    ]
