# Generated by Django 4.1.3 on 2022-12-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0008_alter_cropnitrousestimationdefaultfactor_intercept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropnitrousestimationdefaultfactor',
            name='slope',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
