# Generated by Django 4.2.1 on 2024-02-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_forestdisturbance_disturbance_type'),
        ('ipcc', '0008_remove_forestmanagementagb_to_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forestmanagementagb',
            unique_together={('climate', 'land_use_type', 'region', 'forest_condition_type', 'from_year', 'forest_type')},
        ),
    ]
