# Generated by Django 4.1.3 on 2022-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0008_rename_soil_soilorganiccarbon_soil_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilorganiccarbon',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
