# Generated by Django 4.2.1 on 2024-03-19 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_notes_note_text'),
        ('ipcc', '0009_alter_forestmanagementagb_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firescombustionfactor',
            name='land_use_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
    ]
