# Generated by Django 4.1.3 on 2022-11-29 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        ('ipcc', '0009_alter_soilorganiccarbon_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestTotalBiomass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
    ]
