# Generated by Django 4.1.3 on 2022-12-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_annualcropping_ha_start_rate'),
        ('ipcc', '0009_alter_cropnitrousestimationdefaultfactor_slope'),
    ]

    operations = [
        migrations.CreateModel(
            name='TillageCarbonStockExchangeFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('tillage_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype')),
            ],
        ),
    ]
