# Generated by Django 4.2.1 on 2024-05-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_floodedrice_cultivation_period_start_and_more'),
        ('ipcc', '0010_alter_firescombustionfactor_land_use_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewettingcarbonfactor',
            name='soil_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.soiltype'),
            preserve_default=False,
        ),
    ]
