# Generated by Django 4.1.3 on 2022-12-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_annualcropping_ha_start_rate'),
        ('ipcc', '0010_tillagecarbonstockexchangefactor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandUseStockExchangeFactor',
            new_name='LandUseCarbonStockExchangeFactor',
        ),
    ]
