# Generated by Django 4.2.1 on 2024-06-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_organicsoil_peat_type'),
        ('ipcc', '0011_rewettingcarbonfactor_soil_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LivestockAnimalWasteManagementSystem',
            new_name='LivestockAWMS',
        ),
    ]
