# Generated by Django 4.1.3 on 2022-12-01 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_afforestationinput_final_ag_biomass_gt_20yrs_t2'),
        ('ipcc', '0011_afforestationlandusestockexchangefactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboveGroundNetBiomassGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_after_20_years', models.FloatField()),
                ('value_before_20_years', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
    ]
