# Generated by Django 4.1.3 on 2022-12-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0012_abovegroundnetbiomassgrowth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abovegroundnetbiomassgrowth',
            old_name='value_before_20_years',
            new_name='value_upto_20_years',
        ),
    ]
