# Generated by Django 4.2.1 on 2024-07-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_historicalsettlement_agb_t2_start_and_more'),
        ('ipcc', '0012_rename_livestockanimalwastemanagementsystem_livestockawms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nitrousemissionfactor',
            name='name',
        ),
        migrations.AlterField(
            model_name='nitrousemissionfactor',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='SettlementEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flu', models.FloatField(default=1)),
                ('fmg', models.FloatField(default=1)),
                ('fi', models.FloatField(default=1)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('settlement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.settlementtype')),
            ],
        ),
        migrations.CreateModel(
            name='InputsNitrousEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
    ]
