# Generated by Django 4.2.1 on 2024-07-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_annualcropping_organic_soil_and_more'),
        ('ipcc', '0012_rename_livestockanimalwastemanagementsystem_livestockawms'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUseNitrousEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
    ]
