# Generated by Django 4.1.3 on 2022-12-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_afforestationinput_final_ag_biomass_gt_20yrs_t2'),
        ('ipcc', '0013_rename_value_before_20_years_abovegroundnetbiomassgrowth_value_upto_20_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfforestationCombustionFactorValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(null=True)),
                ('ch4', models.FloatField(null=True)),
                ('n2o', models.FloatField(null=True)),
                ('value', models.FloatField()),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
    ]
