# Generated by Django 4.2.1 on 2024-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0013_remove_nitrousemissionfactor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementef',
            name='biomass',
            field=models.FloatField(default=0),
        ),
    ]
