# Generated by Django 4.1.3 on 2022-12-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_annualcropping_ha_start_rate'),
        ('ipcc', '0013_tillagecarbonstockexchangefactor_climate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organicinputcarbonstockexchangefactor',
            name='climate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.climate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organicinputcarbonstockexchangefactor',
            name='moisture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.moisture'),
            preserve_default=False,
        ),
    ]
