# Generated by Django 4.1.3 on 2023-02-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_salinitytype'),
        ('ipcc', '0014_organicinputcarbonstockexchangefactor_climate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewettingMethaneFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('salinity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salinitytype')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
        migrations.CreateModel(
            name='RewettingCarbonFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
        migrations.CreateModel(
            name='CoastalLitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
        migrations.CreateModel(
            name='CoastalDeadwood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
        migrations.CreateModel(
            name='CoastalBGAGRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
        migrations.CreateModel(
            name='CoastalAboveGroundBiomass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
    ]
