# Generated by Django 4.2.1 on 2024-07-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_historicalsettlement_agb_t2_start_and_more'),
        ('ipcc', '0014_settlementef_biomass'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settlementef',
            unique_together={('settlement_type', 'climate', 'moisture')},
        ),
    ]
