# Generated by Django 4.2.1 on 2024-07-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0015_alter_settlementef_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settlementef',
            unique_together=set(),
        ),
    ]
