# Generated by Django 4.1.3 on 2023-02-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_rewetting_avg_salinity_t2_delete_salinity'),
        ('ipcc', '0015_rewettingmethanefactor_rewettingcarbonfactor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherConstructedWaterbodiesEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
    ]
