# Generated by Django 4.1.3 on 2023-02-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_rewetting_avg_salinity_t2_delete_salinity'),
        ('ipcc', '0016_otherconstructedwaterbodiesemissionfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherconstructedwaterbodiesemissionfactor',
            name='waterbody_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.waterbodytype'),
            preserve_default=False,
        ),
    ]
