# Generated by Django 4.2.1 on 2024-07-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_historicalsettlement_agb_t2_start_and_more'),
        ('ipcc', '0016_alter_settlementef_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settlementef',
            unique_together={('settlement_type', 'climate', 'moisture')},
        ),
    ]
