# Generated by Django 4.1.3 on 2023-02-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_rewetting_avg_salinity_t2_delete_salinity'),
        ('ipcc', '0017_otherconstructedwaterbodiesemissionfactor_waterbody_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSoilCarbonStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Atwood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField(default=0)),
                ('area_2014_km2', models.FloatField(default=0)),
                ('mg_c_ha', models.FloatField(default=0)),
                ('sd', models.FloatField(blank=True, default=None, null=True)),
                ('score', models.FloatField(blank=True, default=None, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
    ]
