# Generated by Django 4.2.1 on 2024-07-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0017_alter_settlementef_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultEmissionFactor',
        ),
    ]
