# Generated by Django 4.2.1 on 2024-07-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0018_delete_defaultemissionfactor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultSoilCarbonStock1Meter',
        ),
    ]
