# Generated by Django 4.1.3 on 2023-02-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_country_continent'),
        ('ipcc', '0019_drainageemissionfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainageemissionfactor',
            name='vegetation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
            preserve_default=False,
        ),
    ]
