# Generated by Django 4.2.1 on 2024-08-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0020_merge_20240814_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandUseNitrousEmissionFactor',
        ),
    ]
