# Generated by Django 4.1.3 on 2023-02-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_perennialcropping_ag_t2_perennialcropping_bg_t2_and_more'),
        ('ipcc', '0021_perennialagb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perennialagb',
            name='vegetation_type',
        ),
        migrations.AddField(
            model_name='perennialagb',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
    ]
