# Generated by Django 4.1.3 on 2023-02-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_sc_t2_perennialcropping_soc_t2'),
        ('ipcc', '0023_perennialmaximumagbc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroplandFMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('tillage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagetype')),
            ],
        ),
        migrations.CreateModel(
            name='CroplandFLU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='CroplandFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('organic_input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype')),
            ],
        ),
    ]
