# Generated by Django 4.2.1 on 2024-08-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_alter_coastalwetland_area_not_drained_or_rewetted_start_and_more'),
        ('ipcc', '0023_alter_rewettingcarbonfactor_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rewettingmethanefactor',
            unique_together={('climate', 'moisture', 'land_use_type', 'salinity')},
        ),
    ]
