# Generated by Django 4.1.3 on 2023-02-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0024_croplandfmg_croplandflu_croplandfi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perennialagb',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perennialmaximumagbc',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
