# Generated by Django 4.2.1 on 2024-08-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0024_alter_rewettingmethanefactor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationpressurerequirement',
            name='bar_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='irrigationpressurerequirement',
            name='bar_start',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
