# Generated by Django 4.2.1 on 2024-08-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0025_alter_irrigationpressurerequirement_bar_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationpressurerequirement',
            name='initial_denomination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
