# Generated by Django 4.1.3 on 2023-02-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_sc_t2_perennialcropping_soc_t2'),
        ('ipcc', '0025_alter_perennialagb_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croplandfmg',
            name='tillage_type',
        ),
        migrations.AddField(
            model_name='croplandfmg',
            name='tillage_management_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype'),
            preserve_default=False,
        ),
    ]
