# Generated by Django 4.2.1 on 2024-08-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_alter_historicallandusechange_dry_matter_start_and_more'),
        ('ipcc', '0026_alter_irrigationpressurerequirement_initial_denomination'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foresttotalbiomass',
            unique_together={('climate', 'moisture', 'continent', 'land_use_type')},
        ),
    ]
