# Generated by Django 4.1.3 on 2023-02-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0027_perennialagb_continent_perennialbgb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perennialmaximumagbc',
            name='moisture',
        ),
    ]
