# Generated by Django 4.2.1 on 2024-08-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_alter_historicallandusechange_dry_matter_start_and_more'),
        ('ipcc', '0027_alter_foresttotalbiomass_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fludata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fidata',
            name='grassland_management_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grasslandmanagementtype'),
        ),
        migrations.AddField(
            model_name='fludata',
            name='grassland_management_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grasslandmanagementtype'),
        ),
        migrations.AddField(
            model_name='fmgdata',
            name='grassland_management_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grasslandmanagementtype'),
        ),
        migrations.AlterField(
            model_name='fidata',
            name='organic_input_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype'),
        ),
        migrations.AlterField(
            model_name='fludata',
            name='land_use_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
        migrations.AlterUniqueTogether(
            name='fidata',
            unique_together={('climate', 'moisture', 'organic_input_type', 'grassland_management_type')},
        ),
        migrations.AlterUniqueTogether(
            name='fludata',
            unique_together={('climate', 'moisture', 'land_use_type', 'grassland_management_type')},
        ),
    ]
