# Generated by Django 4.2.1 on 2024-08-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_alter_historicallandusechange_dry_matter_start_and_more'),
        ('ipcc', '0028_alter_fludata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmgdata',
            name='tillage_management_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype'),
        ),
    ]
