# Generated by Django 4.2.1 on 2024-08-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_alter_irrigationsystemtype_unique_together'),
        ('ipcc', '0029_alter_fmgdata_tillage_management_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationsystemdata',
            name='irrigation_system_type',
        ),
        migrations.AddField(
            model_name='irrigationsystemdata',
            name='irrigation_system_types',
            field=models.ManyToManyField(to='api.irrigationsystemtype'),
        ),
    ]
