# Generated by Django 4.1.3 on 2023-02-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_afforestation_parent_module_type_and_more'),
        ('ipcc', '0029_afforestationflu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerennialMaximumAGBC',
            new_name='PerennialMaxAGB',
        ),
    ]
