# Generated by Django 4.2.1 on 2024-08-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_alter_irrigationsystemtype_unique_together_and_more'),
        ('ipcc', '0030_remove_irrigationsystemdata_irrigation_system_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationsystemdata',
            name='irrigation_system_types',
        ),
        migrations.AddField(
            model_name='irrigationsystemdata',
            name='irrigation_system_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.irrigationsystemtype'),
        ),
    ]
