# Generated by Django 4.1.3 on 2023-02-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_rename_grassland_at_start_grassland_grassland_management_type_start_and_more'),
        ('ipcc', '0030_rename_perennialmaximumagbc_perennialmaxagb'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrasslandSOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('grassland_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grasslandmanagementtype')),
            ],
        ),
        migrations.CreateModel(
            name='GrasslandAGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
    ]
