# Generated by Django 4.2.1 on 2024-08-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_remove_fueltype_land_use_types_fueltype_module_types'),
        ('ipcc', '0031_remove_irrigationsystemdata_irrigation_system_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationsystemdata',
            name='irrigation_system_type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.irrigationsystemtype'),
            preserve_default=False,
        ),
    ]
