# Generated by Django 4.1.3 on 2023-02-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_fueltype_remove_electricityemission_continent_and_more'),
        ('ipcc', '0031_grasslandsoc_grasslandagb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallFisheryFUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('fishery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fisherytype')),
                ('gear_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.geartype')),
            ],
        ),
        migrations.CreateModel(
            name='LargeFisheryFUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fishtype')),
                ('gear_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.geartype')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyDefaultEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_co2_eq_m3', models.FloatField(default=None)),
                ('tj_gg', models.FloatField(default=None)),
                ('kg_ch4_tj', models.FloatField(default=None)),
                ('kg_n2o_tj', models.FloatField(default=None)),
                ('density_kg_m3', models.FloatField(default=None)),
                ('co2_emissions', models.FloatField(default=None)),
                ('ch4_emissions', models.FloatField(default=None)),
                ('n2o_emissions', models.FloatField(default=None)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fueltype')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ef_grid', models.FloatField(blank=True, null=True)),
                ('final_ef_grid', models.FloatField(blank=True, null=True)),
                ('operating_margin', models.FloatField(blank=True, null=True)),
                ('combined_margin', models.FloatField(blank=True, null=True)),
                ('for_formulas', models.FloatField(blank=True, null=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
    ]
