# Generated by Django 4.1.3 on 2023-02-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0032_smallfisheryfui_largefisheryfui_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydefaultemissionfactor',
            name='ch4_emissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energydefaultemissionfactor',
            name='co2_emissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energydefaultemissionfactor',
            name='density_kg_m3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energydefaultemissionfactor',
            name='kg_ch4_tj',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energydefaultemissionfactor',
            name='kg_n2o_tj',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energydefaultemissionfactor',
            name='n2o_emissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energydefaultemissionfactor',
            name='t_co2_eq_m3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energydefaultemissionfactor',
            name='tj_gg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
