# Generated by Django 4.2.1 on 2024-08-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0032_alter_irrigationsystemdata_irrigation_system_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricityemission',
            name='ef_grid',
        ),
        migrations.RemoveField(
            model_name='electricityemission',
            name='final_ef_grid',
        ),
        migrations.RemoveField(
            model_name='electricityemission',
            name='for_formulas',
        ),
        migrations.RemoveField(
            model_name='electricityemission',
            name='year',
        ),
    ]
