# Generated by Django 4.1.3 on 2023-02-28 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_grassland_grassland_management_type_start_and_more'),
        ('ipcc', '0033_alter_energydefaultemissionfactor_ch4_emissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrasslandStockExchangeFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmg', models.FloatField(default=1)),
                ('fui', models.FloatField(default=1)),
                ('fi', models.FloatField(default=1)),
                ('grassland_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grasslandmanagementtype')),
            ],
        ),
    ]
