# Generated by Django 4.2.1 on 2024-08-23 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_remove_degradedland_ha_start_and_more'),
        ('ipcc', '0033_remove_electricityemission_ef_grid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricityemission',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country', unique=True),
        ),
    ]
