# Generated by Django 4.2.1 on 2024-08-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0034_alter_electricityemission_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energydefaultemissionfactor',
            name='density',
        ),
        migrations.RemoveField(
            model_name='energydefaultemissionfactor',
            name='net_calorific_value',
        ),
        migrations.RemoveField(
            model_name='energydefaultemissionfactor',
            name='t_co2_eq',
        ),
    ]
