# Generated by Django 4.1.3 on 2023-02-28 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_grassland_grassland_management_type_start_and_more'),
        ('ipcc', '0034_grasslandstockexchangefactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='grasslandstockexchangefactor',
            name='climate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.climate'),
            preserve_default=False,
        ),
    ]
