# Generated by Django 4.1.3 on 2023-02-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0035_grasslandstockexchangefactor_climate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grasslandstockexchangefactor',
            old_name='fui',
            new_name='flu',
        ),
    ]
