# Generated by Django 4.2.1 on 2024-08-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0035_remove_energydefaultemissionfactor_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalwarmingpotential',
            name='ch4_fossil',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
