# Generated by Django 4.1.3 on 2023-03-03 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_grassland_grassland_management_type_start_and_more'),
        ('ipcc', '0036_rename_fui_grasslandstockexchangefactor_flu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestAGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
    ]
