# Generated by Django 4.2.1 on 2024-08-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0036_globalwarmingpotential_ch4_fossil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputreference',
            name='gw_potential',
        ),
    ]
