# Generated by Django 4.1.3 on 2023-03-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_annualcropping_land_use_type_and_more'),
        ('ipcc', '0037_forestagb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropYieldStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_2016', models.FloatField(blank=True, null=True)),
                ('year_2017', models.FloatField(blank=True, null=True)),
                ('year_2018', models.FloatField(blank=True, null=True)),
                ('year_2019', models.FloatField(blank=True, null=True)),
                ('year_2020', models.FloatField(blank=True, null=True)),
                ('average', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('land_use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype')),
            ],
        ),
    ]
