# Generated by Django 4.2.1 on 2024-08-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_alter_project_gw_potential'),
        ('ipcc', '0037_remove_inputreference_gw_potential'),
    ]

    operations = [
        migrations.AddField(
            model_name='energydefaultemissionfactor',
            name='fuel_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.fuelusetype'),
            preserve_default=False,
        ),
    ]
