# Generated by Django 4.1.3 on 2023-03-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_annualcropping_crop_yield_and_more'),
        ('ipcc', '0038_cropyieldstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultEmissionFactors',
            new_name='DefaultEmissionFactor',
        ),
    ]
