# Generated by Django 4.2.1 on 2024-08-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_alter_project_gw_potential'),
        ('ipcc', '0038_energydefaultemissionfactor_fuel_use_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energydefaultemissionfactor',
            options={'verbose_name_plural': 'Energy default emission factors'},
        ),
        migrations.AlterUniqueTogether(
            name='energydefaultemissionfactor',
            unique_together={('fuel_use_type', 'fuel_type')},
        ),
    ]
