# Generated by Django 4.2.1 on 2024-09-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0039_alter_energydefaultemissionfactor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestmanagementagb',
            name='agb_growth_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagementagb',
            name='agb_growth_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagementagb',
            name='agb_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forestmanagementagb',
            name='agb_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
