# Generated by Django 4.0.4 on 2023-03-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0040_inputreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputReference',
        ),
    ]
