# Generated by Django 4.2.1 on 2024-09-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_alter_historicalproject_executing_agency_and_more'),
        ('ipcc', '0040_alter_forestmanagementagb_agb_growth_max_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestockawms',
            options={'verbose_name_plural': 'Livestock Animal Waste Management Systems'},
        ),
        migrations.AlterUniqueTogether(
            name='livestockawms',
            unique_together={('livestock_production_type', 'manure_management_type', 'livestock_category_type', 'ipcc_region')},
        ),
    ]
