# Generated by Django 4.0.4 on 2023-03-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_input_name_input_activity_and_more'),
        ('ipcc', '0041_delete_inputreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_multiplier', models.FloatField(blank=True, null=True)),
                ('co2_emissions_multiplier', models.FloatField(blank=True, null=True)),
                ('n2o_quantity_multiplier', models.FloatField(blank=True, null=True)),
                ('n2o_emissions_multiplier', models.FloatField(blank=True, null=True)),
                ('production_quantity_multiplier', models.FloatField(blank=True, null=True)),
                ('production_emissions_multiplier', models.FloatField(blank=True, null=True)),
                ('gw_potential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.globalwarmingpotential')),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inputtype')),
            ],
        ),
    ]
