# Generated by Django 4.2.1 on 2024-10-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0041_alter_livestockawms_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalwarmingpotential',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='globalwarmingpotential',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='globalwarmingpotential',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
