# Generated by Django 4.0.4 on 2023-03-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_input_name_input_activity_and_more'),
        ('ipcc', '0042_inputreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('macro_input_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.macroinputtype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('water_regime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.waterregimetype')),
            ],
        ),
    ]
