# Generated by Django 4.2.1 on 2024-10-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipcc", "0042_globalwarmingpotential_name_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrasslandBiomass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("agb_t_dm_ha", models.FloatField()),
                ("agb_t_c_ha", models.FloatField()),
                ("bgb_t_dm_ha", models.FloatField()),
                ("bgb_t_c_ha", models.FloatField()),
                ("climate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.climate")),
                ("moisture", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.moisture")),
            ],
            options={
                "unique_together": {("climate", "moisture")},
            },
        ),
        migrations.DeleteModel(
            name="GrasslandAGB",
        ),
    ]
