# Generated by Django 4.0.4 on 2023-03-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_input_name_input_activity_and_more'),
        ('ipcc', '0043_inputemissionfactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputemissionfactor',
            name='macro_input_type',
        ),
        migrations.AddField(
            model_name='inputemissionfactor',
            name='input_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.inputtype'),
            preserve_default=False,
        ),
    ]
