# Generated by Django 4.2.1 on 2024-10-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0043_grasslandbiomass_delete_grasslandagb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afforestationcombustionfactor',
            options={'verbose_name': 'Afforestation Combustion Factor', 'verbose_name_plural': 'Afforestation Combustion Factors'},
        ),
        migrations.AlterModelOptions(
            name='afforestationflu',
            options={'verbose_name': 'Afforestation FLU', 'verbose_name_plural': 'Afforestation FLUs'},
        ),
        migrations.AlterModelOptions(
            name='afforestationlandusestockexchangefactor',
            options={'verbose_name': 'Afforestation Land Use Stock Exchange Factor', 'verbose_name_plural': 'Afforestation Land Use Stock Exchange Factors'},
        ),
        migrations.AlterModelOptions(
            name='atwood',
            options={'verbose_name': 'Atwood', 'verbose_name_plural': 'Atwood'},
        ),
        migrations.AlterModelOptions(
            name='buildingemissionfactor',
            options={'verbose_name': 'Building Emission Factor', 'verbose_name_plural': 'Building Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='burningemissionfactor',
            options={'verbose_name': 'Burning Emission Factor', 'verbose_name_plural': 'Burning Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='coastalagb',
            options={'verbose_name': 'Coastal AGB', 'verbose_name_plural': 'Coastal AGB'},
        ),
        migrations.AlterModelOptions(
            name='coastalbgb',
            options={'verbose_name': 'Coastal BGB', 'verbose_name_plural': 'Coastal BGB'},
        ),
        migrations.AlterModelOptions(
            name='coastaldeadwood',
            options={'verbose_name': 'Coastal Deadwood', 'verbose_name_plural': 'Coastal Deadwood'},
        ),
        migrations.AlterModelOptions(
            name='coastallitter',
            options={'verbose_name': 'Coastal Litter', 'verbose_name_plural': 'Coastal Litter'},
        ),
        migrations.AlterModelOptions(
            name='croplandfi',
            options={'verbose_name': 'Cropland FI', 'verbose_name_plural': 'Cropland FIs'},
        ),
        migrations.AlterModelOptions(
            name='croplandflu',
            options={'verbose_name': 'Cropland FLU', 'verbose_name_plural': 'Cropland FLUs'},
        ),
        migrations.AlterModelOptions(
            name='croplandfmg',
            options={'verbose_name': 'Cropland FMG', 'verbose_name_plural': 'Cropland FMGs'},
        ),
        migrations.AlterModelOptions(
            name='cropnitrousestimationdefaultfactor',
            options={'verbose_name': 'Crop Nitrous Estimation Factor', 'verbose_name_plural': 'Crop Nitrous Estimation Factors'},
        ),
        migrations.AlterModelOptions(
            name='cropyieldstats',
            options={'verbose_name': 'Crop Yield Stats', 'verbose_name_plural': 'Crop Yield Stats'},
        ),
        migrations.AlterModelOptions(
            name='dataonmangrove',
            options={'verbose_name': 'Data on Mangrove', 'verbose_name_plural': 'Data on Mangroves'},
        ),
        migrations.AlterModelOptions(
            name='defaultsoilcarbonstock',
            options={'verbose_name': 'Default Soil Carbon Stock', 'verbose_name_plural': 'Default Soil Carbon Stock'},
        ),
        migrations.AlterModelOptions(
            name='drainageemissionfactor',
            options={'verbose_name': 'Drainage Emission Factor', 'verbose_name_plural': 'Drainage Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='electricityemission',
            options={'verbose_name': 'Electricity Emission', 'verbose_name_plural': 'Electricity Emissions'},
        ),
        migrations.AlterModelOptions(
            name='fidata',
            options={'verbose_name': 'FI Data', 'verbose_name_plural': 'FI Data'},
        ),
        migrations.AlterModelOptions(
            name='firescombustionfactor',
            options={'verbose_name': 'Fires Combustion Factor', 'verbose_name_plural': 'Fires Combustion Factors'},
        ),
        migrations.AlterModelOptions(
            name='fmgdata',
            options={'verbose_name': 'FMG Data', 'verbose_name_plural': 'FMG Data'},
        ),
        migrations.AlterModelOptions(
            name='forestcombustionfactor',
            options={'verbose_name': 'Forest Combustion Factor', 'verbose_name_plural': 'Forest Combustion Factors'},
        ),
        migrations.AlterModelOptions(
            name='forestmanagementagb',
            options={'verbose_name': 'Forest Management AGB', 'verbose_name_plural': 'Forest Management AGB'},
        ),
        migrations.AlterModelOptions(
            name='forestmanagementagbgrowth',
            options={'verbose_name': 'Forest Management AGB Growth', 'verbose_name_plural': 'Forest Management AGB Growth'},
        ),
        migrations.AlterModelOptions(
            name='forestmanagementbgb',
            options={'verbose_name': 'Forest Management BGB', 'verbose_name_plural': 'Forest Management BGB'},
        ),
        migrations.AlterModelOptions(
            name='foresttotalbiomass',
            options={'verbose_name': 'Forest Biomass for Initial Land Use', 'verbose_name_plural': 'Forest Biomass for Initial Land Use'},
        ),
        migrations.AlterModelOptions(
            name='globalwarmingpotential',
            options={'verbose_name': 'Global Warming Potential', 'verbose_name_plural': 'Global Warming Potentials'},
        ),
        migrations.AlterModelOptions(
            name='grasslandbiomass',
            options={'verbose_name': 'Grassland Biomass', 'verbose_name_plural': 'Grassland Biomass'},
        ),
        migrations.AlterModelOptions(
            name='grasslandsoc',
            options={'verbose_name': 'Grassland SOC', 'verbose_name_plural': 'Grassland SOC'},
        ),
        migrations.AlterModelOptions(
            name='grasslandstockexchangefactor',
            options={'verbose_name': 'Grassland Stock Exchange Factor', 'verbose_name_plural': 'Grassland Stock Exchange Factors'},
        ),
        migrations.AlterModelOptions(
            name='inputemissionfactor',
            options={'verbose_name': 'Input Emission Factor', 'verbose_name_plural': 'Input Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='inputreference',
            options={'verbose_name': 'Input Reference', 'verbose_name_plural': 'Input References'},
        ),
        migrations.AlterModelOptions(
            name='inputsnitrousemissionfactor',
            options={'verbose_name': 'Inputs Nitrous Emission Factor', 'verbose_name_plural': 'Inputs Nitrous Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='irrigationphasedata',
            options={'verbose_name': 'Irrigation Phase Data', 'verbose_name_plural': 'Irrigation Phase Data'},
        ),
        migrations.AlterModelOptions(
            name='irrigationpressurerequirement',
            options={'verbose_name': 'Irrigation Pressure Requirement', 'verbose_name_plural': 'Irrigation Pressure Requirements'},
        ),
        migrations.AlterModelOptions(
            name='landusecarbonstockexchangefactor',
            options={'verbose_name': 'Land Use Carbon Stock Exchange Factor', 'verbose_name_plural': 'Land Use Carbon Stock Exchange Factors'},
        ),
        migrations.AlterModelOptions(
            name='largefisheryfui',
            options={'verbose_name': 'Large Fishery FUI', 'verbose_name_plural': 'Large Fishery FUIs'},
        ),
        migrations.AlterModelOptions(
            name='litterdeadwoodcarbonstock',
            options={'verbose_name': 'Litter/Deadwood Carbon Stock', 'verbose_name_plural': 'Litter/Deadwood Carbon Stock'},
        ),
        migrations.AlterModelOptions(
            name='livestockentericef',
            options={'verbose_name': 'Livestock Enteric Emission Factor', 'verbose_name_plural': 'Livestock Enteric Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='livestockmanureef',
            options={'verbose_name': 'Livestock Manure Emission Factor', 'verbose_name_plural': 'Livestock Manure Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='livestockner',
            options={'verbose_name': 'Livestock NER', 'verbose_name_plural': 'Livestock NERs'},
        ),
        migrations.AlterModelOptions(
            name='livestocktam',
            options={'verbose_name': 'Livestock TAM', 'verbose_name_plural': 'Livestock TAMs'},
        ),
        migrations.AlterModelOptions(
            name='livestockvser',
            options={'verbose_name': 'Livestock VSER', 'verbose_name_plural': 'Livestock VSERs'},
        ),
        migrations.AlterModelOptions(
            name='manuremanagementvolatilizationmultiplier',
            options={'verbose_name': 'Manure Management Volatilization Multiplier', 'verbose_name_plural': 'Manure Management Volatilization Multipliers'},
        ),
        migrations.AlterModelOptions(
            name='methaneentericfermentationfactor',
            options={'verbose_name': 'Methane Enteric Fermentation Factor', 'verbose_name_plural': 'Methane Enteric Fermentation Factors'},
        ),
        migrations.AlterModelOptions(
            name='nitrousemissionfactor',
            options={'verbose_name': 'Nitrous Emission Factor', 'verbose_name_plural': 'Nitrous Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='organicinputcarbonstockexchangefactor',
            options={'verbose_name': 'Organic Input Carbon Stock Exchange Factor', 'verbose_name_plural': 'Organic Input Carbon Stock Exchange Factors'},
        ),
        migrations.AlterModelOptions(
            name='organicsoildrainageemissionfactor',
            options={'verbose_name': 'Organic Soil Drainage Emission Factor', 'verbose_name_plural': 'Organic Soil Drainage Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='organicsoilfuelconsumption',
            options={'verbose_name': 'Organic Soil Fuel Consumption', 'verbose_name_plural': 'Organic Soil Fuel Consumptions'},
        ),
        migrations.AlterModelOptions(
            name='organicsoilgefemissionfactor',
            options={'verbose_name': 'Organic Soil GEF Emission Factor', 'verbose_name_plural': 'Organic Soil GEF Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='organicsoilrewettingemissionfactor',
            options={'verbose_name': 'Organic Soil Rewetting Emission Factor', 'verbose_name_plural': 'Organic Soil Rewetting Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='otherconstructedwaterbodiesemissionfactor',
            options={'verbose_name': 'Other Constructed Waterbodies Emission Factor', 'verbose_name_plural': 'Other Constructed Waterbodies Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='peatextractionconversionfactor',
            options={'verbose_name': 'Peat Extraction Conversion Factor', 'verbose_name_plural': 'Peat Extraction Conversion Factors'},
        ),
        migrations.AlterModelOptions(
            name='peatextractionemissionfactor',
            options={'verbose_name': 'Peat Extraction Emission Factor', 'verbose_name_plural': 'Peat Extraction Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='perennialagb',
            options={'verbose_name': 'Perennial AGB', 'verbose_name_plural': 'Perennial AGB'},
        ),
        migrations.AlterModelOptions(
            name='perennialbgb',
            options={'verbose_name': 'Perennial BGB', 'verbose_name_plural': 'Perennial BGB'},
        ),
        migrations.AlterModelOptions(
            name='perennialmaxagb',
            options={'verbose_name': 'Perennial Max AGB', 'verbose_name_plural': 'Perennial Max AGB'},
        ),
        migrations.AlterModelOptions(
            name='rewettingcarbonfactor',
            options={'verbose_name': 'Rewetting Carbon Factor', 'verbose_name_plural': 'Rewetting Carbon Factors'},
        ),
        migrations.AlterModelOptions(
            name='rewettingmethanefactor',
            options={'verbose_name': 'Rewetting Methane Factor', 'verbose_name_plural': 'Rewetting Methane Factors'},
        ),
        migrations.AlterModelOptions(
            name='ricedefaultemissionfactor',
            options={'verbose_name': 'Rice Default Emission Factor', 'verbose_name_plural': 'Rice Default Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='ricesfo',
            options={'verbose_name': 'Rice SFO', 'verbose_name_plural': 'Rice SFOs'},
        ),
        migrations.AlterModelOptions(
            name='ricesfp',
            options={'verbose_name': 'Rice SFP', 'verbose_name_plural': 'Rice SFPs'},
        ),
        migrations.AlterModelOptions(
            name='ricesfw',
            options={'verbose_name': 'Rice SFW', 'verbose_name_plural': 'Rice SFWs'},
        ),
        migrations.AlterModelOptions(
            name='riceyield',
            options={'verbose_name': 'Rice Yield', 'verbose_name_plural': 'Rice Yields'},
        ),
        migrations.AlterModelOptions(
            name='roademissionfactor',
            options={'verbose_name': 'Road Emission Factor', 'verbose_name_plural': 'Road Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='settlementef',
            options={'verbose_name': 'Settlement Emission Factor', 'verbose_name_plural': 'Settlement Emission Factors'},
        ),
        migrations.AlterModelOptions(
            name='smallfisheryfui',
            options={'verbose_name': 'Small Fishery FUI', 'verbose_name_plural': 'Small Fishery FUIs'},
        ),
        migrations.AlterModelOptions(
            name='soilorganiccarbon',
            options={'verbose_name': 'Soil Organic Carbon', 'verbose_name_plural': 'Soil Organic Carbon'},
        ),
        migrations.AlterModelOptions(
            name='tillagecarbonstockexchangefactor',
            options={'verbose_name': 'Tillage Carbon Stock Exchange Factor', 'verbose_name_plural': 'Tillage Carbon Stock Exchange Factors'},
        ),
        migrations.AlterModelOptions(
            name='totalbiomassafterdefo',
            options={'verbose_name': 'Total Biomass for Final Land Use', 'verbose_name_plural': 'Total Biomass for Final Land Uses'},
        ),
        migrations.AlterModelOptions(
            name='trophicstatefactor',
            options={'verbose_name': 'Trophic State Factor', 'verbose_name_plural': 'Trophic State Factors'},
        ),
    ]
