# Generated by Django 4.2.1 on 2024-11-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_packagingtype'),
        ('ipcc', '0044_alter_afforestationcombustionfactor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueChainPackagingEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagingtype')),
            ],
            options={
                'verbose_name': 'Value Chain Packaging Emission Factor',
                'verbose_name_plural': 'Value Chain Packaging Emission Factors',
            },
        ),
    ]
