# Generated by Django 4.2.1 on 2024-11-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_historicalprocessing_country_of_origin_and_more'),
        ('ipcc', '0045_valuechainpackagingemissionfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueChainRefrigerantEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('refrigerant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refrigeranttype')),
            ],
            options={
                'verbose_name': 'Value Chain Refrigerant Emission Factor',
                'verbose_name_plural': 'Value Chain Refrigerant Emission Factors',
            },
        ),
    ]
