# Generated by Django 4.0.4 on 2023-03-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0045_alter_inputemissionfactor_water_regime_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputemissionfactor',
            name='value',
        ),
        migrations.AddField(
            model_name='inputemissionfactor',
            name='co2_eq_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputemissionfactor',
            name='co2_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputemissionfactor',
            name='n2o_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
