# Generated by Django 4.0.4 on 2023-03-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_buildingtype_building'),
        ('ipcc', '0046_remove_inputemissionfactor_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_co2_m2', models.FloatField(blank=True, null=True)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buildingtype')),
            ],
        ),
    ]
