# Generated by Django 4.2.1 on 2024-11-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0046_valuechainrefrigerantemissionfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuechainrefrigerantemissionfactor',
            name='gwp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipcc.globalwarmingpotential'),
            preserve_default=False,
        ),
    ]
