# Generated by Django 4.2.1 on 2024-11-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_remove_historicalpackaging_history_relation_and_more'),
        ('ipcc', '0047_valuechainrefrigerantemissionfactor_gwp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuechainpackagingemissionfactor',
            name='packaging_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagingmaterialtype'),
        ),
    ]
