# Generated by Django 4.0.4 on 2023-03-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_buildingtype_building'),
        ('ipcc', '0047_buildingemission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildingEmission',
            new_name='BuildingEmissionFactor',
        ),
    ]
