# Generated by Django 4.2.1 on 2023-05-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_buildingtype_building'),
        ('ipcc', '0048_rename_buildingemission_buildingemissionfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockVSER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('emission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.emissiontype')),
                ('livestock_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockTAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('emission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.emissiontype')),
                ('livestock_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockEntericEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('livestock_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockEFManure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('emission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.emissiontype')),
                ('livestock_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('manure_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manuremanagementtype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockAnimalWasteManagementSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('emission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.emissiontype')),
                ('livestock_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('manure_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manuremanagementtype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
            ],
        ),
    ]
