# Generated by Django 4.2.1 on 2024-11-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0181_packagingtype_valuechain_transport_storage_and_more"),
        ("ipcc", "0048_alter_valuechainpackagingemissionfactor_packaging_type"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='valuechainpackagingemissionfactor',
        #     name='packaging_type',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagingtype'),
        # ),
    ]
