# Generated by Django 4.2.1 on 2023-05-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_buildingtype_building'),
        ('ipcc', '0049_emissiontype_livestockvser_livestocktam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockNER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('emission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.emissiontype')),
                ('livestock_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
            ],
        ),
    ]
