# Generated by Django 4.2.1 on 2024-11-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0049_alter_valuechainpackagingemissionfactor_packaging_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuechainrefrigerantemissionfactor',
            name='gwp',
        ),
        migrations.RemoveField(
            model_name='valuechainrefrigerantemissionfactor',
            name='refrigerant_type',
        ),
        migrations.DeleteModel(
            name='ValueChainPackagingEmissionFactor',
        ),
        migrations.DeleteModel(
            name='ValueChainRefrigerantEmissionFactor',
        ),
    ]
