# Generated by Django 4.2.1 on 2023-05-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_buildingtype_building'),
        ('ipcc', '0050_livestockner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LivestockEFManure',
            new_name='LivestockManureEF',
        ),
    ]
