# Generated by Django 4.2.1 on 2024-11-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0051_valuechainrefrigerantemissionfactor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuechainpackagingemissionfactor',
            old_name='packaging_type',
            new_name='packaging_material_type',
        ),
    ]
