# Generated by Django 4.2.1 on 2023-05-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0051_rename_livestockefmanure_livestockmanureef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockmanureef',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
