# Generated by Django 4.2.1 on 2023-05-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0052_alter_livestockmanureef_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestocktam',
            name='emission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcc.emissiontype'),
        ),
    ]
