# Generated by Django 4.2.1 on 2023-05-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0053_alter_livestocktam_emission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockvser',
            name='emission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcc.emissiontype'),
        ),
    ]
