# Generated by Django 4.2.1 on 2024-11-19 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_historicalpackaging_name_historicalprocessing_name_and_more'),
        ('ipcc', '0053_remove_valuechainrefrigerantemissionfactor_gwp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueChainRefrigerantEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('gwp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcc.globalwarmingpotential')),
                ('refrigerant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refrigeranttype')),
            ],
            options={
                'verbose_name': 'Value Chain Refrigerant Emission Factor',
                'verbose_name_plural': 'Value Chain Refrigerant Emission Factors',
            },
        ),
        migrations.CreateModel(
            name='ValueChainPackagingEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('packaging_material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagingmaterialtype')),
            ],
            options={
                'verbose_name': 'Value Chain Packaging Emission Factor',
                'verbose_name_plural': 'Value Chain Packaging Emission Factors',
            },
        ),
    ]
