# Generated by Django 4.2.1 on 2024-11-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_historicalpackaging_name_historicalprocessing_name_and_more'),
        ('ipcc', '0054_valuechainrefrigerantemissionfactor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CropYieldStats',
            new_name='CropYieldStat',
        ),
    ]
