# Generated by Django 4.2.1 on 2023-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0054_alter_livestockvser_emission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='largefisheryfui',
            name='median',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='largefisheryfui',
            name='n',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallfisheryfui',
            name='median',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallfisheryfui',
            name='n',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
