# Generated by Django 4.2.1 on 2023-06-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0055_largefisheryfui_median_largefisheryfui_n_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallfisheryfui',
            name='median',
        ),
        migrations.RemoveField(
            model_name='smallfisheryfui',
            name='n',
        ),
    ]
