# Generated by Django 4.2.1 on 2025-02-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0055_rename_cropyieldstats_cropyieldstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowPriceOfCarbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
            ],
            options={
                'verbose_name': 'Shadow Price of Carbon',
                'verbose_name_plural': 'Shadow Prices of Carbon',
            },
        ),
    ]
