# Generated by Django 4.2.1 on 2025-04-22 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0238_remove_tillagetype_name_en_and_more"),
        ("ipcc", "0056_shadowpriceofcarbon"),
    ]

    operations = [
        migrations.CreateModel(
            name="FRACarbonStock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(unique=True)),
                ("agb", models.FloatField(blank=True, null=True)),
                ("bgb", models.FloatField(blank=True, null=True)),
                ("deadwood", models.FloatField(blank=True, null=True)),
                ("litter", models.FloatField(blank=True, null=True)),
                ("carbon_stock_biomass_total", models.FloatField(blank=True, null=True)),
                ("carbon_stock_total", models.FloatField(blank=True, null=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.country")),
            ],
        ),
    ]
