# Generated by Django 4.2.1 on 2023-06-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_rename_inshore_ice_production_country_largefishery_inshore_ice_production_country_t2_and_more'),
        ('ipcc', '0056_remove_smallfisheryfui_median_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestockmanureef',
            old_name='livestock_category',
            new_name='livestock_category_type',
        ),
        migrations.AddField(
            model_name='livestockmanureef',
            name='livestock_production_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype'),
            preserve_default=False,
        ),
    ]
