# Generated by Django 4.2.1 on 2023-06-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0057_rename_livestock_category_livestockmanureef_livestock_category_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestockner',
            old_name='region',
            new_name='continent',
        ),
    ]
