# Generated by Django 4.2.1 on 2025-04-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0057_globalwarmingpotential_name_ru_fracarbonstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalwarmingpotential',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
