# Generated by Django 4.2.1 on 2025-04-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0058_globalwarmingpotential_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fracarbonstock',
            name='year',
            field=models.IntegerField(),
        ),
    ]
