# Generated by Django 4.2.1 on 2023-06-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_ipccregion'),
        ('ipcc', '0058_rename_region_livestockner_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockanimalwastemanagementsystem',
            name='region',
        ),
        migrations.AddField(
            model_name='livestockanimalwastemanagementsystem',
            name='ipcc_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ipccregion'),
            preserve_default=False,
        ),
    ]
