# Generated by Django 4.2.1 on 2025-05-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipcc", "0059_alter_fracarbonstock_year"),
    ]

    operations = []
