# Generated by Django 4.2.1 on 2023-06-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_continent_ipcc_region'),
        ('ipcc', '0059_remove_livestockanimalwastemanagementsystem_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockanimalwastemanagementsystem',
            name='emission_type',
        ),
        migrations.AddField(
            model_name='livestockanimalwastemanagementsystem',
            name='livestock_production_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype'),
            preserve_default=False,
        ),
    ]
