# Generated by Django 4.2.1 on 2025-05-07 12:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ipcc", "0060_globalwarmingpotential_name_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalwarmingpotential",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
