# Generated by Django 4.2.1 on 2023-06-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0060_remove_livestockanimalwastemanagementsystem_emission_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockanimalwastemanagementsystem',
            name='manure_management_type',
        ),
    ]
