# Generated by Django 4.2.1 on 2025-12-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0282_alter_historicalproject_climate_and_more'),
        ('ipcc', '0061_auto_20250507_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForestManagementBGB',
            new_name='ForestManagementRootToShoot',
        ),
        migrations.AlterModelOptions(
            name='forestmanagementroottoshoot',
            options={'verbose_name': 'Forest Management Root-To-Shoot', 'verbose_name_plural': 'Forest Management Root-To-Shoot'},
        ),
    ]
