# Generated by Django 4.2.1 on 2023-06-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_alter_country_continent_alter_country_gleam_region_and_more'),
        ('ipcc', '0061_remove_livestockanimalwastemanagementsystem_manure_management_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestocktam',
            name='region',
        ),
        migrations.RemoveField(
            model_name='livestockvser',
            name='region',
        ),
        migrations.AddField(
            model_name='livestocktam',
            name='ipcc_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ipccregion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockvser',
            name='ipcc_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ipccregion'),
            preserve_default=False,
        ),
    ]
