# Generated by Django 4.2.1 on 2023-06-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0062_remove_livestocktam_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestockanimalwastemanagementsystem',
            old_name='livestock_category',
            new_name='livestock_category_type',
        ),
        migrations.RenameField(
            model_name='livestockner',
            old_name='livestock_category',
            new_name='livestock_category_type',
        ),
        migrations.RenameField(
            model_name='livestockner',
            old_name='production_type',
            new_name='livestock_production_type',
        ),
        migrations.RenameField(
            model_name='livestocktam',
            old_name='livestock_category',
            new_name='livestock_category_type',
        ),
        migrations.RenameField(
            model_name='livestocktam',
            old_name='production_type',
            new_name='livestock_production_type',
        ),
        migrations.RenameField(
            model_name='livestockvser',
            old_name='livestock_category',
            new_name='livestock_category_type',
        ),
        migrations.RenameField(
            model_name='livestockvser',
            old_name='production_type',
            new_name='livestock_production_type',
        ),
    ]
