# Generated by Django 4.2.1 on 2026-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0062_rename_forestmanagementbgb_forestmanagementroottoshoot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='dry_matter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='rag',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
