# Generated by Django 4.2.1 on 2023-07-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0084_rename_livestock_category_livestock_livestock_category_type"),
        (
            "ipcc",
            "0063_rename_livestock_category_livestockanimalwastemanagementsystem_livestock_category_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="livestockanimalwastemanagementsystem",
            name="manure_management_type",
            field=models.ForeignKey(
                default=128,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.manuremanagementtype",
            ),
            preserve_default=False,
        ),
    ]
