# Generated by Django 4.2.1 on 2026-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0063_cropnitrousestimationdefaultfactor_dry_matter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
