# Generated by Django 5.2.17 on 2026-09-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0064_cropnitrousestimationdefaultfactor_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='afforestationcombustionfactor',
            name='ch4_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationcombustionfactor',
            name='ch4_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationcombustionfactor',
            name='co2_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationcombustionfactor',
            name='co2_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationcombustionfactor',
            name='n2o_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationcombustionfactor',
            name='n2o_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationcombustionfactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationcombustionfactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationflu',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afforestationflu',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atwood',
            name='area_2014_km2_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atwood',
            name='area_2014_km2_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atwood',
            name='mg_c_ha_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atwood',
            name='mg_c_ha_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atwood',
            name='n_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atwood',
            name='n_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atwood',
            name='score_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atwood',
            name='score_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atwood',
            name='sd_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atwood',
            name='sd_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingemissionfactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingemissionfactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burningemissionfactor',
            name='ch4_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burningemissionfactor',
            name='ch4_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burningemissionfactor',
            name='co2_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burningemissionfactor',
            name='co2_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burningemissionfactor',
            name='co_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burningemissionfactor',
            name='co_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burningemissionfactor',
            name='n2o_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burningemissionfactor',
            name='n2o_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burningemissionfactor',
            name='nox_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burningemissionfactor',
            name='nox_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coastalagb',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coastalagb',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coastalbgb',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coastalbgb',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coastaldeadwood',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coastaldeadwood',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coastallitter',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coastallitter',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croplandfi',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croplandfi',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croplandflu',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croplandflu',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croplandfmg',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croplandfmg',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='intercept_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='intercept_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='n_ag_residues_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='n_ag_residues_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='n_bg_t_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='n_bg_t_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='rs_t_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='rs_t_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='slope_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='slope_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='agb_c_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='agb_c_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='agb_dry_matter_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='agb_dry_matter_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='agb_growth_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='agb_growth_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='bgb_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='bgb_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='c_fraction_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='c_fraction_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='dw_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='dw_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='litter_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='litter_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='r_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='r_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='soc_ref_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataonmangrove',
            name='soc_ref_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultsoilcarbonstock',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultsoilcarbonstock',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drainageemissionfactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drainageemissionfactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energydefaultemissionfactor',
            name='ch4_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energydefaultemissionfactor',
            name='ch4_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energydefaultemissionfactor',
            name='co2_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energydefaultemissionfactor',
            name='co2_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energydefaultemissionfactor',
            name='n2o_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energydefaultemissionfactor',
            name='n2o_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fidata',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fidata',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firescombustionfactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firescombustionfactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fludata',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fludata',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fmgdata',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fmgdata',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestcombustionfactor',
            name='ch4_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestcombustionfactor',
            name='ch4_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestcombustionfactor',
            name='co2_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestcombustionfactor',
            name='co2_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestcombustionfactor',
            name='n2o_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestcombustionfactor',
            name='n2o_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestcombustionfactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestcombustionfactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagementagb',
            name='agb_growth_max_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagementagb',
            name='agb_growth_min_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagementagb',
            name='agb_max_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagementagb',
            name='agb_min_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagementroottoshoot',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forestmanagementroottoshoot',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foresttotalbiomass',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foresttotalbiomass',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grasslandbiomass',
            name='agb_t_dm_ha_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grasslandbiomass',
            name='agb_t_dm_ha_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grasslandstockexchangefactor',
            name='fi_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grasslandstockexchangefactor',
            name='fi_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grasslandstockexchangefactor',
            name='flu_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grasslandstockexchangefactor',
            name='flu_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grasslandstockexchangefactor',
            name='fmg_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grasslandstockexchangefactor',
            name='fmg_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputemissionfactor',
            name='co2_eq_value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputemissionfactor',
            name='co2_eq_value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputemissionfactor',
            name='co2_value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputemissionfactor',
            name='co2_value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputemissionfactor',
            name='n2o_value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputemissionfactor',
            name='n2o_value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='calorific_value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='calorific_value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='ch4_emissions_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='ch4_emissions_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='co2_emissions_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='co2_emissions_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='density_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='density_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='emission_factor_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='emission_factor_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='n2o_emissions_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationphasedata',
            name='n2o_emissions_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationpressurerequirement',
            name='avg_pressure_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationpressurerequirement',
            name='avg_pressure_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationpressurerequirement',
            name='head_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationpressurerequirement',
            name='head_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationsystemdata',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationsystemdata',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landusecarbonstockexchangefactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landusecarbonstockexchangefactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefisheryfui',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largefisheryfui',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litterdeadwoodcarbonstock',
            name='dw_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litterdeadwoodcarbonstock',
            name='dw_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litterdeadwoodcarbonstock',
            name='litter_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litterdeadwoodcarbonstock',
            name='litter_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockawms',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockawms',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockmanureef',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockmanureef',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockner',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockner',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestocktam',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestocktam',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockvser',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockvser',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manuremanagementvolatilizationmultiplier',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manuremanagementvolatilizationmultiplier',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='methaneentericfermentationfactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='methaneentericfermentationfactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nitrousemissionfactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nitrousemissionfactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoildrainageemissionfactor',
            name='ch4_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoildrainageemissionfactor',
            name='ch4_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoildrainageemissionfactor',
            name='co2_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoildrainageemissionfactor',
            name='co2_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoildrainageemissionfactor',
            name='doc_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoildrainageemissionfactor',
            name='doc_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoildrainageemissionfactor',
            name='n2o_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoildrainageemissionfactor',
            name='n2o_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoilfuelconsumption',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoilfuelconsumption',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoilrewettingemissionfactor',
            name='ch4_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoilrewettingemissionfactor',
            name='ch4_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoilrewettingemissionfactor',
            name='co2_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoilrewettingemissionfactor',
            name='co2_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoilrewettingemissionfactor',
            name='doc_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoilrewettingemissionfactor',
            name='doc_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoilrewettingemissionfactor',
            name='n2o_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organicsoilrewettingemissionfactor',
            name='n2o_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherconstructedwaterbodiesemissionfactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherconstructedwaterbodiesemissionfactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionconversionfactor',
            name='volume_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionconversionfactor',
            name='volume_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionconversionfactor',
            name='weight_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionconversionfactor',
            name='weight_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionemissionfactor',
            name='ch4_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionemissionfactor',
            name='ch4_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionemissionfactor',
            name='co2_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionemissionfactor',
            name='co2_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionemissionfactor',
            name='doc_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionemissionfactor',
            name='doc_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionemissionfactor',
            name='n2o_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peatextractionemissionfactor',
            name='n2o_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialagb',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialagb',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialbgb',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialbgb',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialmaxagb',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennialmaxagb',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewettingcarbonfactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewettingcarbonfactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewettingmethanefactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewettingmethanefactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ricedefaultemissionfactor',
            name='cultivation_period_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ricedefaultemissionfactor',
            name='cultivation_period_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ricedefaultemissionfactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ricedefaultemissionfactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ricesfo',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ricesfo',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ricesfp',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ricesfp',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ricesfw',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ricesfw',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riceyield',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riceyield',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roademissionfactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roademissionfactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementef',
            name='biomass_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementef',
            name='biomass_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementef',
            name='fi_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementef',
            name='fi_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementef',
            name='flu_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementef',
            name='flu_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementef',
            name='fmg_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementef',
            name='fmg_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfisheryfui',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallfisheryfui',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilorganiccarbon',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilorganiccarbon',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalbiomassafterdefo',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalbiomassafterdefo',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trophicstatefactor',
            name='chloa_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trophicstatefactor',
            name='chloa_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trophicstatefactor',
            name='value_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trophicstatefactor',
            name='value_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
