# Generated by Django 4.2.1 on 2023-07-04 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_croptype_remove_annualcropping_land_use_type_and_more'),
        ('ipcc', '0066_remove_firescombustionfactor_land_use_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropnitrousestimationdefaultfactor',
            name='land_use_type',
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='crop_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.croptype'),
            preserve_default=False,
        ),
    ]
