# Generated by Django 4.2.1 on 2023-07-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_alter_annualcropping_minor_crop_type_t2'),
        ('ipcc', '0069_remove_cropyieldstats_land_use_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smallfisheryfui',
            unique_together={('fishery_type', 'gear_type')},
        ),
    ]
