# Generated by Django 4.2.1 on 2023-07-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0087_smallfisherygeartype_and_more"),
        ("ipcc", "0070_alter_smallfisheryfui_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="largefisheryfui",
            name="gear_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.largefisherygeartype",
            ),
        ),
        migrations.AlterField(
            model_name="smallfisheryfui",
            name="gear_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.smallfisherygeartype",
            ),
        ),
    ]
