# Generated by Django 4.2.1 on 2023-07-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_largefishery_gear_type_start_and_more'),
        ('ipcc', '0071_alter_largefisheryfui_gear_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largefisheryfui',
            name='gear_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.largefisherygeartype'),
        ),
    ]
