# Generated by Django 4.2.1 on 2023-07-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_extractionsoiltype'),
        ('ipcc', '0073_alter_firescombustionfactor_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croplandflu',
            name='crop_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.croptype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cropnitrousestimationdefaultfactor',
            name='crop_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.croptype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cropyieldstats',
            name='crop_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.croptype'),
            preserve_default=False,
        ),
    ]
