# Generated by Django 4.2.1 on 2023-07-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_extractionsoiltype'),
        ('ipcc', '0074_alter_croplandflu_crop_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firescombustionfactor',
            name='crop_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.croptype'),
            preserve_default=False,
        ),
    ]
