# Generated by Django 4.2.1 on 2023-07-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0075_alter_firescombustionfactor_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largefisheryfui',
            name='median',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='largefisheryfui',
            name='n',
            field=models.IntegerField(null=True),
        ),
    ]
