# Generated by Django 4.2.1 on 2023-07-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0076_alter_largefisheryfui_median_alter_largefisheryfui_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='largefisheryfui',
            name='value',
        ),
    ]
