# Generated by Django 4.2.1 on 2023-07-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_remove_perennialcropping_land_use_type_and_more'),
        ('ipcc', '0077_remove_largefisheryfui_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='largefisheryfui',
            unique_together={('fish_type', 'gear_type')},
        ),
    ]
