# Generated by Django 4.2.1 on 2023-07-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0078_alter_largefisheryfui_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultemissionfactor',
            old_name='input',
            new_name='organic_input_type',
        ),
    ]
