# Generated by Django 4.2.1 on 2023-07-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_alter_perennialcropping_crop_type'),
        ('ipcc', '0079_rename_input_defaultemissionfactor_organic_input_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AfforestationCombustionFactorValues',
            new_name='AfforestationCombustionFactor',
        ),
        migrations.RenameModel(
            old_name='CombustionFactorValues',
            new_name='CombustionFactor',
        ),
        migrations.RenameModel(
            old_name='DataOnMangroves',
            new_name='DataOnMangrove',
        ),
    ]
