# Generated by Django 4.2.1 on 2023-07-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_agroforestrysystem'),
        ('ipcc', '0080_rename_afforestationcombustionfactorvalues_afforestationcombustionfactor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perennialagb',
            name='land_use_type',
        ),
        migrations.RemoveField(
            model_name='perennialbgb',
            name='land_use_type',
        ),
        migrations.RemoveField(
            model_name='perennialmaxagb',
            name='land_use_type',
        ),
        migrations.AddField(
            model_name='perennialagb',
            name='crop_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.croptype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialbgb',
            name='crop_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.croptype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialmaxagb',
            name='crop_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.croptype'),
            preserve_default=False,
        ),
    ]
