# Generated by Django 4.2.1 on 2023-07-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_rename_livestock_category_type_livestock_livestock_category_type_start_and_more'),
        ('ipcc', '0081_remove_perennialagb_land_use_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockner',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='livestockner',
            name='emission_type',
        ),
        migrations.RemoveField(
            model_name='livestockner',
            name='value',
        ),
        migrations.AddField(
            model_name='livestockner',
            name='ipcc_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ipccregion'),
            preserve_default=False,
        ),
    ]
