# Generated by Django 4.2.1 on 2023-07-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0082_remove_livestockner_continent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockner',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
