# Generated by Django 4.2.1 on 2023-07-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_activity_change_rate_start_activity_change_rate_w_and_more'),
        ('ipcc', '0083_livestockner_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethaneEntericFermentationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('ipcc_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ipccregion')),
                ('livestock_category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockcategorytype')),
                ('livestock_production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livestockproductiontype')),
            ],
        ),
    ]
