# Generated by Django 4.2.1 on 2023-07-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_rename_emission_factor_n20_t2_w_livestock_emission_factor_n2o_t2_w_and_more'),
        ('ipcc', '0084_methaneentericfermentationfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManureManagementVolatilizationMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
    ]
