# Generated by Django 4.2.1 on 2023-08-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0085_manuremanagementvolatilizationmultiplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energydefaultemissionfactor',
            old_name='ch4_emissions',
            new_name='ch4',
        ),
        migrations.RenameField(
            model_name='energydefaultemissionfactor',
            old_name='co2_emissions',
            new_name='co2',
        ),
        migrations.RenameField(
            model_name='energydefaultemissionfactor',
            old_name='density_kg_m3',
            new_name='density',
        ),
        migrations.RenameField(
            model_name='energydefaultemissionfactor',
            old_name='kg_n2o_tj',
            new_name='n2o',
        ),
        migrations.RenameField(
            model_name='energydefaultemissionfactor',
            old_name='tj_gg',
            new_name='net_calorific_value',
        ),
        migrations.RenameField(
            model_name='energydefaultemissionfactor',
            old_name='t_co2_eq_m3',
            new_name='t_co2_eq',
        ),
        migrations.RemoveField(
            model_name='energydefaultemissionfactor',
            name='kg_ch4_tj',
        ),
        migrations.RemoveField(
            model_name='energydefaultemissionfactor',
            name='n2o_emissions',
        ),
    ]
