# Generated by Django 4.2.1 on 2023-08-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_rename_irrigationtype_irrigationsystemtype_and_more'),
        ('ipcc', '0086_rename_ch4_emissions_energydefaultemissionfactor_ch4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationSystemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('irrigation_system_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.irrigationsystemtype')),
            ],
        ),
    ]
