# Generated by Django 4.2.1 on 2023-08-08 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_rename_irrigationtype_irrigationsystemtype_and_more'),
        ('ipcc', '0088_alter_irrigationsystemdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationsystemdata',
            name='irrigation_system_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.irrigationsystemtype'),
        ),
    ]
