# Generated by Django 4.2.1 on 2023-08-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_rename_irrigationtype_irrigationsystemtype_and_more'),
        ('ipcc', '0089_alter_irrigationsystemdata_irrigation_system_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationPhaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_factor', models.FloatField()),
                ('calorific_value', models.FloatField(blank=True, null=True)),
                ('co2_emissions', models.FloatField(blank=True, null=True)),
                ('ch4_emissions', models.FloatField(blank=True, null=True)),
                ('n2o_emissions', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fueltype')),
            ],
        ),
    ]
