# Generated by Django 4.2.1 on 2023-08-08 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_remove_irrigationphase_energy_source_type_and_more'),
        ('ipcc', '0090_irrigationphasedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationPressureRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_denomination', models.CharField(max_length=255)),
                ('bar', models.FloatField(blank=True, null=True)),
                ('avg_pressure', models.FloatField()),
                ('head', models.FloatField()),
                ('irrigation_system_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.irrigationsystemtype')),
            ],
        ),
    ]
