# Generated by Django 4.2.1 on 2023-08-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0091_irrigationpressurerequirement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigationpressurerequirement',
            old_name='bar',
            new_name='bar_start',
        ),
        migrations.AddField(
            model_name='irrigationpressurerequirement',
            name='bar_end',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
