# Generated by Django 4.2.1 on 2023-08-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_remove_irrigationphase_groundwater_irrigation_system_type_and_more'),
        ('ipcc', '0093_remove_irrigationpressurerequirement_irrigation_system_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationpressurerequirement',
            name='groundwater_irrigation_system_type',
        ),
        migrations.AddField(
            model_name='irrigationpressurerequirement',
            name='irrigation_system_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.irrigationsystemtype'),
            preserve_default=False,
        ),
    ]
