# Generated by Django 4.2.1 on 2023-08-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0094_remove_irrigationpressurerequirement_groundwater_irrigation_system_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestocktam',
            name='emission_type',
        ),
    ]
