# Generated by Django 4.2.1 on 2023-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0095_remove_livestocktam_emission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationpressurerequirement',
            name='bar_end',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='irrigationpressurerequirement',
            name='bar_start',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
