# Generated by Django 4.2.1 on 2023-09-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0096_alter_irrigationpressurerequirement_bar_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grasslandstockexchangefactor',
            name='soc',
            field=models.FloatField(default=0.77),
        ),
    ]
