# Generated by Django 4.2.1 on 2023-09-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0097_grasslandstockexchangefactor_soc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grasslandstockexchangefactor',
            name='soc',
        ),
    ]
