# Generated by Django 4.2.1 on 2023-09-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0098_remove_grasslandstockexchangefactor_soc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grasslandsoc',
            name='value',
            field=models.FloatField(default=1),
        ),
    ]
