# Generated by Django 4.2.1 on 2023-09-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0099_alter_grasslandsoc_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grasslandsoc',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
