# Generated by Django 4.2.1 on 2023-09-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0100_alter_grasslandsoc_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingemissionfactor',
            old_name='kg_co2_m2',
            new_name='value',
        ),
    ]
