# Generated by Django 4.2.1 on 2023-09-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_rename_crop_yield_floodedrice_crop_yield_start_and_more'),
        ('ipcc', '0101_rename_kg_co2_m2_buildingemissionfactor_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiceSFW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('water_management_type_after_cultivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watermanagementtypeaftercultivation')),
            ],
        ),
        migrations.CreateModel(
            name='RiceSFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('water_management_type_before_cultivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watermanagementtypebeforecultivation')),
            ],
        ),
        migrations.CreateModel(
            name='RiceSFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('organic_amendment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicamendmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='RiceDefaultEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
            ],
        ),
    ]
