# Generated by Django 4.2.1 on 2023-09-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_floodedrice_ha_start_floodedrice_ha_w_and_more'),
        ('ipcc', '0102_ricesfw_ricesfp_ricesfo_ricedefaultemissionfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiceYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
            ],
        ),
    ]
