# Generated by Django 4.2.1 on 2023-09-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0103_riceyield'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricedefaultemissionfactor',
            name='cultivation_period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
