# Generated by Django 4.2.1 on 2023-09-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_coastalwetlandparameter_coastalwetland'),
        ('ipcc', '0104_ricedefaultemissionfactor_cultivation_period'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoastalAboveGroundBiomass',
            new_name='CoastalAGB',
        ),
        migrations.RenameModel(
            old_name='CoastalBGAGRatio',
            new_name='CoastalBGB',
        ),
        migrations.CreateModel(
            name='DefaultSoilCarbonStock1Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
    ]
