# Generated by Django 4.2.1 on 2023-09-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_waterbody'),
        ('ipcc', '0105_rename_coastalabovegroundbiomass_coastalagb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrophicStateFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('chloa', models.FloatField()),
                ('trophic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trophictype')),
            ],
        ),
    ]
