# Generated by Django 4.2.1 on 2023-09-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_rename_ch4_rewetting_start_coastalwetland_ch4_rewetting_t2_start_and_more'),
        ('ipcc', '0106_trophicstatefactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsoilcarbonstock1meter',
            name='soil_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.soiltype'),
            preserve_default=False,
        ),
    ]
