# Generated by Django 4.2.1 on 2023-09-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0107_defaultsoilcarbonstock1meter_soil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsoilcarbonstock1meter',
            name='unit',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
