# Generated by Django 4.2.1 on 2023-09-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_sitelocationtype_and_more'),
        ('ipcc', '0108_defaultsoilcarbonstock1meter_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoadEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('road_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roadtype')),
            ],
        ),
        migrations.CreateModel(
            name='PeatExtractionConversionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('weight_unit', models.CharField(default='tC/t air dry peat', max_length=100)),
                ('volume', models.FloatField(default=0)),
                ('volume_unit', models.CharField(default='tC/m3 air dry peat', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('peat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peattype')),
            ],
        ),
        migrations.CreateModel(
            name='PeatEctractionEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(default=0)),
                ('co2_unit', models.CharField(default='tC/ha/yr', max_length=100)),
                ('doc', models.FloatField(default=0)),
                ('doc_unit', models.CharField(default='tC/ha/yr', max_length=100)),
                ('ch4', models.FloatField(default=0)),
                ('ch4_unit', models.CharField(default='kg CH4/ha/yr', max_length=100)),
                ('n2o', models.FloatField(default=0)),
                ('n2o_unit', models.CharField(default='kg N2O/ha/yr', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('peat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peattype')),
                ('site_location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitelocationtype')),
            ],
        ),
        migrations.CreateModel(
            name='OrganicSoilRewettingEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(default=0)),
                ('co2_unit', models.CharField(default='tCO2-C/ha/yr', max_length=100)),
                ('doc', models.FloatField(default=0)),
                ('doc_unit', models.CharField(default='tCO2-C/ha/yr', max_length=100)),
                ('ch4', models.FloatField(default=0)),
                ('ch4_unit', models.CharField(default='kg CH4-C/ha/yr', max_length=100)),
                ('n2o', models.FloatField(default=0)),
                ('n2o_unit', models.CharField(default='tN2O-N/ha/yr', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moduletype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('peat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peattype')),
            ],
        ),
        migrations.CreateModel(
            name='OrganicSoilGefEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(default=0)),
                ('co2_unit', models.CharField(default='g CO2-C/kg dry matter burned', max_length=100)),
                ('co', models.FloatField(default=0)),
                ('co_unit', models.CharField(default='g CO/kg dry matter burned', max_length=100)),
                ('ch4', models.FloatField(default=0)),
                ('ch4_unit', models.CharField(default='g CH4/kg dry matter burned', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='OrganicSoilFuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('unit', models.CharField(default='t dm/ha', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('fire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.firetype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='OrganicSoilDrainageEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(default=0)),
                ('co2_unit', models.CharField(default='tC/ha/yr', max_length=100)),
                ('doc', models.FloatField(default=0)),
                ('doc_unit', models.CharField(default='tC/ha/yr', max_length=100)),
                ('ch4', models.FloatField(default=0)),
                ('ch4_unit', models.CharField(default='kg CH4/ha/yr', max_length=100)),
                ('n2o', models.FloatField(default=0)),
                ('n2o_unit', models.CharField(default='kg N2O/ha/yr', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moduletype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('peat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peattype')),
                ('site_location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitelocationtype')),
            ],
        ),
    ]
