# Generated by Django 4.2.1 on 2023-09-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0109_sitelocationtype_roademissionfactor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteLocationType',
        ),
    ]
