# Generated by Django 4.2.1 on 2023-09-28 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_remove_organicsoil_is_fire_on_soil_start_and_more'),
        ('ipcc', '0110_delete_sitelocationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewettingEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='tC/ha/yr', max_length=100)),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
            ],
        ),
    ]
