# Generated by Django 4.2.1 on 2023-09-28 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_remove_organicsoil_is_fire_on_soil_start_and_more'),
        ('ipcc', '0111_rewettingemissionfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewettingemissionfactor',
            name='vegetation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype'),
            preserve_default=False,
        ),
    ]
