# Generated by Django 4.2.1 on 2023-09-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_remove_organicsoil_is_fire_on_soil_start_and_more'),
        ('ipcc', '0112_rewettingemissionfactor_vegetation_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeatEctractionEmissionFactor',
            new_name='PeatExtractionEmissionFactor',
        ),
        migrations.DeleteModel(
            name='RewettingEmissionFactor',
        ),
    ]
