# Generated by Django 4.2.1 on 2023-09-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_forestmanagement_forest_condition_type_and_more'),
        ('ipcc', '0113_rename_peatectractionemissionfactor_peatextractionemissionfactor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestManagementAGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agb_min', models.FloatField(default=0)),
                ('agb_max', models.FloatField(default=0)),
                ('agb_growth_min', models.FloatField(default=0)),
                ('agb_growth_max', models.FloatField(default=0)),
                ('agb_unit', models.CharField(default='tonnes d.m./ha', max_length=100)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.continent')),
                ('forest_condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forestconditiontype')),
                ('forest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foresttype')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetationtype')),
            ],
        ),
    ]
