# Generated by Django 4.2.1 on 2023-10-31 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_remove_annualcropping_minor_crop_type_start_and_more'),
        ('ipcc', '0114_forestmanagementagb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croplandflu',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='cropnitrousestimationdefaultfactor',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='cropyieldstats',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='firescombustionfactor',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='perennialagb',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='perennialbgb',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='perennialmaxagb',
            name='crop_type',
        ),
        migrations.AddField(
            model_name='croplandflu',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cropnitrousestimationdefaultfactor',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cropyieldstats',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firescombustionfactor',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialagb',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialbgb',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perennialmaxagb',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
    ]
