# Generated by Django 4.2.1 on 2023-11-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0217_rename_dry_matter_end_landusechange_dry_matter_w_and_more'),
        ('ipcc', '0115_remove_croplandflu_crop_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilorcaniccarboncnratio',
            name='land_use_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
        ),
    ]
