# Generated by Django 4.2.1 on 2023-11-20 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0221_remove_coastalwetland_vegetation_type_and_more'),
        ('ipcc', '0116_alter_soilorcaniccarboncnratio_land_use_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abovegroundbiomass',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='abovegroundnetbiomassgrowth',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='belowgroundbiomass',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='coastalagb',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='coastalbgb',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='coastaldeadwood',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='coastallitter',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='combustionfactor',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='defaultsoilcarbonstock',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='defaultsoilcarbonstock1meter',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='drainageemissionfactor',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='forestagb',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='forestmanagementagb',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='litterdeadwoodcarbonstock',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='rewettingcarbonfactor',
            name='vegetation_type',
        ),
        migrations.RemoveField(
            model_name='rewettingmethanefactor',
            name='vegetation_type',
        ),
        migrations.AddField(
            model_name='abovegroundbiomass',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abovegroundnetbiomassgrowth',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='belowgroundbiomass',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coastalagb',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coastalbgb',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coastaldeadwood',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coastallitter',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combustionfactor',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultsoilcarbonstock',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultsoilcarbonstock1meter',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drainageemissionfactor',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forestagb',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forestmanagementagb',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='litterdeadwoodcarbonstock',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewettingcarbonfactor',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewettingmethanefactor',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
    ]
