# Generated by Django 4.2.1 on 2023-11-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0117_remove_abovegroundbiomass_vegetation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coastalagb',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
