# Generated by Django 4.2.1 on 2023-11-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0118_coastalagb_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='coastalbgb',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
