# Generated by Django 4.2.1 on 2023-11-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0119_coastalbgb_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nitrousemissionfactor',
            old_name='moisture_type',
            new_name='moisture',
        ),
    ]
