# Generated by Django 4.2.1 on 2023-11-30 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0241_activity_modules_alter_activity_unique_together'),
        ('ipcc', '0120_rename_moisture_type_nitrousemissionfactor_moisture'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrasslandSoilOrganicCarbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('grassland_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grasslandmanagementtype')),
            ],
        ),
    ]
