# Generated by Django 4.2.1 on 2023-11-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcc', '0121_grasslandsoilorganiccarbon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrasslandSoilOrganicCarbon',
        ),
    ]
