# Generated by Django 4.2.1 on 2023-12-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0282_alter_activity_duration_t2'),
        ('ipcc', '0122_delete_grasslandsoilorganiccarbon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FLUData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moduletype')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
            ],
        ),
        migrations.CreateModel(
            name='FIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('organic_input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organicinputtype')),
            ],
        ),
    ]
