# Generated by Django 4.2.1 on 2023-12-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0282_alter_activity_duration_t2'),
        ('ipcc', '0123_fludata_fidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climate')),
                ('moisture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moisture')),
                ('tillage_management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tillagemanagementtype')),
            ],
        ),
    ]
