# Generated by Django 4.2.1 on 2023-12-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0282_alter_activity_duration_t2'),
        ('ipcc', '0124_fmgdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fludata',
            name='module_type',
        ),
        migrations.AddField(
            model_name='fludata',
            name='land_use_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landusetype'),
            preserve_default=False,
        ),
    ]
