# Generated by Django 4.2.1 on 2023-12-21 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0285_project_start_year"),
        ("ipcc", "0125_remove_fludata_module_type_fludata_land_use_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fludata",
            unique_together={("climate", "moisture", "land_use_type")},
        ),
    ]
