# Generated by Django 4.2.1 on 2023-12-23 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipcc", "0126_alter_fludata_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electricityemission",
            name="continent",
        ),
    ]
