# Generated by Django 4.2.1 on 2024-01-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipcc", "0127_remove_electricityemission_continent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="largefisheryfui",
            name="median",
        ),
        migrations.RemoveField(
            model_name="largefisheryfui",
            name="n",
        ),
        migrations.AddField(
            model_name="largefisheryfui",
            name="value",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
