# Generated by Django 4.2.1 on 2024-01-24 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0299_merge_20240124_1136"),
        ("ipcc", "0128_remove_largefisheryfui_median_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="livestockvser",
            unique_together={
                ("livestock_production_type", "livestock_category_type", "ipcc_region")
            },
        ),
    ]
