# Generated by Django 4.2.1 on 2024-01-24 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0300_climate_moistures"),
        ("ipcc", "0129_alter_livestockvser_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="livestockmanureef",
            unique_together={
                (
                    "emission_type",
                    "livestock_production_type",
                    "livestock_category_type",
                    "climate",
                    "moisture",
                    "manure_management_type",
                )
            },
        ),
    ]
