# Generated by Django 4.2.1 on 2024-02-06 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0315_remove_disturbancetype_activity_and_more"),
        ("ipcc", "0130_alter_livestockmanureef_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grasslandagb",
            unique_together={("climate", "moisture")},
        ),
    ]
