# Generated by Django 4.2.1 on 2024-02-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0317_alter_annualcropping_crop_yield_start_and_more"),
        ("ipcc", "0131_alter_grasslandagb_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="forestmanagementagb",
            name="climate",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.climate"
            ),
            preserve_default=False,
        ),
    ]
