# Generated by Django 4.2.1 on 2024-02-08 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipcc", "0132_forestmanagementagb_climate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forestmanagementagb",
            old_name="continent",
            new_name="region",
        ),
    ]
