# Generated by Django 4.2.1 on 2024-02-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0317_alter_annualcropping_crop_yield_start_and_more"),
        ("ipcc", "0133_rename_continent_forestmanagementagb_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForestCombustionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("co2", models.FloatField(null=True)),
                ("ch4", models.FloatField(null=True)),
                ("n2o", models.FloatField(null=True)),
                ("value", models.FloatField()),
                (
                    "climate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.climate"
                    ),
                ),
                (
                    "forest_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.foresttype"
                    ),
                ),
                (
                    "land_use_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.landusetype",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CombustionFactor",
        ),
    ]
