# Generated by Django 4.2.1 on 2024-02-08 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0317_alter_annualcropping_crop_yield_start_and_more"),
        ("ipcc", "0134_forestcombustionfactor_delete_combustionfactor"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AboveGroundBiomass",
            new_name="ForestAboveGroundBiomass",
        ),
    ]
