# Generated by Django 4.2.1 on 2024-02-12 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipcc", "0136_forestabovegroundbiomass_climate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forestagb",
            name="continent",
        ),
        migrations.RemoveField(
            model_name="forestagb",
            name="land_use_type",
        ),
        migrations.DeleteModel(
            name="ForestAboveGroundBiomass",
        ),
        migrations.DeleteModel(
            name="ForestAGB",
        ),
    ]
