# Generated by Django 4.2.1 on 2024-02-12 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0317_alter_annualcropping_crop_yield_start_and_more"),
        ("ipcc", "0137_remove_forestagb_continent_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AboveGroundNetBiomassGrowth",
            new_name="ForestAGBGrowth",
        ),
    ]
