# Generated by Django 4.2.1 on 2024-02-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0317_alter_annualcropping_crop_yield_start_and_more"),
        ("ipcc", "0138_rename_abovegroundnetbiomassgrowth_forestagbgrowth"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForestManagementBGB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold", models.FloatField(blank=True, null=True)),
                ("value", models.FloatField()),
                (
                    "forest_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.foresttype",
                    ),
                ),
                (
                    "land_use_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.landusetype",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.region"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BelowGroundBiomass",
        ),
    ]
