# Generated by Django 4.2.1 on 2024-02-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0317_alter_annualcropping_crop_yield_start_and_more"),
        ("ipcc", "0139_forestmanagementbgb_delete_belowgroundbiomass"),
    ]

    operations = [
        migrations.AddField(
            model_name="forestmanagementbgb",
            name="climate",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.climate"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="forestmanagementbgb",
            name="forest_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.foresttype"
            ),
        ),
    ]
