# Generated by Django 4.2.1 on 2024-02-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0317_alter_annualcropping_crop_yield_start_and_more"),
        ("ipcc", "0140_forestmanagementbgb_climate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForestManagementAGBGrowth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_after_20_years", models.FloatField()),
                ("value_upto_20_years", models.FloatField()),
                (
                    "climate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.climate"
                    ),
                ),
                (
                    "forest_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.foresttype"
                    ),
                ),
                (
                    "land_use_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.landusetype",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.region"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ForestAGBGrowth",
        ),
    ]
