# Generated by Django 4.2.1 on 2024-02-12 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0319_remove_landusetype_regions"),
        ("ipcc", "0142_litterdeadwoodcarbonstock_climate_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="afforestationflu",
            unique_together={("climate", "moisture", "land_use_type")},
        ),
    ]
